### ISSUE TITLE
Layers moving button is updated incorrectly.

### ISSUE THREAD

**Issue by IMMZ** [bjorn/tiled#1005]
Steps to reproduce:
1. Create map.
2. Create layer A. Buttons 'move up / move down' are disabled.
3. Create layer B.
4. Choose upper one (B) and delete it.
5. Now the bottom one (A) is active but 'move up' button is active this time with only single layer on the map which is not correct behaviour.

**Comment by bjorn** [comment]
Good catch. Fortunately, it does nothing when you click it. :-)

Are you working on a fix?

**Comment by IMMZ** [comment]
Not yet :) Just left it up here, maybe someone wants to accept a challenge.
