### ISSUE TITLE
Prevent user from creating "nan" polylines through resizing

### ISSUE THREAD

**Issue by LearnCocos2D** [bjorn/tiled#1016]
I just created a polyline that ended up like so in the TMX file:

```
  <object id="2" x="nan" y="148" width="nan">
   <polyline points="nan,0 nan,-4"/>
  </object>
```

Properties view:

![screen shot 2015-07-07 at 11 32 05](https://cloud.githubusercontent.com/assets/214599/8543251/d5840cac-249b-11e5-96ee-c454ecee2020.png)

While I can select that object from the objects list it can still create a range of problems, specifically at runtime depending on the implementation of the TMX reader/renderer. Since the line isn't shown or selectable on the map it's also not standing out as a potential problem.

How to create a nan polyline? Good question! :)

It took me a moment to reproduce. As prerequisite you need a polyline with 3 points. Then use the select objects tool and select the line. This should bring up the resize arrows on every side and corner. Try to squeeze down the path to a point. Most of the times this will end up drawing a single dot, that's not the problem. The problem appears because in some way (can't really say for sure how) it's possible to drag all the points together to the same location or even "slightly farther" - basically this happened: I had a single line segment left, then dragged the top side down over and under the other remaining segment point when the line vanished entirely and gave nan coords. 

Or perhaps it's just a random floating point inaccuracy that adds up when you keep resizing the line?

Note: I have not tested this but I think it's quite possible this problem could occur with other object types too.

**Comment by bjorn** [comment]
This is probably related to #981. A fix was attempted at #982 but there remained some problems with it and @IMMZ decided to tackle other issues for now. I'll try to fix it for the next release, unless somebody beats me to it.
