### ISSUE TITLE
Failed to build for DEB

### ISSUE THREAD

**Issue by modos189** [bjorn/tiled#1019]
I'm trying to make DEB package for 12.2 and 12.3 releases using the command
dpkg-buildpackage -rfakeroot
but I get an error about the lack of library libtiled.so.1, which is present in the debian/tiled-daily/usr/lib/tiled/

On the launchpad repository same error, the build log: https://launchpadlibrarian.net/207253905/buildlog_ubuntu-vivid-amd64.tiled_0.12.2-3_BUILDING.txt.gz

Please tell me how to fix and build :)

**Comment by modos189** [comment]
I corrected the path to the library and created pull: https://github.com/bjorn/tiled/pull/1021

**Comment by bjorn** [comment]
As such that patch is not something I can accept since it would break the library references for the default `LIBDIR` which is simply `$${PREFIX}/lib`.
