### ISSUE TITLE
Loading of plugins fails, when stored under /usr/lib64 on Linux

### ISSUE THREAD

**Issue by jansing** [bjorn/tiled#1020]
Tiled does not seem to find its plugins, when they are located in /usr/lib64 instead of /usr/lib. Running on openSUSE 13.2 from package (https://build.opensuse.org/package/show?project=games%3Atools&package=tiled).

Example:
```
$ tiled --export-formats
Export formats: 
```

Symlinking /usr/lib64/tiled to /usr/lib/tied fixes this.
I realized that building from source and running `make install` installs the plugins to `/usr/local/lib` instead of `/usr/local/lib64`, where I would have expected.

**Comment by Ablu** [comment]
That spec files misses `USE_FHS_PLUGIN_PATH=yes` apparently. See http://pkgs.fedoraproject.org/cgit/tiled.git/tree/tiled.spec for my specfile from fedora.

**Comment by bjorn** [comment]
Please report it as a packaging issue. I don't think Tiled can know where the libs should go. Or if it can, maybe write a patch for Tiled's project file. :-)

**Comment by jansing** [comment]
Hm, okay. Seemed to be a bug in the plugin loader to me, since loading of libtiled.so worked from that same directory. Sorry for the noise and thanks for the great work! :)

**Comment by Ablu** [comment]
Well it actually was a "bug" (or better shortcoming) in the plugin loader. I fixed it in a404606925c0f0edbc9cee5e04f48d9a7d490d6b by allowing to force it to the FHS guide using the said qmake variable.

**Comment by bjorn** [comment]
Ah right, and if you use this FHS option, then the plugins won't load if you run Tiled without installing it first. So it's mainly for packaging purposes.
