### ISSUE TITLE
Fill tool + random + probability

### ISSUE THREAD

**Issue by cryptk** [bjorn/tiled#1026]
I have a set of grass tiles, one is a plain green color and the other 3 have some faint detail added to them.  They have the following probabilities set on them:

plain green = 1.0
detail1 = 0.01
detail2 = 0.01
detail3 = 0.01

I attempted to select all 4 tiles with the Ctrl key, select random mode, and the fill tool, and it seems like the probabilities are ignored.  It also seems like the probabilities are ignored with the stamp tool as well.

In fact, the only place that it seems like the probabilities are used is with the Terrain tool, which is great, unless you want to fill a really large area and have it match up.

It would be pretty sweet to be able to select multiple tiles (with Ctrl) and the random mode and have it be a "weighted random" to where the probabilities that are set are taken into account.

**Comment by kheftel** [comment]
I'm pretty sure this just got included in the daily builds, though I don't know github well enough to find a link to them.

**Comment by bjorn** [comment]
The daily builds are not hosted on github, they're linked from the [downloads page](http://www.mapeditor.org/download).

And indeed I just implemented this feature in commit 5977e9c080ae69ca056612f6b4c5b170e021ee11.
