### ISSUE TITLE
Map Resize can erase Objects

### ISSUE THREAD

**Issue by Chaoseiro** [bjorn/tiled#1032]
So, it's not really a Bug, just an implementation that I believe is too harsh on the user. Currently, when you resize a map to a smaller width or height, any Object that would stay off-map limits is erased.
I believe a better implementation would be to or leave the objects on their original position, off-limits, or move them inside the map's new limits.

Why that? Well, at least in my case, I have one base map with all objects and properties set, and whenever I'll design a new level, I just resize this base map. The problem is when the new map is smaller than this base, since when the map is resized, any object that would stay off-limits is erased.

I can undo and move the desired objects inside the new map's dimension, and of course I could leave all objects at (0,0), so this problem would not happen.

But I believe that the current implementation can be frustrating sometimes, since there's not even a warning "Some objects will be erased, proceed?".

Here are two images to demonstrate this behavior, see the Door object layer hierarchy:
Base Map (12x6 tiles):
![basemap](https://cloud.githubusercontent.com/assets/1577400/8764959/0fdfbd62-2dcd-11e5-95ac-cafb4c13ef36.PNG)

Base Map Resized (8x12 tiles):
![basemapresized](https://cloud.githubusercontent.com/assets/1577400/8764960/15c1fe3e-2dcd-11e5-9af2-494027f49ada.PNG)

Pull Request #877 can solve this, since I won't need this base map anymore, but maybe that warning message would not hurt :P

**Comment by bjorn** [comment]
Instead of adding a warning message, maybe there should be a checkbox saying something like "Delete objects outside of map boundaries", to make this behavior more explicit as well as optional?

**Comment by Chaoseiro** [comment]
Having this option would be great, since this behavior is hidden from the user until he tries it.

**Comment by IMMZ** [comment]
@bjorn Hi bro! I'm ready to implement this such way => Show message box after resize map dialog 'Do you want to remove objects which are outside of map?' With 'Yes/No' buttons and appropriate behavior. 'Crop to selection' will remove all objects without any messages. I think the last one function is used when user decided to drop all the things which is not in his selection area. Would it be enough? Any corrections, offers?

**Comment by bjorn** [comment]
@IMMZ Why an additional dialog instead of a checkbox like I suggested in my last comment?

**Comment by IMMZ** [comment]
@bjorn, I thing the msgbox would be much noticeable but it's nothing more than my opinion. That could be the checkbox.
1) Where I can should place the checkbox? To resize map dialog?
2) Should it's state be stored between dialog's reopenings or every time the state is %default_state%?
3) What is %default_state%? checked or unchecked?

**Comment by bjorn** [comment]
1) Yes, in the resize map dialog. One problem here is probably, that there is no "map resize dialog". There is only a "resize dialog" which is somewhat more general purpose. So possibly extending it with a checkbox should be optional.

2) Default to the last used state, so store in preferences. See for example how the NewMapDialog does this.

3) Default to remove the objects.

**Comment by bjorn** [comment]
@IMMZ Regarding your question on IRC, feel free to just add that checkbox to the `resizedialog.ui` for now. When we re-use this dialog for resizing something else than a map later (for example, just a layer), we can add some code that hides it.

**Comment by IMMZ** [comment]
@bjorn, ok, thanks. Then I think I can start to implement that.
P.S. What about last words at #930 ? Is that task still active or not?

**Comment by bjorn** [comment]
@IMMZ Sure, the command-line tools could still be made translatable.

**Comment by IMMZ** [comment]
@bjorn, ok that will be the 2nd target since my disappearing

**Comment by bjorn** [comment]
@IMMZ Alright. Nice to see you back, btw!

**Comment by IMMZ** [comment]
@bjorn thanks.
