### ISSUE TITLE
"Tiled.exe has stopped working" Exception Code: c0000005

### ISSUE THREAD

**Issue by Digitehk** [bjorn/tiled#1036]
Hello,

Today I've hit the grind stone hard to learn tons about game design. My findings have lead me to 'Tiled' for it's powerful take on top down development.

Though a huge hang up is causing the software to crash, very quickly, now. After using the software for about 25-30 mins following a tutorial. I was very confused about the "Edit Terrain Information" feature, causing me to have many funny or rather.. out of control tile spawns with one sweep of the mouse. Far greater than the my 3 wide chuck of dirt that I was attempting to path across my map; a small, grass textured 25x25 tile 32x32 pixels ea. And 32x32 base tiles.

After playing around for about more 5 mins, the crashes started. My first thought, was that my failed 'Terrain Edit' was calculating in an incredibly random and intense fashion to cause the crash.

It crashed 3 more times while messing with the editor, and VIOLA! I've learned what to select, and how to avoid the wrong tile mixture.

After opening a fresh project. Same size as my previous, I textured the first layer with grass and moved on to create my path, with a perfect/clean result, it crashes again.

Last but not least, now anytime I click the Terrain Editor, it instantly crashes.

I've used the most recent daily install, to last weeks, and finally to 10.0 from 17-Sep-2014. All with the exact same, recurring crash.

" 
Problem Event Name:	APPCRASH
  Application Name:	tiled.exe
  Application Version:	0.0.0.0
  Application Timestamp:	019ae7c8
  Fault Module Name:	tiled.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	019ae7c8
  Exception Code:	c0000005
  Exception Offset:	00039a64
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
"

Hopefully I can get some assistance to carry on my game dev!

Thanks again~
DigitehK

**Comment by bjorn** [comment]
Unfortunately none of the information you provided would help me to reproduce this crash. Would it be possible for you to send over the files you're working on? Given that the crash is so easy to reproduce for you now indicates it has something to do with the data. If you can't share them publically you can e-mail them to bjorn@lindeijer.nl.

**Comment by bjorn** [comment]
So based on the instructions you sent my e-mail there is one crash I could reproduce, which will happen consistently when pressing the "+" button to add a new terrain type. However, that crash is new and is not happening with Tiled 0.12.3. So maybe you can into some other crash when trying older versions.

**Comment by bjorn** [comment]
Once the next daily build for Windows is available, please try if you can still get it to crash.
