### ISSUE TITLE
Moving objects up/down in object layer

### ISSUE THREAD

**Issue by Cream256** [bjorn/tiled#1037]
Hi!

I have searched though the issues and haven't found similar to this, so I'm posting. 
Could you implement moving objects in the object list up / down? Right now, objects are rendered from top to bottom, and this is an issue in my game. If I could choose which object could be rendered first, just moving it up in the object list, that would be great.

Right now, I have to do it manually in the .tmx file.

Thanks!

**Comment by bjorn** [comment]
Currently, you can't do this in the object list. However, you can change the rendering order in the object context menu, if you enable manual drawing order in the properties of the object layer:

![selection_029](https://cloud.githubusercontent.com/assets/531764/8785514/743f6738-2f28-11e5-8a63-e4057713f936.png)
