### ISSUE TITLE
Hexagonal(staggered)  error

### ISSUE THREAD

**Issue by captals** [bjorn/tiled#1040]
![1](https://cloud.githubusercontent.com/assets/311825/8869177/87b8e378-3213-11e5-833a-3a91a55653e7.png)
When tile width = 14, height=12,the tile is right.When tile width is large than 14, height large than 12.Tile is error.

**Comment by bjorn** [comment]
This vertical line is the "Tile Side Length", which you have set to 6 pixels.

**Comment by captals** [comment]
Tile Side Length in the image is 6.You can see.

**Comment by bjorn** [comment]
@captals I noticed, as per my previous comment. If there is a problem you're trying to point out to me, please be more specific.

**Comment by captals** [comment]
The two side in red circle's length is shorter than is neighbour side.

**Comment by captals** [comment]
I need those two sides have the same size as the six sides of the hexagon.

**Comment by bjorn** [comment]
Then increase the value of the Tile Side Length property. 6 pixels is not enough for the sides to have the same length.

**Comment by captals** [comment]
![Uploading 2.png…]()
![Uploading 3.png…]()
![Uploading 1.png…]()

How can I set Tile Side Length value by Tile width and height?If I set 100 same as width and height,it's error.

**Comment by bjorn** [comment]
> [Uploading 1.png…]()
> [Uploading 2.png…]()
> [Uploading 3.png…]()

If you want to show me screenshots, please wait for the upload to be finished until adding your comment.

I'd say just experiment around with the tile side length after setting your tile width and height, until you're happy with the result. You can see the effect on the grid immediately, right?

**Comment by captals** [comment]
I can't upload image.It always fails.

**Comment by captals** [comment]
![1](https://cloud.githubusercontent.com/assets/311825/8887438/b05a25e8-32b4-11e5-9817-3a5c9064d516.png)
![2](https://cloud.githubusercontent.com/assets/311825/8887439/b1e1094a-32b4-11e5-9c13-80f9fdab25f2.png)
![3](https://cloud.githubusercontent.com/assets/311825/8887440/b1e2467a-32b4-11e5-8438-81da5f1ebd45.png)
How can I set Tile Side Length value by Tile width and height?If I set 100 same as width and height,it's error.

**Comment by bjorn** [comment]
> How can I set Tile Side Length value by Tile width and height?If I set 100 same as width and height,it's error.

Yes, a tile side length that is the same as the tile size does not make much sense, since then the shape is not hexagonal but square. In general, the length of the side is probably more like 2/3rd of the tile size, but it all depends on which tile graphics you'd like to use.
