### ISSUE TITLE
create hexagonal map corner overlap

### ISSUE THREAD

**Issue by captals** [bjorn/tiled#1045]
I have a map image named map.png.I want to create a hexagonal map.But there it a problem exist.When I drag map.png to tile map editor.The tile is squre,not hexagonal.And it lead to image corner overlap.

![1](https://cloud.githubusercontent.com/assets/311825/8903734/a917abc8-348c-11e5-9693-c6c45a77788d.jpg)

**Comment by captals** [comment]
![map](https://cloud.githubusercontent.com/assets/311825/8905490/56d6a424-3499-11e5-826a-ecc964bb3103.png)

**Comment by bjorn** [comment]
There is no support for cutting source tilesets into hexagon shapes. If you want to draw a hexagonal map, you need [hexagon shaped tile images](http://opengameart.org/art-search-advanced?field_art_tags_tid=hexagon).

Eventually I may support cutting hexagons out of textures, but such a feature is currently very low on the priority list. This is because there's a lot of parameters involved and it would only work for "flat" tiles.

**Comment by captals** [comment]
Can software named hexagon shaped tile images. that you recommend use in cocos2d-x game?

**Comment by captals** [comment]
Can software named hexagon shaped tile images. that you recommend use in cocos2d-x game?





At 2015-07-28 16:28:13, "Thorbjørn Lindeijer" <notifications@github.com> wrote:


There is no support for cutting source tilesets into hexagon shapes. If you want to draw a hexagonal map, you need hexagon shaped tile images.

Eventually I may support cutting hexagons out of textures, but such a feature is currently very low on the priority list. This is because there's a lot of parameters involved and it would only work for "flat" tiles.

**Comment by bjorn** [comment]
I don't know if there's any specific software for creating hexagon shaped tile images, but personally I would use either GIMP or Inkscape, depending on the style.

**Comment by captals** [comment]
I see tile collision editor in tile editor map,but I can't find the tutorial document.I want to use use square tile for map and tile collision editor for building hexagon mesh map for pathfinding.Is this solution feasible?

**Comment by captals** [comment]
square tile for building rendering map

**Comment by bjorn** [comment]
Do you expect to draw anything but exact hexagon shapes on your tiles? Because in that case, it will be more efficient to build your mesh for pathfinding in code based on a simple "collides=yes/no" custom property in Tiled.

**Comment by captals** [comment]
I want to draw a map that consist of hexagon tile.But now tile map editor can not auto divide my big image divide into hexagon tile,only rectangle tile.So I have to take second solution that make map consist of two layer,bottom layer that consist of rectangle tile for rendering map and up layer consist of hexagon tile for finding path.Because this game want to find path by hexagon shape tile,not rectangle shape tile.

**Comment by bjorn** [comment]
I'm sorry @captals, but it is your problem to solve. I provide Tiled for free in the hope that it may be useful to others, but if it does not do exactly what you want you either have to change it or solve your problem some other way. Or support me financially so that I can afford to spend more time on adding features to Tiled, so that it may eventually cover also your use-case. Good luck!

**Comment by captals** [comment]
Thank you.I try to solve it by myself first.

**Comment by captals** [comment]
When I want to export as a *.wlk file.It report Not find collision layer.How can I set then I can export a file with postfix .wlk?

**Comment by bjorn** [comment]
There is no reason why you would want to export as `.wlk` file.

**Comment by captals** [comment]
The .wlk file can save my collision information for finding path.

**Comment by bjorn** [comment]
Well, only if your collision information follows the same logic as that of [The Mana World](https://www.themanaworld.org/). Then, you'll need to add a tile layer called "collision". For each tile on this layer that is not the first in its tileset, a 1 is written out while for empty tiles and the first tile of the tileset, a 0 is written out.

**Comment by captals** [comment]
I success export wlk file.But I don't know how to parse it and validate that it is right?

**Comment by bjorn** [comment]
You could try to read the code that writes it to figure out how to read it:

https://github.com/bjorn/tiled/blob/master/src/plugins/tmw/tmwplugin.cpp#L72-L80

But please, you're going off topic on this issue and I have no time to help you.
