### ISSUE TITLE
bjorn/tiled Truck Factor

### ISSUE THREAD

**Issue by gavelino** [bjorn/tiled#1048]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **bjorn/tiled** and obtained a value of **1**.

The developer responsible for this TF is:

Thorbjorn Lindeijer - author of 85% of the files 

To validate our results, we would like to ask **bjorn/tiled** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **bjorn/tiled**?

(b) Do you agree that **bjorn/tiled** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(b) Does **bjorn/tiled** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by bjorn** [comment]
> (a) Do you agree that the listed developer is the main developer of bjorn/tiled?

Yes, that's me.

> (b) Do you agree that bjorn/tiled will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

Me winning the lottery would probably be the best thing that could happen to Tiled (but I don't buy into stupidity tax). If I'd get hit by a bus, Tiled will remain as it is and will probably be useful to people for some time, until somebody else builds a better tool to replace it. Actually, this will eventually happen when I don't get hit by a bus as well, just not as soon.

> (b) Does bjorn/tiled have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

People who have read the source code have found it largely clean and easy to follow.

**Comment by gavelino** [comment]
Thank you for your answer.
