### ISSUE TITLE
Use current save format when Saving As

### ISSUE THREAD

**Issue by mrgan** [bjorn/tiled#1049]
To reproduce: Open a map in the .json format, or create a new map and save it in the .json format. Now click Save As. Note that the format has reverted to .tmx.

My workflow is to create one "template" map, then make minor adjustments and re-save with a new name. Currently, I also have to set the format to .json manually every time I do this.

**Comment by bjorn** [comment]
I think this is a bug and I may have fixed it already as part of a rather large local change. I'll have to check.

**Comment by bjorn** [comment]
Yes, it's fixed by local changes, but the change is too big to go into Tiled 0.13, so I'll make a smaller fix for this issue for this release.
