### ISSUE TITLE
Middle mouse button scrolling in tileset view

### ISSUE THREAD

**Issue by eqstuff** [bjorn/tiled#1050]
I would like to be able to hold down the middle mouse button to scroll in all directions with the mouse inside the tileset view area (the bottom right pane of the editor), similar to how it can be done in the main editing area (it shows an icon of a hand gripping the map).
I have a very large tileset and having to click each individual scroll bar is tedious and slow. Zooming out helps some but the tiles become small, pixelated and hard to distinguish between each other.

**Comment by kheftel** [comment]
fyi scroll wheel scrolls vertically, shift + scrollwheel scrolls horizontally (at least on my mac). might help.
