### ISSUE TITLE
Proposal: Custom properties hierarchy

### ISSUE THREAD

**Issue by gogoprog** [bjorn/tiled#1051]
Hello,

I'd like to be able to set hierarchical custom properties so I can set the following :

Custom Properties:
 - Obstacle
    - Strength : 42
 - Spawner
    - Type : Enemy
    - Interval : 20

...

What do you think?

**Comment by bjorn** [comment]
I think it should be implemented eventually. I'll close this issue since it's a duplicate of #489. :-)
