### ISSUE TITLE
Object's properties aren't shown when changing layer

### ISSUE THREAD

**Issue by IMMZ** [bjorn/tiled#1053]
Tiled: unstable version (tiled-daily: Tiled 2015-08-02 )
Steps to reproduce:
1) Choose any object on obj layer.
2) Add some custom properties to it.
3) Change current layer for any tile layer
4) Change the current layer back to object layer
5) Our object is still selected but custom properties we add are not shown. We should manually click again - they will appear and selection will be changed to rotation mode.

Attached gif animation shows the situation.
![Bug animation](http://s2.postimg.org/dobj56q15/anim.gif)

**Comment by bjorn** [comment]
This is about context and the behavior is as intended. Notice that when you click a layer, the Properties window will show the properties of that layer. If you want it to display the properties of the selected object again, you need to click it again.
