### ISSUE TITLE
JSON format Objectgroup wrong draworder value

### ISSUE THREAD

**Issue by jobayle** [bjorn/tiled#1057]
Dear Tiled developers,

Exporting a map to JSON format produces Objectgroups with the property:
```json
"draworder": "topdown",
```

While it should write:
```json
"draworder": "top-down",
```
as it is defined in the documentation and as it is done in the TMX format.

Thanks.

**Comment by bjorn** [comment]
The bug was in the documentation, actually both JSON and TMX are writing out "topdown". Thanks for the report!
