### ISSUE TITLE
Tile Animation Editor: was showing the wrong tileset

### ISSUE THREAD

**Issue by LearnCocos2D** [bjorn/tiled#1058]
So I came back to my already open Tiled window with multiple maps open. I went straight to "View -> Tile Animation Editor".

The editor window opened but it showed me the tileset of another map. After resizing the window - I think - and re-opening the tile animation editor it showed the correct tileset. Changing the tab to the other map and back did not fix it.

I tried a repro but couldn't. Sorry that the description is vague. If I run into this again I'll update the issue.

**Comment by LearnCocos2D** [comment]
Happened again:

- I had Tiled open with 2-3 maps and went to "View Tile Animation Editor". All fine, it showed me the tileset of the current map.
- I closed the animation editor window.
- I went to finder and opened a couple more TMX files.
- I selected one of the newly opened TMX files, and decided to have a look at the Animation Editor.
- Animation editor opened, showing the tileset of the map in step 1. 
- Closing and reopening the animation editor did not make the tileset of the currently selected map appear.
- I closed the animation editor again, THEN selected a tile in the currently open map's tileset.
- Now the animation editor showed me the current map's tileset.

So it seems the animation editor basically remembers the most recently "selected" tileset and uses that, rather than the currently displayed tileset of the currently displayed map.

**Comment by bjorn** [comment]
Ok, this is a somewhat serious issue because it leads to incorrect undo behavior and can even cause a crash, for example when you undo an animation edit after closing the actually affected map caused the tileset to get deallocated. Thanks for the report!
