### ISSUE TITLE
Tile Animation indicator icon ("film strip") looks odd on some tilesets

### ISSUE THREAD

**Issue by LearnCocos2D** [bjorn/tiled#1061]
On this Iso tileset where tiles have a large height (64x192 whereas grid is 64x33) the tile animation indicator overlay/icons look nothing like film strips:

<img width="281" alt="screen shot 2015-08-26 at 15 52 52" src="https://cloud.githubusercontent.com/assets/214599/9495208/a48c2030-4c0a-11e5-8574-0c95b1d50ad4.png">

It looks quite okay for tilesets with square size and/or tile size not differing from grid size:

<img width="513" alt="tileset-with-anim-tile" src="https://cloud.githubusercontent.com/assets/214599/9495215/af88eeb4-4c0a-11e5-828d-fe5cceb9b5da.png">

**Comment by bjorn** [comment]
Right, that looks quite bad. In fact I always still wanted to get around to tweaking this animation indication based on feedback from @Bertram25 in [this comment](https://github.com/bjorn/tiled/issues/57#issuecomment-33116228). Thanks for opening an issue about it.
