### ISSUE TITLE
Image Layer transparent color property cannot be reset once edited

### ISSUE THREAD

**Issue by Seanba** [bjorn/tiled#1062]
When you first add a new Image Layer to your Tiled file the Transparent Color property is effectively ignored (like how "use transparent color" would behave in Tilesets if you left it unchecked) even though it has a value of black:  \[0, 0, 0] (255).

However, once you edit that property Tiled starts to use it (and save the transparent color out to your TMX file).

My problem is that once you do this you can't go back to having Tiled ignore or stop using the transparent color. Is there a way we can make this a true optional property?

**Comment by bjorn** [comment]
Right, basically it is missing a button to "unset" this value. The only way to do this at the moment is to edit your map file in a text editor and reload it.

And currently, it displays "black" when the value is not set. This is how the Qt Property Browser solution I used works and it could be quite difficult to change this to for example "Not set" in this case.

**Comment by bjorn** [comment]
Just noting that this is basically the same issue as #446.
