### ISSUE TITLE
Saving map fails with access error

### ISSUE THREAD

**Issue by DarkByte** [bjorn/tiled#1065]
While editing the map, saving fails randomly, as in the attached image.

I checked with LockHunter a few times, the file was never in use by any application, except Tiled.

While this issue may not seem much, it gets frustrating really fast (especially since, sometimes, I get the error multiple times in a row) and it sometimes slows the system. It can even take a few seconds for the next dialog (the Save As, since saving in the current file fails) to pop up. (Honestly, I'd even be happy to have an option to skip the automatic Save As dialog that's triggered by this error).

I'm using Windows 7 x64 and Mac OSX 10.10 Yosemite (I have the same problem on both systems).

![image](https://cloud.githubusercontent.com/assets/345800/9618262/e998d33c-510d-11e5-9247-b42780b0f15b.png)

**Comment by bjorn** [comment]
Do you have any idea since when this is happening? If not, could you try if it happens also in older versions of Tiled? Thanks!

**Comment by DarkByte** [comment]
My apologies, it seems to have been a problem related to the Dropbox client. Sorry!

Still, the option to "[Show | Hide] <Save As> dialog if save failed" would be great.

Thank you and sorry again!

**Comment by bjorn** [comment]
I think you're right about the need to suppress the Save As dialog when such an error occurs. I don't think it needs to be an option.

**Comment by DarkByte** [comment]
That would be great, thank you.
