### ISSUE TITLE
Store default custom properties for tiles (instead of object instances)

### ISSUE THREAD

**Issue by caiolopez** [bjorn/tiled#1069]
I couldn't find any way to store custom properties outside a placed object, which makes me always have to open other TMX files to control+c their objects in order to not have to write all the custom properties one by one again. It would be awesome to be able to store their custom property  -- at least their names -- so i can just insert tiles as objects that already bear the property-set ready to be filled in.

**Comment by bjorn** [comment]
I think this is covered by issue #367.

The idea is that there would be a global definition of object types, and that the property editor would display the properties based on the type of the object, regardless of whether these properties are already set in the instance.

**Comment by caiolopez** [comment]
Sorry about the repeated post then. I'll close this one, thank you.
