### ISSUE TITLE
When intalling Tiled switching to English doesn't work

### ISSUE THREAD

**Issue by Ulli-RPG** [bjorn/tiled#1074]
Hey guys,
I just installed the latest Tiled Version on my new Windows 10 system. The following problem occured the same way with my old Win 8.1 64bit.

I'm running a German OS but I prefer to install Tiled in English. Even after choosing English when installing, it's German afterwards.
Is it a valid work around to delete the "qt_de.qm" and "tiled_de_qm"? in the translations folder? With deleting them it switched back to English after a restart.

Thank you!

**Comment by Ablu** [comment]
You can change the language in the settings 
![screenshot from 2015-09-08 19-05-25](https://cloud.githubusercontent.com/assets/741061/9741779/96b1fb22-565c-11e5-8186-a2bf2182fa0a.png)

Though if it does not update after your system changed (and maybe rebooted) it sounds like a bug.

**Comment by bjorn** [comment]
> I'm running a German OS but I prefer to install Tiled in English. Even after choosing English when installing, it's German afterwards.

The language choice in the installer is only for the installer. It does not affect the language used by Tiled. To change that, the usual way is to go into the Preferences and change the language there, as pointed out by @Ablu. But removing the `qt_de.qm` and `tiled_de.qm` files also works of course. :-)

**Comment by Ulli-RPG** [comment]
Ah I see XD 
Thank you very much Ablu & Bjorn!
