### ISSUE TITLE
Suggestion: implement support for exporting files to the Unity engine.

### ISSUE THREAD

**Issue by laetemn** [bjorn/tiled#1076]
Native support for export maps created for the Unity engine would be interesting.

**Comment by HgM3rk** [comment]
Look it up, Someone has already spent a lot of time Implementing this.

**Comment by laetemn** [comment]
THX

**Comment by bjorn** [comment]
Yep, you can do it with [Tiled2Unity](http://www.seanba.com/introtiled2unity.html), which has very good support for Tiled's features.

There is also [Tiled to Unity](https://www.assetstore.unity3d.com/en/#!/content/17260) sold on the Asset Store, which is useful for turning your 2D Tiled map into a 3D environent.
