### ISSUE TITLE
"Collection of Image" ext. Tileset with TSX and images in different subfolders only shows empty map

### ISSUE THREAD

**Issue by LearnCocos2D** [bjorn/tiled#1081]
It seems Tiled 0.13 is no longer able to find "collection of images" tiles if

- the tileset is an external TSX located in a subfolder relative to the TMX file
- the image files are in a different subfolder relative to the TMX file

I assume that this used to work because the user (Brett) reported this as a bug to me, and the setup surely works in TilemapKit (after I fixed a bug). I further assume that Brett isn't using 0.13 because the `tilecount` attribute is absent from the TMX files.

Issue is based on this TilemapKit bug report: http://forum.tilemapkit.com/t/could-not-find-tileset-for-tile-gid-81/

Of the [linked TMX files](http://forum.tilemapkit.com/uploads/default/original/1X/f4e64a8d68febaa90e0e45b73e76048eb9f04cf7.zip) Test.tmx doesn't display anything in Tiled 0.13.0 (and 0.13.1).

I only get an empty map, see: http://forum.tilemapkit.com/uploads/default/optimized/1X/d2f2316dffdbfbb56d17c891c631c4e00894ccf5_1_531x500.png

The folder structure is as follows:

![screen shot 2015-09-13 at 17 19 08](https://cloud.githubusercontent.com/assets/214599/9837335/92a0fcc6-5a3b-11e5-9cb7-63161f60c88a.png)

Note: I removed most PNG files just to keep the size of the screenshot in check, there are a lot more. Also, ignore Test-2.tmx.

**Comment by LearnCocos2D** [comment]
FYI: testing on OSX 10.11 beta. If you can't reproduce let me know, I could re-check on 10.10 next week.

**Comment by bjorn** [comment]
The tile image references from the external tileset are actually wrong. These references should always be relative from the file that contains the reference, not from the map file. This makes sense, right? In your archive, the `.tsx` file is missing the `../` necessary to refer to the tiles correctly.

Tiled should not fail silently in this case, though. That's something I need to fix. The expected behavior in this case would be to report that it can't find the tile images.

**Comment by bjorn** [comment]
Now with change a80fca2a5a72e6f71386d73650afe112137ae7fe, allowing the user to load the map anyway is the correct behavior. However, there should still be a warning shown to the user somehow to notify him that some images failed to load.

Also, it is not possible to correct the image references yet for external tilesets, but that's issue #242.

**Comment by bjorn** [comment]
This problem is taken care of by the recent feedback added when opening a map with broken links. Now, a list of images that Tiled could not find is displayed above the map view.
