### ISSUE TITLE
Rotating buttons at toolbar

### ISSUE THREAD

**Issue by lab313ru** [bjorn/tiled#1084]
It would be great to add these buttons at toolbar. Because rotating only implemented with shortcuts, and there is no visual buttons for that.

**Comment by bjorn** [comment]
Ah yes, same for flipping horizontally / vertically.

**Comment by bjorn** [comment]
I think before implementing this, we need to add the possibility of a tool-specific tool bar, otherwise the UI will get too cluttered. There's other tools that could benefit from such a tool bar as well.

**Comment by ketanhwr** [comment]
@bjorn, what all other tools should be added to this tool bar as well, according to you?

**Comment by bjorn** [comment]
@ketanhwr Well, there's a lot of tools with options that could use visualization in the UI. However, before this can be implemented a tool-specific tool bar needs to be introduced that switches content based on the currently selected tool.

**Stamp Tool** (and probably Bucket Fill tool as well)
* Flip horizontally / vertically
* Rotate left / right
* Random Mode
 
**Terrain Brush**
* "Single corner edit mode" (currently Ctrl modifier)
* "Mirror mode" (current Alt modifier)

**Rectangular Select** (and Magic Wand, Select Same Tile)
* Subtract / Add / Exclusive-Or (currently Ctrl, Shift and Ctrl+Shift modifiers)

And there's some new features that could be a good fit for this as well, like a paint tool where you can control the size of the brush.

**Comment by ketanhwr** [comment]
Oh, this one would kind-of be like a mini-project then.

**Comment by bjorn** [comment]
@ketanhwr Yes, the complex bit is not actually part of this issue, but this issue depends on it. It's the part where each tool can somehow set up tool bar widgets on a context-sensitive tool bar (or a context-sensitive dock widget, which is how GIMP solved it).

**Comment by lab313ru** [comment]
Wow, thank you very much!)
