### ISSUE TITLE
Allow plugins to be enabled/disabled

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1088]
Tiled is shipping with some very specific plugins that are not useful to most people and sometimes even confusing. It should be possible to disable these plugins and some of them should be disabled by default.

Plugins (bold ones will remain enabled by default):

* **csv**
* droidcraft (disable, uses confusing generic `.dat` file extension)
* flare (disable, uses confusing generic `.txt` file extension)
* **json**
* **lua**
* **python**
* replicaisland (disable, uses confusing generic `.bin` file extension)
* tengine (disable, uses `.lua` extension which makes it harder to use the Lua plugin)
* **tmw** (export-only with specific `.wlk` extension)

**Comment by Ablu** [comment]
Why is the tmw plugin enabled by default? I saw at least one case wehre the `.wlk` caused confusion too. Also TMW itself does not use the exporter itself anymore I think but uses a Makefile to do the exporting... So not sure if that is really needed to be enabled by default.

**Comment by bjorn** [comment]
@Ablu I did not expect it to be confusing since it will only show up in "export" and it's clearly labeled. However, if you are right that this direct-export from Tiled is never used by TMW, then it should of course be disabled by default as well.

Hmm, this made me realize that all formats will need to stay available when Tiled is launched with the `--export-map` or `--export-formats` option.

**Comment by bjorn** [comment]
I've done some work on this now. Some notes for when I continue:

Disabling some plugins by default will require storing which plugins the user enabled or disabled explicitly, rather than just keeping a list of disabled plugins.

Also, there should not be a hardcoded list of plugins disabled by default, but rather each plugin should have in its meta data a flag that tells Tiled whether it should be loaded by default.

**Comment by bjorn** [comment]
I've decided to disable all "project specific" plugins, which includes the TMW plugin. Only the general purpose plugins for JSON, Lua, CSV and Python scripts are now enabled by default.

> Hmm, this made me realize that all formats will need to stay available when Tiled is launched with the --export-map or --export-formats option.

And I've decided to keep disabled plugins also disabled for these command line actions. It's nice because it avoids extension ambiguity for the Lua format.
