### ISSUE TITLE
Notify about new releases (update check)

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1089]
Tiled should check automatically for new releases and notify users about the availability of an update, including to show either a list of changes or link to the release notes.

And of course it should be possible to turn this off. Probably even to disable it entirely at compile-time, for distribution packages.

**Comment by bjorn** [comment]
Consider whether to use [Sparkle](http://sparkle-project.org/) and [WinSparkle](http://winsparkle.org/).

**Comment by laetemn** [comment]
That would be extremely helpful!

Include the software WinSparkle in a version '0.14.2' the Tiled to warn the release of new updates, such as Tiled 1.0 would be something very useful.

**Comment by bjorn** [comment]
It does seem easy to integrate, but I may still prefer to do my own so I don't want to rush the decision.

**Comment by bjorn** [comment]
I've just successfully auto-updated a fake Sparkle-enabled Tiled 0.15.0 installed on OS X to a Tiled 0.15.1 test release. Will still need to do some code cleanup before pushing this, and then of course I'll also look at integrating WinSparkle.

**Comment by bjorn** [comment]
Sparkle and WinSparkle are now powering auto-updates of the OS X and Windows snapshots respectively, and it can be turned off or manually triggered from the Preferences dialog. So issue is closed!
