### ISSUE TITLE
TMX icon doesn't appear in x64 version

### ISSUE THREAD

**Issue by lab313ru** [bjorn/tiled#1099]
After installing latest x64 build, and running Tiled, icons for tmx files became empty.

**Comment by bjorn** [comment]
I take it you're talking about the Windows daily builds?

Not sure what may be causing this right now.

**Comment by DrMefistO** [comment]
Yep, I mean daily builds.

**Comment by bjorn** [comment]
Hmm, seems to work for me. I'll close this old issue, but let me know if it's still broken.
