### ISSUE TITLE
Plugin support (maybe).

### ISSUE THREAD

**Issue by laetemn** [bjorn/tiled#1105]
Looking at the amount of insertion of new features in the applications software Tiled.

I began to think it might be interesting to implement a system to support plugins, which would be responsible for, obviously, get new plugins (maybe .dll files), which would be carried by the Tiled and would then show its features in the main program interface or through dialog boxes that would be invoked by key combination.

PS: Sorry my English. I'm using Google Translator.

**Comment by bjorn** [comment]
Tiled already supports C++ plugins that add support for loading and saving new map and tileset formats. And one of the plugins shipping with Tiled is a Python plugin that allows you to write Python scripts that add support for new formats.

Extending the plugin system to handle more use-cases is covered by issue #454.
