### ISSUE TITLE
JSON tilesets working great, but can't import existing ones

### ISSUE THREAD

**Issue by MikauSchekzen** [bjorn/tiled#1108]
I'm facing an issue with the release of Tiled 0.14.1 on Windows 10 where I can't import tilesets saved as JSON format via the program itself. The only option I get is .tsx format. There is a dropdown menu to select a file format to import, but it only lists .tmx.

For now, I can add the tileset manually via a text editor(also taking firstgid into consideration, of course), but it's annoying and most likely shouldn't be this way.
![issue](https://cloud.githubusercontent.com/assets/2879734/10280529/169e72fe-6b6e-11e5-87a2-5ede4264f252.jpg)

**Comment by bjorn** [comment]
Ouch, that's a rather unfortunate oversight. :-(
