### ISSUE TITLE
Tabbed maps share current tool

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#1110]
If I open Map A that uses Tileset X and Map B that uses Tileset Y, select a tile from Y and tab back over to A, the cursor still shows B/Y's tile. Each map should probably have its own memory for the Stamp Tool. It's probably a non-issue for other tools.

**Comment by bjorn** [comment]
This is intentional. The assumption is that the user is generally working on a set of related maps, and this feature allows quickly copying areas between maps.

**Comment by karai17** [comment]
The issue I see is that you might not be using the same tilesets, or have
them named the same way, so it confuses me how Tiled can do this reliably.
Another issue is that in my example, each map had a single tileset that was
not the same as the other (different name, different image) so switching
between maps becomes very odd.

Perhaps only perform this action when both maps contain the same tileset
(check by image path i guess?) and update the UI so that the next map's
selected tileset is the appropriate one?


---
Landon Manning
lmanning17@gmail.com

**Comment by kheftel** [comment]
If Map B doesn't have Tileset X, and you draw tiles into it from Tileset X, tiled adds tileset X to the map. 

It's pretty straightforward in my opinion.

Here's a sample screen recording:

![multipletilesets](https://cloud.githubusercontent.com/assets/669328/10315791/91b07f90-6c19-11e5-8624-e97840bda7e3.gif)

**Comment by bjorn** [comment]
Right, thanks @kheftel for providing that nice demonstration!

@karai17 This feature works well together with the recently introduced Tile Stamps widget, where you can store tiles pieces persistently for use in any map. If a map does not have the required tilesets, they will be added as soon as you try to paint with the stamp. It can be a very nice way of avoiding the whole adding of tilesets procedure.

Of course there can be strange cases like taking an orthogonal stamp and painting with it on an isometric map. But I see currently no reason to disallow people from doing that.
