### ISSUE TITLE
Copy/Cut/Paste between .tmx files

### ISSUE THREAD

**Issue by awasem** [bjorn/tiled#1113]
There are a few issues here and I am not sure how they are related or how to properly explain so please bear with me.

When copy/cut and pasting from one .tmx to another Tiled incorrectly pastes the wrong image. It seems to be in issue with how the tile ids are numbered when you look at the .json file. It seems that when it numbers them individually to get the tile id # it gets confused about what tile set it is in when it is copy/cut/pasted. You can move different tile sets into the far left and get different images pasted after on single copy action. For instance, it is like it is pasting from the left tile set row 2 column 3 regardless of the the actual tile set it is copied from. 

When I copy a bunch of tiles from file A and put them in file B it does not recognize which are in B already and which are not, so it creates a duplicate tile set from file A in file B. But the tiles it actually pastes are from the original set from B which are not the correct tile images.

If I have two tile sets X and Y. Y is on the left and X is on the right. I copy something from tile set X row 2 column 3 and paste it. It pastes from tile set Y row 2 column 3. Without copying anything else, If I then switch X and Y so tile set X is on the left and the proper tile is located in row 2 column 3 it will paste the correct tile.

**Comment by EdenIndustries** [comment]
For what it's worth, I also get this odd behaviour from time to time, though I haven't figured out any repro case.

**Comment by kheftel** [comment]
Are you changing the order of tile sets between the copy and paste operations?

**Comment by awasem** [comment]
Yes, this seems to work mostly when there are only 2 different tile sets. When there are 3 or more it mostly pastes a blank tile like this screenshot.
![screenshot 2015-10-07 10 21 42](https://cloud.githubusercontent.com/assets/15002425/10345313/a98fe212-6cdd-11e5-8a4f-6b52f397fccb.png)
![screenshot 2015-10-07 10 22 17](https://cloud.githubusercontent.com/assets/15002425/10345314/aa2e1680-6cdd-11e5-858d-1af646604bab.png)

**Comment by awasem** [comment]
as you can see here the texture file is located in both tile-sets, and both are located in
{
         "firstgid":1,
         "margin":0,
         "name":"spin-tiles",
         "properties":  
}
but with different id numbers. "345"  and "136"
![screenshot 2015-10-07 10 36 16](https://cloud.githubusercontent.com/assets/15002425/10345733/87f33688-6ce0-11e5-864a-c04a599413a6.png)
![screenshot 2015-10-07 10 44 49](https://cloud.githubusercontent.com/assets/15002425/10345734/88063bf2-6ce0-11e5-81e3-cbef112e9ec4.png)

**Comment by awasem** [comment]
I am copying from AW_sampleLevel_v1-L01-twoset_3 to AW_map_source_2015-10-06

**Comment by bjorn** [comment]
@awasem Until you posted some screenshots I had not realized you were talking about copy/pasting tile objects, as opposed to pasting pieces of a tile layer. Similarly, I did not know you were dealing with embedded image collection tilesets.

I can imagine these use-cases are currently not working as expected, since they will need some extra logic which I had not thought about yet. I will have a look at what I can do about these things as soon as I have some time.

**Comment by awasem** [comment]
Okay great! thanks for your help and for your patience while I try to communicate the issue. Your work is much appreciated!

**Comment by bjorn** [comment]
Please let me know if you still see issues with this in Tiled 0.14.2.

**Comment by awasem** [comment]
Hi Bjorn! I have been using 0.14.2 for a solid week now and it has been working flawlessly! I am copying and pasting all over the place! Thanks!

**Comment by bjorn** [comment]
@awasem That's great to hear, thanks!
