### ISSUE TITLE
Open multiple maps into tabs, not windows

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#1116]
If I select several maps and open them, Tiled spawns an individual window for each map. I think a better solution here would be to open a single window and load each map into a new tab.

In addition to this, add a new item to File to create a new window and allow users to drag tabs between windows. That would be pretty swanky.

**Comment by kheftel** [comment]
For me, the latest released version of Tiled (0.14.1) on OSX already opens multiple maps as tabs, not windows, even if Tiled was previously closed.

**Comment by karai17** [comment]
My observances are on Windows 10.

**Comment by kheftel** [comment]
I can confirm that this does happen on windows 8.1 as well, in tiled 0.14.1

**Comment by bjorn** [comment]
It is an OS X feature to reuse the same application instance to open files and Qt / Tiled support this feature. On Windows and Linux, Tiled will need to implement this kind of logic by itself. Fortunately, a Qt solution called QtSingleApplication is available which could be integrated.

**Comment by bjorn** [comment]
I picked this task for the first pair-programming session with @willluongo. We took a bit longer than 2 hours, which is really not bad.

People who like to open their maps from the file manager or console should love this. And if not, there's the `--new-instance` command line option to override this behavior.
