### ISSUE TITLE
Error in the language selection screen

### ISSUE THREAD

**Issue by laetemn** [bjorn/tiled#1119]
@bjorn 

Apparently there is an error in the language selection screen.
In the first line should be listed Portuguese (Portugal), but is listed Portuguese (Brazil).

The second line is correct!

**Comment by bjorn** [comment]
Heh, right, I vaguely remember noticing that before. Now I looked into the problem and pushed a fix to the 0.14 branch. This issue will close when it is merged to master.

**Comment by bjorn** [comment]
Note that the Brazil translation is now called `tiled_pt.ts` and no longer `tiled_pt_BR.ts`. This is mainly to make sure it works as fallback for Portuguese regardless of the country. The Portuguese Portuguese files is now called `tiled_pt_PT.ts`.

You can, but you don't need to change your pull request regarding this. I'll make sure to apply the updates to the right file.

**Comment by laetemn** [comment]
OK.
Thank you! :+1: :D
