### ISSUE TITLE
Missing documentation for hexagonal map attributes in the TMX File Format page

### ISSUE THREAD

**Issue by baylej** [bjorn/tiled#1122]
Dear Tiled developers,

The [TMX File Format page](http://doc.mapeditor.org/reference/tmx-map-format/) does not seem to have documentation for the *hexagonal* map orientation and attributes that were added in Tiled 0.11

According to [the changelog page](http://doc.mapeditor.org/reference/tmx-changelog/):

> Tiled 0.11
> • Added hexagonal to the supported values for the orientation attribute on the map element. This also adds staggerindex (even or odd) and staggerdirection (rows or columns) and hexsidelength (integer value) attributes to the map element, in order to support the many variations of staggered hexagonal. The staggerindex attribute is now also supported when using the staggered map orientation.

Using tiled 0.11 to produce an hexagonal map, in the TMX file I find the *staggerindex* attribute, but no *staggerdirection* attribute, instead there is a *staggeraxis* attribute, but it is not documented.

Documentation for **map.nextobjectid** is also missing.

Thanks.

**Comment by bjorn** [comment]
This has been done eventually.
