### ISSUE TITLE
Use an eye icon instead of a checkbox for layer visibility

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1127]
Would look nicer and be more intuitive. It's what all other graphical applications are doing!

Also this would allow extending it with a lock icon later on, when implementing #734.

**Comment by CaptainFrog** [comment]
+1 for this!

**Comment by IMMZ** [comment]
I'll put it in my 'Tiled Contribution Pack'.
Some moments:
1. Where to get icons?
2. What about implementation? I offer to create a new class 'LayerCheckBox' with properties 'locked' and 'visible'. If i correct icon could be shown by reimplementing paint (...) func.
