### ISSUE TITLE
Menu bar missing using Ubuntu 14.04 and AwesomeWM

### ISSUE THREAD

**Issue by alesegdia** [bjorn/tiled#1132]
I tried by pressing all F# buttons, also ALT and nothing shows. When I enter in Ubuntu's default Unity window manager, I can see the bar only when the window is maximized, but if the window is floating, the same issue appears.

**Comment by bjorn** [comment]
Do you see this issue only with Tiled? It does not sound related to Tiled but rather to some patches Ubuntu may be applying to Qt to get the menu bar to behave differently in Unity.

**Comment by alesegdia** [comment]
Well, it is present with XChat for example, but pressing F9 solves the issue. Also, don't really know if XChat uses Qt. QtCreator works flawless. I also thought it could be a Unity related issue, some kind of config but have tried hard searching for it and found nothing. I also asked at AwesomeWM people. 

Everyone seems to be throwing the issue to the outside, and I completely understand it. I'm somehow convinced it does not have anything to do with Tiled but I'm so desperate that I tried here too, just to check if this could be solved around here.

Thanks for your attention anyway, I'll try harder (if that's possible) and come with news if I get something clear.

**Comment by bjorn** [comment]
> Also, don't really know if XChat uses Qt.

It doesn't, XChat is based on GTK.

> QtCreator works flawless.

Did you install it via your system package management or via the Qt Online Installer? The latter uses its own version of Qt and now your system one.

**Comment by alesegdia** [comment]
Neat. Maybe I have the Qt Online Installer version.

Qt Creator info:

```
Based on Qt 5.5.0 (GCC 4.9.1 20140922 (Red Hat 4.9.1-10), 64 bit)
```

And then:

```
$ dpkg -s qt5-default
(...)
Version: 5.2.1+dfsg-1ubuntu14.3
(...)
```

I'll try to compile tiled with the Qt version of the Online Installer and tell.

**Comment by alesegdia** [comment]
Yes yes yes! Solved! Thanks for the hint. Silly of me that didn't try that earlier. I just thought that if everyone uses repository version of Qt, mine should work too. Now I see it didn't have to.

This saved the day. I was annoyed of having to use any other window manager to use tiled. I guess there is some issue with Ubuntu 14.04 Qt repo version, at least when not using Unity.

Thanks again.

**Comment by bjorn** [comment]
So it's probably a bug with the patches Ubuntu is applying to Qt to make it do its menubar thing in Unity, affecting AwesomeWM users for probably all Qt applications.

Since your version of Ubuntu is ancient, you could try upgrading to 15.10 to see if the issue has been fixed in the meantime.

I'll close this issue since there isn't really something I can do about in Tiled, apart from distributing binaries shipping their own version of Qt, but that's not something I have time for right now and besides, that may cause issues for Unity users, who would not get the expected menubar behavior.

**Comment by alesegdia** [comment]
I prefer to continue using 14.04 since it's the long term version, but I hope they fixed this. Yes, it totally does not make sense to keep this issue opened. Anyway, it may help others having the same problem. Thanks again!

**Comment by bjorn** [comment]
Removing the `appmenu-qt5` package also resolves the issue, providing an alternative to compiling Tiled yourself (https://twitter.com/darkgodone/status/669468417032912897).

The only downside should be that the menu bar for any Qt 5 applications will no longer integrate with Unity.
