### ISSUE TITLE
Reducing map size with overlayed objects

### ISSUE THREAD

**Issue by HexTank** [bjorn/tiled#1133]
If you have a big map that is larger than your physical screen and you have an object, say a rectangle or poly lines that wrap the edges of the map, then you reduce the map to something smaller, you can't then change the poly points of the objects as there's no way to scroll to select the points.

It seems the scroll bars need to take in to account all layers max extents rather than just the map size itself.

**Comment by bjorn** [comment]
Yeah, that's pretty much a bug in this use-case. It's also related to issue #245.

**Comment by bjorn** [comment]
This bug is largely fixed now that #245 is done (now you can pan over the edges as well as use the mini-map to navigate there). In the next new feature release of Tiled, you can also use the mouse wheel to scroll past the edges (change dab4f29c1acc9adeb2c2ffff1afe763509fd7832).
