### ISSUE TITLE
Tiled crashes on startup after upgrading to 0.14.2

### ISSUE THREAD

**Issue by theoutlander** [bjorn/tiled#1134]
I think I was on 0.12.2 or something from a few months ago. I was just using it fine and decided to check if there were updates. After installing the latest, the app crashes on startup. I tried disabling opengl too, but that's not the issue based off the error I'm seeing. I wasn't able to pinpoint the issue with process monitor either, but it appears that it cannot open some file that it's looking for. I was organizing some of my assets/tmx files earlier, but I even reverted those so their paths were same as before, but it still crashes.

![image](https://cloud.githubusercontent.com/assets/749084/10836118/369fd2a8-7e67-11e5-80b7-4ee257f92c6e.png)

**Comment by bjorn** [comment]
Did you try downgrading to Tiled 0.12.2 to check if this is a new problem?

The screenshot you post only shows an error dialog. What you're saying is that after pressing Ok there, Tiled crashes? If so, would it be an option for you to compile Tiled yourself and run it in the debugger to pinpoint exactly where in the code it goes wrong?

**Comment by theoutlander** [comment]
After about 15 attempts, it just launched and I can't get it to crash again. I can certainly try building it locally (later this week) and circle back.

**Comment by tasogare3710** [comment]
It failed to startup in my environment (win 10 pro build 10240), version 0.12.3 In no problem.

Although I was examined by VS JIT debugger has thrown the exception Qt5Gui.dll! 0x01063100.

**Comment by toddcarnes** [comment]
When I build the 32 bit version using Mingw 4.9.2 and Qt 5.5 (64 bit Widows 10), everything works just fine. I can't try the 64 bit and/or the Visual Studio flavors right now.

**Comment by bjorn** [comment]
@toddcarnes But do you see the problem with the provided binaries?

**Comment by SourceR85** [comment]
In my case, Tiled crash when i try to open the Maps-View. (Tiled 0.14.2 32 bit, Win10 x64)

**Comment by bjorn** [comment]
@SourceR85 Then in your case it's almost certainly because you've enabled the OpenGL rendering option in the Preferences. I recommend to just leave it disabled for now.

**Comment by toddcarnes** [comment]
I will try them when I get home from work today.

**Comment by toddcarnes** [comment]
I tried downloading and installing both the 32 bit and the 64 bit versions.Both of them started right up for me with no crashes.

**Comment by bjorn** [comment]
Closing this old issue because it has no sufficient information to fix anything and no hope that this would ever change.
