### ISSUE TITLE
Long name of layer leads to crash

### ISSUE THREAD

**Issue by varnie** [bjorn/tiled#1136]
Hello. 
I have Tiled version 0.14.2 compiled from the source code manually, Ubuntu 14.04.3 LTS
Tiled gets coredumped when it has a layer with very long name.

Steps to reproduce:
Open Tiled, create new map (width: 10 tiles, height: 10 tiles, tile size: 32px, tile height: 32 px), then press and *hold* "ctrl+shift+D" for some time, until it crashes with:

> QXcbShmImage: shmget() failed (22) for size 34169756 (11881x719)
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5853, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5854, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5855, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5856, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5859, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5867, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5868, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5869, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5870, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5871, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5872, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5873, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5874, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5875, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5876, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5877, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5878, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5879, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5880, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5881, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5882, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5883, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5884, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5885, resource id: 11881, major code: 130 (Unknown), minor code: 3
 QXcbConnection: XCB error: 2 (BadValue), sequence: 5886, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5887, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5888, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5889, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5890, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5891, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5892, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5893, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5894, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5895, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5896, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5900, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5901, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5902, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5903, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5904, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5905, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5906, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5907, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5908, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5909, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5910, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5911, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5912, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5913, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5914, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5915, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5916, resource id: 11881, major code: 130 (Unknown), minor code: 3
QXcbShmImage: shmget() failed (22) for size 35682532 (12407x719)
QXcbConnection: XCB error: 2 (BadValue), sequence: 5926, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5927, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5928, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5929, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5932, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5938, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5939, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5940, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5941, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5942, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5943, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5946, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5947, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5948, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5949, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5950, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5951, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5952, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5953, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5954, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5955, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5956, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5957, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5958, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5959, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5960, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5961, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5962, resource id: 12407, major code: 130 (Unknown), minor code: 3
QXcbShmImage: shmget() failed (22) for size 37606576 (13076x719)
QXcbConnection: XCB error: 2 (BadValue), sequence: 5972, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5973, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5974, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5975, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5978, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5984, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5985, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5986, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5987, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5988, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5989, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5992, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5993, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5994, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5995, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5996, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5997, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5998, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 5999, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6000, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6001, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6002, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6003, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6004, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6005, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6006, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6007, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbConnection: XCB error: 2 (BadValue), sequence: 6008, resource id: 13076, major code: 130 (Unknown), minor code: 3
QXcbShmImage: shmget() failed (22) for size 39530620 (13745x719)
Segmentation fault (core dumped)

I guess there should be some limit for the max. number of available layers.
I'd be glad to provide more relevant information if you need.

**UPDATE**
Oh, I just discovered what caused the issue. **It is not the large number of layers, it is the long name of the layer!** If we have a single layer, which has very long 'name', then it tends to crash. For example, try to load the following tmx file: https://www.dropbox.com/s/q4156qb8lix3m9d/TILED-long-layer-name-leads-to-crash.tmx?dl=0

What's even worse is that now Tiled crashes every time I run it! It tries to restore the previous loaded map somehow and crashes. I managed to resolve that by updating my ~/.config/mapeditor.org/tiled.conf and now Tiled starts again :-)

**Comment by bjorn** [comment]
Alright, it didn't crash for me, but it did make Tiled completely unusable and have render artifacts:

![workspace 1_059](https://cloud.githubusercontent.com/assets/531764/11038699/97a382f2-8704-11e5-9bb4-1884d23c8be7.png)

This is really a Qt issue, but I guess I'll try trimming the layer names to some reasonable length to avoid it.

**Comment by bjorn** [comment]
This is probably due to the layer name display in the status bar, which causes the main window to grow. It's probably hitting some limit there. So should be fixed by avoiding the label from increasing the window's minimum width.

**Comment by bjorn** [comment]
So, I didn't actually manage to stop the label from growing (and a QLabel has no built-in elide support, it seems). But, I replaced the label with a combo box, which I think was even better.
