### ISSUE TITLE
Function that takes a tile as argument and selects it?

### ISSUE THREAD

**Issue by njairath** [bjorn/tiled#1143]
I've been attempting to implement a feature that selects all tiles with a given set of custom properties, but I'm having trouble figuring out how to select particular tiles without a mouse click event. Is there a function that takes a tile as an argument and selects it? I've been searching through the codebase for a few days now, but haven't been able to find it.

**Comment by bjorn** [comment]
You change the tile selection by using `MapDocument::setSelectedArea`, or using the `ChangeSelectedArea` undo command if you want it to integrate with undo/redo (recommended).

You can make a `QRegion` based on a certain tile selection criteria by using `TileLayer::region`, passing in a function that returns whether a certain cell should be part of the region (see other uses for examples).
