### ISSUE TITLE
new object-shapes: circles and points

### ISSUE THREAD

**Issue by rellig** [bjorn/tiled#1149]
I would like to have the option to add a "real" circle instead of an ellipse. Defined by center and radius. My current workarround is to just use an ellipse and ignoring the width, using height as radius, but it feels dirty to me.

Related to that I would also like to add a simple point. A shape with just one dimension. Currently I use a polyline and ignore the actual line. Same "problem" as above, it just doesn't feel right.

**Comment by bjorn** [comment]
I don't see why it matters how you define the circle/ellipse, but I can imagine an option to fix the ratio of the ellipse to 1:1 would be useful. Note that you can already hold Shift while placing, or Ctrl while resizing, to keep the ellipse a circle. (and I only now realized the inconsistency that crept into there... sorry about that)

Adding a separate object type for marking points would certainly make sense. It has come up before, like on issue #1137.

**Comment by rellig** [comment]
Thanks! I already use Shift/Ctrl to keep my view in tiled clean. And I can see why it seems strange to have an extra object for a "special ellipse".

As I said, both issues can be easily worked arround. I just wanted to mention it here and see if maybe someone else thought alike.

And thanks for your work on this project, bjorn!

**Comment by bjorn** [comment]
You're welcome, @rellig. Thanks for the feedback! :-)

**Comment by bjorn** [comment]
Closing this issue since the remaining missing feature, point objects, is already covered by issue #661.
