### ISSUE TITLE
Proposal: Bezier curves (or similar splines)

### ISSUE THREAD

**Issue by JesseTG** [bjorn/tiled#1150]
I know that we can already encode Bezier curves, B-splines, or similar just by using a polyline...but different libraries may compute curves differently, and occasionally using the completely wrong name.  Maybe we can implement splines by encoding them as polynomials or something?

**Comment by bjorn** [comment]
Duplicate of issue #562.

Also see pull request #776.

**Comment by JesseTG** [comment]
Ah, crap.  Sorry about that.
