### ISSUE TITLE
Large Tiles Do Not Draw Properly

### ISSUE THREAD

**Issue by tragicmanner** [bjorn/tiled#1151]
When working in a map that has 8x8 tiles, using 32x32 tiles only draws 13 of the necessary 16 tiles:

![13outof16](https://cloud.githubusercontent.com/assets/5327369/11575004/1bf54bb0-99cc-11e5-8551-cb1d7d83509a.png)

Steps:
1. Create a project that has an 8 x 8 tilesize
2. Import a tileset that is made up of 16 8x8 tile "blocks"
3. Only 13 of the 16 tiles draw when using the stamp with them

**Comment by bjorn** [comment]
Actually the entire 32x32 tile is drawn, but the smaller 8x8 tiles to its right are drawn on top of it.

It is probably easier if you add your tileset as 8x8 tiles if your map is using an 8x8 grid.

If you don't care that some smaller tiles are drawn below, you can also change the Tile Render Order of your map. If you put it on "Left Down" then you won't generally have other tiles on top, unless they are also larger than 8x8.
