### ISSUE TITLE
Toolbar Button Toggle for Preferences > AutoMapping > Use Automapping, when drawing

### ISSUE THREAD

**Issue by Red-Eagle-LXIX** [bjorn/tiled#1152]
Reason:
At times one wants to have the rules applied immediately while working.  However, during development of rule sets, it is often imperative to see how Tiled's Terrain Tool and Stamp tools will act on their own without rules.
Currently it is rather inconvenient to switch the use of AutoMapping on and off during the same session.

A quick toggle button on the toolbar would facilitate the speed at which the compares between rules active and rule inactive during drawing would help this.

**Comment by bjorn** [comment]
I guess another menu item just below "AutoMap" would suffice as well? I don't want to clutter the tool bar too much.
