### ISSUE TITLE
"Maximizing" Tiled main window (windows 10) is causing Tiled to crash instantly

### ISSUE THREAD

**Issue by caiolopez** [bjorn/tiled#1153]
Will happen by clicking the maximize button, by double clicking the window handle, and by clicking the left window menu command, and also via keyboard shortcuts.

**Comment by bjorn** [comment]
Ok, a few questions:

* Since when does this happen?
* Do you have OpenGL mode enabled?
* Does it also happen more generally when resizing the window?

I guess it could be the same issue as reported [here on the forums](http://forum.mapeditor.org/t/crash-on-resize/953), but so far I don't know what could be causing this yet.

**Comment by caiolopez** [comment]
Thank you for the quick response, bjorn!

It only happens when I resize Tiled's window. Can't be sure when it stopped working -- I don't recall using Tiled on my recently formated Windows 10 machine. I'd guess it stopped working over here on windows 10, Tiled version 0.14.1, but I can't be sure.

Interesting and quite scary fact: just clicked the "use openGL accelerated..." checkbox and tiled crashed instantly, and for good. It won't open again for more than a few seconds without crashing again :\\ Is there a config file I can delete to restore tiled defaults? Danke!

**Comment by caiolopez** [comment]
And no, resizing tiled window was ok, as long as I woulnd MAXIMIZE it.

**Comment by bjorn** [comment]
Command line to the rescue:
```
tiled.exe --disable-opengl
```
So you're using the stable release and not a daily build? That's really annoying to have a crash on maximize in there. :/

**Comment by caiolopez** [comment]
Yup, I only use stable releases of Tiled :P
Caio used Command Line, it was very effective, thank you! Obviously, crashing on maximize is still there, though I can just not maximize it.
How else can I help to solve this problem?

**Comment by bjorn** [comment]
If you feel adventurous, you can help by checkout out Tiled from the git repository, compiling and running it yourself with [Qt](http://www.qt.io/download-open-source/) in debug mode, cause then when it crashes it will be able to show more information.

In any case, I'll reboot to Windows 10 and try maximizing Tiled soon.

**Comment by caiolopez** [comment]
I'll try that! As a non-programmer, it might take a little while to get the whole thing up and running, though :\

**Comment by bjorn** [comment]
@caiolopez I've just rebooted to Windows 10 and tried maximizing Tiled 0.14.2 32-bit. Unfortunately, it is not crashing for me, leaving me with no clue as to what may be wrong. :-(

**Comment by caiolopez** [comment]
I'll see what I can do. Thank you, bjorn

**Comment by SourceR85** [comment]
Okay... i confirm the same problem on my system (Win 10 x64 Pro).
Tiled (v0.14.2, without OGL) is in maximized state when i start it. minimize > maximize > crash.

**Comment by caiolopez** [comment]
Yay, I'm not alone! Now please tell me you're into coding/debugging,
because I'm a complete noob at this :\

**Comment by SourceR85** [comment]
I tried to build Tiled but i need help with Qt Creator...
i got a linker-error:
```
LINK : fatal error LNK1104: Datei "python27_d.lib" kann nicht geöffnet werden.
jom: C:\Repos\build-tiled-Desktop_Qt_5_5_1_MSVC2013_64bit-Debug\src\plugins\python\Makefile.Debug [..\..\..\plugins\tiled\python.dll] Error 1104
jom: C:\Repos\build-tiled-Desktop_Qt_5_5_1_MSVC2013_64bit-Debug\src\plugins\python\Makefile [debug] Error 2
jom: C:\Repos\build-tiled-Desktop_Qt_5_5_1_MSVC2013_64bit-Debug\src\plugins\Makefile [sub-python-make_first] Error 2
jom: C:\Repos\build-tiled-Desktop_Qt_5_5_1_MSVC2013_64bit-Debug\src\Makefile [sub-plugins-make_first-ordered] Error 2
jom: C:\Repos\build-tiled-Desktop_Qt_5_5_1_MSVC2013_64bit-Debug\Makefile [sub-src-make_first-ordered] Error 2
18:48:30: Der Prozess "D:\Qt\Tools\QtCreator\bin\jom.exe" wurde mit dem Rückgabewert 2 beendet.
Fehler beim Erstellen/Deployment des Projekts tiled (Kit: Desktop Qt 5.5.1 MSVC2013 64bit)
```
Can someone help me with the settings (and where i can find the Linker-Paths settings)?
Its a while since i used a C-IDE/Compiler...

**Comment by SourceR85** [comment]
Finaly i got en error message for you:
```
The inferior stopped because it triggered an exception.

stopped in thread 0 by: Exception at 0x7ffa3daeb9ec, code: 0x0000005: write access violation at: 0x1, flags=0x0 (first chance)
```

**Comment by SourceR85** [comment]
i think this might help you more:
```
0	QRasterPaintEngine::penChanged	qpaintengine_raster.cpp	686	0x7ffe40abc3cd
1	QPainter::setPen	qpainter.cpp	3857	0x7ffe40adc7a9
2	QCommonStyle::drawControl	qcommonstyle.cpp	2197	0x6e97c4e8
3	QWindowsStyle::drawControl	qwindowsstyle.cpp	1864	0x6ea37721
4	QWindowsXPStyle::drawControl	qwindowsxpstyle.cpp	2533	0x6ea194c0	
5	QWindowsVistaStyle::drawControl	qwindowsvistastyle.cpp	1467	0x6ea05ca1
6	QStyledItemDelegate::paint	qstyleditemdelegate.cpp	414	0x6edd6b67
7	QTreeView::drawRow	qtreeview.cpp	1769	0x6ed50492	
8	QTreeView::drawTree	qtreeview.cpp	1504	0x6ed4f5c2	
9	QTreeView::paintEvent	qtreeview.cpp	1329	0x6ed4eff9	
10	QWidget::event	qwidget.cpp	8831	0x6e909811	
11	QFrame::event	qframe.cpp	540	0x6eaeccdf	
12	QAbstractScrollArea::viewportEvent	qabstractscrollarea.cpp	1200	0x6ebc9c8c	
13	QAbstractItemView::viewportEvent	qabstractitemview.cpp	1686	0x6ece9eca	
14	QTreeView::viewportEvent	qtreeview.cpp	1310	0x6ed51c40	
15	QAbstractScrollAreaPrivate::viewportEvent	qabstractscrollarea_p.h	102	0x6e896025	
16	QAbstractScrollAreaFilter::eventFilter	qabstractscrollarea_p.h	118	0x6ebceccd	
17	QCoreApplicationPrivate::sendThroughObjectEventFilters	qcoreapplication.cpp	1072	0x6f7ad3eb	
18	QApplicationPrivate::notify_helper	qapplication.cpp	3712	0x6e8a1f96	
19	QApplication::notify	qapplication.cpp	3681	0x6e89f773	
20	QCoreApplication::notifyInternal	qcoreapplication.cpp	965	0x6f7ac9a4	
21	QCoreApplication::sendSpontaneousEvent	qcoreapplication.h	227	0x6f90e4ec	
22	QWidgetPrivate::sendPaintEvent	qwidget.cpp	5628	0x6e9130cd	
23	QWidgetPrivate::drawWidget	qwidget.cpp	5569	0x6e912bc8	
24	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5761	0x6e913617	
25	QWidgetPrivate::drawWidget	qwidget.cpp	5619	0x6e913065	
26	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5761	0x6e913617	
27	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5748	0x6e9134e4	
28	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5748	0x6e9134e4	
29	QWidgetPrivate::drawWidget	qwidget.cpp	5619	0x6e913065	
30	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5761	0x6e913617	
31	QWidgetPrivate::drawWidget	qwidget.cpp	5619	0x6e913065	
32	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5761	0x6e913617	
33	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5748	0x6e9134e4	
34	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5748	0x6e9134e4	
35	QWidgetPrivate::paintSiblingsRecursive	qwidget.cpp	5748	0x6e9134e4	
36	QWidgetPrivate::drawWidget	qwidget.cpp	5619	0x6e913065	
37	QWidgetBackingStore::doSync	qwidgetbackingstore.cpp	1229	0x6e8bb68a	
38	QWidgetBackingStore::sync	qwidgetbackingstore.cpp	1033	0x6e8b8a9b	
39	QWidgetPrivate::syncBackingStore	qwidget.cpp	1904	0x6e915790	
40	QWidgetWindow::handleResizeEvent	qwidgetwindow.cpp	705	0x6e94fc7c	
41	QWidgetWindow::event	qwidgetwindow.cpp	233	0x6e94e3ba	
42	QApplicationPrivate::notify_helper	qapplication.cpp	3716	0x6e8a1fb6	
43	QApplication::notify	qapplication.cpp	3160	0x6e89ccdb	
44	QCoreApplication::notifyInternal	qcoreapplication.cpp	965	0x6f7ac9a4	
45	QCoreApplication::sendSpontaneousEvent	qcoreapplication.h	227	0x6f90e4ec	
46	QGuiApplicationPrivate::processGeometryChangeEvent	qguiapplication.cpp	2069	0x7ffe407202c3	
47	QGuiApplicationPrivate::processWindowSystemEvent	qguiapplication.cpp	1594	0x7ffe40720c0b	
48	QWindowSystemInterface::sendWindowSystemEvents	qwindowsysteminterface.cpp	626	0x7ffe406e62fc	
49	QWindowsGuiEventDispatcher::sendPostedEvents	qwindowsguieventdispatcher.cpp	85	0x7ffe41f691c2	
50	qt_internal_proc	qeventdispatcher_win.cpp	416	0x6f85be78	
51	DispatchMessageW	USER32		0x7ffe61bc1169	
52	DispatchMessageW	USER32		0x7ffe61bc0c97	
53	QEventDispatcherWin32::processEvents	qeventdispatcher_win.cpp	818	0x6f85c9bf	
54	QWindowsGuiEventDispatcher::processEvents	qwindowsguieventdispatcher.cpp	74	0x7ffe41f69099	
55	QEventLoop::processEvents	qeventloop.cpp	129	0x6f7a7938	
56	QEventLoop::exec	qeventloop.cpp	204	0x6f7a7b73	
57	QCoreApplication::exec	qcoreapplication.cpp	1229	0x6f7aaa41	
58	QGuiApplication::exec	qguiapplication.cpp	1528	0x7ffe4071c2f8	
59	QApplication::exec	qapplication.cpp	2977	0x6e89c7da	
60	main	main.cpp	296	0x7ff6aefafe95	
61	WinMain	qtmain_win.cpp	113	0x7ff6af0d764d	
62	__tmainCRTStartup	crtexe.c	618	0x7ff6af0d6c51	
63	WinMainCRTStartup	crtexe.c	466	0x7ff6af0d69ce	
64	BaseThreadInitThunk	KERNEL32		0x7ffe61a08102	
65	RtlUserThreadStart	ntdll		0x7ffe63e0c264	
```

**Comment by bjorn** [comment]
Hmm, I've seen this `penChanged` crash while OpenGL was enabled only so far, so it's somewhat worrying that this can also crash without OpenGL.

No Tiled code seems to be involved in the stack trace, so it's probably an issue in Qt. I've found that this this issue has been reported against the Qt Creator IDE itself as well:

https://bugreports.qt.io/browse/QTCREATORBUG-14888

I'll add a comment there and let's hope the Qt guys can fix this eventually.

In the meantime, do you both have the Maps view open? I think this crash was more likely to occur while that was the case.

**Comment by SourceR85** [comment]
You are right, Tiled survives as long as the Maps View is closed (enabling before and after maximizing works).

**Comment by bjorn** [comment]
@SourceR85 I think it's more likely related to the Qt version rather than the Windows 10 version. I don't personally know whether I had some Windows patch installed or not. Did you try older Tiled releases to see if they're also affected? Or, since you've managed to compile yourself, you could try whether Qt 5.4 or 5.3 were also affected. This may help them find out what's broken.

**Comment by SourceR85** [comment]
This time I compile with Qt 5.4.2 MSVC2013 64bit.
Tiled runs stable while I maximize and have Maps View open.

**Comment by bjorn** [comment]
@SourceR85 Thanks for testing! I've posted this in a comment at the [reported Qt bug](https://bugreports.qt.io/browse/QTCREATORBUG-14888).

**Comment by bjorn** [comment]
This crash is [fixed for Qt 5.6.1](https://bugreports.qt.io/browse/QTBUG-48823), so I hope that release will not be too far off.

**Comment by caiolopez** [comment]
This is great! It will really help my workflow.

**Comment by bjorn** [comment]
This issue is fixed in the current [snapshot builds](https://update.mapeditor.org/snapshots-win/) (starting from tiled-0.16.1006), which are compiled against Qt 5.6.1. I'll probably make a Tiled 0.16.2 release with these fixes sometime soon.

**Comment by caiolopez** [comment]
Thank you!
