### ISSUE TITLE
Problems with

### ISSUE THREAD

**Issue by kimygottlieb** [bjorn/tiled#1155]
It doesnt work in windows 64 bits :/

**Comment by SourceR85** [comment]
It works.
Probably you have OpenGL activated and map viewer open, try to open tiled this way:
Open Run dialog: [Win] + [R]
Search for Tiled.exe (e.g. "C:\Program Files\Tiled\tiled.exe")
past in the parameter --disable-opengl
``` "C:\Program Files\Tiled\tiled.exe" --disable-opengl ```
and it should run

**Comment by bjorn** [comment]
"Problems with"? Problems with what?

**Comment by bjorn** [comment]
With no further information there's nothing I can do. Both the 32-bit and 64-bit versions of Tiled should work fine on Windows 64-bit.
