### ISSUE TITLE
Move an object order up/down in its current object layer

### ISSUE THREAD

**Issue by jrmgx** [bjorn/tiled#1156]
I saw that we can move an object layer up/down (change layer order) 
but it seems not possible to do the same with one object.
The order of objects has an importance in my game engine

It could be nice to have the same kind of option

**Comment by bjorn** [comment]
You mean a tile on a tile layer?

Should it just replace whatever tiles may already be on the layer above/below?

What if there are objects layers, should they just be skipped?

**Comment by jrmgx** [comment]
Oops I meant an object in an object layer
I edited the issue to be more clear

**Comment by bjorn** [comment]
Ah, that's already possible. Try changing the drawing order of the object layer to "manual" in its properties and you'll find context menu items for raising or lowering the selected object.

**Comment by jrmgx** [comment]
I don't have this option (or can not find it)
I checked that I've got the last version of Tiled
see https://www.dropbox.com/s/5hlazggci7i8l0s/Capture%20d%27%C3%A9cran%202015-12-10%2021.10.40.png

**Comment by bjorn** [comment]
@jrmgx You're looking at the properties of an object, while the option I mentioned is in the properties of the object layer.

**Comment by jrmgx** [comment]
You're right,
thank you for your help :)
