### ISSUE TITLE
Is it possible to dock/snap the Collision Editor?

### ISSUE THREAD

**Issue by noam-c** [bjorn/tiled#1160]
My workflow for Tiled involves having it take up my entire screen (I'm using a 13" MacBook so real-estate is a little limited). If I open up the Collision Editor to do work in it, it ends up being hidden whenever I interact with the main window. My workaround currently is to invoke the keyboard shortcut for the collision editor twice, in order to bring it to the foreground. But ideally it would be nice to snap it to the side like the Properties dock, or somehow keep it in the foreground more permanently. Is there a way to do that, currently?

**Comment by bjorn** [comment]
This seems like an OS X specific issue, because the collision editor window is definitely staying on top for me on Linux / Xfce. In general it should be staying on top, because the main window is the "parent" of the collision editor window.

I considered making it a dock when I added it, but decided not to do that because of conflicting shortcuts with the main window.

**Comment by noam-c** [comment]
Interesting; it makes sense that this would be OS X specific. Given that you're treating this as a bug, please let me know if there is any other information that I can provide.

OS X version: Yosemite 10.10.5
Tiled version: 0.13.0

**Comment by bjorn** [comment]
With the tileset editing now happening in its own tab, I want to try turning this editor into a dock widget after all.

**Comment by noam-c** [comment]
Thank you so much, @bjorn!

**Comment by bjorn** [comment]
Now the collision editor is a dock widget in the tileset editor:

![-orthogonal-outside tmx-outdoor tiled_167](https://cloud.githubusercontent.com/assets/531764/26355026/6ee0bf38-3fc7-11e7-98c3-cff6d725ee62.png)

**Comment by noam-c** [comment]
Fantastic! I know that there are a lot of demands on your time, @bjorn, so I really appreciate you taking time to address this issue. This will greatly speed up the workflow for editing collisions on OS X. 😃
