### ISSUE TITLE
Object resort

### ISSUE THREAD

**Issue by HumanRegret** [bjorn/tiled#1168]
would it be possible to add in object resorting when/if objects are deleted from a layer, Currently it causes ghost objects that don't exist and causes issues :(

**Comment by bjorn** [comment]
Can you be a little more specific? I'm not really sure what you're talking about. Nothing should remain after deleting objects.

**Comment by karai17** [comment]
I think what he means is that if you create 5 objects, and delete the third one, the ids remain as `1 2 4 5` instead of resorting to ` 1 2 3 4`. This was a problem last night while debugging STI since I commonly use `ipairs` to loop through `map.objects` but there was a hole in the table since the map.lua file's first object started with an id of 4.

**Comment by bjorn** [comment]
Well, this is intentional because these IDs were meant to be used to uniquely refer to objects from custom properties or even external files. Renumbering them would destroy such references.

**Comment by karai17** [comment]
That seems strange to me. I can understand referring to them from external
programs (which renumbering would allow) but tying objects together via
custom properties seems like a very niche use case.


---
Landon Manning
lmanning17@gmail.com

**Comment by bjorn** [comment]
> tying objects together via custom properties seems like a very niche use case

That is only because it is still a little clumsy since custom properties are always strings. Once property types are implemented, there can be an "object reference" type, allowing Tiled to make it easier to make links as well as to render links.

**Comment by karai17** [comment]
How would you export this link to, say, Lua?


---
Landon Manning
lmanning17@gmail.com

**Comment by bjorn** [comment]
> How would you export this link to, say, Lua?

Just as the number that it is, right?

**Comment by karai17** [comment]
Hm. I still don't really like it, but I guess it's not up to me. I'd prefer
an ordered list of objects. You could always use the object's name as a
custom property.


---
Landon Manning
lmanning17@gmail.com

**Comment by bjorn** [comment]
> You could always use the object's name as a custom property.

Names are not unique, and they could change at will, breaking an unknown set of links. Of course naming has also advantages, but in supporting the connecting of objects explicitly in Tiled (#707), they don't really work.

**Comment by bjorn** [comment]
Closing this since the original poster never clarified his problem.
