### ISSUE TITLE
Exporting to JSON GID error

### ISSUE THREAD

**Issue by grogancolin** [bjorn/tiled#1170]
The export toJSON functionality begins GIDs from 1 instead of 0.

Is this intended behavior?

If it is intended, then this bug relates to "tileproperties", as these do indeed start from 0 (so tileproperties[0] == GID 1, if you get me?)
Otherwise, the bug is in the layers array under the "data" element.

**Comment by bjorn** [comment]
GID 0 is "no tile" and GID 1 is the first tile in the first tileset. "GID" means "global ID" and it can refer to a tile from any tileset used by the map.

In contrast, the tile properties refer to the tiles by their local ID within the tileset. There isn't a "no tile" there and the first tile in a tileset usually has a local ID of 0 (with the only exception being image collection tilesets where the first tile was removed).

**Comment by grogancolin** [comment]
Ah ok. I'll manage this application side so! Thanks for the quick reply.
