### ISSUE TITLE
Deleting an object leaves label on screen

### ISSUE THREAD

**Issue by happyponyland** [bjorn/tiled#1171]
Deleting/cutting an object sometimes leaves its label hanging on the screen (clicking the map clears it).
This also happens when deleting an object, clicking to remove the label, then undoing. The object reappears but the label isn't displayed.

**Comment by happyponyland** [comment]
0.14.2, I should probably add!

**Comment by bjorn** [comment]
Hmm, I wonder since when that is broken. It's still broken with 0.15.0 at least... I'll make sure to fix it soon.
