### ISSUE TITLE
Add color picker for setting transparent color of a tileset

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1173]
It would be helpful, if the transparent color of a tileset could be chosen by using a color picker tool on the tileset image.

**Comment by mrjnumber1** [comment]
i know you said this wasn't high priority, but i hope you'll reconsider. sorry i have nothing to add, just want to say it's a convenient feature to have :)

**Comment by bjorn** [comment]
Thanks @Alturos for starting to work on this. Please feel free to ask _any_ questions you may have.

The way I imagined to implement this, would be to add a color picking button, which would cause a pop-up widget to open where the image is loaded and displayed. Left-clicking on it should pick the color of clicked pixel and clicking outside or right-clicking should close it again. Of course, if you have other ideas feel free to suggest or try them.

**Comment by Alturos** [comment]
That's actually very close to what my plan was. I was effectively going to take a similar route as the QColourDialog. 
-Add a button next to the pick a colour button
-Pop up a window with the image in it
-Mouseover updates a little area with the colour preview, clicking seals it.
-Hit Ok to accept, or cancel to not.

That feels a little more consistent with the general UI theme, but happy to slant it more toward the quicker-to-done path you outline above.

**Comment by bjorn** [comment]
I like the idea of a little preview area (and possibly a display of the hex color value next to it). But indeed, I think a single click should be enough rather than adding OK / Cancel buttons. I would try the `Qt::Popup` window flag to avoid creating a draggable window.

**Comment by Alturos** [comment]
Alright, I can go with that. One question next is on window size, do we allow unlimited window size, add a scrollable area, resizable window?

My other question is on styling and formatting, do you have any guidelines published on that? So far I'm just sort of making things looks the same as they do, but there are things I'm curious about, like `auto` for example.

**Comment by bjorn** [comment]
> One question next is on window size, do we allow unlimited window size, add a scrollable area, resizable window?

I think just having a reasonable maximum (maybe based on desktop size) would be enough. Beyond that the image would be rendered scaled down. Of course one could get fancy and allow zooming/panning, but I think it's rarely needed.

> My other question is on styling and formatting, do you have any guidelines published on that? So far I'm just sort of making things looks the same as they do, but there are things I'm curious about, like auto for example.

I'm pretty much using the Qt coding style, but there are some differences. Making things look like the existing code should be fine.

Use `auto` when it improves readability. For example, I would use it for iterators or when the type is clear, like when assigning from `new` or some cast, but not to replace anything shorter than 5 characters.

**Comment by Alturos** [comment]
My only concern with scaling is the ease of selecting the colour from a pixel when scaled (usability and potential added complexity in coding).

**Comment by bjorn** [comment]
> My only concern with scaling is the ease of selecting the colour from a pixel when scaled (usability and potential added complexity in coding).

There would not be complexity because you'd just divide by the scaling factor and pick from the source image. For ease of selecting, I think it will be very rare to have only tiny areas of the transparent color in a tileset, which would be the only case where you'd run into issues.

However, we could also do some kind of auto-panning approach instead of scaling. Where once the maximum window size is reached, the image is shifted proportionally to the location of the mouse on the window. Of course if you need to click a single pixel, that could still lead to issues, but it could make it easier to click the right place in general.

**Comment by Alturos** [comment]
I'll play around with some different ideas then, see which ends up "Feeling" right. The "Most" case is the easy one, but I see no reason to sacrifice the special cases if it doesn't make it more difficult to use.

**Comment by Alturos** [comment]
Brief update, I have the changes for this functionally complete. Going to spend some more time testing/verifying and cleaning up the UI/UX around it.

**Comment by bjorn** [comment]
@Alturos Nice to hear! So I think it should be possible to still include this feature in the Tiled 0.17 release. I'd like to announce string freeze for this release as soon as possible.

**Comment by Alturos** [comment]
At this stage, I'm pretty happy with the UI and functionality, just need to do some cleanup to get it in line with the code style and I'll get the pull request together. Might be a couple days, but shouldn't be more than that.
