### ISSUE TITLE
Ability to change the transparent color of individual objects

### ISSUE THREAD

**Issue by altmoola** [bjorn/tiled#1192]
When creating objects on a map it'd be very useful to be able to change the transparency color of individual objects like the below image.

![image](https://cloud.githubusercontent.com/assets/15036268/12733808/1491d192-c8fa-11e5-9331-683467f5f3ac.png)

**Comment by bjorn** [comment]
I don't really understand what you want to achieve. Is it too transparent to create see your objects?

Generally, these objects are meant for annotational purposes and are not really meant to be visual objects themselves. You have complete control over how objects look if you use tile objects instead.

**Comment by altmoola** [comment]
I simply want to be able to change the color of the objects from transparent gray to a pickable color. If I have a tile that is used for jumping I'd like to be able to color that tile differently so that I can see it while I'm editing the map. It wouldn't appear in a game or anything.

**Comment by bjorn** [comment]
Didn't you already do that with those green and pink objects? Or is this a modified screenshot to serve as a mock-up?

You can change the default gray color for either an entire object layer (in the object layer properties). Alternatively, you can set a different color for each object type in the Tiled preferences.

**Comment by altmoola** [comment]
Yeah that screenshot is a mockup. Instead of changing the entire layer I'd like to be able to do individual tiles.

**Comment by altmoola** [comment]
Looks like the Object Types in preferences will do the job as you said.
