### ISSUE TITLE
Tiled 0.15 won't compile on Windows

### ISSUE THREAD

**Issue by maxbize** [bjorn/tiled#1195]
I was trying to compile Tiled (branch 0.15) on Windows using [these instructions](https://github.com/bjorn/tiled/wiki/Contributing-to-Tiled#building-64-bit-version-of-tiled-on-windows) and got two compilation failures along the lines of
`error: C2440: 'initializing' : cannot convert from 'initializer-list' to 'Foo'
No constructor could take the source type, or constructor overload resolution was ambiguous`

In order to "fix" I had to revert the changes in 47964cf for changeproperties.cpp (RenameProperty constructor ~line 147) and 02c0eea for zoomable.cpp (Zoomable constructor lines ~45-70). These changes seem to be some optimizations that aren't supported with the MSCV2013 compiler. **If simply reverting these changes is an acceptable fix I will gladly produce a PR.** Don't know if you had anything else in mind :)

Note that after this I had ~50 unresolved symbol errors coming from the Python plugin. Since I didn't need the plugin I deleted it and got a successful build.

**Comment by bjorn** [comment]
Hmm, that's strange. Tiled does actually build on Windows for me locally, as well as [on AppVeyor](https://ci.appveyor.com/project/bjorn/tiled/build/job/i8h90uvh6nhturlx). The only difference I can see is that the instructions you linked to specifically asked for Qt 5.3, whereas we're currently at Qt 5.5. But the compiler used is the same.

Also, the Python plugin is supposed to automatically disable when building with MSVC, so it's strange that you would get unresolved symbol errors for it.

Do you see any difference between what you're doing or your system and for example the environment on AppVeyor, that could be causing these issues?

**Comment by bjorn** [comment]
Ah, another thing that may be causing this, the instructions are linking to the Express version of Visual Studio, update 3. In the meantime Microsoft has released a more complete version, "Visual Studio Community 2013 with Update 5". And I believe that's the one I'm using locally as well as on AppVeyor, so maybe give that a try.

**Comment by Frenchie14** [comment]
I downloaded [update 5 for VS 2013](https://www.microsoft.com/en-us/download/confirmation.aspx?id=48129) and the compilation is working for the initializer-lists! 

Still no-go for Python, it's still trying to compile it. When you say it shouldn't compile, are you talking about the "Have Python. Will slither" check?

**Comment by bjorn** [comment]
> Still no-go for Python, it's still trying to compile it. When you say it shouldn't compile, are you talking about the "Have Python. Will slither" check?

No, that means you've opened `tiled.pro` rather than `tiled.qbs`. Please use the Qbs file instead. It is better maintained on Windows.

I'll have to look into actually getting Python to work with MSVC though.

**Comment by Frenchie14** [comment]
Gotcha. Well, opening tiled.qbs results in "dependency Qt.core not found" so that's why I'm using the .pro :smile:. Anyways, it's probably just misconfiguration from the Qt install (although strange that compile works with the other project file). I'm fine just using the .pro file and deleting Python, but if you want to try and figure out what's going on I can help. Otherwise, I'd just suggest adding a note to the install guide to ask users to download update 5 for VS 2013 if they already have it installed (which was the case for me).

Thanks for all your help!

**Comment by bjorn** [comment]
Closing this issue. i've opened #1214 about the Python plugin.
