### ISSUE TITLE
Image layers do not contain image information

### ISSUE THREAD

**Issue by Goombario** [bjorn/tiled#1205]
Image layers do not contain information about the image itself, such as width and height. I feel like this would be a valuable addition. I could certainly use it.

**Comment by bjorn** [comment]
Makes sense, especially since the image size is already stored for tile and tileset images.

But did you consider to use a tile object on an object layer, instead of an image layer? It provides the same and more functionality.

**Comment by Goombario** [comment]
I tried out what you suggested, and it works well! Unfortunately, the library I'm using right now to load tmx files doesn't support multiple images in a tileset, so I'm using a workaround by giving my program the data from an external file. But thank you for the advice. :)
