### ISSUE TITLE
Request Better Snapping or placement For Collision Editor

### ISSUE THREAD

**Issue by tkeene** [bjorn/tiled#1206]
If you hold down Control when placing points in the collision editor, it snaps the point to the nearest corner. However, there is no way to snap points to midway points or other useful points when setting up collision for shallow ramps or slopes (short of hand-editing the XML so that they are precisely placed at 0.5, 0.25, or 0.333 repeating positions). An option for changing the snap scale (the distance intervals used when holding down Control) to a value other than 1.0 would be great.

Alternatively, an option to type in coordinates for individual points would suffice.

This is undesireable for slopes and ramps in 3d platformers, which may need to be smooth and error-free for game physics to work properly on them.

**Comment by bjorn** [comment]
Please try enabling 'snap to fine grid', the fine grid can be configured in the preferences. It should also work in the collision editor.

**Comment by tkeene** [comment]
Oh, that works. Didn't know I could do that.

**Comment by bjorn** [comment]
At some point in the future, there will be a Tiled manual in which you can find out about this and all other somewhat hidden Tiled features. :)
