### ISSUE TITLE
Tile Subdivision

### ISSUE THREAD

**Issue by Blizzardo1** [bjorn/tiled#1219]
Is it possible to have Tile Subdivision? e.g. Create a 32x32 with 8x8 tiles on a 32x32 grid?

**Comment by bjorn** [comment]
No, your map grid determines the distance between the cells at which you can place tiles. There's no way to put tiles at a finer level.

You can however put 32x32 tiles on a 8x8 map grid. But they will overlap by 24 pixels if you put them right next to each other, so if you don't want that you'd have to leave gaps between those bigger tiles.
