### ISSUE TITLE
Resizing existent tileset

### ISSUE THREAD

**Issue by coNNecTT** [bjorn/tiled#1221]
Hello, I'm trying to replace existent tileset with a bigger version of it, which increases the amount of columns and messes up the tiles. Should I make a small program to offset the tiles in the tileset manually or is there a way to fix it? And I guess Tiled doesn't support changing the tileset's dimensions (when there already are tiles placed in the map)?

**Comment by bjorn** [comment]
Actually Tiled does support adapting to changing of image size, but if you _also_ change the size of your tiles, then you have to be careful. When Tiled detects that your tileset has a different amount of columns than it had before, it will ask you whether you want to adjust the tile indices on the map (at least as of Tiled 0.15, it does this with a popup). Then, it's up to you to decide whether you want Tiled to do this or not.

Basically, if you are going to change both your image size and your tile size, then make sure the tileset still has the same amount of tile columns and tell Tiled _not_ to adjust the indices. Everything should be fine then.

And if you're changing the image size but not the tile size, and thus changing the number of tile columns in your tileset, then you tell Tiled that you _do_ want it to adjust the tile indices of the map.

Best make sure you got a backup and play with it. If you think Tiled is doing something wrong, I welcome a bug report with specific instructions on how you did it.

**Comment by coNNecTT** [comment]
Hm, so I do get the popup and I don't change the tile size (or margin with spacing), I just increase the amount of tiles, but after clicking "Yes", it doesn't fix the tiles, the only change I notice is a random row of tiles being created(6,6 to 49,6 coordinates).

**Comment by bjorn** [comment]
Ok, I'm going to need more detailed information about what you are doing and possibly the files you're doing it with, in order to be able to try helping you.

**Comment by coNNecTT** [comment]
I just reproduced it in a new map. At first i tried doing it with 4 tiles and filling 4 corners of map with them, it worked. Then I added 3 rows of tiles and placed them all randomly in corners for each row, now it broke. Here are the files: [https://www.dropbox.com/s/a2naepqt30tcc49/Tiled%20resize%20bug.rar?dl=0](url)
The tileset should be replaced with "test2.png" for the bug to occur.
