### ISSUE TITLE
Automap doesn't recognize rules when they the region is out of bounds

### ISSUE THREAD

**Issue by hamburml** [bjorn/tiled#1224]
I am using automap for border generation in Tiled.
It works (but I think there is a memory leak issue.. while working with lots of rules (and using them often) I sometimes have over 1 GB Ram usage.)

Nevertheless I have a rule (region) (3x3) where only the middle cell is tested (input). The other cells should be set (output). Automapping doesn't accept this rule for border-cells. 
I could create new rules for solving this, but one rule would be perfectly fine when the automapping just ignores the out of bounds situation and just goes on.

I have uploaded a short example. Just open example.tmx
[automap.zip](https://github.com/bjorn/tiled/files/170474/automap.zip)

Thanks!

**Comment by bjorn** [comment]
Sounds like a bug but it might be tricky to fix. I'll try to get to it eventually, or maybe @stefanbeller would like to come back to have a look at it?

> (but I think there is a memory leak issue.. while working with lots of rules (and using them often) I sometimes have over 1 GB Ram usage.)

Regarding this, I think it is likely just the undo history, which is unlimited at the moment. The automapper tries to reduce the amount of information stored by calculating a diff, but if it affects the entire border then the changed region will be the whole map.

**Comment by stefanbeller** [comment]
That sounds like a bug (originally designed as a feature) to me.

What is intentional is that the output may be larger than the investigated area for the inputs. This however doesn't apply rules when the output would not fit completely on the map, i.e. if the output would be cropped by the map border, the rest which would end up on the map is not put out correctly?

Do I understand that right?

**Comment by Michael-Hamburger** [comment]
@stefanbeller Yes. The output is larger than the input. The input is found and the output can't be fit on the map and should be cropped by the map border.

**Comment by stefanbeller** [comment]
![tiled1224](https://cloud.githubusercontent.com/assets/455868/15266500/27b6d47c-195c-11e6-85b7-8d48b18348f4.png)

This is what is desired IIUC.
