### ISSUE TITLE
Can't delete animated tile frame

### ISSUE THREAD

**Issue by ericmuyser** [bjorn/tiled#1232]
Hey guys,

Seems like I must be doing something wrong. But I've tried everything I can think of, searched for docs, and youtube videos - there's almost nothing on animation. 

I just want to delete a frame and it won't let me. I'm tried the DELETE key, CMD +  DELETE, dragging it to the right, left, everywhere.

![image](https://cloud.githubusercontent.com/assets/156768/13925432/82a6eeda-ef45-11e5-9904-2ecf3c7c8dc2.png)

Also, does anybody know if there's a way to specify the speed? or I need to use a custom property for that I imagine.

Cheers,
Thanks!

**Comment by Seanba** [comment]
Are you using tileset files (with the TSX extension)? If so, you may need
to "import" the tileset file first before you make changes.

**Comment by ericmuyser** [comment]
Hi @Seanba :)

I'm using JSON extension, and I've imported the tileset. Everything is working in the game too :)

**Comment by bjorn** [comment]
If it was an external tileset, then the list of frames would be somewhat clearly disabled, like so:

![screen shot 2016-03-21 at 20 33 44](https://cloud.githubusercontent.com/assets/531764/13931655/97025f22-efa4-11e5-898d-ae02a8ac7c1d.png)

However, I'm not sure what the problem could be here. I've tried reproducing it on my old Mac Mini and after selecting the frames I want to delete, both the Delete key and the Backspace key work fine (I don't have an actual Apple keyboard to test this with, unfortunately).

I think I should anyway consider adding a small tool bar with explicit Add and Remove buttons.



> Also, does anybody know if there's a way to specify the speed? or I need to use a custom property for that I imagine.

The speed is determined by the number alongside each frame, which is the frame duration. The 100 means "100 ms" (I should really add the "ms" there to make this obvious).

**Comment by bjorn** [comment]
Just to ask, which version of Tiled is this? Latest release? Nightly build? Custom compile? In the last case, which version of Qt was used?

**Comment by ericmuyser** [comment]
Oh my god. I can click on that `100`? I get it now, and I can't believe I couldn't figure that out before.

Anyway I updated to the lastest Tiled from the website download page. No go.

Perhaps it's a plugin intercepting the delete key? Strange, I've had no issues with other apps.

Menu bar buttons would be awesome.

I'll let you know what I can find!

**Comment by ericmuyser** [comment]
Animations are a killer feature and it took me sooo long to figure it out. I saw them in a zelda map I downloaded, but couldn't figure out how to edit the animation. Finally found it in the menu bar under View. I think the indicator is missing from the map I downloaded, in the tileset area, or, it's blended in I can't tell which is animated which is not.

**Comment by bjorn** [comment]
@ericmuyser Did you close this because the problem is fixed for you in the latest version of Tiled?
