### ISSUE TITLE
Image layer position not saved

### ISSUE THREAD

**Issue by ericmuyser** [bjorn/tiled#1234]
Heya!

Seems to me that the position of image layers is not being saved to the JSON.

I see this in the UI:
![image](https://cloud.githubusercontent.com/assets/156768/13943384/41eff5b6-efb9-11e5-898f-9ee1d1962a50.png)

I see this in the code:
![image](https://cloud.githubusercontent.com/assets/156768/13943380/34b179b0-efb9-11e5-884a-ba88fd07df79.png)

I can see it's dragging the grid when I drag the image layer. I don't see why it would do that..

Thoughts?

Godspeed,
E

**Comment by ericmuyser** [comment]
Oh geez, it says offsetx and y right there... Sorry please disregard!
*Kind of curious why it doesn't just use x/y, and why those are there, but not important!*

**Comment by bjorn** [comment]
> Kind of curious why it doesn't just use x/y, and why those are there, but not important!

Actually I should remove these `x` and `y` values. They would be the position of the layer in tile units, but this is a relic from the Java version of Tiled that isn't used by the Qt version. I'm using `offsetx` and `offsety` for consistency with the tile and object layers.
