### ISSUE TITLE
Individual tile offset commit removed?

### ISSUE THREAD

**Issue by hedgehog90** [bjorn/tiled#1240]
I don't understand why this commit has since been removed:
https://github.com/bjorn/tiled/commit/9b5590795d66ac525b9c9b39b8d390e3b0fa00e6

The old issue: https://github.com/bjorn/tiled/issues/871

I require this feature for my project, I've just spent several hours with Qt trying to get it working but I can't.

**Comment by bjorn** [comment]
That commit has not been removed, it was just never merged. The reason is that it is incomplete. Nobody ever finished it or opened a pull request for it.

Issue #871 is not old. It's an open issue about a feature that could be added in the future. But there are many such issues and it's hard to choose which features to work on in the limited time i have for doing Tiled development.

> I require this feature for my project, I've just spent several hours with Qt trying to get it working but I can't.

Are you having trouble adding this particular feature, or are you having trouble compiling Tiled at all? In the latter case, just tell us where it's going wrong and we could try to help you.

**Comment by hedgehog90** [comment]
I managed to solve my problem this morning. Qt was a pain to get working with my setup. Btw you should mention in the contributing page that Windows users will need to install Wix to get it working.

Anyway, I did a tiny hack to get it working, in maprenderer.cpp I added a couple lines so each tile is offset by the amount specified in the XML.

Sorry about the misunderstanding, I thought the commit was merged. I'm fairly new to github, still learning the jargon :)

**Comment by bjorn** [comment]
> Btw you should mention in the contributing page that Windows users will need to install Wix to get it working.

Hmm, that should not be required. The installer does not build by default, but I guess the presence of this build job may still cause issues when WiX is not there. I'll make sure to fix this.

I guess it also does not help that they just released Qt 5.6, and in my initial testing Tiled did not compile against this version yet. If you got bitten by zlib header issues, then this would be it. Of course I'll try to fix that soon as well.

> Anyway, I did a tiny hack to get it working, in maprenderer.cpp I added a couple lines so each tile is offset by the amount specified in the XML.

Right, that must be similar to [what this guy did](https://github.com/bjorn/tiled/commit/5a97ea6871fbfa998d1176448197f4ea5fb27870). A quick hack usually does the job for people, though to include the feature properly a lot more work is needed unfortunately.

> Sorry about the misunderstanding, I thought the commit was merged. I'm fairly new to github, still learning the jargon :)

Yeah it's a little confusing that you can link to commits that have only been pushed to forks, using a URL that links to the original repository, like was done here. But if you look at a change that _is_ included in my repository, then you'll see GitHub indicating the branches it is included in. For example you can see "master" below the commit message here:

https://github.com/bjorn/tiled/commit/d454e3dcde28c8f02ede53584807ad5167323f37

**Comment by hedgehog90** [comment]
Thanks for that.
I've got Qt 5.6. The build errors were all to do with WixModule not having 6 or 7 variables set, like minVersion, maxVersion, something like buildtoolpath, and more. I looked it up for another module and it appears to be triggered when an autodetect fails.
Hope that helps.

**Comment by bjorn** [comment]
> I've got Qt 5.6. The build errors were all to do with WixModule not having 6 or 7 variables set, like minVersion, maxVersion, something like buildtoolpath, and more. I looked it up for another module and it appears to be triggered when an autodetect fails.
> Hope that helps.

Right, that's actually a bug in Qbs that I fixed locally, as well as [patching up the file on AppVeyor](https://github.com/bjorn/tiled/blob/master/appveyor.yml#L25). I should really get my fix into Qbs properly, but then it'll still be a while until this fix is included in the latest Qt Creator release. In the meantime I should also make sure Tiled builds without WiX altogether, anyway.
