### ISSUE TITLE
Collection of different sized images tilemap - Bad placement in tilesets window

### ISSUE THREAD

**Issue by hedgehog90** [bjorn/tiled#1241]
![2016-03-28 21_01_57-assetsthe one fla_](https://cloud.githubusercontent.com/assets/5526342/14088696/e956fa88-f528-11e5-98f6-968aafdac0d0.png)

There must be a better way to organize the tiles for rare instances like mine where I require different sized tiles.
I've made my tileset so it consists of single piece wall objects, the image above shows a fence tile that is placed as a single tile.
Is there a simple hack I can do so that the tiles are sorted more appropriately?

**Comment by bjorn** [comment]
The simple hack would be to group your tiles roughly by size while adding them to separate image collections.

On the Tiled side, a relatively simple solution would be to introduce a mode where each tile gets the same amount of space, like when showing thumbnails in a file manager.

**Comment by hedgehog90** [comment]
The second option sounds ideal. Could you point me in the right direction as to which source file I should edit and how?

**Comment by bjorn** [comment]
Sure, you'll have to adjust the `TileDelegate` in `tilesetview.cpp`:

https://github.com/bjorn/tiled/blob/master/src/tiled/tilesetview.cpp#L53

Adjusting its `sizeHint` and `paint` member functions according to your needs.

Directly modifying this code would be the quickest way. Of course, for integration back into Tiled, it will need to be implemented as an additional view mode. That will be quite a bit more work.
