### ISSUE TITLE
Tileset column count modified algorithm issue

### ISSUE THREAD

**Issue by Tibec** [bjorn/tiled#1242]
Hi, 
I just tried to resize a tileset used in one my maps and it appear that Tiled detect the column change and apply an algorithm to adapt the map.

I did'nt have looked into the source code but it appear that if a tile is empty (= 0, in the csv format) it mess up completely the whole map. I've fixed my problem by setting all empty field to 2 (i guess anything different from 0 work)

I hope it could help you to fix that

**Comment by NoseKills** [comment]
Confirmed.

**Comment by bjorn** [comment]
The bug was a little embarrassing and due to trying to use a shadowed variable. But it's fixed now and will be released with Tiled 0.16.2 (or soon the snapshot builds).
