### ISSUE TITLE
Pressing backspace when a property section is selected causes a crash

### ISSUE THREAD

**Issue by xtrium-lnx** [bjorn/tiled#1245]
Pretty much everything is in the title.
Found in v.0.14.2 but changelog doesn't show any fix on this.
To reproduce : Open a TMX file, select an object. In the properties panel, select a section title (ie. "Map" or "Custom properties"), press backspace => Instant crash.

**Comment by bjorn** [comment]
Thanks for the report! The fix will be included in Tiled 0.16.1 eventually.
