### ISSUE TITLE
OS X require tileset Unicode filename to be stored using NFD

### ISSUE THREAD

**Issue by bitinn** [bjorn/tiled#1247]
This is a strange problem involving multiple parties, I will try my best to summarize it:

When Tiled export a map data, it uses NFC for the Unicode tileset filename, this is mostly fine, until you try to `zip` the data on OS X, which seems to enforce NFD.

So when an engine tries to load a map, it will unfortunately not be able to find the tileset with NFC name, but only with NFD name.

I recently encounter this while working with LÖVE engine.

The problem, however, is whether we should fix it from Tiled or LÖVE, I am opening an issue on both side...

ref:
- https://github.com/karai17/Simple-Tiled-Implementation/issues/103
- https://marcosc.com/2008/12/zip-files-and-encoding-i-hate-you/
- https://en.wikipedia.org/wiki/Unicode_equivalence
- for an example on NFD/NFC https://mothereff.in/html-entities#%E3%83%88%E3%82%99%E3%82%A2%E5%A4%96%E8%A3%85%0A%E3%83%89%E3%82%A2%E5%A4%96%E8%A3%85

**Comment by bitinn** [comment]
Link for LÖVE: https://bitbucket.org/rude/love/issues/1153/os-x-require-tileset-unicode-filename-to

**Comment by bjorn** [comment]
Hmm, I was never aware this problem existed with Unicode. One would have hoped they would have standardized on a single normalization form...

In any case, it appears Qt has an option for normalizing strings to a certain form:

http://doc.qt.io/qt-5/qstring.html#normalized

Now, does this need to be an option, or should I always normalize the output to NFD when on OS X?

**Comment by bitinn** [comment]
An option might be better, I imagine no one wants to discover Tiled exports map data in different Unicode form on different platform. It's also a pain for team collaboration and asset versioning if export data are not consistent across platform.

Lua never had great Unicode support so I guess most people will just avoid using non-ASCII filenames. Export with NFD should be the last resort not default (and god knows what would happen when you try to load NFD filenames on Windows).

**Comment by bitinn** [comment]
I just don't think this is worth your time tackling, and I have converted all my assets to ASCII filenames (because I can't really tell if the same issue would happen on Windows/Linux/iOS/Android, given LOVE is cross-platform and `zip` is involved).

Closing this.

**Comment by bjorn** [comment]
Alright. Thanks for bringing the issue to my attention anyway!
