### ISSUE TITLE
Custom brushes/stamps

### ISSUE THREAD

**Issue by davidgfnet** [bjorn/tiled#1250]
Is there anything like a custom brush? I played around for a couple days but couldnt find it. The idea is that having a very limited and low count set of tiles (for which I define collison properties and stuff) I'd like to create "stamps", this is, to define a particular arrangement of them that I can use to "paint" the terrain with. Otherwise I have to paint using one tile at a time.

Any suggestions or ideas? This app rocks! I like it. If this feature is not implemented I might implement it myself :)

**Comment by bjorn** [comment]
Did you try to create your arrangements on the map, then capturing the region using right-click drag, and then saving your current stamp for later in the Tile Stamps view (which isn't open by default)? It sounds like this is close to the feature you're looking for.

**Comment by davidgfnet** [comment]
Brilliant! Sorry for that, I couldn't find the Stamps view, it wasn't opened by default on my computer. I'll just close this issue, I hope it can help people that look for the same issue in the future.
Thanks for your excellent work!

**Comment by bjorn** [comment]
Eventually I'll get around to adding the feature to the "Tiled Manual", so that more people will know about it. I'm glad to hear it's what you were looking for! :-)
