### ISSUE TITLE
New libraries to support Tiled

### ISSUE THREAD

**Issue by linux-man** [bjorn/tiled#1251]
For [Processing](https://processing.org/): [Ptmx](https://github.com/linux-man/ptmx). Already in Processing contributed library list.
For [p5.js](http://p5js.org/): [p5.tiledmap](https://github.com/linux-man/p5.tiledmap).
Just my small contribution to this great tool.

**Comment by bjorn** [comment]
Sorry for the late response, but I finally got around to adding these. Thanks a lot!
