### ISSUE TITLE
Fatal crash when exiting Tiled with Object Type Editor Window open

### ISSUE THREAD

**Issue by Seanba** [bjorn/tiled#1253]
FYI: Tiled crashes on exit if the Object Type Editor gui is open when you close the app down.

**Comment by bjorn** [comment]
Hmm, I just tried opening Tiled in the debugger, opening the Object Types Editor and then closing Tiled, and got a normal exit. Is there anything else involved in reproducing this crash?

**Comment by Seanba** [comment]
I can't reproduce it today either so there must be something additional I was doing to cause the crash. I will play closer attention if I see it again.

**Comment by bjorn** [comment]
I just encountered and fixed a crash on exit and I have a hunch that is the one you were experiencing (e443413db906e08f9029913773502ecd3fee6481). :-)
