### ISSUE TITLE
No focus on Tiled app window

### ISSUE THREAD

**Issue by todorone** [bjorn/tiled#1256]
With new convenient multi tabs feature in Tiled there is small issue - after you open another .tmx file through external file manager Tiled app window doesn't get focus so you have to manually activate it.

OS: Windows 7

**Comment by bjorn** [comment]
I think Windows does this intentionally. Instead, the application will be highlighted on the taskbar, right? Still, it's probably worth looking into actually raising the window.

**Comment by todorone** [comment]
Yeah, now Tiled just highlight itself on taskbar. But tradinitional and expected behaviour on Windows is to gain focus when we open corresponding file...

**Comment by bjorn** [comment]
Hmm, I'm not sure if there's an easy fix for this.

The code already does:
```c++
actWin->setWindowState(actWin->windowState() & ~Qt::WindowMinimized);
actWin->raise();
actWin->activateWindow();
```
And the docs for `activateWindow` say:
> On Windows, if you are calling this when the application is not currently the active one then it will not make it the active window. It will change the color of the taskbar entry to indicate that the window has changed in some way. This is because Microsoft does not allow an application to interrupt what the user is currently doing in another application.

Yet, I see other applications raising themselves to the front in this scenario...

**Comment by bjorn** [comment]
Alright, there will be an option in Qt 5.7 to get the window to raise regardless: https://bugreports.qt.io/browse/QTBUG-14062
