### ISSUE TITLE
Paste in place

### ISSUE THREAD

**Issue by todorone** [bjorn/tiled#1257]
One very minor feature that i really miss in Tiled is "Paste in place"(Ctrl+Shift+V) so i can paste object not to mouse cursor location but to location object has been copied/cut from. Or maybe i'm missing something and it's possible somehow?

**Comment by bjorn** [comment]
Ah, no this is not possible at the moment. I think it would be a good feature to add, but can you elaborate a bit on the use-case of such a feature?

**Comment by todorone** [comment]
It's very convenient when you need to move object from one layer to another: select object - Cut - click on layer - Paste-in-place. Another handy case when you have for example coin and you need one more, strictly one tile right from previous position, you select it, Copy, Paste-in-place, and Shift + ->...
As i mentioned it's not that most wanted feature, just thought it's easy to implement...

**Comment by bjorn** [comment]
Thanks, sounds like a must-have feature really!

For moving objects between layers, there's also a entry in the context menu, but it can be good to have multiple ways of achieving the same thing, especially if it is an expected workflow.
