### ISSUE TITLE
Sick interface

### ISSUE THREAD

**Issue by hocuspucus** [bjorn/tiled#1258]
When I try to deattach a panel (ie, tilesets) it gets attached back somewhere else automatically because, whenever I drop it outside the map SO I CAN SEE A THING (I don't have a 20"+ monitor like I guess the owner does) it gets attached back, and whenever a window is attached I spend more than a minute scrolling like a dumbass to find what I want to find.

I will record a video of how I spend more time REARRANGING THE DAMN WINDOWS than actually making maps.

INTERFACE 0/10

I tried to use this 5 years ago and turns out today nothing has changed. Come on, Bcorn, tell me: am I the first person ever to say that this interface FUCKING SUCKS? Did you make it on purpose to frustrate a few human beings? Was it an accident? Don't you care about other people's suffering? 

If you don't want to fix this BUG, at least write a TUTORIAL. WRITE DOCUMENTATION ON HOW TO ARRANGE THE WINDOWS IN ORDER TO AVOID WANTING TO BREAK THE KEYBOARD IN YOUR FACE.

No offense.

**Comment by bjorn** [comment]
> No offense.

I find it hard to read your request without getting offended, because of all the screaming and cursing. Do you realize I provide this tool for free, for whoever finds it useful? I'm eager to hear feedback, but please make an effort to stay constructive.

**Comment by hocuspucus** [comment]
Sorry if I offended you. I thought you would take it as a funny critique, not as an insult.

Interface 0/10
Map editing, unique tool potential 10/10

Maybe if we remake the interface in a photoshop-like structure we could start asking for a few bucks per download. Think about it.

**Comment by Ablu** [comment]
> No offense.
If you intend to write a "no offense" maybe you should not use caps lock.



> am I the first person ever to say that this interface FUCKING SUCKS?

Yes. You are (to my knowledge).
At least you are the first person who writes such an insulting person on this issue tracker.

Sure recently a few new docks got added, but I always found the interface very clean and easy to learn.

Before opening such issues please think about it that the author of this amazing tool put hours of unpaid work into this and provides it for free.

If I view your recent comments here on Github you should probably work on your communication skills and try to be constructive or, frankly, find a different platform for disregarding people's work.

Regards,
Ablu

**Comment by hocuspucus** [comment]
I already apologized just in case he really felt disrespected. It wouldn't be fair for you to jump on me after I've apologized, but you don't seem to be very fair nor very smart, so it's okay. I forgive you.
I don't usually stalk people, but since you do, I'll stalk back. Look, You remind me of Abu of Aladdin, so your nickname is missing an "l", and after you take a moment to think about the deep meaning of this I'd ask you to consider if your obviously bullied childhood has had any negative impact in your present judgemental ability. I believe you to be a truly socially inept, an asperger monkey, a scum that tells others what he has been told: work on my communication skills? My ass. First you learn english, and when you have a basic understanding of english, you will be able to understand the communicative gap between you and me, which is like the gap between earth and sky. You fail to see my criticism as useful or convenient because you can't be auto-critic. If you were, you would probably consider suicide after wasting the best years of your life behind a computer and finding out too late that you have no talent for it. Good job defending your cyberfriend, but such a bad timing. Now run away to the only place in this world where you probably feel valuable: an irc channel. 

This is what I learned about you by reading your recent comments here on Github. Now I'd wish you good luck, but you wouldn't know what to do with it even if you got it. 

P.S: Add this to the poor design issue: fixed paths to load map resources so moving/sharing files between computers is not drag&drop but a time consuming task.

**Comment by kheftel** [comment]
Insulting the author of this software who provides it for free is not the way to get changes implemented.

You can't scream and curse in all caps and say "sorry just joking" and expect it to undo all the negative comments.

**Comment by bjorn** [comment]
I can't respond to your criticisms since I'd need to dig them out of the personal insults in which they are buried. If you make an effort to stay civil and constructive, please feel free to open new issues, one per topic please.
