### ISSUE TITLE
Precompiler Fails at @ symbol in tiled.rc.in

### ISSUE THREAD

**Issue by winstonliu** [bjorn/tiled#1264]
In windows, the precompiler doesn't recognize `@VERSION@` in line 7 of `src/tiled.rc.in`. It fails with 
`error RC2018: unknown character '0x40'`.

Changing this value to `0,16,0` allows the precompiler to continue the build.

**Comment by bjorn** [comment]
Right, I haven't used qmake on Windows since a long time. This `src/tiled.rc.in` is only properly supported when building with the `tiled.qbs` project, which is what I would recommend you to do.

**Comment by bjorn** [comment]
I looked shortly into the possibility of fixing up the qmake project file, but it's just annoying work and looks like a waste of time because the Qbs project works fine. Hence I've pushed the above commit, just so people get a proper error when they try to use the qmake project.

**Comment by mitchcurtis** [comment]
Could you add some short instructions or link in that message that explains how qbs can be used? I don't even know if I have to build qbs myself, or if it come prebuilt with Qt binaries, and I'm a Qt dev. :)

**Comment by bjorn** [comment]
> Could you add some short instructions or link in that message that explains how qbs can be used? I don't even know if I have to build qbs myself, or if it comes prebuilt with Qt binaries, and I'm a Qt dev. :)

You can just open the top-level `tiled.qbs` file in Qt Creator, which ships with Qt. Qt Creator also ships with the `qbs` command-line tool, which I use for builds on AppVeyor.

> It's weird that it requires Qt Script... that seems like an odd choice for a new module.

I guess it's because Qbs is not so new anymore. I'm sure they are planning to change this dependency, given that QtScript is deprecated.

**Comment by mitchcurtis** [comment]
Ah, thanks!
