### ISSUE TITLE
Make snapshot builds for Fedora work again

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1269]
The Fedora daily builds hosted at https://copr.fedorainfracloud.org/coprs/ablu/tiled-dailies/ seem to be stale. The last build was triggered 5 months ago and failed.

Hopefully @Ablu can help getting them to work again, as well as switching them from the `master` to the `snapshot` branch.

**Comment by Ablu** [comment]
argh.... I need to setup some tracking for that...

**Comment by Ablu** [comment]
I have a nearly working tito setup now. This would allow you to register a webhook to trigger rebuilds in copr automatically.

Issues in tito which prevent this at the moment:
 * dgoodwin/tito#222
 * dgoodwin/tito#227

**Comment by bjorn** [comment]
Cool! The second one seems like the hardest one on their part, but we could put a file in the top level for now once dgoodwin/tito#222 is fixed?

**Comment by Ablu** [comment]
Yeah... that should work... though we still need to wait until the first bug is fixed, in a release and the release is on the copr servers. Well I will still prepare the pullrequest. But it will only start working once the other steps are done.

**Comment by bjorn** [comment]
@Ablu What's the status on this? It seems daily builds are up to date now, so is there still something to do before closing this issue?

**Comment by Ablu** [comment]
Yeah the builds work again. I still do not like that the package has the same name as the official package...  The current procedure forced me to an ugly epoch trick. I will likely rename it in the future somewhen so switching back to the normal tiled package is easier. But that should work with the current infrastructure.

**Comment by bjorn** [comment]
Alright, closing this issue then. Thanks!
