### ISSUE TITLE
Color as a property type

### ISSUE THREAD

**Issue by superqix** [bjorn/tiled#1275]
It's low priority, but would be nice to have a custom property that pulled up the color selector. Right now we type HEX colors into a string field.

**Comment by bjorn** [comment]
This should be really easy to implement, so I'll make sure to get to this soon.

Also, thanks for being such a generous patron, as well as for your work on [ponytiled](https://github.com/ponywolf/ponytiled)! Eventually I hope to get around to trying out / evaluating the many Tiled support libraries out there, and I'd definitely like to check this one out as well.

**Comment by superqix** [comment]
No worries... Tiled is a tool that we use all the time. Thank you for your efforts.

**Comment by bjorn** [comment]
Let me know if you find any issues. :-)

**Comment by superqix** [comment]
Sweet. Thanks.

**Comment by ficion** [comment]
This is a really small issue, but I would like to add that instead of "color", it might be better called "rgba", since that's the way the color seems to be saved.

**Comment by bjorn** [comment]
> This is a really small issue, but I would like to add that instead of "color", it might be better called "rgba", since that's the way the color seems to be saved.

Hmm, I don't see why the storage format should determine the name of the property type. It could be stored in many ways, but it's still a color. The format is `#AARRGGBB` actually, which will be written in the documentation.
