### ISSUE TITLE
Cannot open json files

### ISSUE THREAD

**Issue by Coconaut11** [bjorn/tiled#1286]
I save my map as JSON file, I close tiled, and if I want to open the map again, I can't!!!

Tiled Says:

Error, It's not a map file.
Line 1, Column 1

[The File](https://bitbucket.org/Coconaut_/indie-game/src/8e3a6faa9ebb792f2b09a2ecb930101ae0d5d9f0/Survival%20Zombie/res/maps/testMap.tmx?at=master)

**Comment by bjorn** [comment]
If you link into your repository, please make sure it is publicly viewable. Right now I get:

> Access denied
>
> Use the links at the top to get back.

**Comment by Coconaut11** [comment]
ok Here is it:

{"height":16,
 "layers":[
        {
         "data":[2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 17, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 18, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 5, 6, 6, 6, 6, 6, 7, 1, 1, 1, 19, 1, 1, 1, 5, 6, 42, 22, 22, 22, 22, 22, 40, 7, 18, 1, 1, 1, 19, 5, 42, 22, 22, 22, 22, 22, 22, 22, 22, 40, 7, 1, 1, 1, 1, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 40, 7, 1, 1, 1, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 2, 17, 1, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 2, 1, 1, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 2, 1, 1, 18, 10, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 1, 1, 2, 1, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 8, 39, 1, 2, 2, 2, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 1, 17, 2, 2, 2, 37, 38, 10, 22, 22, 22, 22, 22, 22, 22, 23, 1, 1, 1, 2, 2, 1, 1, 37, 38, 10, 22, 22, 22, 22, 8, 39, 2, 2, 1, 1, 1, 19, 1, 1, 1, 37, 38, 38, 38, 38, 39, 2, 2, 2],
         "height":16,
         "name":"Capa de Patrones 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":16,
         "x":0,
         "y":0
        }, 
        {
         "color":"#ff0000",
         "draworder":"topdown",
         "height":16,
         "name":"Collisions",
         "objects":[
                {
                 "height":256,
                 "id":3,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":0,
                 "id":4,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":258,
                 "x":0,
                 "y":256
                }, 
                {
                 "height":256,
                 "id":11,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":257,
                 "y":0
                }, 
                {
                 "height":1,
                 "id":12,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":257,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":64,
                 "id":13,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":15,
                 "x":47,
                 "y":95
                }, 
                {
                 "height":46,
                 "id":14,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":15,
                 "x":63,
                 "y":161
                }, 
                {
                 "height":4,
                 "id":15,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":14,
                 "x":81,
                 "y":203
                }, 
                {
                 "height":13,
                 "id":16,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":2,
                 "x":96,
                 "y":209
                }, 
                {
                 "height":4,
                 "id":19,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":27,
                 "x":99,
                 "y":220
                }, 
                {
                 "height":13,
                 "id":20,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":1,
                 "x":128,
                 "y":225
                }, 
                {
                 "height":3,
                 "id":21,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":57,
                 "x":131,
                 "y":236
                }, 
                {
                 "height":10,
                 "id":22,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":190,
                 "y":225
                }, 
                {
                 "height":2,
                 "id":23,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":14,
                 "x":192,
                 "y":223
                }, 
                {
                 "height":47,
                 "id":26,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":3,
                 "x":203,
                 "y":175
                }, 
                {
                 "height":5,
                 "id":27,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":15,
                 "x":207,
                 "y":171
                }, 
                {
                 "height":59,
                 "id":28,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":4,
                 "x":220,
                 "y":112
                }, 
                {
                 "height":4,
                 "id":29,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13,
                 "x":206,
                 "y":112
                }, 
                {
                 "height":13,
                 "id":30,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":4,
                 "x":203,
                 "y":97
                }, 
                {
                 "height":3,
                 "id":31,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":13,
                 "x":192,
                 "y":97
                }, 
                {
                 "height":14,
                 "id":32,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":5,
                 "x":186,
                 "y":81
                }, 
                {
                 "height":4,
                 "id":33,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":14,
                 "x":176,
                 "y":81
                }, 
                {
                 "height":14,
                 "id":34,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":4,
                 "x":172,
                 "y":66
                }, 
                {
                 "height":6,
                 "id":35,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":76,
                 "x":97,
                 "y":65
                }, 
                {
                 "height":14,
                 "id":36,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":3,
                 "x":97,
                 "y":66
                }, 
                {
                 "height":4,
                 "id":37,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":36,
                 "x":65,
                 "y":80
                }, 
                {
                 "height":14,
                 "id":38,
                 "name":"",
                 "rotation":0,
                 "type":"",
                 "visible":true,
                 "width":5,
                 "x":64,
                 "y":82
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":false,
         "width":16,
         "x":0,
         "y":0
        }],
 "nextobjectid":39,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tileheight":16,
 "tilesets":[
        {
         "columns":16,
         "firstgid":1,
         "image":"..\/tiles\/tiles.png",
         "imageheight":256,
         "imagewidth":256,
         "margin":0,
         "name":"Standard",
         "spacing":0,
         "tilecount":256,
         "tileheight":16,
         "tilewidth":16,
         "transparentcolor":"#ffffff"
        }],
 "tilewidth":16,
 "version":1,
 "width":16
}

**Comment by bjorn** [comment]
Hmm, strange, I can open that file fine, it just reports that it can't find the `tiled.png` tileset. I tried with Tiled compiled from `master` as well as Tiled 0.16.0. Which version of Tiled are you using?

**Comment by Coconaut11** [comment]
I'm also using version 0.16.0
What can I do?


2016-05-30 11:58 GMT+02:00 Thorbjørn Lindeijer <notifications@github.com>:

**Comment by Coconaut11** [comment]
mmm...
Thinking about it... It might be because I the file is saved as TMX and
Tiled tries to open as a TMX file, not as JSON file.

What do you think?


2016-05-30 12:03 GMT+02:00 Roger Esteve <coconaut7@gmail.com>:

**Comment by bjorn** [comment]
Yes, I just realized that his error:
```
Error, It's not a map file.
Line 1, Column 1
```
Is actually not from the JSON plugin, but from the TMX map reader. So, it appears you're trying to open a .json map as a .tmx file.

If you store a map in JSON format, its extension should be .json and not .tmx. Probably this is something I should check for when the map gets saved...

**Comment by Coconaut11** [comment]
Yes thank you!
What can I do now, before you solve it?

2016-05-30 12:07 GMT+02:00 Thorbjørn Lindeijer <notifications@github.com>:

**Comment by bjorn** [comment]
> What can I do now, before you solve it?

Just rename your file to have a .json extension, so that Tiled picks the right map reader when you try to open the file.

**Comment by Coconaut11** [comment]
okk thanks


2016-05-30 12:11 GMT+02:00 Thorbjørn Lindeijer <notifications@github.com>:

**Comment by IMMZ** [comment]
@bjorn , I can look into it. What behavior is expected in this case?
1) Silently replace current file extension from suggested file name to something from the map format if the file name isn't ended by it? (Maybe MapFormat class should have 'QString extension() const' method?) => mymap.json?
2) Silently 'ADD' the new extension from map format if file name isn't ended by it?  => 'mymap.tmx.json'.
3) Any other ideas?

Silence could be replaced by some warning message box.

**Comment by bjorn** [comment]
@IMMZ Ideally, the extension of the suggested file name should change when you change the type. However, I do not think this is possible through the Qt API. Maybe I'm wrong, so feel free to look into that.

If it is indeed not possible, a warning message would probably be the next best thing. Something along the lines of "The file extension does not match the chosen file type. Tiled may not automatically recognize your file when loading. Are you sure you want to save with this extension?". This warning should probably only be added to the Save action and not the Export action.

**Comment by IMMZ** [comment]
It seems that automatic change of suggested filename after changing the filter is impossible through the Qt API. I made first try to solve it.

**Comment by bjorn** [comment]
> It seems that automatic change of suggested filename after changing the filter is impossible through the Qt API.

I noticed at least Windows and OS X native and Qt's own save dialogs already update the extension when you change the selected filter. It's only the native GTK save dialog that doesn't do this.

So in general people should be fine, unless they change the extension manually rather than changing the file type through the combo box, and in that case the new warning dialog will pop up now.
