### ISSUE TITLE
Show Tile Animations option should reset animation

### ISSUE THREAD

**Issue by bitinn** [bjorn/tiled#1288]
As mentioned in #57, tile animation goes out of sync easily during editing and the only solution at the moment is to close and re-open the file.

Given there is not an easy fix, should we just reset animation when you trigger `Show Tile Animations`, that way we at least get a way to reset and sync them properly.

Currently `Show Tile Animations` merely stops or resumes the timer.

PS: I can imagine someone out there using current feature to quickly examine how their animations looks in every frame but I think tools like Aseprite are much more suited for animation editing. Plus Tiled does have a preview screen for animation, just not powerful enough (as discussed in #811)

**Comment by bjorn** [comment]
One way to fix it would be to reset all animations once any animation has been edited. I think I'd prefer that to requiring people to pause/unpause the animations.
