### ISSUE TITLE
Multi column on view/toolbar layout

### ISSUE THREAD

**Issue by giuseppelt** [bjorn/tiled#1291]
I really miss the feature to arrange viewpanels/toolbars on multiple columns, side by side.

Actually you can only have left and right columns, where you can stack panels only vertically. 

On wide screens, there's lot of room to optimize better the space available. I want to achieve something like this:
![image](https://cloud.githubusercontent.com/assets/7147291/15708612/befc6034-27ff-11e6-819d-65dfb0e821d2.png)

**Comment by bjorn** [comment]
I think `QMainWindow` supports that, but it comes at the cost of making simple and more common layouts harder to achieve. I'll try to enable this advanced mode and if I don't like having it on by default, I can make it available as an option.

**Comment by bjorn** [comment]
Please check out a snapshot build when it is done compiling (may take an hour) and let me know how this works for you!
