### ISSUE TITLE
delete key (selection) doesn't work on mac osx

### ISSUE THREAD

**Issue by HawkenKing** [bjorn/tiled#1296]
It works from Edit > Delete. 

From the keyboard it doesn't work.

**Comment by bjorn** [comment]
Which version?

If not the latest snapshot, can you try it with that one?
http://update.mapeditor.org/snapshots-osx/tiled-2016.06.05.dmg

It is built against a newer version of Qt and I wonder if it makes any difference.

**Comment by bjorn** [comment]
Hmm, I've tried to reproduce this issue on a Mac Mini (OS X 10.11) in both Tiled 0.16.1 (built against Qt 5.5) as well as using the master branch (built against Qt 5.5 and Qt 5.6), but could not reproduce the issue. Both the `Delete` as well as the `Backspace` keys work for deleting objects.

If you're using an older version, could you try upgrading? And if not, could you provide any additional information about what may be needed to reproduce this problem?

**Comment by bjorn** [comment]
Presumed fixed since no response was received. Also we still have #1744 open about this, which is essentially a duplicate but also unclear in terms of how to reproduce it.
