### ISSUE TITLE
Eraser selection (suggestion)

### ISSUE THREAD

**Issue by HawkenKing** [bjorn/tiled#1297]
Would be nice to have an eraser that can delete more than one block at a time. The select > delete is slow because you need to use the menu command. Would be nice to have this as a tool.

In most other apps this is handled by making the eraser as a box drawing tool on click-drag.

**Comment by kheftel** [comment]
The delete key also works to delete the current selection.

**Comment by bjorn** [comment]
> The delete key also works to delete the current selection.

Except, see issue #1296 that @HawkenKing also reported. :-)

> In most other apps this is handled by making the eraser as a box drawing tool on click-drag.

Yes, I think this would be a useful addition to the eraser. What about sticking that on right-click drag?
