### ISSUE TITLE
Add SKTilemap to Libraries and Frameworks page.

### ISSUE THREAD

**Issue by TomLinthwaite** [bjorn/tiled#1298]
Hi Bjorn,

I was wondering if it was possible to add my tilemap library to the Libraries and Frameworks page on your website (mapeditor.org). It's for Sprite Kit, written in Swift.
You can find the GitHub page for it here: https://github.com/TomLinthwaite/SKTilemap
I am actively updating it, and I expect the next big update will be compatibility with Swift 3 get its official release this month.

Thank you.

**Comment by bjorn** [comment]
It's definitely possible, in fact you could add it yourself in a pull request to this repository. The list lives in `docs/reference/support-for-tmx-maps.md`. I'll add it later this week anyway, unless you're faster. :-)

Thanks a lot for developing and maintaining this library!

**Comment by TomLinthwaite** [comment]
OK Thanks, I've made the pull request.
And no thank you for making such a good program!

**Comment by bjorn** [comment]
> I've made the pull request.

I don't see your pull request yet. Did you forget something?

**Comment by TomLinthwaite** [comment]
Ok I think I mucked it up last night. I've done it again hopefully this time properly. Sorry my GitHub skills are lacking :P
