### ISSUE TITLE
Changing property types without deleting them

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#1304]
Currently, to change a property, you must delete it and re-add it with the new type and value. While this generally makes sense, it should be possible to convert between types to produce sensible values:

* int 0 -> bool false
* int 0 -> string "0"
* bool false -> string "false"
* bool false -> int 0
* string "false" -> bool false
* string "false" -> int 0

or other such things.

**Comment by Alturos** [comment]
I'm curious, for this ticket, in the case of data that doesn't convert, would nuking the data be acceptable?

**Comment by bjorn** [comment]
I think it should either leave out or disable menu items showing types to which no conversion is possible.

When opening the menu, Tiled could use `QVariant::convert` to attempt a conversion to each supported type and check the return value.
