### ISSUE TITLE
Pinch to zoom no longer works on OSX, causing unwanted jump to 1% zoom

### ISSUE THREAD

**Issue by bfod** [bjorn/tiled#1305]
in .15 I could pinch-to-zoom in OSX, but in .16 if I pinch at all it jumps to 1% zoom and can't be zoomed back. That would be a non-fatal bug, except the pinch gesture is often detected in OSX so the display is often unwantedly jumping to 1% zoom.

**Comment by bjorn** [comment]
That's bad news. Unfortunately, I have no way to test this myself. :S

Since I don't think I changed anything related to this in Tiled 0.16, I fear it may be a Qt bug. I'll have to check which version of Qt Tiled 0.15 was built against to see if it could be a regression. Also, could you try if this still happens in the current snapshot, which is built against Qt 5.6?

https://update.mapeditor.org/snapshots-osx/

**Comment by pouwelsjochem** [comment]
Hi Bjorn,

I just had a look at the new OS X snapshot.. It's different :p It does not go to 1% anymore, but what happens now is the following:

*200% zoom*
*pinching to zoom*
*It starts zooming, but get's pulled back again every frame or so, something like this happens (made up numbers): 200% -> 210% -> 201% -> 220% -> 203% -> 236% -> 206%*
*stopped pinching, zoom stopped at 206%*
*but expected zoom to be more like 250% or something*

I hope this makes sense, if extra information is needed for debug I could record my screen.

**Comment by bjorn** [comment]
Tiled 0.17 was released against Qt 5.7. Did that change anything regarding this issue?

**Comment by pouwelsjochem** [comment]
Hi, sorry for the late reply. 
I am using Tiled 0.18 but the issue is still here.
Do you want me to make a screen recording?

**Comment by bjorn** [comment]
@pouwelsjochem I'm sad to hear it's still there. A recording could be illustrative. Ultimately, I'm wondering how to reproduce this issue myself. I recently got a Wacom Intuos Pro and I wonder if I could reproduce it if connected to my Mac Mini.

**Comment by pouwelsjochem** [comment]
Ah alright, perhaps that will also result in the same bug. But for now, here's the video :)
[https://www.dropbox.com/s/r1zenqaf0n82kv2/zoomBug.mov?dl=0]

Explanation of what is happening:
- I start off with a very slow 'pinch to zoom', which jumps back all the time
- At around 0:06 I do a quick 'pinch to zoom', this does work
- At around 0:10 I start doing the same as the first 2 steps but with zooming-out

**Comment by necrotek** [comment]
Pinch to zoom also does not work with windows 10 tablet mode Tiled v 0.18.2.  I am not sure if this is  a related issue so did not want to start a new topic.  2 finger swipe to move the map Does not work either. It moves the map but snaps back to the original location on release.

**Comment by bjorn** [comment]
@necrotek Ah, thanks for mentioning that. I think that should be possible for me to reproduce, and if I can fix that then we can see if it also fixes the problems on macOS

**Comment by bjorn** [comment]
Alright, I can reproduce this also on my Mac Mini with an Intuos Wacom tablet. Will see if I can find an issue in the code.
