### ISSUE TITLE
Automap doesn't map top edge on different layer

### ISSUE THREAD

**Issue by jusw85** [bjorn/tiled#1308]
I have a single tile mapping (A --> B) from input_Background to output_Collision.
```
regions:
A
input_Background:
A
output_Collision:
B
```

I've floodfilled a 4x4 background as follows:
```
Background:
AAAA
AAAA
AAAA
AAAA
```

Result after Automapping:
```
Background:
AAAA
AAAA
AAAA
AAAA

Collision:
....
BBBB
BBBB
BBBB
```

Expected result:
```
Background:
AAAA
AAAA
AAAA
AAAA

Collision:
BBBB
BBBB
BBBB
BBBB
```

Sample file:
[example.zip](https://github.com/bjorn/tiled/files/321625/example.zip)

**Comment by bjorn** [comment]
I've seen this happening too. Not sure yet what could be causing it. Maybe @stefanbeller has an idea.

**Comment by bjorn** [comment]
I've tried looking into this for a while, but while I can reproduce the issue, I've so far been unable to find out where it goes wrong. In the debugger and printing to console, everything seems to be going fine. But the result in Tiled is clearly wrong. :S

**Comment by bjorn** [comment]
Ok... the layer seems to be shifted, since grabbing a tile brush from it reveals that it does actually have the rules correctly applied. This would explain things, since layers not positioned at 0,0 are not officially supported in Tiled and have never been tested, so it can lead to strange problems.

**Comment by bjorn** [comment]
Hmm, no, it's not that simple... when capturing, the layer isn't shifted. So it's only shifted when painting the layer. I think something goes wrong with the layer draw margins.
