### ISSUE TITLE
Color Property

### ISSUE THREAD

**Issue by adsilcott** [bjorn/tiled#1324]
In some cases having a custom property type of "color" would be useful. 

I would like to set an ambient color property for each map, for the sole purpose of passing it to my game to affect the color of shadows that it generates. It makes sense to add this as a map property in Tiled. It could be an int, but probably better as a string that holds the RGBA hex code (e.g. "7B7CC1FF"), since it's more human readable and there are plenty of methods to parse that format. 

It would be _convenient_ if there was a Color option for parameters that would let me set that value with a color dialog, though I understand if this is too special-case for the effort.

**Comment by bjorn** [comment]
This property type is already there in the snapshot builds and will be in Tiled 0.17. See issue #1275. :-)

**Comment by adsilcott** [comment]
Ah I missed that in my search! Thanks!
