### ISSUE TITLE
Point Object

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#1325]
In general, I feel like most of the object shapes are kind of useless for actual use in most games. What I feel would be the most useful would be a simple Point object so you can place points all over the map and use those as, say, enemy spawners or whatever. Obviously each object has its use, but I think a Point would be good for general use.

The problem with using other shapes for something as specific as an enemy spawn point is that the coordinates are fairly ambiguous. Where in a square is the origin? Top left? Bottom left? Center? It's not immediately obvious. A simple point would be extremely obvious and you don't need to deal with any other data that you don;t need such as size or radius.

**Comment by Seanba** [comment]
I think point objects could serve an important purpose and I think it's been brought up before and is on Bjorn's list of things to get to.

But two quick points:

1. The other shape types are not only useful, but _essential_. I couldn't have made Tiled2Unity without them. Rectangles and Polygons for collisions or triggers, polylines for path segments and one-way platforms, and the Tile Object for decorating a map with sprite data (i.e. representing where a sprite would be spawned in the map), etc..
2. A circle object _is_ unambiguous at representing a point in space. (Although I agree a point would better serve this purpose.)

**Comment by karai17** [comment]
For certain game types, the objects can be useful. For most, I think they aren't. But that's besides the point (pun extremely intended). What is important here is that a Point object is super useful and should totally be added.

**Comment by Seanba** [comment]
> For certain game types, the objects can be useful. For most, I think they aren't.

I can't imagine a game of any complexity not having shape primitives as first class data types. Whatever game you currently have plans for making the time will come that you need one of these object types for a collision or trigger volume, or for pathfinding, or any number of features.

**Comment by kheftel** [comment]
Just use a circle of a certain size and use its center to represent the point, or a one-tile square and take its center (what I currently do).  That way you can actually see and manipulate your point objects as you design the level.

**Comment by karai17** [comment]
Neither of those options are really acceptable. A point is a very basic and
useful primitive to have.


---
Landon Manning
lmanning17@gmail.com

**Comment by Seanba** [comment]
While I agree a point primitive is useful a circle, most certainly, _is_ acceptable. Good luck making your game.

**Comment by bjorn** [comment]
Guys, I agree Tiled could use an explicit point object, but it's also true that it already offers plenty of alternatives, which is why it hasn't been a priority.

Actually the biggest reason I see for having such an object, is that all the other objects are resizable. It is annoying to avoid hitting one of the 9 resize handles for objects that just mark a location (you _could_ hold Alt to avoid this, but it would be better if the handles weren't there at all).

**Comment by agersant** [comment]
I'm going to take a stab at implementing this. I'm hoping it shouldn't be too hard because I can look at the existing shapes for the general idea.

**Comment by bjorn** [comment]
@agersant That looks like a great start! Please don't hesitate to open a pull request early on so I can already give some feedback on the code.
