### ISSUE TITLE
can i export part of layers and with own type

### ISSUE THREAD

**Issue by SeminYun** [bjorn/tiled#1336]
hi. 

i have two question 

can i export part of layers.
if layers have test01, test02, test03,  and i only wanna export test02, how can i do this?

second question
how can i own export data?  does only way modify code on github?
(this reason is i wanna use each parts(server and client)

thx always

best regards..

**Comment by bjorn** [comment]
> can i export part of layers.
> if layers have test01, test02, test03, and i only wanna export test02, how can i do this?

No, at the moment the only way to export only some layers of your map would be to write your own exporter or to (temporarily) delete the layers that you do not want to export before doing the export.

> how can i own export data? does only way modify code on github?
> (this reason is i wanna use each parts(server and client)

You own your data. Tiled is free software and as such makes no restrictions on how you use it. But if you want to reuse Tiled _source code_, then you need to abide its license (GPL) and release the rest of the code under the same license.

The low level parts of Tiled, in the `src/libtiled` directory, are BSD licensed and as such can be used without affecting the license of the rest of your source code.
