### ISSUE TITLE
Ctrl+s saves unfinished objects

### ISSUE THREAD

**Issue by futile** [bjorn/tiled#1348]
OS: Linux
Tiled version: 0.17.0

## How to reproduce:
* Create a new empty map (details don't matter)
* Add an object layer
* Select the polyline tool, and place a single point, DO NOT finish or cancel the line
* Hit "Ctrl+s" and save the map somewhere
* HIt "Escape" to cancel editing the polyline

## Problem:
* The saved file now contains an entry for the unfinished polyline.
* After cancelling creation of the polyline in the editor, the tab will not be marked as "modified", as indicated by a '*' in front of the filename. However, saving again will write a different file, one without the polyline.

The same happens for polygons, ellipses, rectangles and tile-objects as well. I did not check the windows and os x versions for this issue.

**Comment by bjorn** [comment]
Just don't hit Ctrl+S while using some tool. :-)

Anyway, you're right, it's actually something I hadn't anticipated when implementing this. It could be solved by either blocking the Save action while a tool is active, or by not actually referencing the new object from the map yet while placing it. I'll try to go for the latter, but it could be a tricky change.

**Comment by bjorn** [comment]
Didn't turn out to be so tricky, but I pushed it to `master` instead of `0.17` since it's such a rare bug and there is always a small risk of introducing more serious issues.

**Comment by futile** [comment]
@bjorn thanks for the quick fix! It wasn't a major problem for me, I just noticed that it happened and thought I'd report it. Thanks again :)
