### ISSUE TITLE
No output in CLI

### ISSUE THREAD

**Issue by buckle2000** [bjorn/tiled#1352]
x64 version 0.17.0
![default](https://cloud.githubusercontent.com/assets/10850402/18300755/c1f517c6-74fe-11e6-94a6-dc9323a07673.PNG)

**Comment by buckle2000** [comment]
functional though

**Comment by bjorn** [comment]
Right, graphical Windows applications can't actually output to a console as far as I am aware. See issue #953. The solution would be to put command-line functionality in a separate executable as done in PR #1187.

**Comment by bjorn** [comment]
Just noting that even without having a separate tool like in #1187, issue #953 was eventually addressed with change d5882a5e3ee8a98e9106ff2acc108b8c969a4637.
