### ISSUE TITLE
Collision Mesh Not Exporting after update to .17

### ISSUE THREAD

**Issue by 2dduane** [bjorn/tiled#1355]
Not sure why, but I'm on ver .17 tiled and 1.0.7.8 tiled2unity. I create my tiles, create collisions in collision editor and run export as usual except this time no collision object gets generated.  Was there a workflow change? Never had problem till now.  Thank you.

**Comment by Seanba** [comment]
Hi duane, if the future this is probably best suited for the Tiled2Unity github, not Tiled, but the colliders should be exported just fine. Check for any errors/warnings in Tiled2Unity and in Unity's console window. If there is nothing helpful there you can you send me your TMX file and the exported *.tiled2unity.xml file to debug a bit.

**Comment by bjorn** [comment]
Since there was no further information provided and no indication that it would be an issue in Tiled, I'll close this now. Thanks for jumping in, @Seanba!
