### ISSUE TITLE
Sometimes can't draw any polygon on an ObjectLayer

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#1358]
Sometimes , can't draw any polygon on an ObjectLayer.
0.17 for  macOS 

I've  used TiledMap many years and I know how to draw polygons.
I think I don't take  any basic or  low level mistake.

**Comment by bjorn** [comment]
Please try to be more specific than "sometimes". Also, is this a new problem in Tiled 0.17 or did you encounter it also in older versions?

**Comment by bjorn** [comment]
Many years have passed and I haven't heard any other reports about people being unable to draw a polygon. Without further information there's no way to know what went wrong here, so I'll close this issue.
