### ISSUE TITLE
Type conversion when exporting to Lua

### ISSUE THREAD

**Issue by buckle2000** [bjorn/tiled#1359]
![default](https://cloud.githubusercontent.com/assets/10850402/18550425/5c9244ba-7b86-11e6-934a-21e5550527e1.PNG)
Strings!

**Comment by buckle2000** [comment]
Also, generated lua file is larger than the original tmx file.

**Comment by bjorn** [comment]
That those numbers are printed out as strings is a bug that I shall have to look into.

The generated Lua file is often larger for two reasons. All variables are printed on their own line, while in XML the attributes are all on the same line as the starting element. Second, in the Lua format most variables are included unconditionally to make the file easier to work with, while in the TMX format, attributes that have their default value are generally left out.

**Comment by buckle2000** [comment]
If a field is empty, it will represent in the exported lua file like this:
`some_field = ""`
just drop this field!

**Comment by bjorn** [comment]
> If a variable is empty, it will represent in the exported lua file like this:
> some_field = ""
> IMO just don't output this variable!

I think we should indeed leave more out, for example the "type" and "name" properties when they are left empty. 

@Karai17 what is your opinion on this?

**Comment by karai17** [comment]
I don't necessarily like omitting data since it makes the Lua file very unreliable, meaning a library will need to type check every single field it tries to use, lest some edge case causes it to be nil, crashing the program.

I also don't really like stringifying data that is not normally a string, but that feels like the lesser of two evils here. What fields, specifically, are we talking about?

**Comment by bjorn** [comment]
> I also don't really like stringifying data that is not normally a string, but that feels like the lesser of two evils here. What fields, specifically, are we talking about?

The highlighted ones, so the `tileid` and `duration` of each animation frame. It would of course be easier for everyone if those were exported as numbers, and I'm a little confused that they aren't.

**Comment by kheftel** [comment]
> I don't necessarily like omitting data since it makes the Lua file very unreliable, meaning a library will need to type check every single field it tries to use, lest some edge case causes it to be nil, crashing the program.

I thought the convention with Lua was that missing data is nil, and you'd have to check data for it anyway. Makes more sense to use nil (i.e. omit it) than an empty string IMHO.

**Comment by karai17** [comment]
Is that a new bug? I don't recall those being strings before... but that aside, those would never be empty to begin with, since any animation frames with no data... aren't frames, and the whole frame would be omitted, no?

**Comment by karai17** [comment]
@kheftel That depend son the data. My concern is having to make extremely padded code filled with asserts or the equivalent to try/catches. It's annoying and complicated. I'd rather any empty data be present if the data is something that should be present to begin with, such as an object name being an empty string.

**Comment by bjorn** [comment]
> Is that a new bug? I don't recall those being strings before... but that aside, those would never be empty to begin with, since any animation frames with no data... aren't frames, and the whole frame would be omitted, no?

May be a new bug, not sure yet, will see when fixing it. In any case we're talking about two different issues here and the empty values thing of course doesn't apply to the animation frame info.

**Comment by bjorn** [comment]
So, that wasn't a new bug, just something I missed while adding this to the Lua export. Fix will be released with Tiled 0.17.1. Thanks for reporting it!
