### ISSUE TITLE
Please add native GameMaker Studio export support

### ISSUE THREAD

**Issue by cursedtoast** [bjorn/tiled#1369]
This would be heavenly! GMS map editor is both good and awful. Tiled, however, would be perfect! It's the perfect pair, and with so many people jumping on board from the Humble Bundle, many would want to take advantage of it.

**Comment by bjorn** [comment]
@cursedtoast With pull request #1386 merged and several follow-up changes pushed, I'm eager to hear any further feedback before this new plugin gets included in the next release. I'll update the snapshots later today so that it will be easier to try it out.
