### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by battletag12** [bjorn/tiled#1376]
I run Tiled and create a new tileset. When i hit the browse button, it crashes

**Comment by battletag12** [comment]
I'm on Windows 10

**Comment by battletag12** [comment]
![aaaaa](https://cloud.githubusercontent.com/assets/10885518/19413003/ef4003b2-92d6-11e6-9012-df36b5ea4daa.PNG)
![aaa](https://cloud.githubusercontent.com/assets/10885518/19413004/ef535aac-92d6-11e6-8167-cc2ece2e4c11.PNG)
![aaaa](https://cloud.githubusercontent.com/assets/10885518/19413005/ef5a169e-92d6-11e6-8906-185548c7928e.PNG)

**Comment by bjorn** [comment]
Thanks for the report! Does Tiled also crash if you avoid the Browse button by dragging the tileset image on top of the Tilesets view? That should open the new tileset dialog with the source image already filled in.

**Comment by battletag12** [comment]
ok ill try it

**Comment by battletag12** [comment]
It works

**Comment by battletag12** [comment]
oh wait
i cant save the map it crashes

**Comment by battletag12** [comment]
anytime when it has to open an import/export window it crashes.

**Comment by battletag12** [comment]
oh wait, I fixed it. I just downloaded the win32 version and it worked

**Comment by bjorn** [comment]
So it must be either a bug in Qt or a packaging issue (and I think it may be more likely the latter). The 32-bit builds are done with MinGW instead of Visual Studio, so they are less likely to be affected by DLL compatibility issues.

**Comment by bjorn** [comment]
Going to close this one since I never heard anyone else about this issue and don't know what to do about it. Quite possibly, the issue no longer exists with current Tiled versions.
