### ISSUE TITLE
Misaligned grid and selection after offset change

### ISSUE THREAD

**Issue by nykm** [bjorn/tiled#1377]
Hello, I did not find any open issues relating exactly to this one.

Problem:

1. Open _sewers.tmx_ example
2. Select tiles (i.e. _Magic Wand_ tool)
3. Select _Offset Layers_ tool
4. Drag the Bottom layer with left mouse button to change the offset
5. Tile selection seem to be misaligned
6. Switch to Top layer
7. Both grid and selection seem to be misaligned

However, this misalignment is corrected when the Bottom layer is selected again which tells me that this is a bug (see the gif).

![offsetissue](https://cloud.githubusercontent.com/assets/9414577/19416191/b51b5bac-9392-11e6-8970-a65083dabd81.gif)

So I'm wondering, is this a bug or a feature?

Versions:
- Tiled 2016.05.25 for Linux (64-bit) 
- Compiled version from Github sources ~week 41 / 2016

**Comment by bjorn** [comment]
The grid seems to be doing the right thing. It is displaying the grid for the currently selected layer, so it is shifted when you select the layer that has an offset.

But there's a bug in that the selection is not immediately moving along with the layer while you apply an offset to it.
