### ISSUE TITLE
Select tile under mouse in tileset dock

### ISSUE THREAD

**Issue by Ablu** [bjorn/tiled#138]
Sometimes I want to find out from which tileset a special tile is. It would be nice to have some shortcut + click which then changes to the right tileset, selects and centers on the tile.

**Comment by bjorn** [comment]
I decided to close this issue, but the current behavior is just to select the tile and with change ed4cc0d35ad9348aa8302f9737719ef871beae14 also to switch tilesets. It doesn't make sure the tile is also visible, however.

Also, this only covers tile layers. There is still no way to select the tile used by a tile object. This could be solved by adding a context menu action.

**Comment by bjorn** [comment]
> It doesn't make sure the tile is also visible, however.

Correction, it appears it does!
