### ISSUE TITLE
 Unreadable CLI Output

### ISSUE THREAD

**Issue by buckle2000** [bjorn/tiled#1381]
![default](https://cloud.githubusercontent.com/assets/10850402/19615897/a16a9a18-9839-11e6-9130-889d20f19e76.PNG)

**Comment by bjorn** [comment]
This looks like some kind of encoding problem. Unfortunately, I am not sure how to reproduce it locally so testing a fix will be a little challenging.

It does appear that some characters do show up correctly. Could it also be that your font is missing the characters that appear as `?`?

**Comment by buckle2000** [comment]
I am sure my font has enough character sets.

**Comment by bjorn** [comment]
Found the reason for this bug. The answer is in the [`qPrintable`](http://doc.qt.io/qt-5/qtglobal.html#qPrintable) documentation:
> Note: qDebug(), qInfo(), qWarning(), qCritical(), qFatal() expect %s arguments to be UTF-8 encoded, while qPrintable() converts to local 8-bit encoding. Therefore qUtf8Printable() should be used for logging strings instead of qPrintable().

**Comment by bjorn** [comment]
@buckle2000 The above fix will soon be in the [snapshot builds](https://update.mapeditor.org/snapshots-win/). If possible, please check whether it is fixed.

**Comment by buckle2000** [comment]
![default](https://cloud.githubusercontent.com/assets/10850402/21962584/e2648dc2-db63-11e6-8d57-67a5b9b48b5e.PNG)
It is fixed.

**Comment by bjorn** [comment]
@buckle2000 Awesome, thanks for the confirmation!
