### ISSUE TITLE
type="file" is not being properly reflected by the object property editor

### ISSUE THREAD

**Issue by WildPyromancer** [bjorn/tiled#1387]
A strange issue I encountered while tinkering with my asset conversion pipeline was when I generate an objecttypes.xml (I have a separate tool that I use for object compositing) to be imported into Tiled, it won't display the proper UI element in the property editor. It seems to default to the text field for any of these.

As an experiment, I re-exported the generated file with Tiled that I had previously imported and any of the generated fields that had the type of "file" had no type element in the xml.

-- so --
`<property name="Component.someFile" type="file" default="" />`

-- would become --
`<property name="Component.someFile" default="" />`

Even weirder still is that if I import my generated objecttypes.xml, _add_ a file element to that generated file, and then re-export it, that will be exported properly.

-- so --
`<property name="Component.someFile" type="file" default="" />`

-- would become --
```
<property name="Component.someFile" default="" />
<property name="addedInTiled" type="file" default="" />
```

This issue persists on a fresh restart of the program and I also confirmed that Tiled is not loading another separate objecttypes.xml file. This problem with the editor cells is also consistent between the World Editor Properties toolbar and the Object Properties Editor window. Any separately added properties I believe display correctly on restart.

I've checked my pipeline generated objecttypes.xml against the Tiled generated objecttypes.xml, and aside from some spacing differences, they both look to be the same, so I am inclined to believe that this may be a bug.

**Comment by bjorn** [comment]
Thanks for the report! Turned out I forgot to update some code when adding the `color` and `file` property types. Will be fixed in an upcoming patch release, or try a snapshot build if you need a fix sooner.
