### ISSUE TITLE
QT Wacom tablet issue

### ISSUE THREAD

**Issue by DanFessler** [bjorn/tiled#139]
As an artist/developer, I consistently use my tablet as my primary mouse input.  Qt has developed bugs with Wacom input.  Here is a bug report talking about the issue:  https://bugreports.qt-project.org/browse/QTBUG-6127

This issue has been open for a very very long time and has still not seen a fix.  If you read through the comments you will find that some people have found a patch for the problem that has not yet been implemented into Qt itself.  Would it be possible to implement it into Tiled for the time being so I can actually get work done efficiently?

**Comment by vheuken** [comment]
Just tested Tiled 10.1 with a Wacom Bamboo tablet on Debian Sid.
Everything seems to work perfectly fine.

**Comment by bjorn** [comment]
@vheuken I think this issue was only happening on Windows. But since there hasn't been any news for almost a year and it should be fixed since Qt 5.2 anyway, I'll just close this.
