### ISSUE TITLE
Tiled Crashes if there are missing tileset images

### ISSUE THREAD

**Issue by Archeia** [bjorn/tiled#1393]
What happened was, my team completely disregarded what I said about tilesets being in the same folder.  So I had to set them and I didn't want to do them manually in the json files, however the moment I open, Tiled crashes. 
![image](https://cloud.githubusercontent.com/assets/6222499/20158186/cf65466e-a713-11e6-9da8-c02c89d15fe3.png)

**Comment by bjorn** [comment]
Hmm, in general Tiled does not crash when there are missing images, so probably something happens in your scenario that is a bit more special.

Would it be possible for you to share the JSON file that caused Tiled to crash on startup?

**Comment by Archeia** [comment]
Okay!

**Comment by Archeia** [comment]
I hope it uploaded this time;;;

**Comment by Archeia** [comment]
Ack, that took me a while but here you go! https://rpgmaker.net/media/content/users/778/locker/Camp.zip

**Comment by bjorn** [comment]
Thanks, that helped a bunch!

It's caused by a tile animation, which is missing a check on whether the frame in the animation is actually pointing to a valid tile.

**Comment by Archeia** [comment]
That makes sense, thank you!
