### ISSUE TITLE
Saving to network drive, the progress cannot access the file [...]

### ISSUE THREAD

**Issue by jan-jue** [bjorn/tiled#1404]
![image](https://cloud.githubusercontent.com/assets/11463000/20947834/4e9f5b24-bc11-11e6-8ba5-e07fcf7bc59c.png)

All i am doing is pressing "save" on my windows 10 system to save my current map over network on a  folder on a linux server (synology).

**Comment by bjorn** [comment]
This sounds similar to the issue with saving to a Dropbox folder (#1402). The planned solution for now is to add an option to disable safe saving of files.

**Comment by bjorn** [comment]
Please try the latest [snapshot build](https://update.mapeditor.org/snapshots-win/). The problem should no longer be there if you disable safe writing of files.
