### ISSUE TITLE
"Delete" sign gray and disabled in Custom Properties of Object installed to Map

### ISSUE THREAD

**Issue by Epsiloncool** [bjorn/tiled#1414]
This bug appears when you try to remove previously added Custom Property from installed Object.
The "-" icon looks inactive and in fact, it is not working. However "Delete" key works fine here.

Scrshot: http://epsiloncool.ru/i/E20161213-232531.png

**Comment by bjorn** [comment]
I think this happens when the custom property had been previously defined for the object type, in your case `pointlight`. Indeed it makes sense that it should stay enabled, as a way to unset the property. Thanks for bringing this up!

**Comment by bjorn** [comment]
I needed to make a small followup fix (a4da0fb53e4b37340f322c898c212685b6b15f02) but now these buttons should be working fine. The snapshot builds will update soon and the fix will be in Tiled 0.18.
