### ISSUE TITLE
Use <map> node `version` attribute for feature-signalling/format version

### ISSUE THREAD

**Issue by Yanrishatum** [bjorn/tiled#1416]
Since Tiled developing new features, it's becoming more and more important to store format version in the TMX file. So far XML do not contain any explicit attribute/node to tell which format used and which features are available.  
I propose using `version` attribute as explicit format version for XML, removing any guessing on format version on parser side. This attribute is here for very long time and always had value of `1.0`, hinting that it was planned to use it as format version, yet it never used that way.

**Comment by bjorn** [comment]
I should have been doing this since a long time, but I planned to start incrementing this version attribute once reaching Tiled 1.0. Fortunately, that version is not far off anymore (should be early next year).
