### ISSUE TITLE
Cropping and Offset Map Commands causes Visual Issues

### ISSUE THREAD

**Issue by Archeia** [bjorn/tiled#1418]
- I add a guide image (that I exported from an older tiled json file).
- I select the entire image from a tile layer (since using Guide Layer won't let you select any other tools).
- Crop Selection
- The size is not accurate and at some really frustrating cases, Tiled would add offset to my guide image _and_ some map layers unexpectedly. It rarely happens on smaller maps but on maps like 40x30 + the bug becomes more apparent.

**Comment by bjorn** [comment]
Thanks for noticing and reporting this! The report came in a busy time where I was struggling with a cough and about to leave for family visits, so I only noticed it again today.

You can find the fix in the snapshot builds (as long as you're not on macOS, I'll make sure those builds update again tomorrow) and it will be included in an upcoming Tiled 0.18.1 release. I hope the fix works for you.
