### ISSUE TITLE
Easier hiding of layers

### ISSUE THREAD

**Issue by Loffe** [bjorn/tiled#142]
I'd like slight change of behavior in the layer dock. When I uncheck a layer to hide it, I don't want the hidden layer to become selected. (There is not much you can do with a hidden layer, right?)

Say I have a map with two layers A & B, and I am working in A. For some reason I want to hide B. In the current version, 0.8, I have to uncheck B and then reselect A.

I propose to keep the current selection when unchecking a layer.

(When revealing a layer by checking it, it should be selected as it works now)

**Comment by bjorn** [comment]
I'm closing this since I haven't heard of this problem since 2012 and toggling the checkbox is not changing the currently selected layer. We can assume this was an issue in a much older version of Qt.
