### ISSUE TITLE
Object's Y coordinate and scaling issues with GameMaker room exporter.

### ISSUE THREAD

**Issue by kevintrepanier** [bjorn/tiled#1426]
The room exporter seems to work finely for tiles but have some issues with objects
Issues found :

- Y coordinate of objects have been changed this way : original Y from Tiled minus the object's height = registered Y in GM room.

- Scalings are lost (back to 1.00 in GM). (note : I only tried vertical scaling)

**Comment by bjorn** [comment]
> Y coordinate of objects have been changed this way : original Y from Tiled minus the object's height = registered Y in GM room.

Right, that behavior is only necessary for tile objects, which have bottom-left origin in Tiled. But the exporter was doing it for all objects.

> Scalings are lost (back to 1.00 in GM). (note : I only tried vertical scaling)

Scaling was not supported at all. I'm adding support for scaling tile object instances now.

**Comment by bjorn** [comment]
I've fixed these issues as well as adding exporting of tile objects without type as `tile` elements (84616079f645a0c9bf837ca35ca75771e5193037) and adding support for horizontal and vertical flipping (e6d8a3226e2f7d5abb7eacae4698e1081a593059).
