### ISSUE TITLE
Python option

### ISSUE THREAD

**Issue by FunIsDangerous** [bjorn/tiled#1436]
I dont seem to find a python option anywhere when exporting, I have the 32bit windows version installed and the dll is enabled.

**Comment by bjorn** [comment]
I should write some documentation about this, but the reason is that Python does not ship with Tiled. You need to install Python 2.7 to allow that plugin to load.

**Comment by FunIsDangerous** [comment]
I seem to have python 2.7.5 and there's still not an option to export as python

**Comment by bjorn** [comment]
Ah, sorry the Python plugin does not implement an export to Python, but rather allows implementing import/export plugins in Python.

If you want to just read a map in a Python program, there are several 3rd party libraries available for this.
