### ISSUE TITLE
Collision process, am i missing something?

### ISSUE THREAD

**Issue by MistaGoustan** [bjorn/tiled#1437]
First off, love your application. I'm donating for sure, good work.

I am having a little trouble understanding something about colliders though. If you go into the "Layers" pane you can have 3 types of things in there (Layer, Object, and Image). I know how to add colliders to an object smoothly, but my question is, is the same functionality existant to a "Layer". See below.

![image](https://cloud.githubusercontent.com/assets/15217463/22620592/f28e73ba-eadc-11e6-962f-9ce120254b5b.png)

**Comment by bjorn** [comment]
> First off, love your application. I'm donating for sure, good work.

Thanks a lot!

> I am having a little trouble understanding something about colliders though. If you go into the "Layers" pane you can have 3 types of things in there (Layer, Object, and Image). I know how to add colliders to an object smoothly, but my question is, is the same functionality existant to a "Layer". See below.

The tools you have highlighted all operate on objects or create new objects. This is only possible on Object Layers, so they are disabled when you have a Tile Layer selected. If you want to add a rectangle object as a collision box, you need to select the "CanHaveCollision" layer and use the Insert Rectangle tool.

I'm curious what behavior you had expected instead. Maybe there's a feature missing or maybe things could be made more intuitive.

**Comment by MistaGoustan** [comment]
My confusion is with the separation of responsibility between the layers and objects. So if I was making a wall with colliders I would need both a layer and an object, like this? 

![image](https://cloud.githubusercontent.com/assets/15217463/22657393/56246d16-ec64-11e6-8510-23baf3807980.png)

Is there a way where they can both be on a single object? If not, shouldn't there be? when I use tiled2unity they all end up separate (exactly as they are in the Tiled editor)  and this is frustrating. 
for example:
![image](https://cloud.githubusercontent.com/assets/15217463/22657870/ff1240b4-ec65-11e6-8226-727fc2d24093.png)

**Comment by Seanba** [comment]
Have you looked into the Tile Collision Editor in Tiled? That allows you to put colliders on a tile-by-tile basis and these get baked into the same GameObject in via Tiled2Unity.

**Comment by MistaGoustan** [comment]
I looked at the Tile Collision Editor so many times and it didn't click until now. the reason being is because I couldn't visually see my colliders on the Tiled map after placing tiles I have already edited using the Editor until I actually exported it into unity. I also had "Snap to Grid" selected, and that just put the icing on the confusion cake. lol 

If I may, I'd like to suggest making the colliders that are baked in have some kind of visual indicator showing they have colliders on them when viewing them in the map editor. That'd help out the newbie's a ton. :) 

All in all, the functionality is a god sent, and you both rock. For real, keep up the awesome work!

![image](https://cloud.githubusercontent.com/assets/15217463/22674657/28e7cbe0-ecaf-11e6-9b5f-5842dc83860b.png)

**Comment by bjorn** [comment]
> If I may, I'd like to suggest making the colliders that are baked in have some kind of visual indicator showing they have colliders on them when viewing them in the map editor. That'd help out the newbie's a ton. :)

I believe that is covered by issue #799. It is definitely something I'd like to get around to at some point.

I'm glad to hear to hear this feature suits you so well!
