### ISSUE TITLE
Weird lines stays on screen whenever I move a object.

### ISSUE THREAD

**Issue by abos5** [bjorn/tiled#1439]
As pointed out by red rectangle in the image below, there are weird lines on my tiled map.
Has anyone else had this problem?

![image](https://cloud.githubusercontent.com/assets/5197118/22632107/745f020e-ec51-11e6-8f5d-b41f87de795b.png)

**Comment by bjorn** [comment]
Can you describe what you're doing to get those lines to appear?

**Comment by abos5** [comment]
I wonder if it's because of my environment.

Here is how I reproduce those lines.

1.  Create a new ".tmx" file.
![image](https://cloud.githubusercontent.com/assets/5197118/22653356/0af97cae-ecc4-11e6-8bb2-94c6d43cfb51.png)


2. Import a tile set downloaded from http://opengameart.org/content/timbered-house

![image](https://cloud.githubusercontent.com/assets/5197118/22653330/ff3b43e8-ecc3-11e6-84f0-bd4bb6bd5c08.png)

3. Create a object layer, put one of those houses into the map. And those lines appear when I try to scale or move the house. 
![image](https://cloud.githubusercontent.com/assets/5197118/22653210/b4d7f0c6-ecc3-11e6-8a98-b2e4c5f8661b.png)

**Comment by abos5** [comment]
![image](https://cloud.githubusercontent.com/assets/5197118/22653598/e0cf86e8-ecc4-11e6-9689-51731b51ed82.png)
![image](https://cloud.githubusercontent.com/assets/5197118/22653613/ea63a7c0-ecc4-11e6-97d2-dd4c22dc38ff.png)
![image](https://cloud.githubusercontent.com/assets/5197118/22653656/0f158e3a-ecc5-11e6-9942-aaa40fe5ab57.png)

**Comment by bjorn** [comment]
Ok, there's a bug with the tile object outlines. They will render at the size of the source image regardless of the scaling, which is unexpected and causing the artifacts.

To avoid the artifacts you can turn off these outlines for now at _View -> Show Tile Object Outlines_. I'll have to look into fixing that.

**Comment by abos5** [comment]
Thank you.
It works like a charm. ^_^

**Comment by bjorn** [comment]
It seems I fixed this in change ae21d31e767f5d1cd42987be6e1dbc36ef29bf60 but forgot to close this issue. Please let me know if you still see this issue with tile object outlines enabled, thanks!
