### ISSUE TITLE
Tiled map Editor error

### ISSUE THREAD

**Issue by childsong** [bjorn/tiled#1443]
When I drag my picture to the new block,it will remind me that "open map error" ,"File of map cannot be used". I want to know how to resolve this question.Thank you very much!

**Comment by bjorn** [comment]
For now, you need to drag pictures to the Tilesets view rather than the map view, cause if you drag them to the map view it will try to open them as a map file.

I would like to try improving the handling of dropped files eventually.

**Comment by bjorn** [comment]
Closing issue since it is covered by #1031.
