### ISSUE TITLE
Add a Windows XP compatible build

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1445]
Support for Windows XP was dropped in Qt 5.7 (used since Tiled 0.17.0). Some people are still trying to use Tiled on Windows XP, so it would make sense to add an explicit Windows XP build compiled against Qt 5.6.

http://discourse.mapeditor.org/t/help-tiled-broke/1851/10
https://twitter.com/Yanrishatum/status/828606259985313792

Currently, the last release of Tiled that works on Windows XP was [Tiled 0.16.2](https://github.com/bjorn/tiled/releases/tag/v0.16.2).

**Comment by PazerOP** [comment]
I wouldn't worry about people trying to use Windows XP, especially if it requires maintaining builds against two different versions of Qt.

**Comment by bjorn** [comment]
@PazerOP The work required here should be one-time only with hardly any maintenance needed after that. It's mostly about setting up the `appveyor.yml` to also build against Qt 5.6.

**Comment by bjorn** [comment]
The following build was done against Qt 5.6.2 and should work on Windows XP:

**Comment by Yanrishatum** [comment]
@bjorn We tested it. The .msi installer does not even launch. And with archived version antivirus started to scream on `automappingconverter.exe` to be infected with `Win32:Evo-gen[Susp]`

**Comment by bjorn** [comment]
> The .msi installer does not even launch.

Ok, that could be expected since Windows XP probably ships with a too old version of MSI. Fortunately we have the 7-zip version.

> And with archived version antivirus started to scream on automappingconverter.exe to be infected with Win32:Evo-gen[Susp]

Well, that is most definitely a false positive. Feel free to upload the file to a service like https://www.virustotal.com/. On the other hand, this particular executable is of no interest to your artists and can just be deleted. Could you still try if Tiled works?

**Comment by Yanrishatum** [comment]
Yep, does work. Thanks for listening to those small fraction of people who still use XP and do not discard them :)
About false positive: Yeah, I was sure it false positive, but wanted to notify. Artist use Avast, and out of all antiviruses only Avast flagged `automappingconverter.exe` as a virus. Also it marked `tmxviewer.exe` as well.

**Comment by bjorn** [comment]
A Windows XP compatible build is now available as .zip file from https://thorbjorn.itch.io/tiled. It does not include the auto-updating system, so I recommend installing it through the [itch.io app](https://itch.io/app), which will keep it up to date (assuming their app works on WinXP).
