### ISSUE TITLE
Layer color doesn't show on Objects because of by-default object type color

### ISSUE THREAD

**Issue by Riva3000** [bjorn/tiled#1448]
There is Layer Color param that shows all Objects in that layer colored.
There are also Object Types and Color setting for object type.
Object Type color overrides Layer color.

Now every Object seem to have a default empty? type.
Also Object Types settings are not per .tmx. They carry over to any map.

Now what I did was create a map with several colored object layers full of objects.
Than I probably by accident created new Object Type and gave it **empty string name**.
That Type than maped to every Object with no (empty) type.
Suddenly for every map I opened all objects showed with default gray color dispite their Layer color settings. 
![tied editor layer colors issue](https://cloud.githubusercontent.com/assets/5049959/23078320/8c28d1a8-f548-11e6-9ea2-ac8c4a5a38e6.png)
The accidentaly created Object Type with empty Type name mapped to every object and overriden the color.

Seemd like a bug and took me a while to figure out.

At least the part that Object Type with empty string name maps to all Objects with no type seem like a bug though.

**Comment by bjorn** [comment]
You're right that it's a little unexpected, though it could also be used as a feature so I'm not in a rush to "fix" this. I think it's rare to run into this, so possibly for every person being confused by it there is somebody else actually relying on this behavior.

It may be that it makes sense to change this behavior as part of implementing #1410.

**Comment by Riva3000** [comment]
Understood.

The most cofusing part is that if I just create a new Object Type (in Object types editor) and NOT touch its name field (leaving it null I guess ?) it doesn't map to Objects with no type.
But if I click into the Object Type name field, enter nothing, and press enter, it probably assigns an empty string ? there and suddenly it maps to the Objects. And the Object Type name field looks empty as before, no indication for user of that.

Maybe if you can at some point add some indication there and better yet also replace the Type field's value in Object properties with something like "default type" instead of just empty field. 
Would make things a lot clearer imho.

**Comment by bjorn** [comment]
> The most cofusing part is that if I just create a new Object Type (in Object types editor) and NOT touch its name field (leaving it null I guess ?) it doesn't map to Objects with no type.

Hmm, that is more like a bug. There is no difference between an unset type and an empty type, so what is missing here is mostly some update handling.

**Comment by bjorn** [comment]
So change 02ba8cd60b9b32afab3ccdd09247b062d41733e6 should at least fix that most confusing part. It's a small change that'll be included along some other fixes with Tiled 0.18.2.
