### ISSUE TITLE
Command for exporting to png

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1453]
### Request
It would be nice if we could run a command to export a tmx file to an image or something else.

### Examples
**Export to image**
Linux
`$ tiled.appImage -file=randomfile.tmx -export=image`
Windows
`> tiled.exe -file=randomfile.tmg -export=image`
Generates randomfile.png

**Export to json**
Linux
`$ tiled.appImage -file=randomfile.tmx -export=json`
Windows
`> tiled.exe -file=randomfile.tmg -export=json`
Generates randomfile.json

etc etc

### Reason

Some games may have user contributed levels/maps (take for example [happy wheels](http://vignette2.wikia.nocookie.net/happywheels/images/6/67/User_Level_Browser.png/revision/latest?cb=20140314070444)). We want the users to make their own map with tiled and upload a .tmx file. We can already read the file, but exporting it to png isn't yet possible. That would be so awesome if possible!

### Note
If this feature is going to be made, API documentation would be nice :)

**Comment by bjorn** [comment]
Exporting to other formats is already possible (see `tiled --export-map` and `tiled --export-formats`). That does not include images though. For that, a secondary application called `tmxrasterizer` is shipping with Tiled.

**Comment by issy123** [comment]
awesome! Thank you for your fast response :)
