### ISSUE TITLE
In objects view being able to add columns

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1462]
### Request
It would be nice if we could add columns to the objects list. Like id, x,y.
When you right click on the columns you should see a list of columns you can add/remove.

### Example

![27u04nt](https://cloud.githubusercontent.com/assets/531764/23527189/404523f2-ff95-11e6-8d1d-200d70e3010b.png)

### Reason

Same as #1453

### Note

It would be nice to add custom attributes too! But maybe I ask too much.

**Comment by bjorn** [comment]
> It would be nice if we could add columns to the objects list. Like id, x,y.
> When you right click on the columns you should see a list of columns you can add/remove.

Good idea! It could be implemented by using `QHeaderView::setSectionHidden` and `Qt::CustomContextMenu`.

> Same as #1453

What does this have to do with exporting to PNG? Wrong number?

> It would be nice to add custom attributes too! But maybe I ask too much.

That is definitely asking too much! :-P

Actually this would be entirely possible, but the implementation would look very different and could work relatively independent of the other feature, so it should just be done in its own patch. You would not use `setSectionHidden` but would instead talk to the `MapObjectModel` about adding custom columns.

**Comment by issy123** [comment]
>>Same as #1453

>What does this have to do with exporting to PNG? Wrong number?

This:
> Some games may have user contributed levels/maps (take for example happy wheels). We want the users to make their own map with tiled and upload a .tmx file. 

It has to do with parsing contributed maps and giving the users some information to work with if errors occur.


If I tell the user the object with id x has an invalid value of property y
If he has to click on every single object he has made to get object x, this wouldn't be user-friendly.

You may ask why not refer to object name or type? Well it can be that this is also not defined, the only way to refer to an object with empty values is by it's ID or location (x,y).

Ps. i'm heavily using tiled so expect more feature requests 🏭 
Hope you won't mind ghehe

**Comment by bjorn** [comment]
Alright, that makes sense.

> Ps. i'm heavily using tiled so expect more feature requests 
> Hope you won't mind ghehe

Not at all, it's great receiving your feedback!

**Comment by bjorn** [comment]
An example implementation of this can be found at https://github.com/rsachetto/sir/blob/0f7d463e9be25c883e49bc734dfc136564c4fe93/src/widgets/treewidgetheader.cpp. Though I'd prefer an implementation that did not rely on subclassing the QHeaderView, but rather used `Qt::CustomContextMenu` to change the context menu of the existing header.
