### ISSUE TITLE
Consider zooming with mouse wheel by default

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1472]
Currently, you need to hold Ctrl in order to zoom in/out with the mouse wheel. However, some editors default to zooming and some users expect this to be the default (see [feedback](http://discourse.mapeditor.org/t/feedback-after-a-couple-months-with-tiled/2090) from @eevee).

I believe GameMaker has actually switched from zooming by default to zooming with Ctrl in GameMaker Studio 2, but they do have a quick option to turn on zooming by default.

Maybe the default should be changed to zooming in/out, but for sure there should be an option for this. Potential problems with doing it by default is that it may confuse people who are using a trackpad, at least if pinch zooming would work (#1305), it would suck if trying to scroll would zoom in/out as well.

**Comment by ketanhwr** [comment]
We can add this option in the Preferences dialog, right?

**Comment by bjorn** [comment]
@ketanhwr That would be the right place indeed, because I don't expect users will toggle it often. It should probably go under "Interface", even though it's a little crowded and the options there are rather varied.
