### ISSUE TITLE
Crash when moving multiple objects between layers

### ISSUE THREAD

**Issue by happyponyland** [bjorn/tiled#1473]
I've been experiencing crashes when using Move Object to Layer. It works if I only have a single object selected, but if I have at least 2 that need to change layer it segfaults. I'm only using rectangles so I'm not sure if it affects other object types.

(I'm using 0.18.1 from the Arch repo, sorry if this is a duplicate report or has been fixed already - I couldn't find any changelog.)

**Comment by bjorn** [comment]
Yep, I had already [fixed that bug](https://github.com/bjorn/tiled/commit/ee4f8980dd4ff4fb07a0f9b9a7b2bf894f1b7087) in Tiled 0.18.2. Now the Arch Linux package is flagged out of date. :-)

Was a silly regression...

**Comment by bjorn** [comment]
The changelog sits in the `NEWS.md` file, btw: https://github.com/bjorn/tiled/blob/master/NEWS.md
