### ISSUE TITLE
Change coordinate info to pixels instead of tiles

### ISSUE THREAD

**Issue by surprise0451** [bjorn/tiled#1483]
Currently, the coordinate info in the bottom left of the screen shows the coordinates of the tile underneath the cursor.

I propose an option to change this to pixels rather than tiles. Here is an illustration to help:

![kr2hoag](https://cloud.githubusercontent.com/assets/531764/23845082/677d7ef4-07c6-11e7-9bc5-7d6e267233db.png)

**Comment by bjorn** [comment]
Pixel coordinates were added to the status bar in Tiled 0.18:

![2017-03-13 08_27_33-orthogonal-outside tmx - tiled](https://cloud.githubusercontent.com/assets/531764/23845201/fede8946-07c6-11e7-8bee-fa1470bf98af.png)
