### ISSUE TITLE
The Filltool crashes !

### ISSUE THREAD

**Issue by heartnode** [bjorn/tiled#1486]
Hey ! I don't now if this has been posted so far, but here's my issue:
Operating System: Win 10
Version : Tiled 0.18.2
Opened a new map tried to use the filltool and it crashes.
Bug was replicated on multiple Win 10 Systems!
HerrJunky

**Comment by bjorn** [comment]
Hmm, do you have more specific instructions about how to reproduce? Did you just create a new map, click the fill tool and then click the map view? No tileset was added to the map? Was a tile selected?

**Comment by bjorn** [comment]
Could it be that you had the "Hardware accelerated rendering" option turned on? At some point I've fixed a crash that was caused by trying to render too many tiles at the same time, which could happen when filling a large empty map with the same tile.

**Comment by bjorn** [comment]
Closing this since it's an old issue with no news from the reporter.
