### ISSUE TITLE
Make the object selection rectangle more visible

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1489]
The selected objects are currently highlighted with a thin dashed black line. This doesn't work on dark backgrounds, and it also works very bad in combination with the "highlight current layer" feature.

![selection_153](https://cloud.githubusercontent.com/assets/531764/23952885/3015c3e4-0993-11e7-89f1-442b2315aaf9.png)

Quiz: which objects are selected?

Based on [feedback](http://discourse.mapeditor.org/t/feedback-after-a-couple-months-with-tiled/2090) from @eevee.

**Comment by ketanhwr** [comment]
Answer to quiz: 
![Answer](https://image.ibb.co/ncjRqa/quizlol.png "Answer")

Do I get a cookie? :joy:
