### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by mariel0299** [bjorn/tiled#1511]
A friend of did some maps, and he sent me via skype i downloaded them and now i have this problem,to mention i have the assets he used, and if i do "locate file " for every files on there ,i can work on it ,but next time i open it is the same 
![help](https://cloud.githubusercontent.com/assets/26693578/24333983/ce11abd2-126a-11e7-89d1-ff50b28c7f06.png) 
please help :)

**Comment by bjorn** [comment]
Please don't double-post. I just answered your question [here](http://discourse.mapeditor.org/t/files-not-found/2226).
