### ISSUE TITLE
Tileset export to TSX removes custom properties of tiles

### ISSUE THREAD

**Issue by Yanrishatum** [bjorn/tiled#1513]
**Tiled version**: Commit f7c2c3f19890132e3780c157155e683086a9aa61  
**OS**: Windows 7  
**Desciption**:  
Exporting tileset from TMX file to TSX  deletes all tile properties in the process. But it does save properties of objects in tile collision objectgroup.  
Reproduced both for image collection and stadart tileset types.
**Steps to reproduce**:
1. Create a tileset, assign any custom properties to said tileset.
2. Export tileset to TSX file.

**Example of data**:
TMX file `<tile>`:
```xml
  <tile id="8">
   <properties>
    <property name="graphic" value="graphics/button_red.anilist"/>
    <property name="module" value="PressurePlate"/>
   </properties>
   <image width="28" height="7" source="graphics/button_red_up.png"/>
   <objectgroup draworder="index">
     <object id="1" x="6" y="3" width="16" height="4">
      <properties>
       <property name="proptest" value="1"/>
      </properties>
     </object>
   </objectgroup>
  </tile>
```
TSX file `<tile>`:
```xml
 <tile id="8">
  <image width="28" height="7" source="graphics/button_red_up.png"/>
  <objectgroup draworder="index">
   <object id="1" x="6" y="3" width="16" height="4">
    <properties>
     <property name="proptest" value="1"/>
    </properties>
   </object>
  </objectgroup>
 </tile>
```

**Comment by bjorn** [comment]
Thanks for the detailed bug report!
