### ISSUE TITLE
Too much indentation in .json format. Increases file size by x2

### ISSUE THREAD

**Issue by RainingChain** [bjorn/tiled#1517]
The .json format has too much of indentation. The indentation increases the file size by a factor of 2 and potentially more in certain cases.
Layers have an indentation of 9. Tiles part of a terrain have an indentation of 17. 

![](http://puu.sh/v2T49.png)
![](http://puu.sh/v2T6B.png)

I have over a thousand maps that I'd like to convert from .tmx to .json but doing so would increase the size by a factor of 2 because of the useless indentation. Without the indentation, the file size is acceptable.

[MapWithIndent.json](http://puu.sh/v2TdP.json) - 28KB
[MapWithoutIndent.json](http://puu.sh/v2Tg6.json) - 14KB
[Map.tmx](http://puu.sh/v2Tjr.tmx) - 13KB

Using Tiled Version 0.18.2

**Comment by bjorn** [comment]
> I have over a thousand maps that I'd like to convert from .tmx to .json but doing so would increase the size by a factor of 2 because of the useless indentation. Without the indentation, the file size is acceptable.

That's an impressive amount of maps!

Would it be an option for you to drop both the indentation and the newlines? Then issue #944 would be what you're looking for. It remains a feature that's still to be implemented, though.

**Comment by bjorn** [comment]
An option to minimize the files on export was added (see #944).

This option will not affect files that are simply saved, under the assumption that minifying files is not generally useful when keeping them in version control, but mostly only useful for distribution. The process of exporting minified versions can be automated on the command-line, however.
