### ISSUE TITLE
Make predefined properties connected to tmx file

### ISSUE THREAD

**Issue by cra0zy** [bjorn/tiled#1519]
Instead of making it so predefined properties are stored in a config file for all the maps, couldn't you make it so you can specify the predefined properties file per map?

**Comment by bjorn** [comment]
It could be done that way, but it would be very annoying for people who have many maps (some projects have [over a thousand](https://github.com/bjorn/tiled/issues/1517)).

So, the planned feature to add is support for a "Tiled project file", which would provide a place for project specific settings like the predefined properties, and it could contain the list of maps and tilesets in the project.

**Comment by bjorn** [comment]
Almost a duplicate of #1263.

**Comment by cra0zy** [comment]
You know, I totally forgot about me opening that issue...
