### ISSUE TITLE
key shortcuts don't work ubuntu 16.10

### ISSUE THREAD

**Issue by wec22** [bjorn/tiled#1532]
all of the key shortcuts don't do anything.  Currently running ubuntu 16.10 and using the daily builds from the ppa.  I have to manually click the save, undo, redo, etc. buttons.  It is really a pain to have to dig into the menus to toggle the grid as frequently as I do.

**Comment by ketanhwr** [comment]
Duplicate of #1458

**Comment by wec22** [comment]
sorry. I tried looking for one, I guess I skimmed over it

**Comment by bjorn** [comment]
Let's hope this will be fixed in Ubuntu 17.04 (to be released in 2 days)... please let us know if so.
