### ISSUE TITLE
Ability to add Custom Properties to Image tag (Feature Request)

### ISSUE THREAD

**Issue by Seanba** [bjorn/tiled#1533]
Hi Bjorn, some users are creating maps with tilesets that use textures with the same filename, albeit they are different files in different folders. This is confusing Tiled2Unity because it doesn't know what to do with these similarly-named textures when they are being exported.

I'd like users to attach a custom property to the <image> tag through some means in Tiled to help direct Tiled2Unity in these cases. A custom property on the tileset itself is already possible but that won't work for tilesets that are made up of a collection of images.

**Comment by bjorn** [comment]
> A custom property on the tileset itself is already possible but that won't work for tilesets that are made up of a collection of images.

In that case, a custom property set on the tile would work, right?

**Comment by Seanba** [comment]
Yes, I think that would be fine in that case. Thanks, Bjorn.
