### ISSUE TITLE
Provide an API that allows Qt Quick games to position game objects within an isometric map

### ISSUE THREAD

**Issue by mitchcurtis** [bjorn/tiled#1538]
https://github.com/mitchcurtis/quick-tmx-viewer is an experiment to see how easy it would be to use Tiled to create a simple isometric game with Qt Quick. Now that the map rendering side is [almost there](https://github.com/bjorn/tiled/pull/1535), the next hurdle becomes showing game objects "within" the map. That is, having e.g. a Rectangle as a child of Tiled.MapItem, that can be moved to different tiles by clicking within a MouseArea. This would be simple with an orthogonal map, but without an API in [quicktiledplugin](https://github.com/bjorn/tiled/tree/wip/qtquick/src/tiledquickplugin), it is kinda tricky.

It would be great to have (invokable) functions exposed somewhere (e.g. MapItem, or in a new MapView type) that take a screen position and return a map/tile position, and vice versa. 

Here's a really rough example of how it might look:

    Tiled.MapLoader {
        id: mapLoader
        source:  "isometric_grass_and_water.tmx"
    }
    
    Tiled.MapView {
        id: mapView
        
        Item {
            id: scene
            
            Tiled.MapItem {
                id: mapItem
                map: mapLoader.map
            }
            
            Rectangle {
                id: player
            }
        }
    }
    
    MouseArea {
        anchors.fill: mapView
        onClicked: {
            var scenePos = mapView.viewPosToScenePos(mouseX, mouseY)
            player.x = scenePos.x
            player.y = scenePos.y
            
            // For tile coordinates:
            // var tilePos = mapView.viewPosToTilePos(mouseX, mouseY)
        }
    }

In addition, there are lots of potential properties in Map that could be exposed, which could be done independently of the feature mentioned above. Just to name a few:

1. [width](https://github.com/bjorn/tiled/blob/master/src/libtiled/map.h#L153)
2. [height](https://github.com/bjorn/tiled/blob/master/src/libtiled/map.h#L163)
3. [tileWidth](https://github.com/bjorn/tiled/blob/master/src/libtiled/map.h#L178)
4. [tileHeight](https://github.com/bjorn/tiled/blob/master/src/libtiled/map.h#L188)

**Comment by mitchcurtis** [comment]
Oh, there's a bunch of these conversion functions already: https://github.com/bjorn/tiled/blob/wip/qtquick/src/libtiled/isometricrenderer.cpp

I don't see the renderer being used much by TileLayerItem though..

**Comment by bjorn** [comment]
> I don't see the renderer being used much by TileLayerItem though..

It's because the interface largely based on QPainter. I think we'll need to split it up or refactor it, so that it becomes useful for both QPainter and Qt Scene Graph based rendering of maps.

But for now, you can use these map renderers for adding coordinate conversion functions to the map item.

**Comment by mitchcurtis** [comment]
> But for now, you can use these map renderers for adding coordinate conversion functions to the map item.

Ah, perhaps that's more reasonable for now. I was going to add a [MapView](https://github.com/mitchcurtis/tiled/blob/mapview/src/tiledquickplugin/mapview.h) type, but it's hard to think of a decent relationship between the view, the "scene" and the map item itself.

**Comment by bjorn** [comment]
> Ah, perhaps that's more reasonable for now. I was going to add a MapView type, but it's hard to think of a decent relationship between the view, the "scene" and the map item itself.

Yeah, right now the relationship is limited to communicating to the map item what its visible part is. Though when in the future support for parallax scrolling layers is built-in, a special MapView class may start to make sense.

**Comment by mitchcurtis** [comment]
Fixed by https://github.com/bjorn/tiled/pull/1539.
