### ISSUE TITLE
Add the LITIengine to the list of java .tmx libraries

### ISSUE THREAD

**Issue by gurkenlabs** [bjorn/tiled#1549]
The 2D Java Game Engine **LITIengine** supports maps in the .tmx format:
Website: [LITIengine.com](https://litiengine.com)
Github: [gurkenlabs/litiengine](https://github.com/gurkenlabs/litiengine)

There is also a stand alone library (that is no longer actively developed) which allows to deserialize .tmx maps into Java objects:
Github: [gurkenlabs/tmx-deserializer](https://github.com/gurkenlabs/tmx-deserializer)

Please add those libraries to the list of support for .tmx maps (http://doc.mapeditor.org/reference/support-for-tmx-maps/)

**Comment by bjorn** [comment]
Note that you can edit the file here and open a pull request:

https://github.com/bjorn/tiled/edit/master/docs/reference/support-for-tmx-maps.md

> There is also a stand alone library (that is no longer actively developed) which allows to deserialize .tmx maps into Java objects:

I'd rather not add unmaintained stuff to the list. The list could use some serious cleanup instead. :-/
