### ISSUE TITLE
Allow user to insert pushpins in object layers

### ISSUE THREAD

**Issue by adrianlopezroche** [bjorn/tiled#1551]
The current version of Tiled allows users to insert rectangles, ellipses, polygons, polylines, and tiles into object layers, but it's missing the ability to add simple (x,y) position markers. These can be represented as pushpins (see Google Maps for an example) and can be used to mark things like starting positions or spawn points for players and enemies.

**Comment by bjorn** [comment]
I like the idea of representing these objects as pins!

The general feature of "point object" is already covered by issue #1325.
