### ISSUE TITLE
Write output from custom commands to Debug Console window

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1552]
Tiled has a Debug Console window, but it isn't really used. The only thing it is used for at the moment is to allow writing some debug lines from Python plugins.

It would be useful to write the output from custom commands also to the Debug Console.

This would avoid the need for workarounds like [described in this forum topic](http://discourse.mapeditor.org/t/running-python-from-the-command-tool-behaves-wierdly/2277?u=bjorn).

**Comment by ketanhwr** [comment]
@Ablu this is what we planned, right?
