### ISSUE TITLE
tmxrasterizer segmentation fault error

### ISSUE THREAD

**Issue by issy123** [bjorn/tiled#1556]
When I try to generate an png from my tmx file I get an segmentation fault using this command:
`tmxrasterizer test.tmx test.png`

I saw in the ubuntu error reporting that it had something to do with an readTileset function.

The tmx file uses an external tileset

**Comment by issy123** [comment]
I just tested it with an simple map using an external tileset, it crashed.
Here are the test files:
[externalTileset.zip](https://github.com/bjorn/tiled/files/960040/externalTileset.zip)

I am using ubuntu 16.04 and have tmxrasterizer v1 and tiled v0.14.2

**Comment by bjorn** [comment]
> I am using ubuntu 16.04 and have tmxrasterizer v1 and tiled v0.14.2

From the [Tiled 0.15 changelog](https://github.com/bjorn/tiled/blob/master/NEWS.md#0150-4-january-2016):
* Fixed crash in tmxrasterizer and tmxviewer

Without further testing, I reckon that is probably the one you're running into. On Ubuntu, you could install `tiled-daily` builds using [this PPA](https://launchpad.net/~mapeditor.org/+archive/ubuntu/tiled). Or you can upgrade to Ubuntu 17.04, which has Tiled 0.17.0.

**Comment by issy123** [comment]
This works thanks :+1:
