### ISSUE TITLE
Add support for editing Stardew Valley maps

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1560]
Stardew Valley maps are stored inside `.xnb` files (produced by Microsoft XNA Game Studio) in `.tbin` format (a [binary tile map format](https://tide.codeplex.com/SourceControl/latest#TileMapEditor/xTile/Format/TbinFormat.cs) used by [tIDE](https://tide.codeplex.com)). It should be possible to write a Tiled plugin that can directly load and save such maps.

* [SimpleXNBDemapper](https://github.com/Inari-Whitebear/SimpleXNBDemapper) shows how `.tbin` and `.png` files can be unpacked from (and packed into) the `.xnb` files (see [Program.cs](https://github.com/Inari-Whitebear/SimpleXNBDemapper/blob/master/SimpleXNBDemapper/Program.cs))

* [TbinFormat.cs](https://tide.codeplex.com/SourceControl/latest#TileMapEditor/xTile/Format/TbinFormat.cs) shows how a `.tbin` file can be parsed

On the Tiled forum [somebody reported](http://discourse.mapeditor.org/t/copying-and-pasting-between-maps-broken/2318) to have successfully extracted the necessary `.tbin` and `.png` files and then used tIDE to open the map and save it as `.tmx` so that it could be opened in Tiled. It would be cool to simplify this process by supporting `.tbin` and maybe even `.xnb` files containing `.tbin` files directly.

**Comment by spacechase0** [comment]
So I got my XNB loader working for most of the Stardew files (and certainly the ones Tiled would need). It's [here](https://github.com/spacechase0/XNB). I re-ported the library I mentioned earlier [here](https://github.com/spacechase0/libmspack-lzx).

If you aren't happy with that license for that compressor, someone apparently wrote their own [here](https://github.com/LeonBlade/xnbcli/blob/master/app/Presser/Lzx.js). (It doesn't have a license right this moment, but the author tells me he'll put one up in the next day or two. He mentioned "MIT or whatever" earlier today.)

I'm probably going to be writing a tbin loader soon to feature-creep my own project. I'll throw that under MIT as well.

**Comment by bjorn** [comment]
@spacechase0 That's so awesome! Let me know if I can help in any way. Right now, I've got a lot of other things with higher priority, like fixing things for Tiled 1.0.1, mentoring the GSoC students and updating the manual, but I'd really like to work on this as well.

**Comment by spacechase0** [comment]
I got stuck for a while since I didn't know `func( a(), b() )` didn't guarantee the execution order of `a` and `b`, but my [Tbin loader](https://github.com/spacechase0/Tbin) is done now.

**Comment by spacechase0** [comment]
It looks like I'd just need to create something similar to the Json plugin, right?

I noticed that nothing uses the STL. Should I port the things I already wrote to Qt classes, or is the STL fine? (I assume either way I'll be putting these as a sub-directory in the plugin?)

I see that there is a way to add support for another image format with a `QImageIOPlugin`. How reasonable would it be to implement it this way? Or would you prefer a more "manual" approach? (If the latter, some guidance would be appreciated. I keep getting lost trying to find things in the codebase.)

**Comment by bjorn** [comment]
> It looks like I'd just need to create something similar to the Json plugin, right?

At this point, you could import this .tbin loader and turn it into a Tiled plugin. For that it would need to be stripped from its SFML dependency and the logger statements need to be changed.

Note however that there are some differences between tIDE and Tiled that may be problematic:

* tIDE appears to support different tile size per layer, Tiled does not. Hopefully SV doesn't use this feature.
* tIDE appears to store properties for each tile location, which Tiled doesn't directly support (for performance reasons). When loading, objects would need to be created to store these properties and when saving would need to be serialized back to the tile layer.
* tIDE appears to store full tile animations instead of tile indexes in animated locations, and different frames of an animation can come from different tilesets. In contrast, Tiled defines an animation on the tile and refers to it by tile index as usual, and it can only use frames from the same tileset. This means the loader would need to add new tiles for each unique animation encountered, and animations with frames from different tilesets can't be supported (though care could be taken to keep them intact upon saving by using additional meta-data).

> I noticed that nothing uses the STL. Should I port the things I already wrote to Qt classes, or is the STL fine? (I assume either way I'll be putting these as a sub-directory in the plugin?)

Using STL is fine. Actually `std::map` is used by `RangeSet`. :-)

> I see that there is a way to add support for another image format with a QImageIOPlugin. How reasonable would it be to implement it this way? Or would you prefer a more "manual" approach? (If the latter, some guidance would be appreciated. I keep getting lost trying to find things in the codebase.)

I'd say we should implement just the `.tbin` support at first, since it will already help people, and we can then indeed look at adding this.

**Comment by spacechase0** [comment]
> At this point, you could import this .tbin loader and turn it into a Tiled plugin. For that it would need to be stripped from its SFML dependency and the logger statements need to be changed.

That shouldn't be hard. The SFML stuff is just `sf::(Ui|I)nt(8|16|32)` [which is always `(unsigned)? (char|short|int)` anyways](https://github.com/SFML/SFML/blob/master/include/SFML/Config.hpp#L201).

The logger stuff was mainly for my debugging. There used to be a lot more. :P Do you want me to transition those to Tiled or just remove them?

> tIDE appears to support different tile size per layer, Tiled does not. Hopefully SV doesn't use this feature.

It doesn't.

> tIDE appears to store full tile animations instead of tile indexes in animated locations, ... (though care could be taken to keep them intact upon saving by using additional meta-data).

The game itself always keeps animations on the same tileset, so unless you want "full" tbin support we can ignore that.

**Comment by bjorn** [comment]
> The logger stuff was mainly for my debugging. There used to be a lot more. :P Do you want me to transition those to Tiled or just remove them?

For as much as the logged output is actually needed for user feedback about errors, it could be changed to error codes that lead to translatable strings in the Tiled plugin. The parts that are only for debugging should probably just be removed.

**Comment by spacechase0** [comment]
This is probably pretty simple, but I'm getting an error that says "Referenced directory 'G:/Forks/tiled/src/plugins/tbin' does not contain a qbs file." after editing `plugins/plugins.qbs`. Going to the directory does in fact have a qbs file. Any ideas?

**Comment by bjorn** [comment]
The name of the file may need to match the folder name. It is called `tbin.qbs`?

**Comment by spacechase0** [comment]
It does.

I don't know if this is related or a separate issue, but the folder doesn't show in Qt Creator either.

**Comment by bjorn** [comment]
@spacechase0 I got this when I tried to run `qbs`:
```
[bjorn@thor tiled-pr]$ qbs build
Restoring build graph from disk
Resolving project for configuration default
ERROR: /home/bjorn/projects/tiled-pr/src/plugins/tbin/tbin.qbs:8:9 Unexpected token `string literal'
```
It is due to a missing comma after the first file name in the list.

**Comment by bjorn** [comment]
Thanks to @spacechase0, there should now no longer be a need to go through tIDE to edit Stardew Valley maps. I tested it on some extracted .tbin files and it seemed to work very well! The new plugin is [now included in the development snapshot](https://twitter.com/thorbjorn81/status/884874949994962944).

@spacechase0 Do you think it makes sense to continue with actually supporting opening maps directly from .xnb files? I guess with your XNB loader it would be no problem to do it for the maps, but it may be hard to make it work for the tileset images (though the plugin could load them in some custom way I think - probably better than doing a Qt image IO plugin). But if in general people anyway need to unpack and repack their data then loading directly from .xnb files isn't that useful.

**Comment by bjorn** [comment]
Note to self: don't forget to add the tbin plugin to the Windows MSI installer.

**Comment by spacechase0** [comment]
It could be convenient in some cases, but it definitely is not necessary. People who only edit the map would fine it useful, but those who edit the tilesheets do still need to repack the images. (And those of us who make new maps for SMAPI mods don't need to pack either.)

**Comment by bjorn** [comment]
@spacechase0 Then I'll close this issue. Thanks a lot for your work on this!
