### ISSUE TITLE
.tsx tilesets are not added to .tmx if used as object tilesets

### ISSUE THREAD

**Issue by Yanrishatum** [bjorn/tiled#1571]
**Currently**:
If you open .tsx in Tiled, it will add tileset to the tabs, but if you place any objects from that tileset onto map, it creates this:
```xml
<object id="66" gid="0" x="275.5" y="79.5" width="10" height="10"/>
```
Note that gid is `0`. While I work in tiled, it displays the sprite correctly, but if I will close the tmx file and then open it, instead of objects there will be a rectangle, displaced by object height down.  
Important: If I add any image from tsx file as a tile it does add tsx to the list. 

**Proposal/what expected**:

1. As soon as object from .tsx will be placed onto map, Tiled should add this .tsx to the tileset list, and assign correct gids to the objects. 
2. There should be button to explicitly add .tsx file to the map. (if there is, it is not obvious on where exactly)

![sample](http://wb.yanrishatum.ru/i/R7DHP.png)  
The sprite above is what added to .tmx file. Rectangle below is a result of re-opening same .tmx file.

Reproduced on commit dc87d80294f7aa607e5290fc1b93599dcc6f2c92

**Comment by bjorn** [comment]
Hmm, I'm sure this has been reported before though I can't find the issue about it now. In any case I should remember to investigate. The expected behavior is that the tileset will be added to the map automatically when it is used.
