### ISSUE TITLE
Crop to Selection leaves a weird boundary which cannot be painted upon

### ISSUE THREAD

**Issue by ketanhwr** [bjorn/tiled#1572]
After using the crop to selection option, I noticed a bug. It left behind a black boundary which cannot be painted upon. (See the screenshot)
It happens randomly, I'm not able to reproduce it again.

![Screenshot](https://preview.ibb.co/kHC25v/Screenshot_from_2017_05_19_11_49_32.png)

**Comment by bjorn** [comment]
Did you maybe have a shifted layer? Maybe an accidental use of the Offset Layer tool?

**Comment by ketanhwr** [comment]
It was, in my opinion, just a graphic issue. I was trying the offset layer tool at a very fast speed iirc.

**Comment by bjorn** [comment]
I just used the Offset Layer tool to shift the tile layer a little bit, and it looks exactly the same:

![-desert tmx tiled_222](https://user-images.githubusercontent.com/531764/31659494-9ff28684-b334-11e7-8b17-492f8767eebd.png)

This is not a bug, it's just the darker area used for highlighting the current layer (it would darken layers below the current layer), which will become larger as a result of the layer offset.
