### ISSUE TITLE
Feature: Fill tool to delete tiles

### ISSUE THREAD

**Issue by Brianum** [bjorn/tiled#1573]
Add a possibility to the Fill tool (for example: right click) to make the fill tool delete an area of tiles of the same time at once.

**Comment by ketanhwr** [comment]
Hi, thanks for your suggestion! This issue is already listed in #7, you can close this one :slightly_smiling_face:

**Comment by bjorn** [comment]
#7 is about context menu actions that could be added to tiles in the Tileset view.

This feature request is already covered however but the Magic Wand tool:

* Select Magic Wand (W)
* Click tile to select area you want to delete
* Press Delete to erase the tiles in the selected area

So, I'm not convinced that it would be a good idea to put right-click on such a feature. Instead, some people expect right-click to capture, the same way it does when using the Stamp Brush, and I think that's a reasonable thing to expect to work.

**Comment by Brianum** [comment]
Thank you for pointing out the proper way to do this.

**Comment by bjorn** [comment]
No problem. :-)

**Comment by jonathanpperry** [comment]
In case anyone else stumbles on this, I had a random scattering of tiles that were disconnected, etc. You can just do Cmd/Control + A to select the whole map, Delete, and voila, all your tiles are deleted.
