### ISSUE TITLE
Tileset tile properties are now wrapped in <objectGroup>

### ISSUE THREAD

**Issue by mtdowling** [bjorn/tiled#1581]
After upgrading to Tiled 1.0 (awesome update, btw!), I'm seeing that custom properties added to tileset tiles are now nested under `<objectGroup><properties></properties></objectGroup>` in the save tileset XML data rather than just placing `<properties>` directly inside of each `<tile>`.

**How the issue can reproduced:**

Load a tileset in Tiled 1.0 that was created using a pre-1.0 version of Tiled for which tiles have custom properties. Click on a tile. Notice that none of the custom properties that were applied to the tile are shown in the "Custom properties" window pane. Now add a new property to the tile and save the tileset. Now open the tileset and look at that tile. The tile now has a definition like the following:

```
<tile id="714">
  <properties>
   <property name="foo" type="bool" value="true"/>
   <property name="baz" value="Bar"/>
  </properties>
  <objectgroup draworder="index">
   <properties>
     <property name="foo" type="bool" value="true"/>
     <property name="baz" value="Bar"/>
   </properties>
  </objectgroup>
 </tile>
```

**What behavior you expected instead**

1. I would expect that properties add to tilesets created before the 1.0 release show up in the custom properties panel in the tileset editor.
2. I don't see the reason for wrapping custom properties of a tile in a tileset in the `<objectGroup>` node. I would have expected that custom properties added to tiles in a tileset just get placed in  a `<properties>` element directly inside of the `<tile>` element rather than wrapping it in an `<objectGroup>` element.

**What actually happened**

Answered above.

**Tiled version, operating system, etc. if possibly relevant.**

1.0 on a Mac.

**Comment by bjorn** [comment]
Hmm, you seem to be editing the properties of the object group rather than those of the tile. This happens when you are in "collision editor" mode. Do you have the collision editor open? In that case just close that to change the properties of the tiles themselves.

Probably this is something that should somehow be made more clear...

**Comment by mtdowling** [comment]
You're correct! Thanks for the quick response.

I didn't even know you could edit object group properties like that. Thanks for letting me know.
