### ISSUE TITLE
Glitch when trying to reset redefined proper to inherited value

### ISSUE THREAD

**Issue by noidexe** [bjorn/tiled#1583]
### How the issue can reproduced:
 - Create an object type and add at least two properties
 - Assign the type to some object
 - modify the value of one of the inherited properties

### What behavior you expected instead
 - The "remove propery (minus sign) " button should be enabled
 - Clicking on it should remove the redefined property and leave the inherited value in its place

### What actually happened
Sometimes the "remove property" button is unavailable and sometimes it is. It seems to depend on the number of properties selected or the previously selected property

Video demonstration:
[![demo](http://img.youtube.com/vi/C5PGOZek4NY/0.jpg)](https://youtu.be/C5PGOZek4NY "Demo")

Tiled 1.0.0
Windows 10 1703 64bit

**Comment by bjorn** [comment]
Similar problems [reported on the forum](http://discourse.mapeditor.org/t/custom-properties-panel-non-editable/2445/2).
