### ISSUE TITLE
json Export data invalid (very large integers)

### ISSUE THREAD

**Issue by chyde** [bjorn/tiled#1594]
My export data came out as this, with huge integers  

    "data":[ 67, 111, 3221225586, 3221225541, 3221225541, 3221225541, 3221225541, 3221225541, 3221225541, 3221225541, 3221225541, 3221225541, 1610612850, 0, 0, 0, 0]

I have excluded lots of 0's and other valid values, but this is the general problem.  I was using some multi-tile painting when creating the data, so maybe the export is referencing some internal id, and not the literal tile?

**Comment by chyde** [comment]
These tiles are ones that were rotated from their original orientation!

**Comment by bjorn** [comment]
Right, such values occur when flipping or rotating tiles due to the highest bits being used to store this information. This is [documented in the TMX Map Format page](http://doc.mapeditor.org/reference/tmx-map-format/#tile-flipping), and it also applies to the JSON format.
