### ISSUE TITLE
Tile types file still not referenced anywhere in exported map file

### ISSUE THREAD

**Issue by Rakoonic** [bjorn/tiled#1598]
The tile types file continues to be entirely unlinked to the exported map that uses it.

v1.0.0 OSX

**Comment by bjorn** [comment]
This issue duplicates #228. Though I commented at #1263 why I wasn't inclined to implement this, I may have to rethink that decision given the popular demand for having this file referenced from the map. Either that, or I need to move forward with introducing a project file.
