### ISSUE TITLE
Tiled V1.0.0 doesn't show full tilesheet

### ISSUE THREAD

**Issue by Archeia** [bjorn/tiled#1601]
Hello, here's an image that tells my issue:

![88dpmo4](https://user-images.githubusercontent.com/531764/26867364-584dfc46-4b65-11e7-8b98-be6e7738d86f.jpg)

Here's the tileset in question:

![jlbs8jj](https://user-images.githubusercontent.com/531764/26867372-5d27e434-4b65-11e7-96aa-ab1f19727071.png)

**Comment by bjorn** [comment]
It's because your bottom row is only 30px high instead of 32px high. Tiled will only cut full tiles from the tileset.

**Comment by Archeia** [comment]
Oh, dang, my math failed me there. Thanks!
