### ISSUE TITLE
Edit Terrain Information button documentation out of date.

### ISSUE THREAD

**Issue by falsewall** [bjorn/tiled#1606]
http://doc.mapeditor.org/manual/using-the-terrain-tool/#editing-with-the-terrain-tool is currently including some out of date instructions.  The article needs to be reviewed, by someone with more Tiled experience than myself.

Here is one set of instructions that need to be updated.
![terraintool](https://user-images.githubusercontent.com/7212364/26981829-534b3ab0-4d04-11e7-9b5d-a9fda6bf27c6.JPG)

The "Edit Terrain Information" Button in the screenshot no longer exists in this area.  If someone could add a chunk of instructions to bridge this gap in the documentation that would be appreciated.

**Comment by bjorn** [comment]
First click on Edit Tileset:

![2017-06-09 17_19_13-edit terrain information button documentation out of date issue 1606 bjorn](https://user-images.githubusercontent.com/531764/26982212-f6381ed6-4d37-11e7-94b9-edc74e3578ae.png)

Then you find this feature here:

![2017-06-09 17_19_41-edit terrain information button documentation out of date issue 1606 bjorn](https://user-images.githubusercontent.com/531764/26982213-f63f6efc-4d37-11e7-89b9-9855797c67b4.png)

Unfortunately I didn't get around to update the documentation before the release, but it is a high priority.
