### ISSUE TITLE
Optimization for export prompt (prompted too often)

### ISSUE THREAD

**Issue by jppresents** [bjorn/tiled#1610]
Hi,

My issue is the following, when you export your map (ctrl + e) tiled asks where to export to and the filename determines the format. 
This is fine.

But every time you export again after you have:
- ran an external Command
- reloaded the map (ctrl + r)
- restart tiled
the export prompt behaves again as if you were exporting for the first time.

It would be great if tiled could "remember" the export choice (even between sessions) by saving it to the tmx file.

It would also be great if there was an option to "always export on save". So that just saving the file executes the setup method of exporting.

Use case:
When the game you develop does not read the tmx file but the exported files (in my case json) this would make the workflow of creating and testing a level more streamlined.

**Comment by bjorn** [comment]
Yep, the same topic recently came up at issue #1584.

Actually some of those things could actually be considered bugs. Running an external command or reloading the map should not lead to Tiled forgetting the last export location and format. But indeed it would be nice if it could even be stored in the map file.

> It would also be great if there was an option to "always export on save". So that just saving the file executes the setup method of exporting.

I like this suggestion. I wish it was already doing by writing a small script, but making Tiled scriptable will be a larger project for later this year. For the next release just adding such a thing as an option makes sense.

**Comment by bjorn** [comment]
Both saving the last used export file name and format, as well as an option to automatically export on save were added now. :-)
