### ISSUE TITLE
Can no longer bulk-edit tile properties since 1.0

### ISSUE THREAD

**Issue by eevee** [bjorn/tiled#1611]
Previously, it was possible to select multiple tiles and add a property to all of them at once in the properties pane.  Since 1.0, only the last tile selected will be affected.

**Comment by bjorn** [comment]
Hmm, I can't reproduce this. Can you be more specific about the version you're using and the steps you're doing?

**Comment by eevee** [comment]
Oh wait, sorry, I see what happened.  I had the collision editor open, which changes the properties dialog to the properties of the tile's object layer, and _that_ can't be bulk-edited (but isn't what I wanted to edit anyway).  That's surprising, but I don't know if it's really a UI bug or just the natural result of changing the collision editor to a panel.

I do notice that I can't seem to _delete_ properties from a tile's object layer.  The delete and edit buttons are grayed out.

**Comment by bjorn** [comment]
> That's surprising, but I don't know if it's really a UI bug or just the natural result of changing the collision editor to a panel.

You're not the first to be surprised by this (see issue #1581). I'll probably really need to tweak the UI here in some way, since the only way to notice this is by paying attention to the first line in the Properties view (which says "Object Group" instead of "Tile" when the collision editor is open).

> I do notice that I can't seem to delete properties from a tile's object layer. The delete and edit buttons are grayed out.

Maybe running into #1583? The logic for whether these buttons are enabled has become rather complicated... I'll be sure to look into that tomorrow.

**Comment by eevee** [comment]
Also, if I create a `bool` property on multiple tiles at once, it initially appears as a string property with value `false`.  It becomes a checkbox if I reselect the tiles.

**Comment by bjorn** [comment]
> Also, if I create a bool property on multiple tiles at once, it initially appears as a string property with value false. It becomes a checkbox if I reselect the tiles.

So, this was due to the property getting set on a selected-but-not-current tile first, and then when it got set on the current tile, it wasn't changing the type of the property correctly. Anyway, will be fixed in the next snapshot / release.
