### ISSUE TITLE
tiled has stopped working

### ISSUE THREAD

**Issue by Blurr3d** [bjorn/tiled#1614]
whenever i try to open a tiled file that i have created the program displays that it has stopped working and offer to close or debug the program
![image](https://user-images.githubusercontent.com/29470568/27206591-528cdb0c-5230-11e7-9bf7-80b20baf3965.png)

**Comment by ketanhwr** [comment]
Hi, can you mention the version of Tiled, and the version of your operating system as well?

**Comment by bjorn** [comment]
Could you try if this still happens with Tiled 1.0.1?

Also, crashes on Windows are often related to OpenGL rendering. Did you enable this and could you try disabling it (if you can't reach the preferences dialog, you can disable it by passing `--disable-opengl` as a command-line argument).

**Comment by bjorn** [comment]
No response from reporter and issue remains without any information about how to reproduce it, so closing this one.
