### ISSUE TITLE
No Collision Editor Option?

### ISSUE THREAD

**Issue by EuphoticWolf** [bjorn/tiled#1619]
![capture](https://user-images.githubusercontent.com/29587545/27362930-0416fb36-55f7-11e7-964e-ecdab0bee9ef.PNG)

Please Help?

**Comment by Seanba** [comment]
These shots should help, You need to the edit the tileset now ...

![image](https://user-images.githubusercontent.com/6980630/27365195-5e3f2f68-5604-11e7-88d9-ac93136ed81d.png)

... then the Tile Collision Editor menu item will appear ...

![image](https://user-images.githubusercontent.com/6980630/27365227-88e485b0-5604-11e7-9b9d-27a2a1d00a0c.png)

**Comment by EuphoticWolf** [comment]
Thank You!

**Comment by bjorn** [comment]
Hopefully covered by the short [Tile Collision Editor](http://doc.mapeditor.org/en/latest/manual/editing-tilesets/#tile-collision-editor) section that is part of the new [Editing Tilesets](http://doc.mapeditor.org/en/latest/manual/editing-tilesets/) page.
