### ISSUE TITLE
Mac - Tiled freezes if Fill tool is selected after copy/paste

### ISSUE THREAD

**Issue by HackingCommonIssues** [bjorn/tiled#1624]
I've noticed that Tiled seems to infinitely hang if I select the fill tool after I copy/paste a set of selected tiles.

OSX Yosemite version 10.10.4
Tiled for macOS: V 1.0.1

Case: Select an area with Rectangular Select tool, Cut and then paste somewhere else in the map.  So its basically a giant stamp.  If then the next thing I do is select the fill tool (usually by hitting F Key by accident) while the selection is still active, meaning I still see a transparent version of my selection and the tileset view has a bunch of tiles selected, Tiled will freeze up and I have to force quit to get out.  Attaching a screen of what it looks like when frozen.

![screen shot 2017-06-25 at 4 18 47 pm](https://user-images.githubusercontent.com/8573482/27519450-16d67282-59c2-11e7-9f64-eae00e3885e7.png)

**Comment by bjorn** [comment]
Thanks for the detailed steps to reproduce! I've fixed it for the upcoming Tiled 1.0.2 release now.
