### ISSUE TITLE
Default animation duration

### ISSUE THREAD

**Issue by greeny** [bjorn/tiled#1631]
Hi, is there any way to set default animation frame duration in tile animations editor? The default 100 does not fit me and I have to do around 500 animated tiles, so I would love to have a way to set it by default to something else. I don't mind compiling my own version of tiled with different value, but I was not able to find, where it is set in code.

**Comment by bjorn** [comment]
Yes, there should definitely be a way to change the default duration.

If compiling your own Tiled isn't a problem, you can change this line in `tileanimationeditor.cpp`:
```c++
static const int DEFAULT_DURATION = 100;
```

> I have to do around 500 animated tiles

I kind of pity you even with a good default duration... the current animation editor is really not suitable for setting up a huge amount of animations, and you may be better off using a text editor. Suggestions for how to improve the UI are welcome.

**Comment by greeny** [comment]
Hi, thanks for response :) I will try to compile it with different duration as you suggested.
Many of my files have same layout of animated tiles (e.g. coords 0|0, 1|0 and 2|0 is first tile, 1|1, 2|1, 3|1 is second tile, etc.), so in theory this can help, as I will only do the first file and then export to JSON and change that JSON to match other files (which should basically be only terrain name and image file). But I am also playing with idea of generating whole JSON by custom-written tool. I will see.

So for your question about UI, not sure how this will fit in and be actually implementable, but you can do some multiselect for tiles, so you select a pattern, say first 10 rows, first column and mark them as first frame, then using the same pattern you can select another frames. This will work only in case that image files are well-structured, but that should be the case anyway.

Attaching example file i found somewhere using google search (not mine, just example), but I have similary structured file:
![image](https://user-images.githubusercontent.com/3734204/27640334-48ad1c44-5c19-11e7-8d69-2bebcc6af905.png)

So in this case you could select first two rows and mark them as first frame, then 3rd and 4th rows and mark as second frame, and 5th+6th rows as third frame.

That could improve it a bit and also fasten the process of animating tiles. But this may be only my usage case and others might have other ideas for UI improvement.

**Comment by bjorn** [comment]
I'll close this since a *Frame Duration* entry was added in the meantime that allows changing the default (as well as applying another value to multiple frames at once).

However, there's still a need for improvement here when there are multiple tiles involved in an animation, so I'll refer to issue #811 to keep the visibility on your suggestion for potential future changes. Thanks!
