### ISSUE TITLE
minor selection display bug

### ISSUE THREAD

**Issue by jppresents** [bjorn/tiled#1644]
When setting an object layer to be not visible, the last selection stays behind until you click somewhere on the map.

Expected: When the objects are no longer displayed the selection rect should also no longer be visible.

Tiled Windows 64Bit, Version 1.0.2, run under Windows 10

Demonstration:
![Demonstration Gif](http://jppresents.net/static/files/images/tiled-selection.gif)

**Comment by bjorn** [comment]
This is intensional. Explicit or implicit visibility of the object does not affect the selection rectangle, because also invisible objects will be affected by any editing operations or property changes so it is important to be aware of them.

Note that it is also possible to select invisible objects, via the Objects dock.

**Comment by bjorn** [comment]
What is a minor display bug though, is that the tile grid is rendering on top of the labels and the selection rectangle... that is something I'd like to address sometime.

**Comment by jppresents** [comment]
I see your point - I thought making a layer invisible should deselect all objects on this layer. 
(And making them no longer affected by editing.)

**Comment by bjorn** [comment]
> I see your point - I thought making a layer invisible should deselect all objects on this layer.
> (And making them no longer affected by editing.)

I think it is not a good idea. The user may toggle visibility just temporarily and may not expect it to affect the selection. Also, I guess then invisible objects should also not be selectable from the Object view, which I think is not helpful.

In the development snapshots, layer locking has been added. But similarly, locking an object layer only prevents new interactions with the objects. Objects that are already selected can still be changed, as can objects that are selected through the Objects view.

The idea behind it is really that visibility and locking are mainly useful to control interaction on the map view, and it would just be annoying if you really couldn't change the invisible or locked objects anymore without toggling the visibility or locked state of their layer, even through the Objects view.
