### ISSUE TITLE
rotation map chip Exporting to GM:S1.4

### ISSUE THREAD

**Issue by pomderi** [bjorn/tiled#1653]
GreatApp! Exporting to GameMakerStudio 1.4 does not reflect the rotation of the map chip and it becomes a mirror image.

Sorry if it was a known problem. thank you!!

**Comment by bjorn** [comment]
There is no way to represent tile rotation in a GameMaker: Studio 1.4 room, at least not that I know of. As such the tile rotation feature can't be supported for this export format.

GameMaker: Studio 1.4 _can_ rotate instances, and rotated instances are supported by the export plugin. For this you need to use a tile object and the tile needs to be given a type matching one of your objects in GameMaker.

**Comment by pomderi** [comment]
@bjorn  Thank you. I understood what I should do on GameMaker:Studio1.4. Thanks!!
