### ISSUE TITLE
1.0.2 on Win10 - Entry Point Not Found

### ISSUE THREAD

**Issue by cacciatc** [bjorn/tiled#1654]
Updating to 1.0.2 on Win10 from Tiled Edit->Preferences->Updates interface and I get the following error when running Tiled:

<img width="343" alt="error" src="https://user-images.githubusercontent.com/149836/28249101-76e6c3e6-6a04-11e7-9ebb-cd545e4e80ca.png">

**Comment by bjorn** [comment]
You'll need to uninstall all versions of Tiled and re-install the latest version. See the following forum topic for a more complete answer:

http://discourse.mapeditor.org/t/having-problems-running-the-program-itself-after-update/2462?source_topic_id=2468
