### ISSUE TITLE
How to get start?

### ISSUE THREAD

**Issue by Mactarvish** [bjorn/tiled#1661]
I downloaded the source code and compiled it in my Qt Creator. When I ran the program, following the dialogue box shown:
![image](https://user-images.githubusercontent.com/13399458/28515116-fdd8a00a-708e-11e7-95c4-645a6d9dfec4.png)

Then I found a example map file and added it, then what should I do? The right botton seems does not work at all...

**Comment by bjorn** [comment]
That is not Tiled, it's the Automapping Rules Converter, which is one of the other tools that are part of the Tiled project.

To run Tiled, click the computer in the sidebar with "Debug" below it and choose "tiled" as the executable to run. Unfortunately, I'm not aware of a way to tell Qt Creator that this is the most useful executable to run by default.

**Comment by Mactarvish** [comment]
Thanks, I got it.
