### ISSUE TITLE
Shortcut to toggle random mode

### ISSUE THREAD

**Issue by ftsf** [bjorn/tiled#1677]
There doesn't appear to be a shortcut to toggle or set the random mode which would be quite useful since it otherwise requires moving the mouse to the toolbar away from where you are working.

**Comment by ketanhwr** [comment]
@ftsf, 'D' is supposed to be the shortcut for random mode.

**Comment by ftsf** [comment]
Excellent, that works!
It's just missing from the documentation here http://doc.mapeditor.org/manual/keyboard-shortcuts/ and the tooltip.

The "edit on github" link from the docs is also broken.

**Comment by bjorn** [comment]
> The "edit on github" link from the docs is also broken.

Yeah, this is because the documentation is in the process of being moved to a new format and hosting platform. In the new format the links will work again (see http://tiled.readthedocs.io/en/latest/manual/keyboard-shortcuts/).
