### ISSUE TITLE
Rearrange order of object types

### ISSUE THREAD

**Issue by Arcanorum** [bjorn/tiled#1679]
It would be cool if we could rearrange the order of the list of object types.

![rearrange-object-types](https://user-images.githubusercontent.com/9785268/29008256-ccb8845e-7b0b-11e7-9630-61b4e6e0664b.PNG)

**Comment by bjorn** [comment]
Maybe it makes more sense to show them in alphabetical order?

**Comment by Arcanorum** [comment]
Situational/subjective. Perhaps being able to press on the "Type" column heading to arrange things alphabetically, or press again to switch between reverse-alphabetically, but still able to manually rearrange them if needed, otherwise someone might want to have types "grouped" next to each other in the list in a certain way that wouldn't follow alphabetical ordering.

I suppose if you did go with alphabetical ordering, we could just prefix each type with a character to adjust the order, if a bit cumbersome.

**Comment by bjorn** [comment]
Usually it's a little strange to combine manual sorting with automated sorting. Since the order of the object types is not actually relevant and this dialog is generally not used very often, I'd say we just sort the list by name.
