### ISSUE TITLE
Add an icon in the Tileset Editor for the Animation Editor like the Collision Editor has

### ISSUE THREAD

**Issue by anchpop** [bjorn/tiled#1686]
It's kind of hard to find as-is I think. Please excuse my shitty ms paint mockup!

![image](https://user-images.githubusercontent.com/3711047/29258461-c9d164b4-8087-11e7-9f12-fa2e61879e5f.png)

**Comment by ketanhwr** [comment]
Hmm, seems like a nice improvement. @bjorn should I add this?

**Comment by bjorn** [comment]
@ketanhwr Alright, but please make sure to finish your existing projects first.
