### ISSUE TITLE
Crash on macOS when undoing collider and redrawing

### ISSUE THREAD

**Issue by JJSignals** [bjorn/tiled#1695]
macOS Sierra 10.12.6 - Tiled 1.0.2

When drawing a collider on a tile, then hitting CMD+Z to undo, the program will crash as soon as I let go of the mouse after drawing a new collider.

I've been able to reproduce this every time, so far. Deleting colliders and redrawing, however, works perfectly fine.

**Comment by bjorn** [comment]
I'm not able to reproduce the crash upon mouse release, but I did find an issue with handling the undo when one of the collision objects is selected. I'll include that fix in Tiled 1.0.3, please reopen this issue if it's still not fixed. Thanks!
