### ISSUE TITLE
where is collison editor on 1.0.2?

### ISSUE THREAD

**Issue by SeminYun** [bjorn/tiled#1700]
hi i update to new version 1.0.2

and i can't find collision editor ..?

where is it?

**Comment by ketanhwr** [comment]
In the TIleset editor, you can find it in Tileset menu -> Tile Collision Editor

**Comment by bjorn** [comment]
So, you now first have to open the tileset editor, using the small button below the tileset view. Opening tilesets in a separate editor was done to improve the support for external tilesets, which can now also be opened independently of map files.
