### ISSUE TITLE
Please consider adding an AppStream metainfo file

### ISSUE THREAD

**Issue by probonopd** [bjorn/tiled#1709]
Please consider adding an AppStream metainfo file, https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

This would allow app centers and directories like https://appimage.github.io/Tiled/ to present the application with more relevant metadata, screenshots etc.

Please close this ticket _once_ a new release including an AppStream file is available for download, then I can include it in https://appimage.github.io.

Reference:
https://github.com/AppImage/appimage.github.io/issues/63

**Comment by bjorn** [comment]
We already have one at https://github.com/bjorn/tiled/blob/master/tiled.appdata.xml, see also issue #596.

Does something need to change for it to be picked up by the AppImage directory?

**Comment by probonopd** [comment]
Sorry for the oversight. According to https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html, it should be in `usr/share/metainfo/%{id}.metainfo.xml`. So probably renaming `tiled.appdata.xml` to `tiled.metainfo.xml` should do the trick. The AppStream spec was changed some time ago.

**Comment by probonopd** [comment]
Edited above

**Comment by probonopd** [comment]
Are you sure it is actually shipped? I can't seem to find it in `Tiled-2017.08.28-x86_64.AppImage`:
me@host:~$ find /tmp/.mount_Tiled-P4DYQ9/ | grep xml
/tmp/.mount_Tiled-P4DYQ9/usr/share/mime/packages/tiled.xml

**Comment by bjorn** [comment]
I guess it's actually only included in the Fedora package using a manual packaging step. I'll look into shipping it in the AppImage.

**Comment by bjorn** [comment]
@Ablu Please be aware that the `tiled.appdata.xml` file is now installed by qmake / qbs, so you may have to adjust the Fedora packaging a little.
