### ISSUE TITLE
Plugin for tbin files not included in 1.0.3 installer

### ISSUE THREAD

**Issue by Entoarox** [bjorn/tiled#1711]
I am a modder for Stardew Valley, and just got reports that Tiled still does not support tbin files, after looking into it, it seems that the tbin plugin is not being included in (at least) the Windows and OSX releases.

After checking the previous issue about tbin files: Here is your reminder to include the plugin :laughing:

**Comment by bjorn** [comment]
1.0.x releases are bugfix releases that do not add new features. The plugin is part of the development snapshots and will be included in the Tiled 1.1 release.

Please do not hesitate to install a development snapshot to use the plugin. It could use some testing and I'd love to get feedback before making the 1.1 release.
