### ISSUE TITLE
Commands sub-menu is not being immediately updated after language change

### ISSUE THREAD

**Issue by 0blu** [bjorn/tiled#1714]
After changing language the sub-menu "Commands" is not being updated correctly.

![IMG](https://user-images.githubusercontent.com/7039020/29844420-7c9d8f30-8d0f-11e7-8d1f-e5726ad77fd7.png)

**Comment by bjorn** [comment]
This may be either because the text isn't reset when the language changes, or because this string isn't translated yet. Does it update after restart?

**Comment by 0blu** [comment]
Yes, it's displayed right after a quick restart.

I am using Version 1.0.3

**Comment by 0blu** [comment]
The WinSparkle Popup is also not in the editor's language... but this might be a QT Problem.
![1utxscg](https://user-images.githubusercontent.com/7039020/29845422-0a93324c-8d13-11e7-9904-fbab1698f03f.png)

Just remove this entry to reproduce:
``HKEY_CURRENT_USER\Software\mapeditor.org\Tiled\WinSparkle``

**Comment by ketanhwr** [comment]
Okay, I missed this one. I'll fix it.

**Comment by bjorn** [comment]
> The WinSparkle Popup is also not in the editor's language... but this might be a QT Problem.

Actually the WinSparkle popup isn't done with Qt and I didn't do anything to set its language, so it's probably picking that up from your system. Maybe there is a way to tell it to use the language selected in Tiled. On the other hand, I'm not really fond of this updating method and am considering to replace it by a simple new version check.
