### ISSUE TITLE
Improve XML serialization of tile gid

### ISSUE THREAD

**Issue by gurkenlabs** [bjorn/tiled#1716]
The XML output format of tiles within a tile layer currently always contains the `gid` of a tile, even when its value is "0".
By removing the empty `gid` values, the size of the XML output file can be drastically improved, especially if multiple tile layers are present. 

We've tested this manually and it seems to have no influence on the functionality and the maps can still be loaded and edited properly.

Although there are more performant approaches to store tile layers (like CSV), it would still be reasonable to improve the filesize for the XML approach.

**current XML:**

    <layer name="ground_detail2" width="20" height="20">
     <data>
      <tile gid="0"/>
      ...

**desired XML:**

    <layer name="ground_detail2" width="20" height="20">
     <data>
      <tile/>
      ...

**Comment by bjorn** [comment]
> Although there are more performant approaches to store tile layers (like CSV), it would still be reasonable to improve the filesize for the XML approach.

Right, I'll agree to make this change, but I'd like to point out that the XML mode for tile layer data is actually _deprecated_, which is why it can't be selected in the New Map dialog since a long time now. Do you have a reason to use it over the other options?

**Comment by gurkenlabs** [comment]
> Do you have a reason to use it over the other options?

Actually there is **no particular reason** besides that we originally implemented the tile layer deserialization in our framework that way. But since this approach is now _deprecated_ (which is reasonable), I think we'll also adjust the serialization process.

Just a sidenote:
Since we use a JAXB object mashalling/unmarshalling process in our java framework to handle map serialization, it is hard to support both, the xml element and string approach in parallel (at least not in a performant way).
Thank you for pointing out that the XML approach is _deprecated_. This helps a lot in the decision making concerning this topic.
