### ISSUE TITLE
[BUG] Missing alpha part of color (#argb format) of Text object

### ISSUE THREAD

**Issue by ldurniat** [bjorn/tiled#1717]
Hi,

I just started new map for [Corona SDK](https://coronalabs.com). Map was loaded using [ponytiled ](https://github.com/ponywolf/ponytiled) module. I noticed that alpha part of `color` property for _Text_ object is missing. I get  `color="#55ff7f"` (rgb format) instead of `"#ff55ff7f"` (argb format). Custom color property work fine for the same _Text_ object: `color2="#ffff557f"` (argb format). 
I use 1.0.3 version for Win 7 64bit.

My map saved in json format:

```
{ "height":40,
 "layers":[
        {
         "draworder":"topdown",
         "name":"Warstwa Obiektu 1",
         "objects":[
                {
                 "height":38.5,
                 "id":1,
                 "name":"",
                 "properties":
                    {
                     "color2":"#ffff557f"
                    },
                 "propertytypes":
                    {
                     "color2":"color"
                    },
                 "rotation":0,
                 "text":
                    {
                     "color":"#55ff7f",
                     "text":"Hello World",
                     "wrap":true
                    },
                 "type":"",
                 "visible":true,
                 "width":126.5,
                 "x":209,
                 "y":214.5
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "x":0,
         "y":0
        }],
 "nextobjectid":2,
 "orientation":"orthogonal",
 "renderorder":"right-down",
 "tiledversion":"1.0.3",
 "tileheight":22,
 "tilesets":[],
 "tilewidth":22,
 "type":"map",
 "version":1,
 "width":25
} 
```

**Comment by bjorn** [comment]
The [documentation](http://doc.mapeditor.org/en/latest/reference/tmx-map-format/#text) (granted, this is the TMX format, but the JSON format follows largely the same structure) states:

> color: Color of the text in `#AARRGGBB` or `#RRGGBB` format (default: #000000)

It depends on whether you're actually using the alpha value. Maybe this wasn't the best choice, and indeed for the custom properties it's currently always writing the alpha part. But in any case it's not a bug.

On a side note, in the meantime CSS4 is scheduled to add [8 digit hex notation](https://drafts.csswg.org/css-color/#hex-notation), but they put the alpha on the other side. :-/

**Comment by ldurniat** [comment]
In general maybe adding always the alpha part would be good way to go with color property.
Thanks for your answer :) 
Have a nice day.

**Comment by bjorn** [comment]
Yeah, it's just that the same applies to map and tileset background colors and the object group color, and starting to always write the alpha part could trip off a bunch of code that was written before Tiled started to (optionally) write the alpha part (it does that since Tiled 0.15).
