### ISSUE TITLE
Allow replacing existing objects with template instances

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1722]
There should be a way to turn an already placed object into a template instance. Essentially the reverse of the "Detach" action that turns a template instance into a regular object.

Of course, the question is which template to use. I think there are two options:

* Add "Replace with Template" context menu action that uses the template selected in the Templates view.
* Add a menu similar to the one shown at issue #818, which allows selecting the template in the menu.

I'm somewhat leaning towards the first option.

**Comment by bjorn** [comment]
@thabetx Is this something you may still get around to?

**Comment by thabetx** [comment]
This looks like a good idea. I prefer the first option, mostly because it will have the same workflow as replacing the tile of an object. I will look into it.

**Comment by bjorn** [comment]
Implemented in 6404b3ddd921684e3182cfb98867970ff5cfb6ff.
