### ISSUE TITLE
Map view boundaries don't update correctly for infinite maps

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1727]
Currently for infinite maps, the map view boundaries are not being updated as the map grows. This causes the scroll bars to be essentially useless and it causes the map origin to be centered whenever you change the zoom level.

This is a known issue, which wasn't addressed yet because actually updating the boundaries was causing the view to shift while editing, which is also not what we want. We need to find some way of either updating the scene rect without the view shifting around, or changing the way the panning works to be independent of the scene rect (I'd probably prefer the latter option, but it may be too complicated and cause other issues).

Related to this are also the issues with the Mini-map view (broken interaction and non-matching view rect).

**Comment by bjorn** [comment]
Another thing related to this, is that for infinite maps the "highlight current layer" feature fails to darken layers below the current layer, because the item that's supposed to do this gets an empty size.

**Comment by ketanhwr** [comment]
Woah, nice! :slightly_smiling_face:
