### ISSUE TITLE
Allow fixing wrong paths to tilesets in templates

### ISSUE THREAD

**Issue by thabetx** [bjorn/tiled#1732]
Currently Tiled can fix a wrong path of a template referenced by a map. But doesn't offer fixing tileset references inside of template files.

Since template files aren't opened as top-level documents and any changes to them are saved immediately, they will need some special handling.

**Comment by bjorn** [comment]
I've updated the title and description of this task to account for change ce60ac9100ef33931c54a8a648e2936ddd8fefc7, which removed the template groups.

**Comment by thabetx** [comment]
The scenario for this is opening a map which has an instance of a template that has a broken link to a tileset. The main thing here is that there is no thing wrong with the MapDocument itself, and the map doesn't own the template and has no means of changing it.

This is exactly like fixing the image of the tileset, we open the tileset and fix it there.

So, what about offering to fix the template by loading it in the template viewer, there would be an option there to fix the tileset, I'm currently thinking of a context menu entry called "Replace Broken Tileset", and we should also be able to right click and replace the tile like #1525 (Replace object tile) .

I'm not sure if this is the best solution, and I'm open for suggestions.

**Comment by bjorn** [comment]
@thabetx I like your suggestion, but I think it would need to be rather visible rather than hidden in a context menu, so for example a bar saying "Tileset not found" with a "Locate Tileset" button at the top of the template view.

Hmm, do we handle already images failing to load in a tileset referenced by a template? I think not...

In general I'm wondering if there isn't an easier way of dealing with broken references...

**Comment by thabetx** [comment]
I'm thinking of adding a "Fix Tileset" button beside the tools in the templates dock, it only appears when there is a problem with the tileset, and it should work like the fix button in the broken links widget (promoting to change the path if it's the problem or open the tileset if the image is the problem).

**Comment by bjorn** [comment]
@thabetx Yeah, that could work fine.

**Comment by bjorn** [comment]
Closed by #1831.
