### ISSUE TITLE
Chunked tile layer data for JSON and Lua formats

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1733]
The TMX format now supports saving tile layer data in chunks, which avoids using a lot of space to store large empty areas. This new storage mode is currently always used for the now supported "infinite maps".

However, chunked tile layer storage was not implemented yet for the JSON format, and neither for the Lua export. Both formats could probably use a similar mechanism to reduce the amount of data stored for tile layers with large empty areas.

**Comment by Seanba** [comment]
Is this chunked format in a currently released version of Tiled?

**Comment by bjorn** [comment]
@Seanba It will be in Tiled 1.1, but right now it is already part of the development snapshots. Currently, this format is only used for maps marked as Infinite (it's a checkbox in the New Map dialog). The chunk element is [documented here](http://doc.mapeditor.org/en/latest/reference/tmx-map-format/#chunk).

It remains possible to just allocate a tile layer as an array and write the data from the chunks into it, but Tiled internally avoids allocating tile layers as such now (regardless of whether the map is infinite).

**Comment by Seanba** [comment]
Bjorn, are chunks always 16x16 in size? Or is there some algorithm that determines their size? (Just curious, I'm not making any hard-and-fast assumptions with Tiled2Unity support of this.)

**Comment by bjorn** [comment]
@Seanba Currently they are always 16x16 in size, but this may change in the future. I think internally in Tiled I see little reason to ever change it, but in the file format it could make sense to merge adjacent chunks into a single chunk. Or to allow smaller chunks, to reduce the amount of empty tiles written out further.

So ideally, Tiled2Unity should be ready to handle also map files with chunks of different size. While loading, Tiled will handle chunks of any size even though internally it will currently always map onto 16x16 chunks.
