### ISSUE TITLE
Segmentation fault (core dumped) when overwriting new map

### ISSUE THREAD

**Issue by Ev1lbl0w** [bjorn/tiled#1734]
I get consistent exceptions of "Segmentation fault (core dumped)" (memory leak) by simply creating a new map, saving it, and creating a new map with the exact same name, which ask me to overwrite it.

Steps to reproduce:
 - Create a New Map (any definitions) and save it.
- Create another New Map, and save it to the same location and with the same name as the one before. (It asks to overwrite the old map)
- After a second or two, it crashes.

I tested this on both the release (*Tiled-1.0.3-x86_64*) and snapshot (*Tiled-2017.08.29-x86_64*)

My operating system is Ubuntu 16.04 LTS 64-bits

**Comment by bjorn** [comment]
Why would you do such a thing? :-/

But yeah, it's easily reproducible and should be fixed. I'll look into fixing it soon, but I may not get around to it until next week. Thanks for the report!

**Comment by bjorn** [comment]
So, the easiest way to reproduce this was actually:

* Create a New Map
* Press Ctrl+R (Reload)

See explanation in the commit message. :-)
