### ISSUE TITLE
Cut/Copy is pasting black tiles

### ISSUE THREAD

**Issue by RaulND** [bjorn/tiled#1736]
For some reason this is happening now (after days of working on this map).. Am I doing something wrong here? Is this a known bug?

[GIF HERE](http://i.imgur.com/vMD3aWF.gifv)

Thanks.

**Comment by bjorn** [comment]
It's not a known bug. This could happen when for some reason it can't load the tilesets referenced by the map that it has written to the clipboard (a small map is created from the copied region and saved to the clipboard, using absolute paths to refer to external files).

Don't you know anything about when this started happening? Did you upgrade Tiled or did you change something about your tilesets or their location? In any case knowing a little more about your setup could help in reproducing this issue.

**Comment by RaulND** [comment]
Hi @bjorn , I haven't done anything beyond creating the project, working on it for few hours/days, close it, open it again and so on...

All my tile sets are embedded on the map, and I also upgraded Tiled when I had another issue (when importing to Unity, Tiles were all mixed) which I ended up solving by deleting/re-importing the tile2Unity asset.

I could send you my Tiled folder (including project) if you feel like It could help you find out more about the issue. Just let me know how can I do so privately.

**Comment by Jazcash** [comment]
Exact same issue here on the 2017-09-08 build, Windows x64 snapshot

**Comment by DDRKirbyISQ** [comment]
I'm also seeing this issue, both in the latest snapshot (2017.09.08) as well as 1.0.3.
@bjorn , this appears to be an path-resolution (?) issue, probably more common to embedded tilesets.

In a tmx file, a normal standalone tileset is saved like this:
```
 <tileset firstgid="1" source="mytileset.tsx"/>
```

If you instead create a new embedded tileset, the image source gets saved using a relative path:
```
<tileset firstgid="82" name="myembeddedtileset" tilewidth="25" tileheight="25" tilecount="81" columns="9">
  <image source="../../Sprites/Levels/world0_tileset.png" width="240" height="240"/>
 </tileset>
```

Copying and pasting tiles from this embedded tileset causes a NEW tileset to erroneously be created -- the new tileset has the same name but has 0 tiles, and uses an absolute path for the image source:
```
<tileset firstgid="82" name="myembeddedtileset" tilewidth="25" tileheight="25" tilecount="81" columns="9">
  <image source="../../Sprites/Levels/world0_tileset.png" width="240" height="240"/>
 </tileset>
<tileset firstgid="163" name="myembeddedtileset" tilewidth="25" tileheight="25" tilecount="0" columns="9">
  <image source="c:/Users/DDRKirbyISQ/Coding/rhythm-quest/Assets/Sprites/Levels/world0_tileset.png" width="240" height="240"/>
 </tileset>
```
 
In the editor a new (empty) tab is created for the erroneous tileset.  The newly copied tiles have gids based on the erroneous tileset and appear blank as a result.

It's worth noting that the same issue affects copy/paste for object layers as well, when using a "collection of images" tileset.

**Comment by RaulND** [comment]
Luckily I had a backup before upgrading to  2017.09.08 on 2017.07.11 and everything seems to work perfect now

**Comment by bjorn** [comment]
Couldn't reproduce this on Linux, but I can on Windows.
