### ISSUE TITLE
problem on tile map when i export to unity

### ISSUE THREAD

**Issue by moumnimohamed** [bjorn/tiled#1738]
i release my map is so well on the tiled, but when I export it to there is this problem I can't fix it 
![issue](https://user-images.githubusercontent.com/21304554/30372120-bd60fe56-9874-11e7-9262-61d2914bccdc.PNG)

**Comment by bjorn** [comment]
@Seanba This seems to be the most common problem people encounter with Tiled2Unity. :-/

**Comment by moumnimohamed** [comment]
what I should do now ?

**Comment by bjorn** [comment]
@moumnimohamed Sorry, I think @Seanba can best answer this question, but in the meantime you could check for any documentation on http://www.seanba.com/Tiled2Unity about this

**Comment by Seanba** [comment]
Are there any warnings or errors in your Unity Console window when you export a map into your Unity project? Chances are you have anti-aliasing enabled in your quality settings. This is the #1 cause of seams.

(BTW, from your screen shot I can just barely see a warning along the bottom in your Unity status bar.)

**Comment by Seanba** [comment]
@bjorn: Yeah, Unity is great but it has some deficiencies when it comes to pixel-perfect 2D games. It's usually nothing a bit of management in your project settings can't fix though. (Well, except for maybe physics, which is another discussion.)

**Comment by bjorn** [comment]
Closing this issue since it's getting stale and only indirectly related to Tiled. But feel free to make additional comments.
