### ISSUE TITLE
How to export js with the information of `.tsx` file ?

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#1748]
I create html5 file , so I want to use  js format of Tiled .
But I found when I export js , it's without the information of `.tsx` file .

How to do that ?

----

I know I can embed tsx into tmx , but I don't want to embed tsx, I just want to embed tsx when export tmx to js

**Comment by adrianlopezroche** [comment]
I've been looking for a way to do this, also. I want to keep separate tsx files so I can reuse them in different levels yet still have each tileset's properties included in the exported .json file.

I didn't know you could take a tsx file and embed it (by clicking on the "embed tileset" button under the Tilesets tab), but that's an extra step I would like to avoid.

**Comment by bjorn** [comment]
Tiled should probably have an export option "Embed tilesets on export". It was actually requested before at issue #1091. I'll close as a duplicate and will make sure to add this option to Tiled 1.1.
