### ISSUE TITLE
Configurable size of GIDs

### ISSUE THREAD

**Issue by stefanbeller** [bjorn/tiled#175]
(Moving https://sourceforge.net/apps/mantisbt/tiled/view.php?id=63 to the new issue tracker)

GIDs as of now are 4 byte integer numbers, which is in most cases a lot of overhead, because only a few 100 to 1000 different tiles are used.

So the upper bytes are always zero for storing tile ids. (Note that flipped bits are in the still in the highest bits of the highest byte).
To reduce memory consumption it should be configurable how many bytes are used in a data stream such as in a compressed tilelayer to store one GID.
Having only the required amount of bytes per tile would decrease memory consumption of maps, which would be interesting on mobile devices which are in general short on memory.

On the other hand a custom parser to load the map for the game on the mobile device could ignore the leading bytes and only extract those bytes which are interesting per GID.

**Comment by bjorn** [comment]
Closing this since if optimizations of this kind are necessary, it's really better to implement a custom export format, which can now be done in a JavaScript extension, or of course any external conversion tool.
