### ISSUE TITLE
Add support for horizontally and vertically flipped tiles in tiledquickplugin

### ISSUE THREAD

**Issue by mitchcurtis** [bjorn/tiled#1751]

**Comment by mitchcurtis** [comment]
I'm assuming the rotation would have to be done on the texture vertices manually?

https://github.com/bjorn/tiled/blob/wip/qtquick/src/tiledquickplugin/tilesnode.cpp#L73

I'd be willing to give it a try if you have any pointers for the math, which I suck at.

**Comment by bjorn** [comment]
Fixed by #1942 (issue not closing automatically since it's not on the `master` branch).
