### ISSUE TITLE
TMX documentation not clear on number of 'can contain' types

### ISSUE THREAD

**Issue by dyson** [bjorn/tiled#1754]
I'm working on parsing TMX files and I can't figure out from the documentation if 'can contain' objects can be included multiple times or only once. For example under `<imageLayer>` it expressly mentions "A layer consisting of a single image" so I know there can only be one child image. Other objects are not so clear.

Prefixing or appending something to each 'can contain' object that can be included multiple times would make this much clearer.

Fox example an asterisk to mark 1 or many objects of the same type are accepted:
```
Can contain: <properties>, <layer>*, <objectgroup>*, <imagelayer>*, <group>*
```
It is also not clear at all which attributes/'can contain' objects are required as mentioned in #696 .

**Comment by bjorn** [comment]
I'm working a lot on the documentation lately, so while I'm at it I might as well make sure this information is included. Thanks for bringing it up!

**Comment by dyson** [comment]
Thanks heaps bjorn!

I tried to piece the info together from the JSON docs and from the DTD file which does include this information but they were incomplete and I wasn't sure if it was just me reading the docs wrong!

Cheers!
