### ISSUE TITLE
JavaScript Integration

### ISSUE THREAD

**Issue by DaSniper12** [bjorn/tiled#1755]
Hello, Thorbjørn,

I really want to use a tiled map in a Html and JavaScirpt game that I want to make, but I have been having a hard time displaying the tiles on canvas like I have been able to get the map object in the js file, but I don't know how you display the tiles themselves. Could you possibly add a section in your documentation that explains how you do it?

Regards,
DaSniper

**Comment by bjorn** [comment]
There are many frameworks that you can use to display Tiled maps in the browser, which you can find on the following page:

http://doc.mapeditor.org/en/latest/reference/support-for-tmx-maps/#html5-multiple-engines

Regarding adding a section to the documentation, each of the above frameworks will do it a little differently so it's better to look at their examples and documentation.
