### ISSUE TITLE
Compile errors on windows 7 when building tiled.qbs in QtCreator

### ISSUE THREAD

**Issue by keshav2010** [bjorn/tiled#1763]
After opening the tled.qbs file, just when i clicked on build, after few seconds the progress bar turns red and 37 errors are poped, ( filtered out warnings, only compile errors are being shown here)

```
E:\Qt\5.9.1\mingw53_32\include\QtCore\qcompilerdetection.h:567: error: #error Qt requires a C++11 compiler and yours does not seem to be that.

E:\Qt\5.9.1\mingw53_32\include\QtCore\qbasicatomic.h:61: error: #error "Qt requires C++11 support"

E:\Qt\5.9.1\mingw53_32\include\QtCore\qglobal.h:959: error: ISO C++ forbids in-class initialization of non-const static member 'control'

E:\Qt\5.9.1\mingw53_32\include\QtCore\qflags.h:109: error: 'underlying_type' in namespace 'std' does not name a type

E:\Qt\5.9.1\mingw53_32\include\QtCore\qflags.h:109: error: expected template-argument before '<' token

E:\Qt\5.9.1\mingw53_32\include\QtCore\qflags.h:109: error: expected '>' before '<' token

E:\Qt\5.9.1\mingw53_32\include\QtCore\qflags.h:109: error: template argument 1 is invalid

E:\Qt\5.9.1\mingw53_32\include\QtCore\qflags.h:109: error: expected template-argument before 'value'

E:\Qt\5.9.1\mingw53_32\include\QtCore\qflags.h:109: error: expected '>' before 'value'

E:\Qt\5.9.1\mingw53_32\include\QtCore\qflags.h:112: error: wrong number of template arguments (1, should be 3)

c:\mingw\include\c++\4.6.4\type_traits:849: error: provided for 'template<bool _Cond, class _Iftrue, class _Iffalse> struct std::conditional'

E:\Qt\5.9.1\mingw53_32\include\QtCore\qbasicatomic.h:93: error: 'QAtomicOps' does not name a type

E:\Qt\5.9.1\mingw53_32\include\QtCore\qbasicatomic.h:96: error: 'QAtomicOpsSupport' was not declared in this scope

E:\Qt\5.9.1\mingw53_32\include\QtCore\qbasicatomic.h:96: error: '::IsSupported' has not been declared

E:\Qt\5.9.1\mingw53_32\include\QtCore\qbasicatomic.h:96: error: non-constant condition for static assertion

:-1: error: Process failed with exit code 1.

:-1: error: The following products could not be built for configuration qtc_DesktopK_016b8e1f-debug:
:-1: error: 	automappingconverter
:-1: error: 	libtiled
:-1: error: 	qtpropertybrowser
:-1: error: 	qtsingleapplication
:-1: error: 	terraingenerator
:-1: error: 	tiled
:-1: error: 	tmxrasterizer
:-1: error: 	tmxviewer
:-1: error: 	translations
:-1: error: 	csv
:-1: error: 	defold
:-1: error: 	droidcraft
:-1: error: 	flare
:-1: error: 	json
:-1: error: 	lua
:-1: error: 	replicaisland
:-1: error: 	tbin
:-1: error: 	tengine
:-1: error: 	tmw
:-1: error: 	gmx
```

i did several google searches that suggested me to include` CONFIG   += c++11` in .pro file, but that doesn't work either.

About Qt version im using 
Qt Creator 4.3.1
Based on Qt 5.9.1 (MSVC 2015 32 bit)
Built on Jun 29 2017 4:14:35
From revision e974f0733e

**Comment by bjorn** [comment]
I will have to try reproducing your scenario, but if you have MSVC 2013 available then the easiest fix should be to use that instead.

**Comment by keshav2010** [comment]
I don't have MSVC 2013 but 2015?

**Comment by bjorn** [comment]
> I don't have MSVC 2013 but 2015?

Yes, what I meant was that _if_ you had MSVC 2013 (as well), then you could compile Tiled with that instead.

However, looking again at your initial post and the error messages, I noticed that you're not actually using Qt for MSVC, but you're using Qt for MinGW. That still doesn't really explain these errors, though.

**Comment by keshav2010** [comment]
I tried to alter my Default Kit, instead of MinGW compiler for both C & C++, i switched it to Microsoft Visual C++ Compiler 14.0 (x86), now errors are reduced and following errors are shown 

```
D:\GITHUB_REPOSITORY\tiled\src\libtiled\compression.cpp:32: error: C1083: Cannot open include file: 'QtZlib/zlib.h': No such file or directory

:-1: error: Process failed with exit code 2.

:-1: error: The following products could not be built for configuration qtc_Desktop__c4fafcbf-debug:
:-1: error: 	automappingconverter
:-1: error: 	libtiled
:-1: error: 	qtpropertybrowser
:-1: error: 	qtsingleapplication
:-1: error: 	terraingenerator
:-1: error: 	tiled
:-1: error: 	tmxrasterizer
:-1: error: 	tmxviewer
```

**Comment by keshav2010** [comment]
# UPDATE
The build is now successful after performing some changes in my Kit, 
in _**Tools > Options > Build&Run > Kits**_ 
for the Qt-Version field, earlier it was 

> Qt 5.9.1 MinGW 32bit

, 
I changed it to 

> None

 and it works fine now, irrespective of choice of compiler.

**Comment by bjorn** [comment]
Wow, that's very strange. Are you sure it's still building with Qt 5.9.1?

The `zlib.h` error is a known issue when compiling against Qt 5.9. I'm still using Qt 5.8 for now until I have gotten around to finding a solution for building against Qt 5.9.

**Comment by keshav2010** [comment]
I just changed the Qt-Version from _**Qt 5.9.1 MinGW 32bit**_ to _**None**_ and its working perfectly fine.
