### ISSUE TITLE
Selected object does not properly hide when layer containing it is hidden

### ISSUE THREAD

**Issue by pavle-goloskokovic** [bjorn/tiled#1765]
- How the issue can reproduced

1. Open Tiled
2. Create new Map (any settings are fine)
3. Create new object layer
4. Add few objects to that layer
5. Select any of those objects with Select Object tool
6. Hide objects layer
- What behavior you expected instead:
Arrows displayed around selected object disappear along with the objects of that layer.
- What actually happened:
Arrows displayed around selected object stay visible while selected object and others on hidden layer are properly hidden.
- Tiled version: **Tiled v1.0.2**
- Operating system: **Windows 10 Home 64bit, Version 1703, OS Build 15063.608**

![image](https://user-images.githubusercontent.com/7340300/30927394-9f562c48-a3b8-11e7-8c8b-fb96ad877c93.png)

![image](https://user-images.githubusercontent.com/7340300/30927426-bcee65a4-a3b8-11e7-9686-83b56692c377.png)

**Comment by bjorn** [comment]
That is intentional, see issue #1644 for the rationale.
