### ISSUE TITLE
Add Object Creation Code support to GMX exporter

### ISSUE THREAD

**Issue by gsnook** [bjorn/tiled#1768]
Each object instance on a GMX map can have a gml script added to it which is executed at creation time. This is a handy way to add per-instance instructions to an object in their map editor. It's useful for setting custom properties on an instance, assigning objects into groups, attaching objects to tracks, etc. In the GMX file, it appears as a 'code' parameter in the object instance data: 

`<instance` objName="obj_sawblade" x="896" y="1152" name="SawbladeA" scaleX="1" scaleY="1" rotation="0" `code="parent=DroneA"/>`

At object creation time in Game Maker, the gml shown will execute. In this case, setting variable 'parent' to the string 'DroneA'. I've updated the GMX exporter locally to take any string added in Tiled to a Custom Property named 'code' and export it as the gml creation code on the object instance:

            // Export Code properties as creation code
            if (object->hasProperty("code")) {
                stream.writeAttribute("code", object->propertyAsString("code"));
            }

This addition has helped me fully replace the Game Maker room editor with Tiled.
Hope this helps.

**Comment by bjorn** [comment]
Implemented in change 27fd639a884f5bef91fbbfab67d4dc1769bc483d, which adds support for setting the creation code on both instances and the map.

Thanks for bringing this up!
