### ISSUE TITLE
Automapping doesn't touch terrain brush made tiles

### ISSUE THREAD

**Issue by Lucrecious** [bjorn/tiled#1772]
I expected tiles made by the terrain tool to be affected by automapping, instead they are not.

I'm on Mac OS Sierra 10.12

### Repo
Create a map and associate it with a rule tmx. Make a terrain using the same tiles that automaps affects. Paint something with the terrain tool. Try to apply the automapping. **Bug** The tiles from the terrain tool are not affected by the automapping. However, if I draw over the (supposedly) affected tiles manually, then automapping works.

**Comment by Lucrecious** [comment]
This was a mistake. Closed.

**Comment by hironimusrian** [comment]
Hello,
I have same problem right now.
May i know what is the mistake or solution for this protblem?
