### ISSUE TITLE
Autotiles not merging with edge of map properly

### ISSUE THREAD

**Issue by Tom-III** [bjorn/tiled#1778]
I recently upgraded from an old version of TileD and this is the first issue I found while mapping,
![Edge tiles issue image](https://i.imgur.com/vvImBJv.png)
Green boxes show the correct behavior and red boxes the wrong/bugged behavior.
This happens when using Autotiles and looks really bad to not have them merge with the edge of the map.
In old versions of TileD this used to work.

**Comment by bjorn** [comment]
The change that was made for the upcoming Tiled 1.1 is that the "edge of the map" is no longer treated in some special way (as a result of e49342667f121636b892de7afe35b011880008fb). Instead, it behaves as if the neighboring tiles are empty (which they essentially are).

Maybe it would be possible to adjust your rule to still have the desired outcome? It seems the "edge of forest" rule didn't used to match on the edge of the map, though now it does.

If it is not possible to adjust the rules in a meaningful way, I could add back the special "outside of map" case for fixed-size maps. But I would prefer to avoid special cases when possible.

**Comment by Tom-III** [comment]
I strongly suggest adding it back for the fixed size maps

**Comment by bjorn** [comment]
> Also sorry for calling it Autotiles, I mean terrain brush. (I'm just used to the RPG maker terminology) I'm not talking about automapping here at all, just the regular manual terrain brush

Hmm, then I don't understand it. The behavior for Terrain Brush should not be affected. What version of Tiled are you using exactly? I can't reproduce this issue on `master`. Or maybe you can provide more detailed instructions of how to reproduce it.

**Comment by Tom-III** [comment]
I have the latest snapshot build, and sliding the terrain brush along the edge makes the terrain become edges again instead of seamlessly merging with the edge of the map as if it was the same terrain

**Comment by bjorn** [comment]
Alright, I managed to reproduce the issue. It only happens for transitions to empty space for some reason, so I wasn't able to reproduce any issues in the examples shipping with Tiled (desert and isometric_grass_and_water). That does appear to be a new bug.

**Comment by Tom-III** [comment]
Maybe add a thing so it does not revert the tile if its on the edge of the map?  Some way to have the old behavior

**Comment by bjorn** [comment]
I would have preferred to make a fix that keeps consistent behavior with infinite maps, but that turned out to be more complicated than I'm prepared to deal with now. So the fix puts back an intersection check that avoided this issue from occurring on fixed-size maps. Thanks for reporting this issue!
