### ISSUE TITLE
Add support for layer reordering with mouse

### ISSUE THREAD

**Issue by stefanbeller** [bjorn/tiled#178]
(Moving https://sourceforge.net/apps/mantisbt/tiled/view.php?id=12 here.)
In the layers view being able to rearrange the order of the layers with the mouse would be useful. 

@bjorn said:
(https://sourceforge.net/apps/mantisbt/tiled/file_download.php?file_id=3&type=bug)
Hmm, I've given this a short try. While enabling Drag and Drop in the GUI is very easy (see the attached patch), making it actually functional still seems quite tricky (it's based on mime types). Also, I don't think the GUI looks very appropriate, since it doesn't really indicate the act of moving, but rather points one item at another. There doesn't even seem to be a way of moving a layer to the top or bottom, depending on where it actually inserts it when dropped.

This feature is on hold for now, since I don't think it has much priority, given that you can already just move layers in multiple steps.

**Comment by bjorn** [comment]
Implemented in b6d16deacc36338d3bad9b04a7fedbc093211472 as part of finishing #1038.
