### ISSUE TITLE
Tileset extension confirmation issue

### ISSUE THREAD

**Issue by Ragath** [bjorn/tiled#1782]
When creating a new tileset and saving as an unsupported extension, answering No to the "are you sure?"-confirmation prompt doesn't take you back to the tileset creation dialog as expected, instead it ends the creation process.

**Comment by bjorn** [comment]
Ah, you're right, and this will be a bit tricky to fix because the New Tileset dialog is already closed when the file name dialog is shown. So maybe that code should be moved into the dialog.
