### ISSUE TITLE
QXcbConnection: Could not connect to display 

### ISSUE THREAD

**Issue by cacciatc** [bjorn/tiled#1788]
I recently tried to run Tiled with the --export-map flag as part of an automated build in a docker image and get the following error:
```
QXcbConnection: Could not connect to display 
```

Is it possible to run Tiled --export-map without a display? I am using the tiled package on Ubuntu.

**Comment by bjorn** [comment]
Due to its use of `QGuiApplication` and `QPixmap`, Tiled does need an X server to function. However, you could run a headless X server, like `Xvfb`. That should allow Tiled to run and enable the use of `--export-map`.

**Comment by cacciatc** [comment]
Thanks @bjorn. Installing xvfb and running Tiled ala:
```
xvfb-run tiled --export-map ...
```
did the trick. Is there a good place to document this in the Tiled docs? If so, happy to submit a PR.

**Comment by bjorn** [comment]
> Is there a good place to document this in the Tiled docs? If so, happy to submit a PR.

That's probably something worth adding to [the page about the Export Formats](http://doc.mapeditor.org/en/latest/manual/export/), as part of a section about exporting on the command-line.
