### ISSUE TITLE
Bucket Fill breaks Tiled

### ISSUE THREAD

**Issue by hediasd** [bjorn/tiled#1807]
When I do the following steps, Tiled freezes forever. I was using an orthogonal map, nothing special.
1. Select something with the Rectangular Select (R). It may be a little 2x2 region or a big 10x10, it doesnt matter.
2. Cut the area (CTRL-X)
3. Select Bucket Fill (F) and then CTRL-V (Paste) (the inverse order CTRL-V and F freezes as well)

**Comment by bjorn** [comment]
This sounds like issue #1624, which was fixed in Tiled 1.0.2. I'd recommend using the latest version (1.0.3 currently) or a recent development snapshot.

Tell me if you're already on a recent version, cause then the bug may have resurfaced.
