### ISSUE TITLE
Tiled Crashes on Offset Map -> Resize Map

### ISSUE THREAD

**Issue by anthnich** [bjorn/tiled#1812]
This has been happening with Tiled for me as far as I remember, through multiple versions. Windows 10.

To reproduce:

1. Create a new map.
2. Add an object layer.
3. Insert a Rectangle into the object layer.
4. Go to Map -> Offset Map and offset it by a bit (ex. offset y by 8).
5. Go to Map-> Resize Map
6. Resize the map (ex. resize x from 64 to 80).
7. When hitting OK, Tiled crashes.

**Comment by bjorn** [comment]
> This has been happening with Tiled for me as far as I remember, through multiple versions.

Please do mention the version as well. I just tried this with the current development snapshot and it didn't crash for me.

**Comment by anthnich** [comment]
1.0.3, happening with that version.

**Comment by bjorn** [comment]
Is this still happening for you in the new Tiled 1.1.0 release?

**Comment by anthnich** [comment]
It appears to be fixed! Thank you.

**Comment by bjorn** [comment]
Great, then I'll close this issue. Thanks for testing!
