### ISSUE TITLE
Crash when opening a JSON map or tileset in the templates view/toolbar.

### ISSUE THREAD

**Issue by WeirdConstructor** [bjorn/tiled#1823]
I am using the recent windows 64bit snapshot (Version 2017-11-22).

Steps to reproduce:

1. start tiled.exe
2. create an arbitrary map and save it as JSON
3. open a map
4. show the View->Views&Toolbars->Templates view
5. navigate in the templates view to the in step 2. saved JSON file
6. click on the JSON file

What I expected: An error message or that nothing meaningful happens.

What happened: The application crashed with the message "Tiled has stopped working".

Sorry for not further tracking down the bug in the debugger, I currently don't have a
source tree ready for building tiled. But I guess this one can be tracked down quite
easily. Probably just a missed check somewhere.

**Comment by bjorn** [comment]
Thanks for the report!
