### ISSUE TITLE
Crash when zooming out too much.

### ISSUE THREAD

**Issue by s-m-k** [bjorn/tiled#1824]
When you zoom out too much (Ctrl + mouse wheel), Tiled crashes. Happens every time.

Tiled version 1.0.3, Windows 7

**Comment by bjorn** [comment]
Did you enable OpenGL rendering? If so, does it help to disable it?

**Comment by s-m-k** [comment]
1. Yes.
2. Yes.

Also, without OpenGL rendering, the visual glitches that happen seemingly randomly from time to time are gone.

**Comment by bjorn** [comment]
I could reproduce this issue and I've pushed a fix, which will be included in the 1.1 release and of course the next development snapshot. Let me know if you're still getting this after upgrading.
