### ISSUE TITLE
New tool that supports importing TMX

### ISSUE THREAD

**Issue by DunkUK** [bjorn/tiled#1826]
Hi Bjorn, when you have time, could you update this docs page:
http://doc.mapeditor.org/en/latest/reference/support-for-tmx-maps/
to include my Tiled TMX Importer plugin for Unity:
https://www.assetstore.unity3d.com/en/#!/content/102928
It's designed to import into Unity 2017.2's new native Tilemap system.

Thanks,
Duncan Stead

**Comment by bjorn** [comment]
Add, thanks!

Does Unity's native Tiledmap system support all orientations or only orthogonal maps? In general it would be good to have some documentation about which features are supported. I couldn't find it.

**Comment by DunkUK** [comment]
Unfortunately, Unity's Tilemap system is fresh from the oven with pretty light documentation, but I implemented about as much support as is possible till now so...

- Only orthogonal maps (no isometric, staggered or hexagonal)
- Slightly broken tile sort orders (it has a 'top left', 'top right', 'bottom left', 'bottom right' enumeration on a Tilemap Renderer, but they don't seem to exactly match what Tiled pushes out whatever mapping I try)
- No per-frame animation times, only a constant Tile animation rate
- Supports per-sprite collision, but only as an outline (so I don't try and load the collision objects for Tiles, only for objects)

Those are the main missing fundamental features that I'm aware of so far.
My tool doesn't support loading infinite maps or object templates, but that's my fault 🥉 :3
