### ISSUE TITLE
Wang tiles ignore individual tile probability

### ISSUE THREAD

**Issue by Shorttail** [bjorn/tiled#1830]
With the wang brush, stamp brush, and bucket fill, individual tiles with the same pattern have their probability ignored: If probability of one is 1 and the other is 10, they will both be chosen approximately the same amount of times. 

On the other hand, the probability on the colors themselves is respected by the stamp brush.

**Comment by bjorn** [comment]
Thanks for the report! But, I fixed this on Tuesday. See change 6b81356eea9f52ce7a4feb770f9b8aeda2f4de05. :-)

Will publish a new development snapshot.

**Comment by Shorttail** [comment]
Sorry, I searched only open issues, I guess.

**Comment by bjorn** [comment]
@Shorttail There wasn't an issue opened about this before, I just noticed it while playing with the tool to check if it's ready to be included in the upcoming 1.1 release.
