### ISSUE TITLE
Export into my own data.

### ISSUE THREAD

**Issue by drdiotte** [bjorn/tiled#1837]
Sorry if this has been asked I am a noob here. I have been reading to see but have not seen anything yet.
This is the format I am looking to export the data. 
```
 picture	3000   (can be background image name)

   atpinfo   
      170  382 101    (can be image name.... "170 is image name..... 382= X position...  101 = Y position"
      169  168 101
      241  155 6
      245  410 48
      246  604 23
      229  99 240
      229  291 241
      230  538 239
      164  517 144
      164  530 1
      197  266 103
      197  489 103
```
I love the software if I can just get it to fit my needs.  I want to use is as a room / dungeon builder for a game called The Realm Online.

**Comment by bjorn** [comment]
Just recently I wrote a page about [using Python scripts for exporting to custom formats](http://doc.mapeditor.org/en/latest/manual/python/). The example is very basic, but I imagine this could be a way to enable exporting to your desired format?

The example deals only with tile layers, but it looks like you would want information from object layers. It would work roughly the same way though. I can help in case of questions, but when I have a bit more time (probably in 1-2 weeks) I could also try to write the needed script. I think it would make a nice additional example.

**Comment by drdiotte** [comment]
Thank you hit me up when you have time.. As you can imagine my plate is full also so i understand. All the help/guidance i can get will be much obliged.

**Comment by justgook** [comment]
@bjorn & @drdiotte  i think that can be closed - as now there is new [scripting](https://doc.mapeditor.org/en/latest/reference/scripting/#script-registermapformat) way - that is just few lines of JS (and that can be done by any-one) to create export..

**Comment by bjorn** [comment]
Thanks @justgook, indeed based on the support for JavaScript outputting a map in the above format should be pretty easy.

That said, it sounded like @drdiotte did not have any coding experience, but I can't provide much help with the little information provided. So closing this issue, but please feel free to comment if there's any specific questions about this.
