### ISSUE TITLE
Black Toolbar in OSX

### ISSUE THREAD

**Issue by danman113** [bjorn/tiled#1839]
Hey, I was going to post complaining about scrolling performance on OSX but I realized had Hardware Acceleration turned off. I turned that on and it fixed my performance problems, but now by toolbar is black. This wouldn't be a problem but it also blacks out the currently selected map so I can't read which one it is. This is only on the native theme, fusion works just fine.

Screenshot:
[
<img width="1612" alt="screen shot 2017-12-21 at 3 08 13 pm" src="https://user-images.githubusercontent.com/8608120/34278874-5e929d12-e662-11e7-9f76-50ea654859a2.png">
](url)

**Comment by bjorn** [comment]
> This is only on the native theme, Fusion works just fine.

Good to know, then I would suggest you just use Fusion for now. I'm considering to make it the default anyway to have a consistent experience across platforms.

Regarding the black tool bar, I know about it but it is unfortunately an issue in Qt. It was mentioned already at https://github.com/bjorn/tiled/issues/529#issuecomment-43900019. [QTBUG-39210](https://bugreports.qt.io/browse/QTBUG-39210) and [QTBUG-41257](https://bugreports.qt.io/browse/QTBUG-41257) remain unresolved so far.

**Comment by danman113** [comment]
Good to know, I'll vote. Regarding changing the default theme, I like the native-like experience by default.

Also [this workaround](https://bugreports.qt.io/browse/QTBUG-41257?focusedCommentId=278971&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-278971) might prove useful

**Comment by bjorn** [comment]
> Good to know, I'll vote. Regarding changing the default theme, I like the native-like experience by default.

I'll take your vote into consideration. :-)

> Also this workaround might prove useful.

I had tried that already, see (https://github.com/bjorn/tiled/issues/529#issuecomment-106578902).

**Comment by bjorn** [comment]
[QTBUG-39210](https://bugreports.qt.io/browse/QTBUG-39210) and [QTBUG-41257](https://bugreports.qt.io/browse/QTBUG-41257) are closed as fixed in Qt 5.12, but the latest development snapshot of Tiled (2019.05.08) was built against Qt 5.12 and it's still happening. :-(

**Comment by bjorn** [comment]
Tiled 1.3 built against Qt 5.12.5 is also [still showing this issue](https://twitter.com/hello_lightbulb/status/1197806454411079681) (tweet).

**Comment by bjorn** [comment]
Ok, actually feature is documented to not work correctly in combination with OpenGL widgets (see [`QMainWindow::setUnifiedToolBarOnMac`](https://doc.qt.io/qt-5/qmainwindow.html#unifiedTitleAndToolBarOnMac-prop)). It could be worth trying to disable this setting as soon as OpenGL mode is enabled.
