### ISSUE TITLE
Cannot erase terrains

### ISSUE THREAD

**Issue by maxp-edcast** [bjorn/tiled#1841]
The 'erase terrain' button in the tileset and tilemap editors don't do anything. Clicking delete when the terrain is highlighted also doesn't work. Using OSX 10.13 and tiled 1.0.3

**Comment by bjorn** [comment]
The "Erase Terrain" button in the Tileset Editor is for erasing terrain information, and in the map editor it's for erasing terrain by painting "nothing". For deleting/removing a terrain type, you'll need to use this button:

![terrain tsx tiled_234](https://user-images.githubusercontent.com/531764/34455990-9bc4e55c-ed8b-11e7-8c14-26ea432cf43f.png)

I'll make sure the Delete key also works, though.
