### ISSUE TITLE
Escape sequences are actually escaped in entity properties

### ISSUE THREAD

**Issue by kdrnic** [bjorn/tiled#1842]
While creating a "NPC" entity, I had its "dialog" custom property include escape sequences for a newline, i.e. include "\n". I was expecting Tiled not to escape this, so that the game code could see it as "\" followed by "n". Instead, and I looked in the .tmx XML to be sure, the sequence was escaped. The XML parsing library then read the property as empty (which I know is not exactly compliant, as newlines are allowed in XML attributes, however consider https://www.w3.org/TR/1998/REC-xml-19980210#AVNormalize that is, a recommendation that parsers should normalize all whitespace characters to space characters).
Anyway, the issue is I am not sure it is a good idea to be escaping sequences like that. The user is likely not expecting that. It may have issues with XML parsing. I also don't know if the escaping was accidental by passing the string through a ostream or a printf operation, or if it was a deliberate decision.

**Comment by bjorn** [comment]
If you type "\n" in a text property, then this is taken to mean "newline". Is that causing a problem for you? To comfortably edit multi-line properties I would suggest you click the "..." button next to the property value to open the multi-line text editor.

When saving properties, multi-line values are not saved as attributes. For readability's sake they are stored as text, like this:

```xml
 <property name="test">foo
bar
baz</property>
```

What exactly are you seeing in your .tmx file? I don't understand which escaping you're talking about.

**Comment by kdrnic** [comment]
Humm, I overlooked that bit about the saving on the documentation...

**Comment by bjorn** [comment]
Does that resolve this issue? I don't understand how overlooking that caused these escaping issues.

**Comment by kdrnic** [comment]
I am very sorry, I see it was only my issue... pardon the misshap

**Comment by bjorn** [comment]
Alright, no problem! I'll just close this issue then. Cheers!
