### ISSUE TITLE
Option to embed tilesets or templates on export

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#1850]
Apart from external images, a tiled map can currently depend on external tilesets and external template files. It can be useful to embed such dependencies in the map file, either for compatibility reasons or to make deployment easier.

So the idea is to add the following export options:

* Embed external tilesets
* Detach template instances
* Resolve object type and inherited tile properties (mentioned [on the forum](http://discourse.mapeditor.org/t/properties-via-object-types/3074/2?u=bjorn))

The latter option was [requested](http://discourse.mapeditor.org/t/ability-to-bake-objects-made-using-object-template-function-into-the-map-itself/2929) on the forum [twice](http://discourse.mapeditor.org/t/creating-a-template-for-tiles/21/8). And the former option was mentioned before at https://github.com/bjorn/tiled/issues/1091#issuecomment-266767410.

**Comment by kress95** [comment]
This would be extremely helpful ^_^

**Comment by hexus** [comment]
Super glad this is on the roadmap! :ok_hand:

**Comment by alaa-eddine** [comment]
This would be really nice ! it was one of my requests when Tiled changed the export format.
Well, the workaround is pretty simple (importing the tilesets manually befaure exporting the map) but when working with lot of shared tilesets, it's a source of issues.

I'm very happy to see thi in the roadmap !

**Comment by bjorn** [comment]
The options mentioned in this issue are now all implemented and can be set in the Preferences. They are applied both when exporting maps as well as when exporting tilesets.

In addition, these options are available when exporting maps or tilesets on the command-line. In this case, the preferences are not used.

I tested it quite a bit, but please let me know if you find any issues. Also if you're still missing a particular export option, feel free to suggest it!
