### ISSUE TITLE
Tiled 1.1 trackpad issues on OS X

### ISSUE THREAD

**Issue by tomcashman** [bjorn/tiled#1852]
Scrolling with the trackpad on OS X now triggers zoom in/out of the map instead of moving the scrollbars. Better behaviour would be pinch to zoom.

**Comment by bjorn** [comment]
Hm, right, I wonder if I could make this behave better by default. The current behavior is to zoom in/out on mousewheel without needing to hold Control, but track pad events also arrive as wheel events.

In any case you should be able to simply turn off "Mouse wheel zooms by default" in the Preferences. Also, pinch to zoom should already work as well (can you verify that?). But ideally things would work as expected out of the box. Simply reverting the default of this setting is not ideal for people using a mouse...

**Comment by tomcashman** [comment]
Turning off the setting in preferences works. Pinch to zoom works then also.

I would suggest it should be off by default since most programs such as web browsers, image editors, etc. use Ctrl + Scroll for zoom?

**Comment by bjorn** [comment]
> I would suggest it should be off by default since most programs such as web browsers, image editors, etc. use Ctrl + Scroll for zoom?

Well, it's not fair to compare it to browsers since they primarily scroll vertically. I don't know what most image editors do, but I think many don't require Ctrl for zooming.

However, if we can't find a good fix to have trackpads work nicely by default, then this is certainly a good reason to put the default on requiring Ctrl.

**Comment by bjorn** [comment]
With [Tiled 1.1.3](https://thorbjorn.itch.io/tiled/devlog/26475/tiled-113-released) I made zooming with Ctrl the default, to avoid messing up trackpad panning (321dbe33e553958144a270366f2b9b27a86414d3).
