### ISSUE TITLE
Loading infinite maps in json will cause chunks to not be spaced correctly (1.1.2)

### ISSUE THREAD

**Issue by GaryCXJk** [bjorn/tiled#1878]
## How this issue can be reproduced

Create a map that's at least two chunks wide, then save the map. Now close said map, then re-open the map again.

## What behavior you expected instead

![Before reloading](https://user-images.githubusercontent.com/646757/36048771-b1fbab88-0de0-11e8-85ce-830b041b2139.png)

## What actually happened

![After reloading](https://user-images.githubusercontent.com/646757/36048911-18952022-0de1-11e8-8c56-7fc1550d021c.png)

I assume this issue is caused by a slightly wrong calculation. It seems that chunks are spaced one chunk. The json file itself is fine, the chunks are properly defined and spaced, and when loaded in, for example, a game, the chunks do get placed correctly. It's just that reloading the maps causes the chunks to be spaced incorrectly.

**Comment by bjorn** [comment]
Arg, I really need to do more testing. I've pushed a fix to be included in Tiled 1.1.3, but in the meantime I would recommend using TMX format and only using JSON for export.

Thanks for reporting this issue!

**Comment by bjorn** [comment]
Ah, also, this bug only affected the CSV format (which I think it why I didn't run into it while testing). So another possible workaround is to switch to base64 encoding of tile layer data (in the map properties).

**Comment by GaryCXJk** [comment]
Well, it did give me a reason to implement the decoding of base64 encoded maps.
