### ISSUE TITLE
Isometric Map exporting the tiles in wrong rendering order

### ISSUE THREAD

**Issue by jacobmrhodes** [bjorn/tiled#1879]
I am attempting to create an isometric map and every time I attempt to export it, the layering of the tiles is in the wrong order. I have experimented with different tile render orders and each of them display the tiles in a different order, but ultimately none of them reflect the exact map that the editor displays when I am creating a map.

![2018-02-10 03_22_20-beta level v2 tmx - tiled](https://user-images.githubusercontent.com/23402839/36060157-a6ef8c9c-0e11-11e8-88b8-fdc295a4f644.png)
![2018-02-10 03_22_01-beta level v2 tmx - tiled](https://user-images.githubusercontent.com/23402839/36060158-a6fade30-0e11-11e8-8748-18f42f87a4ae.png)

**Comment by bjorn** [comment]
This issue should have been reported at https://github.com/Seanba/Tiled2Unity.

The "tile render order" is a property that Tiled currently only supports for orthogonal maps. Isometric maps have a special rendering iteration to make sure the tiles are rendered correctly. It looks like Tiled2Unity may be rendering isometric maps using similar logic as orthogonal maps. Is that right, @Seanba?

Isometric maps in Tiled are actually rendered line by line, from top to bottom. This means that while drawing a row it is traversing tiles like:

https://github.com/bjorn/tiled/blob/da9ba8f0c7138850b7c2b9b23e6544d0705a94ae/src/libtiled/isometricrenderer.cpp#L289-L291

and some special logic is needed when advancing to the next column.

Btw, it could be that you need to enable a depth buffer for the rendering order to work correctly in Unity. That is another valid approach to solving this issue.

**Comment by jacobmrhodes** [comment]
If you're confident in your response, I'll close this issue and report it at Tiled2Unity. Or we can wait til Seanba responds. Thanks for the help

**Comment by Seanba** [comment]
Hi there, Jacob. I'm afraid this is something I won't be able to get to in a while due to an overwhelming schedule but if you send me your TMX, textures, and TSX files I'll try to get around to it eventually.

One quick thing to check: Is 'Use Depth Buffer' checked? I'm struggling to remember the details but I think it's possible you need that on in order for Isometric maps to render properly.

**Comment by jacobmrhodes** [comment]
I'll test the 'Use Depth Buffer' tomorrow and report back. I'd feel silly if that's all it takes :)

No worries on a timeframe. Just doing my part to report the issue for now. I'm onto another project for the time-being.

**Comment by jacobmrhodes** [comment]
'Use Depth Buffer' did not resolve the issue. I will close this issue and resubmit it for Tiled2Unity. Thanks guys.
