### ISSUE TITLE
Missing variable in json tileset output

### ISSUE THREAD

**Issue by markwinter** [bjorn/tiled#1881]
http://docs.mapeditor.org/en/latest/reference/json-map-format/#tileset

The documents say a `type` field should be present for tilesets, but it appears to be missing from the actual output. Below is my json output from Tiled version 1.1.2. It's also missing in the tileset json example on that page too.

```
"tilesets":[
        {
         "columns":8,
         "firstgid":1,
         "image":"..\/..\/Downloads\/tmw_desert_spacing.png",
         "imageheight":199,
         "imagewidth":265,
         "margin":0,
         "name":"tmw_desert_spacing",
         "spacing":1,
         "tilecount":48,
         "tileheight":32,
         "tilewidth":32
        }],
```

**Comment by bjorn** [comment]
As the documentation mentions, this variable is "(for tileset files, since 1.0)". The tileset you quoted is not in a tileset file, but embedded in a map file. In this case the "type" is superfluous, since you already know each entry in the array is a tileset.

**Comment by bjorn** [comment]
Btw, since I see you're developing `tmxjson`, are you aware of the recent changes to the JSON format, released with the new development snapshot yesterday? See #1868.

**Comment by markwinter** [comment]
Ah, I completely missed that comment about it being for tileset files.

I didn't see that commit, thanks for pointing it out

**Comment by bjorn** [comment]
> Ah, I completely missed that comment about it being for tileset files.

Alright. I'll close this issue then. :-)
