### ISSUE TITLE
Problem - create map

### ISSUE THREAD

**Issue by gladson** [bjorn/tiled#1884]
![2018-02-16_15-13-08](https://user-images.githubusercontent.com/1013698/36325072-e7b298ee-132c-11e8-91e4-c8c771754add.gif)

![image](https://user-images.githubusercontent.com/1013698/36325383-0d93d1c6-132e-11e8-8ca0-c31cd96c9923.png)

**Comment by bjorn** [comment]
That's weird. I've never heard of this problem before. It seems that actually the map is open, otherwise the "Embed in map" option when creating a new tileset would be disabled. But for some reason it is not displaying...

What version of Tiled are you using?

**Comment by gladson** [comment]
Strange this kind of problem.

![image](https://user-images.githubusercontent.com/1013698/36330261-580d944c-133f-11e8-840b-fe19fa4eae53.png)

**Comment by bjorn** [comment]
Could you try any other version, to see if this is a new problem? Like [Tiled 1.0.3](https://github.com/bjorn/tiled/releases/tag/v1.0.3) or the [latest development snapshot](https://thorbjorn.itch.io/tiled) from itch.io?

**Comment by gladson** [comment]
I'll try to send you a return...

**Comment by gladson** [comment]
latest development snapshot
===================

![2018-02-27_16-26-40](https://user-images.githubusercontent.com/1013698/36753145-b50af064-1bdb-11e8-93ab-cb7b01feab5e.gif)

Tiled 1.0.3 it works. 

But I already use it, in case I wanted to update.

**Comment by bjorn** [comment]
Thanks for the update. That's really strange that the main window fails to update. Even the menu bar isn't repainting... does anything change when you try to resize the window in this state?

Just wondering, did you enable hardware accelerated rendering (OpenGL) at some point? If so, please try if it helps to disable it.

**Comment by bjorn** [comment]
@gladson If you find some time, please let me know whether you're still seeing this issue in [Tiled 1.1.5](https://thorbjorn.itch.io/tiled/devlog/31935/tiled-115-released). It's built against Qt 5.10 rather than 5.9, and I hope it addresses this issue... though this remains the one and only report of this issue so far so it must be a very rare one.

**Comment by bjorn** [comment]
@gladson Are you still around to test whether this also affects the latest build, the [Tiled 1.2 Beta](https://thorbjorn.itch.io/tiled/devlog/45718/tiled-12-beta-released)?

**Comment by gladson** [comment]
Thanks for the feedback, I will test today to certify you have solved it.

**Comment by gladson** [comment]
Solved, with this new version... 
It was very good...
Thank you very much.

**Comment by bjorn** [comment]
@gladson Well, I did nothing to fix it myself, since I was not able to reproduce the problem.

I'm glad to hear the bug is no longer appearing in the current version! Thanks for testing!
