### ISSUE TITLE
Adding Support for Texture Normals

### ISSUE THREAD

**Issue by ScottHerrmann** [bjorn/tiled#1885]
Not necessarily an important feature, but something I've seen myself need to create a workaround for, it would be nice to be able to tile normal to maps rather than have to lay the normals underneath tiles. I'm currently working towards a different means using custom properties to properly layer normal maps based on tileset but it would be nice to have native support.

**Comment by bjorn** [comment]
Is this a duplicate of #830?

**Comment by ScottHerrmann** [comment]
@bjorn that's strange, I looked for normal and normal map and didn't see #830, closed.
