### ISSUE TITLE
Zstd to tiled format and compression ratio

### ISSUE THREAD

**Issue by alphaonex86** [bjorn/tiled#1886]
Hi, can you add at **Tile Layer format** the entry **Base64 (Zstandard compression)** and the level of compression?

- It very more fast on compression and decompression for same ratio than Zlib
- Very more fast at decompression for higher ratio than Zlib
- Compression similar to Lzma, Xz then very better than zlib at higher ratio
- Add option to choose the compression level
- Default to this new entry

I can do the code or donation for this

Cheers, it's a great software.

**Comment by bjorn** [comment]
It definitely looks like [zstd](https://github.com/facebook/zstd) would be interesting to support, however did you actually measure the map loading time and is the decompression really a significant part of it?

And if loading times are such a concern, did you consider writing a specialized binary format to minimize processing time? Or would it alternatively be interesting to enable the chunked layer data format for non-infinite maps? This would significantly reduce the data that needs to be processed of mostly empty tile layers.

> I can do the code or donation for this

You're welcome to work on this and/or to make a donation! :-)

**Comment by alphaonex86** [comment]
Hi,
On 2 map set (1972 maps and 171 maps), the decompression speed is 3-6x more faster with zstd.
Maybe a specialized binary format to minimize processing time can be interesting, but for now I prefer the compression.
I will make donation. I don't known if I have time to work on this.

**Comment by alphaonex86** [comment]
PS: I think it's more logic split map into small chunk than just the layer data. That's split all the overhead to parse the map format too

**Comment by bjorn** [comment]
> PS: I think it's more logic split map into small chunk than just the layer data. That's split all the overhead to parse the map format too

It's not just splitting the layer data in chunks. It's also leaving out empty chunks entirely. That makes a big difference if you have maps with tile layers that are mostly empty, which is not uncommon.

**Comment by alphaonex86** [comment]
https://github.com/alphaonex86/tiled WIP...

**Comment by alphaonex86** [comment]
Zstandard done, I failed to compression level option, can you help me?

**Comment by bjorn** [comment]
> Zstandard done, I failed to compression level option, can you help me?

Please open a pull request, then I can help with review and additional changes.

**Comment by alphaonex86** [comment]
Done https://github.com/bjorn/tiled/pull/1888

**Comment by Seanba** [comment]
Could we put off making this the default option for now?  People building tech off of Tiled may need some time to support this.

**Comment by alphaonex86** [comment]
Here I have put default arguments to transparent usage. I think is good the new map is directly created with new format.

**Comment by bjorn** [comment]
For sure the default will stay on Zlib, no worries @Seanba! We can't have the default require people to rely on custom extraction code, and zlib is still the most commonly available format in frameworks and standard libraries.

@alphaonex86 The Zstandard format doesn't need to be the default. Once somebody switches to it, Tiled will remember that choice so you can use it without needing to choose it again for each new map.

**Comment by alphaonex86** [comment]
Part of my mapper community is asking to get zstd into .tmx format for mi game.

When it will be into official code and binary?

**Comment by bjorn** [comment]
@alphaonex86 I'll have another look at your PR #1888 tomorrow.

**Comment by alphaonex86** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Zstd-1.3.5-Released&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+%28Phoronix%29
15x in performance in small data, as used into tiled map format.

**Comment by alphaonex86** [comment]
Any news? Zstd is implemented into ever more software each time...
