### ISSUE TITLE
Effect of undo doesn't always show immediately

### ISSUE THREAD

**Issue by Koopa1018** [bjorn/tiled#1887]
In version 1.1.1, when I Undo, it sometimes doesn't show the change immediately. When I press ctrl+Z, nothing seems to happen. This is a purely visual bug--the map gets updated as it should, but it doesn't _show_ a change until I either zoom in (thereby forcing a whole-viewport refresh, I would guess) or manually put the cursor over each and every changed tile.

I'd love to give a little more information, but (un)fortunately, it seems to be a fairly sporadic and/or easy to fix bug--oftentimes, the bug disappears when I try to figure it out (which almost certainly makes this least-concern material, I'd assume), and doesn't resurface even when I restart the program.

I can't think what I might have done to get this to happen, but I will try to figure it out. In the meantime, here's my specs:
OS: Windows 10 Pro x64, version 1709
CPU: Intel i7 3770k
GPU: ATI FirePro v4800, though it also happened when I was using an Intel HD 4000
Tiled version: 1.1.1

**Comment by bjorn** [comment]
Could you try to use the latest [_development snapshot_](https://thorbjorn.itch.io/tiled) to see if the problem still persist there? I think it may be fixed there and I am considering to backport that fix to 1.1 for the 1.1.3 release.

**Comment by Koopa1018** [comment]
The glitch hasn't cropped up again, either in the snapshot or in the release. Can't tell if that's because the glitch was fixed, or just because I haven't hit the stimulus that made it happen yet.

Sorry for wasting your time with this. Should've figured out the stimulus before I posted, huh?

**Comment by bjorn** [comment]
> Sorry for wasting your time with this. Should've figured out the stimulus before I posted, huh?

No worries, you noticed an issue and that means it's relevant no matter if we are able to find out how to actually reproduce it. I think I've figured out the problem and fixed it in the above commit. See the explanation for a possible reason why you may have not been able to reproduce it anymore. Thanks for the report! :-)
