### ISSUE TITLE
File Open dialog crash app on Linux Mint 18

### ISSUE THREAD

**Issue by mariombn** [bjorn/tiled#1890]
Hello.
Whenever I do an action that opens a dialog box to select a directory, save or open, the program simply closes.

I tried version 1.0.3 of the program and in this version, the error does not happen.

My Configuration Information:
https://gist.github.com/anonymous/21775c10b0b51b71e18b6a2ed35ba55a

**Comment by bastlenoob** [comment]
Hello.
I'm using linux mint too and I don't have any bug when I do an action that opens a dialog box... I tried the latest version of Tiled (Tiled 1.1.2), which version did you used ?

**Comment by bjorn** [comment]
Also may be worth trying the 1.1.3 release I made today, which is built against a slightly newer Qt version (5.9.4).

**Comment by bjorn** [comment]
No news from reporter, closing old issue.
