### ISSUE TITLE
Copy pasting objects flips order

### ISSUE THREAD

**Issue by kralle333** [bjorn/tiled#1896]
Problem happens when are selection of objects in a layer is selected and then pasted. The objects now have the opposite order. 
I.e. given selected objects 1,2,3, which are copied and pasted, then the resulting objects will have the order, from top to bottom, 3,2,1.

This is especially a problem when drawing order of the layer is set to Manual (Indexing based)

**Step 1:**
Place 3 objects, name them 1,2,3 for convenience sake.
Select the objects.
![step1](https://user-images.githubusercontent.com/5738476/36736431-e358bb0c-1bd8-11e8-94fd-0e82dad636e8.PNG)

**Step 2:**
Paste beneath the other objects and notice how the order has been flipped.
![step2](https://user-images.githubusercontent.com/5738476/36736504-156a9e9e-1bd9-11e8-87b7-b7bd67bf3016.PNG)

**Comment by felaugmar** [comment]
Wow, this is true. 
And yes, when manually rendering (index), it impacts the wanted result.

**Comment by bjorn** [comment]
Will be fixed in Tiled 1.1.3, to be released in a few days.
