### ISSUE TITLE
Probability brush

### ISSUE THREAD

**Issue by Nek** [bjorn/tiled#190]
Or it can be named advanced random mode with ability to set probability for every tile used.
It will require additional configuration panel with presets (think rocky terrain, grassy field etc.)

**Comment by bjorn** [comment]
As of change d35c622b88da3f3858d830a442fb9ba15e2e62c0, the tile probability used by the Terrain Brush is now editable in the Properties view.

I think it would make sense to use this probability also as a relative probability in Random Mode, in addition to the workaround originally suggested by @stefanbeller.

**Comment by kheftel** [comment]
Wow bjorn, that's awesome! Way to go!
