### ISSUE TITLE
Tiled 1.1.3 Is not working in my Mac.

### ISSUE THREAD

**Issue by fmasutti** [bjorn/tiled#1906]
Hello guys, Im not able to use the last version that I downloaded. The program open but I can't create new map / Tile set.

My machine setup and system version.
<img width="265" alt="screen shot 2018-03-15 at 11 06 30" src="https://user-images.githubusercontent.com/3879882/37459734-ef8f3616-2840-11e8-8577-2bddd79d9371.png">

Steps to reproduce the bug.
Step1: Open the program and create a new map/ tile Set.
<img width="604" alt="screen shot 2018-03-15 at 11 04 31" src="https://user-images.githubusercontent.com/3879882/37459686-cf4c5a14-2840-11e8-950d-d54fe78ca912.png">

Step2: Setup your preferences. (I was not able to use anyone of them)
<img width="463" alt="screen shot 2018-03-15 at 11 04 36" src="https://user-images.githubusercontent.com/3879882/37459689-d1989454-2840-11e8-8d26-eb878e9c7b46.png">

Step3: When u save it, an error message will show up. (The file is not create in my file system)
<img width="371" alt="screen shot 2018-03-15 at 10 57 48" src="https://user-images.githubusercontent.com/3879882/37459367-bacdedc4-283f-11e8-9ba9-86bba2ae06d9.png">

**Comment by fmasutti** [comment]
Nvm, it just work fine today... I have no glue y.

**Comment by bjorn** [comment]
@fmasutti Glad you got it to work. I have no idea either why it could have been failing. If you ever run into it again, maybe you'll notice another clue. Please reopen the issue then, thanks!
