### ISSUE TITLE
tiles json empty

### ISSUE THREAD

**Issue by phil123456** [bjorn/tiled#1908]
Hello,

just realised the tiles json export is basicaly empty (appart from a ref to the image file)

fyi

now I'll have to implement annoying xml parsing ....

regards

**Comment by bjorn** [comment]
I just [answered this on the forum](https://github.com/bjorn/tiled/commit/d556aaf4b7c4aea66b4619867438eb40f3e00692).

Issue was fixed in commit d556aaf4b7c4aea66b4619867438eb40f3e00692.
