### ISSUE TITLE
object layer tileset images gid

### ISSUE THREAD

**Issue by Weedshaker** [bjorn/tiled#1923]
Hi,

our designer Ruben, who by the way is a patreon of your project, has started to use flipping vertical/horizontal, of images set within an object layer. I have been calculating the gid of the tileset image by using firstGid and gid but when using flipping, the gid becomes a 10 digit number, starting with 1, 2 and 3 for vertical, horizontal and both, is there a distinct way to calculate the tilesets gid from the 10 digits gid?

Thanks for the answer!

**Comment by Weedshaker** [comment]
THX, I did read it, though I hoped there is something snappier. I would prefer a way I don't have to dig around the data array of the tilemap, not only because of the complexity but also performance wise, may there is a simpler way?

I am gonna have a look to figure this C++ stuff to get it into JavaScript. In the meantime, I highly appreciate if somebody already has a shortcut!?

**Comment by bjorn** [comment]
> I would prefer a way I don't have to dig around the data array of the tilemap, not only because of the complexity but also performance wise, may there is a simpler way?

Reading out and clearing bit flags should not have any noticeable performance impact. These are simple instructions that CPUs and also modern JavaScript VMs should have no problems with.

> I am gonna have a look to figure this C++ stuff to get it into JavaScript. In the meantime, I highly appreciate if somebody already has a shortcut!?

I'm not sure what you are requesting here. Do you think it would be easier to just store a few more arrays with booleans for the various flipping states? If so I would warn you that even though it may be a little easier, it would consume a lot more memory. I'm curious to hear any suggestions.

I believe reading and manipulating bit flags works the same way in JavaScript as in C++.

> our designer Ruben, who by the way is a patreon of your project

My regards to Ruben and thanks a lot for supporting the continued development of this tool!

**Comment by Weedshaker** [comment]
@Seanba , thank you again for pointing me into the right direction!

```javascript
const gid = flipped_horizontally && flipped_vertically ? object.gid - (~FLIPPED_HORIZONTALLY_FLAG + Math.abs(~FLIPPED_VERTICALLY_FLAG)) : flipped_horizontally ? (object.gid - ~FLIPPED_HORIZONTALLY_FLAG) - 1 : (object.gid + ~FLIPPED_VERTICALLY_FLAG) + 1;
```

the above has been working well so far... I assume that I got this right?

@bjorn , you can close this issue. Always, thank you for your support!

**Comment by Weedshaker** [comment]
oh, I can do this on my own, nice ;-)

**Comment by bjorn** [comment]
@Weedshaker Is that code meant to clear the flags? I'm not sure I follow. The code should look much more like the code linked in the documentation, like so:

```javascript
{
    const FLIPPED_HORIZONTALLY_FLAG = 0x80000000;
    const FLIPPED_VERTICALLY_FLAG = 0x40000000;
    const FLIPPED_DIAGONALLY_FLAG = 0x20000000;

    // for testing
    const object = { "gid": 30 | (FLIPPED_HORIZONTALLY_FLAG | FLIPPED_VERTICALLY_FLAG) };

    // reading out the flags
    const flipped_vertically = (object.gid & FLIPPED_VERTICALLY_FLAG) != 0;
    const flipped_horizontally = (object.gid & FLIPPED_HORIZONTALLY_FLAG) != 0;
    const flipped_diagonally = (object.gid & FLIPPED_DIAGONALLY_FLAG) != 0;
    console.log(flipped_vertically, flipped_horizontally, flipped_diagonally)

    // clearing the flags
    const gid = object.gid & ~(FLIPPED_HORIZONTALLY_FLAG | FLIPPED_VERTICALLY_FLAG | FLIPPED_DIAGONALLY_FLAG);
    console.log(gid)
}
```

**Comment by Weedshaker** [comment]
yes, clearing flags but also I avoid the bitwise.

**Comment by bjorn** [comment]
> yes, clearing flags but also I avoid the bitwise.

Why?

**Comment by Weedshaker** [comment]
it is discouraged in javascript. though, this may would have been the one chance to use it. anyways, I just needed to get the gid without the flag, and the code snippet I posted does it. the only strange thing was that it didn't work with the diagonally flag, thats why I am calculating it with the other two.

**Comment by bjorn** [comment]
@Weedshaker The arguments for not using bitwise operations brought forward there are performance, maintainability and readability. But I think solving this problem the way you did is likely slower, less maintainable and less readable in this particular case. In my opinion it indeed qualifies as a good time to make an exception.
