### ISSUE TITLE
JSON format for object width/height/x/y is labelled as int but it should probably be double

### ISSUE THREAD

**Issue by bitinn** [bjorn/tiled#1924]
What I am seeing with snapshot build `2018.03.21`

```
                {
                 "height":18.84375,
                 "id":19,
                 "name":"",
                 "rotation":0,
                 "text":
                    {
                     "color":"#ff0000",
                     "text":"Hello Text",
                     "wrap":true
                    },
                 "type":"",
                 "visible":true,
                 "width":89.546875,
                 "x":-256,
                 "y":-1216
                }],
```

Because there are currently quite a few format difference between snapshot build and stable build (JSON Tileset properties format, for example), I am sticking with snapshot build as the future format Tiled will use, is that a safe assumption?

**Comment by bitinn** [comment]
EDIT: Hmm, actually, maybe object width and height isn't supposed to be int ([which is a doc issue](http://doc.mapeditor.org/en/latest/reference/json-map-format/#object)). Good to know its accuracy is `double`.

**Comment by bitinn** [comment]
OK I have now read more into this and apparently [JSON doesn't have a limit on number size](https://stackoverflow.com/questions/13502398/json-integers-limit-on-size), but RFC recommends `double` for better interoperability.

Here is the thing: Tiled JSON document label quite a few things incorrectly but I am not sure how you want to fix it.

In Spec, JSON only has `number` type, no `int`/`uint`/`double`.

But in practice: developers working with JSON need to know the type they are expecting, for example, without reading TMX spec, I wouldn't know I must use `uint` for the `layer.data` array, as tile flipping will cause tile id to go over `int` range. See below for an example:

```
         "chunks":[
                {
                 "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2684354577, 3221225489, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 1610612753, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                 "height":16,
                 "width":16,
                 "x":0,
                 "y":-16
                }],
```

`3,221,225,489` and `2,684,354,577` are outside of the `int` range and will be casted/serialize incorrectly.

So preferably the document should say `uint` but that's a C# thing, not a JSON/C++ thing. So I am unsure how you want to fix it...

**Comment by bitinn** [comment]
Another good thing to have: explicit `uint` type for `object.id` / `nextobjectid`, from current usage I would expect it to never be negative. Specify `uint` make it consistent with tile id.

(I understand the choice for uint is really due to tile flipping feature, but it's nice to be able to assume `uint` for both tile and object id)

**Comment by bjorn** [comment]
> I am sticking with snapshot build as the future format Tiled will use, is that a safe assumption?

Yes, there are no plans to revert the format changes.

Indeed the JSON format documentation should be more specific / correct about the various number types.

I don't think "never expected to be negative" is a good reason to use `uint` though, so object IDs will probably stay on `int` since that is what they are currently.

**Comment by bitinn** [comment]
Not to bundle too much change in the same issue, but doc might also need to explain object x,y in an infinite map context, so far their values seem cryptic to me.

http://discourse.mapeditor.org/t/object-x-y-on-an-infinite-map/3113

(Haven't looked at actual code yet, don't know where to start as I am not very familiar with C++)
