### ISSUE TITLE
Move Object Down / Up button causes resize of columns

### ISSUE THREAD

**Issue by faulknermano** [bjorn/tiled#1928]
Using Tiled 1.1.4.

- Create an Object Layer.
- Add some Objects (any Object will do) into the Object Layer.
- Re-arrange the Objects by clicking on the Move Object Down/Up buttons
- When you press these buttons you will see that the columns will re-size.
- Also when you remove the columns by RMB and unticking some of the columns, pressing Move Object Down/Up will make those columns re-appear

**Comment by bjorn** [comment]
Looks like this is a [Qt bug](https://bugreports.qt.io/browse/QTBUG-65478).
