### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by R40ul** [bjorn/tiled#193]
Hi,
Thanks for the work that has been done so far. That's really great. 
However, I'd really like to be able to write comments in Tiled, in order to keep in mind some ideas I have while I'm designing my level. I think it would be really useful to write blocs of plain text that would appear over the map (or on a specific layer), but would not be exported with the rest of the level objects.
I haven't found any post talking about this.

Thanks,
Antoine

**Comment by fo-fo** [comment]
I agree that this would be a nice feature. Not only for writing comments for your own design, but also for commenting on somebody else's design (kind of like you can add comments in MS Word and PDF documents).

**Comment by bjorn** [comment]
Please check out the screenshot at #1429 and maybe even try a development snapshot. Tiled now supports Text objects with custom color, font and wrapping options.

Text objects can be used as both plain annotations as well as for objects that are actually used in the game. It's up to you whether you let your game ignore them or not. I believe it is enough to resolve this issue as well, but please let me know what you think.

**Comment by bjorn** [comment]
Closing this issue now since no feedback seems to be coming and the use-case should be fulfilled.
