### ISSUE TITLE
Color property adds Red, Green, Blue properties to Objects Type Editor

### ISSUE THREAD

**Issue by Seanba** [bjorn/tiled#1936]
When a type in the Object Type Editor has a color property it will add additional Red, Green, and Blue properties to the type.

![image](https://user-images.githubusercontent.com/6980630/39078002-a02b858c-44cb-11e8-860a-628893a41d48.png)

The xml from this perhaps shows the bug off better ...

```
<?xml version="1.0" encoding="UTF-8"?>
<objecttypes>
 <objecttype name="SomeType" color="#a0a0a4">
  <property name="Blue" type="int" default="0"/>
  <property name="ColorProperty" type="color" default="#ffffaa00"/>
  <property name="Green" type="int" default="170"/>
  <property name="Red" type="int" default="255"/>
 </objecttype>
</objecttypes>
```

**Comment by bjorn** [comment]
What a strange bug! I'll be sure to look into it soon.
