### ISSUE TITLE
Tool shortcuts no longer work in Tiled 1.15

### ISSUE THREAD

**Issue by kralle333** [bjorn/tiled#1937]
For example: Pressing `T`, when an object layer is selected, no longer selects the Insert Tile tool
Looks like the shortcuts no longer work after commit 687371657b911a5d976314471d6a5981c2480ebd

**Comment by bjorn** [comment]
Thanks for opening an issue about this! I'll look into it right now.

Note that Tiled 1.15 is not out yet, though I realize I did the version bump already. :-)
