### ISSUE TITLE
Object paramater name: Color and Colour

### ISSUE THREAD

**Issue by ldurniat** [bjorn/tiled#1940]
Hi,

tiled (v. 1.1.4, Win) use two names for the same paramater i.e color (in lua and json files) and colour in Tiled itself (for Text object). I think it is better stick to one name:)

Have a nice day:)

ldurniat

**Comment by bjorn** [comment]
Hmm, the English translation seems to be translating all occurrences of "Color" to "Colour", which is wrong since it's meant to be the US English translation.

**Comment by bjorn** [comment]
@monolifed Hey there! Here's just a heads up that the English Tiled translation is meant to be US English (see the change I just pushed). If you'd like to introduce an explicit UK English translation, we can do so, but I'm not sure if it's worth the effort given the minor differences to US English. I'll leave it up to you.

If you are aware of any other UK English-specific translations done in the US English Tiled translation, please let me know or you can adjust them yourself on Weblate.

Thanks a lot for your efforts!

**Comment by monolifed** [comment]
I will check it with EN_US dictionary

**Comment by ldurniat** [comment]
Thanks for answer :)
