### ISSUE TITLE
tiledquick: tiles from second tileset rendered in incorrect positions

### ISSUE THREAD

**Issue by mitchcurtis** [bjorn/tiled#1946]
Expected result:
![tiled](https://user-images.githubusercontent.com/6002340/39925152-d6f2c584-552a-11e8-8f86-36d7bfd00d54.png)

Actual result:
![tiledquick](https://user-images.githubusercontent.com/6002340/39925153-d7164f5e-552a-11e8-837f-1a3d2e0787aa.png)

**Comment by bjorn** [comment]
@mitchcurtis Could you test whether this issue has been fixed in the meantime? We've rewritten the tile layer rendering approach since this issue was reported, though I don't know what could have been causing this.

**Comment by mitchcurtis** [comment]
I don't know when I'll have the time to do that, unfortunately. Feel free to close this if you want, and if I run into it again I will speak up. :)

**Comment by bjorn** [comment]
Alright, let's close it then. I assume it was likely already addressed by either 152344b31a25ad6887417bc9c26752e26c137bb5 or 0712c2067445b61729c87edc8e837c634dc4a908, and then this code was replaced entirely in d3badeff72d31002916a638f107ff92618d89ea4 anyway. :-)
