### ISSUE TITLE
Terrain probability is broken in 1.1.0+

### ISSUE THREAD

**Issue by eCustic** [bjorn/tiled#1949]
Probability seems to be broken in every release since 1.1.0. 
I've tested both creating the tileset/terrain and using the terrain brush in every version from 1.0.3 and up.
It seems to just pick one of the full tiles and only uses that regardless of what the probability is.

**Steps to reproduce:**

1. Create simple terrain from tileset (4 full tiles - probability shown on each tile)
![image](https://user-images.githubusercontent.com/2626362/39934451-240429ec-5546-11e8-9fca-b9f859b00637.png)
Tiled version in this step doesn't seem to matter, it behaves the same regardless.

2. Use terrain brush with the created terrain:
_Version 1.1.5_
![image](https://user-images.githubusercontent.com/2626362/39934652-c5ec4514-5546-11e8-9020-5787d84bd157.png)
_Version 1.0.3_
![image](https://user-images.githubusercontent.com/2626362/39934741-0eb2a360-5547-11e8-90c0-2f6e576fdbc5.png)

**Comment by bjorn** [comment]
Thanks for opening an issue about this! Indeed I've seen a few people who have pointed out problems using the probability.

What is your operating system and which version of Tiled are you using exactly?

I'm afraid it probably has to do with change b9655a37652ed55302a425d9870ec7ea7fdffc42. For some reason this new C++11 API for choosing random numbers is not working for everyone. Maybe it's not supported by a compiler, or maybe I'm using it in the wrong way (though it worked for me). In any case we should find a solution.

**Comment by bjorn** [comment]
Just wondering, but is it broken on the 64-bit version of Tiled as well? Just asking because it's compiled using a different compiler (MSVC 2013 rather than MinGW, which is used for the 32-bit builds).

**Comment by eCustic** [comment]
Just tested and 64-bit version seems to work fine.

**Comment by bjorn** [comment]
Thanks! That somewhat explains why reports of this issue have been a bit rare. Still, I'll look into fixing this also for the 32-bit Windows version.
