### ISSUE TITLE
accidentally closed tileset tab

### ISSUE THREAD

**Issue by LunaPorter** [bjorn/tiled#1966]
When trying to figure out what the tabs do T closed the bottom right tilesets tab and don't know how to re open it edit: i've uninstalled and reinstalled 3 times but it doesn't help

**Comment by bjorn** [comment]
You can get it back through the menu _View -> Views and Toolbars -> Tilesets_.

You can also find some other views there that are hidden by default, and an action to reset the whole thing back to the default layout.

> i've uninstalled and reinstalled 3 times but it doesn't help

Yeah, this does not clear your settings.

**Comment by LunaPorter** [comment]
thank you very much bjorn, it did help.

**Comment by Code-King64** [comment]
Thank you. I was working on a pokemon game, and i was new to tiled. It really helped.

**Comment by RubberCrowy** [comment]
Thank you, bjorn. I had this same issue happen to me just recently today. ... The fact that I looked everywhere in the app and couldn't find what I was looking for, and the issue was something as simple as a closed tab, is just frustrating. 
It was just a closed tab! A _CLOSED_. _TAB_!
