### ISSUE TITLE
Make a C++ library for the Tiled Quick types

### ISSUE THREAD

**Issue by mitchcurtis** [bjorn/tiled#1967]
This would allow games to use Tiled Quick's map rendering to render .tmx maps in Qt Quick games.

**Comment by bjorn** [comment]
I would prefer to first see if we can make the Qt Quick plugin suitable for games (as well as for Tiled Quick, of course). Most Qt QML types do not expose their C++ API either.

Do you have any particular reason you're asking for this now?

**Comment by bjorn** [comment]
> One option is to just make it a library instead, then just register the types in the application. That would actually be nice for me too, because then I could use the types in C++ (whereas I'm currently treating them as QObjects and using invokeMethod()).

Alright, now I read this comment you left at #1945. Why are you doing this, as opposed to using them from QML?

**Comment by mitchcurtis** [comment]
I have C++ code that needs coordinate conversion; basically a bunch of functions forwarding calls to the equivalent functions in `MapItem`:

```
QPointF SceneView::tileToScreenCoords(const QPointF &position) const
{
    if (!mTmxMapItem) {
        qWarning() << "No tmx map item set";
        return position;
    }

    QPointF returnValue;
    if (!QMetaObject::invokeMethod(mTmxMapItem, "tileToScreenCoords", Qt::DirectConnection,
        Q_RETURN_ARG(QPointF, returnValue), Q_ARG(QPointF, position))) {
        qWarning() << "Failed to invoke method";
        return position;
    }
    return returnValue;
}
```

My QML usage is pretty standard:

   ```
 SceneView {
         id: sceneView
         anchors.fill: parent
         scene: scene
         tmxMapItem: mapItem
         enabled: gameReady
    
         Scene {
             id: scene
    
             transform: [
                 Translate {
                     x: -sceneView.offset.x + (((1 / sceneView.zoom) - 1) * (sceneView.width * .5))
                     y: -sceneView.offset.y + (((1 / sceneView.zoom) - 1) * (sceneView.height * .5))
                 },
                 Scale {
                     xScale: sceneView.zoom
                     yScale: sceneView.zoom
                 }
             ]
    
             MapItem {
                 id: mapItem
                 z: -100000
    
                 Connections {
                     target: gameController
                     onPreLevelEntered: mapItem.map = level.tmxMap
                     onPostLevelExited: mapItem.map = null
                 }
    
                 visibleArea: {
                     if (!map)
                         return Qt.rect(0, 0, 0, 0);
    
                     var scale = sceneView.zoom
                     Qt.rect(-scene.x / scale,
                             -scene.y / scale,
                             (map.width * map.tileWidth) / scale,
                             (map.height * map.tileHeight) / scale);
                 }
             }
         }
     }
```

**Comment by mitchcurtis** [comment]
Feel free to close this if it's out of scope, it was just meant as a suggestion (unfortunately they don't let users add labels otherwise I would have :)).

**Comment by bjorn** [comment]
Hmm, though the API you're using here is just exposed by the QML items and is actually part of libtiled, which is already a C++ library that you could use directly.

**Comment by mitchcurtis** [comment]
Just brainstorming here...

```
Tiled::MapReader mapReader;
mTmxMap = mapReader.readMap(mTmxFileName);
```

I can definitely create a "dummy" IsometricRenderer and pass it that map. Thanks. :)

**Comment by bjorn** [comment]
@mitchcurtis Yeah but, why load the map again? You already have `mapItem.map` (which I guess comes from a `Tiled.MapLoader`?), which you could pass to C++.

**Comment by mitchcurtis** [comment]
Oh, that code is where the map is read (I don't use MapLoader). After that, it's set on the map item in QML (onPreLevelEntered: mapItem.map = level.tmxMap).
