### ISSUE TITLE
mapeditor.org outage (?)

### ISSUE THREAD

**Issue by poikilos** [bjorn/tiled#1975]
I cannot get to discourse.mapeditor.org or mapeditor.org. Firefox just says it is having trouble finding the site.

**Comment by bjorn** [comment]
Whoops, I ran out of funds at my hosting provider, and I didn't realize that included the DNS service, which is why it is also affecting those domains even though they are hosted by GitHub and Discourse.

Anyway, I topped up my account and it seems the domains are back up!
