### ISSUE TITLE
Unable to resize objects outside of map bounds in world view

### ISSUE THREAD

**Issue by tomcashman** [bjorn/tiled#1983]
I encountered this issue when I pasted an object at the bottom of a map. See attached screenshot - I was unable to select the bottom arrows and resize the object.

Easily worked around, wouldn't consider it a major issue.

![screen shot 2018-07-24 at 17 59 50](https://user-images.githubusercontent.com/1745420/43154278-b942e61a-8f6b-11e8-8cb8-351b96f2fb1d.png)

**Comment by bjorn** [comment]
Yeah, the mouse events for left mouse button are currently being hijacked in the whole area of neighboring maps. This is not ideal and I still mean to look for a different way of implementing the interaction. Thanks for opening an issue about it!

**Comment by bjorn** [comment]
@tomcashman Please try if the behavior in the [lastest development snapshot](https://thorbjorn.itch.io/tiled/devlog/43780/export-options-and-polishing) resolves this issue, keeping an eye out for possible new issues. Thanks!
