### ISSUE TITLE
Template for Tile Custom Properties 

### ISSUE THREAD

**Issue by katerd** [bjorn/tiled#1991]
When setting custom properties on new tiles in a tilemap I have to add each Custom Property manually and then set the value, and it can become quite laborious and error prone. It would be great if there was functionality within Tiled  to specify a list of all the available properties for tiles, and then set the ones required for that tile?

![image](https://user-images.githubusercontent.com/522347/44307087-32594a80-a394-11e8-9110-1fec890e0677.png)

Not all tiles will require all properties - e.g. tiles blocked from walking will not have a "walk dust colour" for example, but it would make it much easier to author, especially for less tech-savvy folk.

**Comment by bjorn** [comment]
There's two things you can do to make this less laborious and error prone:

* You can select multiple tiles and set / change the properties on all of them at the same time.
* You can copy/paste custom properties (also multiple at the same time).

> It would be great if there was functionality within Tiled to specify a list of all the available properties for tiles, and then set the ones required for that tile?

This is a great suggestion. It is already covered by issue #1410 though, so I'll close this issue.
