### ISSUE TITLE
Quit shortcut is not implemented for windows (easy fix)

### ISSUE THREAD

**Issue by Yoonwoo** [bjorn/tiled#1998]
Currently Tiled uses QKeySequence::Quit when using setShortcut for the quit action. This constant has no standard keyboard shortcut on windows. See [this table in docs](https://doc.qt.io/qt-5.11/qkeysequence.html#standard-shortcuts). 

All platforms use ctrl+Q, so the code can be something like

`mUi->actionQuit->setShortcut(QKeySequence(tr("Ctrl+Q")));`

The code is this at the moment:
`mUi->actionQuit->setShortcuts(QKeySequence::Quit);`

**Comment by bjorn** [comment]
What other apps close with `Ctrl+Q` on Windows? My guess would be only a few that originate from the Linux world, but I may be wrong of course. On Windows the standard close shortcut is `Alt+F4`, which works without explicitly registering it.

That said, unless `Ctrl+Q` is commonly used for something else on Windows, I wouldn't really have a problem with making it an alternative shortcut for quitting.

**Comment by Yoonwoo** [comment]
The only example I have is VLC. I just thought since Tiled will close with CTRL+Q on other platforms it should on Windows too. But its really up to your preference, it doesn't matter much.
