### ISSUE TITLE
tile_object rotates at center but affects the x,y position

### ISSUE THREAD

**Issue by R0Zen** [bjorn/tiled#2005]
Hi, i'm using Tiled as my map editor for my map and I have an issue with it.
the thing is that i'm creating a tile based object with type and custom properties.
everything is works fine until I rotate the object and the X,Y is changing while they shouldn't because I'm rotating on the origin of the object.
I did looked into it and found up that the object is really rotates on the bottom-left axis (why someone would do it idk).
and the thing is that I can't found any setting to change it.
the only way I think i can solve this issue is by fixing it on my game's side but it won't really fix the issue.
and more so my entire graphics library is based on central rotation and position.
can you add a setting to the software to change everything to central position?

**Comment by R0Zen** [comment]
ok I made a simple fix for libgrx.
This will work with any central rendering engine.

`			float t_x = tile.getAttribute("x").getFloatValue();
			float t_y = tile.getAttribute("y").getFloatValue();
			int t_w = tile.getAttribute("width").getIntValue();
			int t_h = tile.getAttribute("height").getIntValue();
			float t_r = 0;
			if (tile.getAttribute("rotation")!=null) // if there is a rotation attribute
			{
				t_r = tile.getAttribute("rotation").getFloatValue();
				Vector3f local = new Vector3f(t_w/2, -t_h/2, 0);
				local.rotateAxis((float) Math.toRadians(t_r), 0, 0, 1);
				local.sub(t_w/2, -t_h/2, 0);
				t_x+=local.x;
				t_y+=local.y;
			}
			// because we like it in the center
			t_x+=t_w/2;
			t_y-=t_h/2;
			// add this tile object to main room
			getParent().addObject(new TileObject(t_x, t_y, t_w, t_h, t_r));`

I will also add this fix to next build of libgrx.

but anyway please add a option to choose central point for objects as asked in #1710

**Comment by bjorn** [comment]
Great work on your fix! I agree we should have the option to change the origin of objects or at least to set a different default project-wide. One of the things to consider for Tiled 1.3.

I'll close this issue since #1710 covers the problem.
