### ISSUE TITLE
Anyone help please?

### ISSUE THREAD

**Issue by ComptuerDood** [bjorn/tiled#2008]
Hi there everytime i save a Map in Tiled a get a
"Unable to get property 'tileSets' of undefined or null reference" trying to re-open it.
It's doing something to the TMX file, which is weird because even if you copy the contents of a working TMX file into one saved in Tiled it still doesn't work!!! ARGH!!!

**Comment by bjorn** [comment]
Can you show a screenshot of this error? Also, could you attach the file that causes this error when you try to open it?

**Comment by bjorn** [comment]
Don't know what to fix here without further information, so closing this issue.
