### ISSUE TITLE
JSON object templates are no longer visible in the Templates window.

### ISSUE THREAD

**Issue by s-m-k** [bjorn/tiled#2009]
Version used: 1.2.0
Windows 10
Template format used: JSON

The templates aren't listed in the Templates window at all. The feature works without problems in 1.1.6.

**Comment by bjorn** [comment]
Fixed it now. The fix will be included in Tiled 1.2.1, which I hope to push out within the next few days.

**Comment by s-m-k** [comment]
Thanks!
