### ISSUE TITLE
[1.2] JSON format inconsistent

### ISSUE THREAD

**Issue by dpeter99** [bjorn/tiled#2020]
the json save format saves the 1.2 version in a way it is not consistent
the doc says that the version is a number, but 1.2 saves it as a float
```"version":1.2,```
I suggest making it a string so it can store more complex versions like "1.2.3"

**Comment by bjorn** [comment]
> the doc says that the version is a number, but 1.2 saves it as a float

Numbers in JSON are floating-point, so the docs are consistent with the behavior here. What you are suggesting is to store the version as a string. Maybe it makes sense, but I think it's not so important and changing it may result in compatibility issues. There is no reason to use more complex versions.

There is another property called `tiledversion`, which is stored as a string. But it can change independently of any format changes and may also take the form of a date (in case of snapshot builds).
