### ISSUE TITLE
Text Object doesn't save in the .tmx file the Alignment Horizontal: "Justify" option.

### ISSUE THREAD

**Issue by roig** [bjorn/tiled#2026]
Using tiled 1.2.0

Text Object doesn't save in the .tmx file the Alignment Horizontal: "Justify" option.

Reproduce:
Create a new map, add an object layer, add a text object, change Alignment Horizontal to Justify, save.

Now check that in .tmx file that option is not saved. My tmx parser can't differentiate Left and Justify options.

If you close Tiled and reopen it and load the map you will see that Alignment horizontal has returned to Left.

**Comment by bjorn** [comment]
Hmm, I must have missed that option, unless it was added to Qt after I implemented the support for text objects. Should not be hard to fix, thanks for reporting it!
