### ISSUE TITLE
I am wondering where I can download old version like v1.0.3

### ISSUE THREAD

**Issue by zhuhengtan** [bjorn/tiled#2036]

**Comment by bjorn** [comment]
Sure, you can download most of the releases [here on GitHub](https://github.com/bjorn/tiled/releases), [Tiled 1.0.3](https://github.com/bjorn/tiled/releases/tag/v1.0.3) is there as well. But why?

**Comment by zhuhengtan** [comment]
> Sure, you can download most of the releases [here on GitHub](https://github.com/bjorn/tiled/releases), [Tiled 1.0.3](https://github.com/bjorn/tiled/releases/tag/v1.0.3) is there as well. But why?

THANKS👍I am learning developing games with cocos-creator, the ide needs v1.0.x tiled maps😂

**Comment by bjorn** [comment]
Hmm, alright. Note that if you're using the TMX format, you can just use the latest version of Tiled since it should still be compatible, as long as you do not rely on any of the new features added in Tiled 1.1. If it doesn't work, please let me know.
