### ISSUE TITLE
Enable "Insert Point" in Collision Editor

### ISSUE THREAD

**Issue by Seanba** [bjorn/tiled#2043]
Hi there. I know points may not make sense as collision geometry but I have the need to define points on a tile that are used in collision detection. Is it possible to add this functionality to the Collision Editor? Thanks.

**Comment by bjorn** [comment]
Hmm, yes, I see no reason not to have that there as well.

**Comment by bjorn** [comment]
Change will be included in Tiled 1.2.2 and the next development snapshot. Not sure yet when either will happen, the latter hopefully within the next week.
