### ISSUE TITLE
TileD not starting anymore

### ISSUE THREAD

**Issue by Firefly130984** [bjorn/tiled#2044]
Full error-message:
Der Prozedureinsprungspunkt
"?toVariant@MapToVariantConverter@Tiled@@QEAA?AVQVariant@@PEBVMap@2@AEBVQDir@@@Z" wurde in der DLL "C:\Program Files\Tiled\tiled.exe" nicht gefunden.

Translation: The entry point of the procedure wasn't found in the DLL.

I de- and reinstalled Tiled for Window 10 64bit but still can't start it.
The first time it happened after the latest update.

**Comment by bjorn** [comment]
> I de- and reinstalled Tiled for Window 10 64bit but still can't start it.

Normally it still means a corrupted install. When you deinstall Tiled, please make sure to deinstall _all_ versions. Please check in the "Add / Remove Software" (or similarly named) section in Windows that you have deinstalled all Tiled entries, and then try installing Tiled again.

If that still doesn't fix it, I can only suggest that you install Tiled without using the installer. There are 7-zip packages available for the development snapshots at https://update.mapeditor.org/snapshots-win/ that you can use as an alternative.

**Comment by Firefly130984** [comment]
Thanks for you reply. It really was a conflict with the first installment from 2017. That would even explain that the issue first occured after the update as I haven't used Tiled for some time. Perhaps let the next update deinstall the old version first.

**Comment by bjorn** [comment]
> Perhaps let the next update deinstall the old version first.

That is what normally happens, but sometimes it doesn't work properly and I have no idea why. MSI is still a rather black magic to me... I'm glad to hear deinstalling all versions manually did the trick as usual!
