### ISSUE TITLE
How to distinguish No and id=0

### ISSUE THREAD

**Issue by 958877748** [bjorn/tiled#2047]
How to distinguish No and id=0

**Comment by bjorn** [comment]
In the files written by Tiled (both the .tmx or .json map files), global tile ID 0 means "no tile", so I do not understand the question. When do you need to distinguish between "No" and "id=0"?

**Comment by 958877748** [comment]
![default](https://user-images.githubusercontent.com/31437616/50429479-adf67580-08f9-11e9-9d5c-05e86df49ebe.JPG)

**Comment by 958877748** [comment]
The ID of the first tile is 0,How do you distinguish it?

**Comment by bjorn** [comment]
In the screenshot you're pointing to the local ID of a tile in its tileset. Within a tileset, there is no "empty cell", and the first tile simply gets ID 0.

This is different from the tile layer data, which does have empty cells and also it can refer to tiles from multiple tilesets. To do this, it uses global tile IDs, and each tileset referenced by the map defines its first global tile ID (the `firstgid` attribute). The global tile ID 0 means "empty cell" and beyond that, you need to look for the tileset with the highest `firstgid` value that is still lower than, or equal to, the global tile ID. You then subtract this `firstgid` value from the global tile ID to get the local tile ID within that tileset.

Note that in addition, global tile IDs support flipping tiles over 3 axis (horizontal, vertical and diagonal) using bitflags. All this is documented at https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#tile-flipping.
