### ISSUE TITLE
libtiled-java incompatible with Java 11

### ISSUE THREAD

**Issue by MinecraftPlaye** [bjorn/tiled#2048]
Using libtiled-java with Java 11 gives me the following error:
`java.lang.NoClassDefFoundError: JAXBException `

It seems to be caused by Java 11 removing java.xml.bind (JAXB).

**Comment by bjorn** [comment]
I'd love to also drop JAXB from libtiled-java. But what does Java provide as an alternative?

**Comment by MinecraftPlaye** [comment]
> 
> 
> I'd love to also drop JAXB from libtiled-java. But what does Java provide as an alternative?

Sadly I don't really now if Java provides an alternative at all.
Thought maybe the following links provide helpful information: [JEP 320](http://openjdk.java.net/jeps/320) and [JAXB Java 9 Doc](https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html)

There seemed to be a way to use [JAXB in Java 9 and 10](https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154), but it [doesn't work in Java 11 ](https://github.com/eclipse-ee4j/jaxb-api/issues/78) anymore.

**Comment by bjorn** [comment]
I don't know exactly how, since JAXB seems to be still used, but Java 11 compatibility was restored by #1925.

**Comment by MinecraftPlaye** [comment]
> 
> 
> I don't know exactly how, since JAXB seems to be still used, but Java 11 compatibility was restored by #1925.

I'm still affected by this problem. As it seems to work in the mentioned pull request, maybe it's a problem with my small example project I just created with Gradle? I'm not really familiar with Maven.
A minimal project which causes this problem for me: [TiledLevelTest.zip](https://github.com/bjorn/tiled/files/4148764/TiledLevelTest.zip). I'm using Eclipse 2019-12. `gradlew eclipse` will set the project up for eclipse.

**Comment by bjorn** [comment]
@MinecraftPlaye Hmm, while this incompatibility problem is probably fixed, the version of libtiled on Maven Central has not been updated with those changes. Could that be causing problems? Or are you using libtiled-java from source?

**Comment by MinecraftPlaye** [comment]
> 
> 
> @MinecraftPlaye Hmm, while this incompatibility problem is probably fixed, the version of libtiled on Maven Central has not been updated with those changes. Could that be causing problems? Or are you using libtiled-java from source?

I'm using the version from Maven Central.

**Comment by MinecraftPlaye** [comment]
> Hmm, while this incompatibility problem is probably fixed, the version of libtiled on Maven Central has not been updated with those changes. Could that be causing problems?

Ok, after some time figuring out how Maven works I got this far with compiling the code from this repository's master branch: 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project libtiled: There are test failures.
```

**Comment by bjorn** [comment]
@MinecraftPlaye The version on Maven Central has now been updated. Could you verify whether this resolves your issue?

**Comment by MinecraftPlaye** [comment]
> 
> 
> @MinecraftPlaye The version on Maven Central has now been updated. Could you verify whether this resolves your issue (and #2052)?

Ok, I just tested it with version 1.2.3 from Maven Central. I'm not sure if this is intended, but without any modifications to my projects it does not work. Adding the same dependency from the maven script of libtiled to all my projects which depend on libtiled solves the problem (tested with the [TiledLevelTest.zip ](https://github.com/bjorn/tiled/files/4148764/TiledLevelTest.zip) from above)
```
implementation group: 'org.mapeditor', name: 'libtiled', version: '1.2.3'
// required by libtiled
implementation group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: '2.3.2'
```

**Comment by bjorn** [comment]
@mikepthomas Is there a dependency we could add somewhere to avoid users like @MinecraftPlaye needing to add this?

**Comment by mikepthomas** [comment]
https://github.com/bjorn/tiled/blob/master/util/java/libtiled-java/pom.xml#L151 This should add the dependencies for any version of Java over version 1.9... it seems to be working fine for tmxviewer-java fine however this is probably because it is a Maven project, I don’t have much experience with Gradle but my guess is that this profile is not being automatically enabled

**Comment by bjorn** [comment]
@mikepthomas Alright, thanks for the quick answer! 

@MinecraftPlaye Maybe you can figure out a way to make this work automatically also with Gradle? If not I guess it would be good to mention the need to add this dependency in the `README.md`.

**Comment by MinecraftPlaye** [comment]
> 
> 
> @mikepthomas Alright, thanks for the quick answer!
> 
> @MinecraftPlaye Maybe you can figure out a way to make this work automatically also with Gradle? If not I guess it would be good to mention the need to add this dependency in the `README.md`.

Alright, I looked into it and could not find anything which resolves this problem. There are a few open issues on Gradle with Maven POM files regarding transitive dependencies, but as far as my limited understanding of Gradle and Maven goes, those are not the cause for this problem.

I did however found this while looking up the Gradle documentation: [Gradle Module Metadata ](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-latest-specification.md). You could potentially provide this file alongside the POM file. In that case Gradle would ignore the POM file and use the Module Metadata file.

**Comment by bjorn** [comment]
@MinecraftPlaye Thanks for looking into it! If providing Gradle Module Metadata is a solution to this then I guess we'd be looking for somebody to maintain such a file. Or we can document the need to add this dependency for Gradle users.
