### ISSUE TITLE
Built in script editor

### ISSUE THREAD

**Issue by tylerhasman** [bjorn/tiled#2049]
I put javascript into objects to be executed by the game engine. This is mainly how I do scripting in my game. However, the string editor for tiled has no formatting so I often have to paste my scripts into a javascript beautifier so that I can read them better. It would be helpful if in the string editor there was a box to tick that would enable a simple line formatted or something.

**Comment by bjorn** [comment]
Hmm, did you consider using a file property instead and just using your preferred editor to edit your script files? Of course there could be some improvement to the multi-line text property editor, but it won't be able to compete with a dedicated text editor.
