### ISSUE TITLE
libtiled-java NullPointerException

### ISSUE THREAD

**Issue by MinecraftPlaye** [bjorn/tiled#2052]
Libtiled crashes with the following exception:

```java
java.lang.NullPointerException
	at tiled.io.TMXMapReader.unmarshalTileset(TMXMapReader.java:367)
	at tiled.io.TMXMapReader.buildMap(TMXMapReader.java:807)
	at tiled.io.TMXMapReader.unmarshal(TMXMapReader.java:848)
	at tiled.io.TMXMapReader.readMap(TMXMapReader.java:876)
	at theengine.fileio.LevelLoader.loadLevel(LevelLoader.java:26)
	at theengine.fileio.LevelLoader.loadLevel(LevelLoader.java:15)
```

```java
// the line which starts loading the level
LevelLoader.loadLevel("C:/Program Files/Tiled/examples/orthogonal-outside.tmx");
// the following path also crashes: C:\\Program Files\\Tiled\\examples\\orthogonal-outside.tmx

    public static Level loadLevel(String path) {
        return LevelLoader.loadLevel(Paths.get(path));
    }
    
    public static Level loadLevel(Path path) {
        TMXMapReader reader = new TMXMapReader();
        if(!reader.accept(path.toFile())) return null;
        
        System.out.println(path.toAbsolutePath().toString());
        
        Map map = null;
        try {
            map = reader.readMap(path.toAbsolutePath().toString());
        } catch (Exception e) {
            // Exception is thrown here!!!
            e.printStackTrace();
        }
```

**Using:**
Windows 10 64bit; 1803
Java 10 x64 (see #2048 as to why not Java 11) with Gradle 4.10.2
libtiled-java: 0.17
javax.xml.bind:jaxb-api:2.3.0
Eclipse 2018-09 (4.9.0)

Trying to use the version from Github instead also failed as I was not able due to missing classes (MapData for example).

**Comment by Ansury** [comment]
Just ran into the missing MapData class myself. File get deleted accidentally or something?

**Comment by Ansury** [comment]
Hmm. Found this commit from 6/20/2017 where a number of these files (MapData + others) suddenly appeared in code, but no *Data classes: 
_Refactor package names to org.mapeditor, **create model from xsd** and update version numbers to 1.0.1_ 

Guessing these *Data classes need to be generated somehow...

**Comment by mikepthomas** [comment]
Hi @Ansury, Yes the siles are generated from an XML schema during the build, I have just pushed a commit to one of my previous pull requests to support building with JDK versions 8 and above:
https://github.com/bjorn/tiled/pull/1925

I have also recently pushed a new version to Maven Central (https://search.maven.org/artifact/org.mapeditor/libtiled/1.0.2/jar) try that and let me know if that fixes the issue :)

**Comment by bjorn** [comment]
@Ansury Did you ever try the new version pushed by @mikepthomas, to see if this issue still exists?

**Comment by bjorn** [comment]
Whoops, maybe I asked the wrong person.

@MinecraftPlaye, did you ever try the 1.0.2 version of libtiled, to see if this issue still exists?

**Comment by MinecraftPlaye** [comment]
> 
> 
> Whoops, maybe I asked the wrong person.
> 
> @MinecraftPlaye, did you ever try the 1.0.2 version of libtiled, to see if this issue still exists?

Ah, thx for the reminder. I kind of forgot about this issue. I just tested it out by setting up a new minimal test project and ran into #2048 ([my comment there](https://github.com/bjorn/tiled/issues/2048#issuecomment-581486106)).

**Comment by MinecraftPlaye** [comment]
Version 1.2.3 from Maven Central resolves this problem.
