### ISSUE TITLE
Question: How to decode base64?

### ISSUE THREAD

**Issue by JuKu** [bjorn/tiled#2053]
How can i decode the base64 string between the <data encoding="base64"> ... </data> tags?

**Comment by Seanba** [comment]
Hi @JuKu. Under what conditions are trying to decode? For instance, if were decoding a base64 string in a C# application then I'd use `Convert.FromBase64String()`.

Depending on what tools or framework you're using this may be a better question for StackOverflow.

**Comment by bjorn** [comment]
Right, closing this since it's better to search for this online and include whatever programming language or framework you're using.

**Comment by JuKu** [comment]
@Seanba @bjorn The question is more what i have to do with the decoded base64 string.
Without base64 encoding there are xml tags, but with, there aren't any tags? Are there only the tileIDs?

**Comment by bjorn** [comment]
@JuKu The base64 encoding is used because the data is binary, which indeed consists only of 32-bit global tile IDs. See [this part of the documentation](https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#data) for details.

**Comment by JuKu** [comment]
Thanks! The junit tests have passed, so it think it work's now.
