### ISSUE TITLE
Add Template View menu option while editing tileset

### ISSUE THREAD

**Issue by marcelvdmade** [bjorn/tiled#2054]
When editing a tileset, you can use the Tile Collision editor to place objects on tiles. It also has the option to place a template. But Initially I closed the template view, and there is no menu option to open the template view again.

**Comment by bjorn** [comment]
I pushed a fix so it will be included in an eventual Tiled 1.2.2 release. Thanks for noticing!

To get it back without it being part of the "Views and Toolbars" menu, you can right-click somewhere on the tool bar or on the header of another dock widget. The Templates view is part of that context menu.
