### ISSUE TITLE
Templates don't update "tileset" when map has changed tileset ordering.

### ISSUE THREAD

**Issue by drakbar** [bjorn/tiled#2055]
I believe this is a bug, and sorry if this is a known issue.
I feel like this falls under #1723.

To reproduce:

1. Create a tileset (not embedded).
2. Create a template of a tile from the tileset that was just created.
3. Create a second arbitrary tileset.
4. **Place a tile from the newly create tileset on the map.**
5. Delete the first tileset. (the template on the map should disappear)
6. Insert that template into the map. (the tileset that it belongs to should be added back)
7. **Save the map**

When you inspect the template file along side the map file, you will notice that the `"firstgid"` fields are different.

Template file:
```
{ "object":
...
 "tileset":
    {
     "firstgid":1,
     "source":"dungeon_tiles.json"
    },
...
}
```

Map file:
```
{
...
 "tilesets":[
        {
         "firstgid":1,
         "source":"mountain_landscape.json"
        }, 
        {
         "firstgid":257,
         "source":"dungeon_tiles.json"
        }],
...
}

```
Format: json 1.2
Tiled Version: 1.2.1
OS: Windows 10

**Comment by bjorn** [comment]
Hmm, why do you consider this a bug? What is the buggy part? There is no reason why the `firstgid` attribute of a tileset referenced by the map should be the same as the `firstgid` attribute of the template's tileset (which will always be 1, since templates use at max one tileset).

Maybe the bug is that a tileset is added to the map even when placing a template instance, since actually the map will not reference this tileset directly unless you override the tile used by a tile object template instance (in which case the map should include a reference to the used tileset).

**Comment by drakbar** [comment]
> (which will always be 1, since templates use at max one tileset).

I just realized that this is what occurs. I guess I originally thought the `firstgid` of the template tileset would correlate to the tileset that was in the map. (i.e. the `firstgid` of the template tileset would mirror the `firstgid` of the map tileset of the same name) I most likely thought because why would it be there if it were always 1. 

> There is no reason why the firstgid attribute of a tileset referenced by the map should be the same as the firstgid attribute of the template's tileset

I agree with the idea that the template should maintain its generic property, mainly because then you have the ability to port the template from map to map. By coupling it to the `firstgid` in the map the template would cease having that aspect of being universal.  

However, unless Tiled uses the `firstgid` value from the template file, I see it as being extraneous to have it in the template file itself. If it is not the case that Tiled uses the `firstgid` from the template file, I feel like `tileset` should be reduced to a string value, instead of an object. Like so:
```
}
"object": ...,
"tileset":"dungeon_tiles.json",
"type":"template"
}
```

**Comment by bjorn** [comment]
> If it is not the case that Tiled uses the `firstgid` from the template file, I feel like `tileset` should be reduced to a string value, instead of an object. Like so:

That way of referring to a tileset would be inconsistent with the JSON map format. The consistency is used in Tiled to reuse the code responsible for loading tilesets and objects when reading maps and templates.

**Comment by drakbar** [comment]
>  The consistency is used in Tiled to reuse the code responsible for loading tilesets and objects when reading maps and templates.

Good enough for me. Closing this issue.
