### ISSUE TITLE
Copy File Path and Open Containing Folder do nothing

### ISSUE THREAD

**Issue by AndreYin** [bjorn/tiled#2059]
Hi there,
It seems that when you have a tileset open, the right click options in it's tab don't work properly.

If you click "Copy File Path", it copies nothing to the clipboard, but it does erase anything you had on your clipboard before.

If you click "Open Containing Folder", it just opens the desktop folder, not the folder where the tileset image is located.

Both of these are in Windows 10.

**Comment by bjorn** [comment]
Thanks for noticing! Fix will be in Tiled 1.2.2, which makes these actions use the file name of the map in which the tileset is embedded.
