### ISSUE TITLE
Hotkey to disable snap to grid not working?

### ISSUE THREAD

**Issue by X-Ray-Jin** [bjorn/tiled#2061]
I remember times when it was possible to hold ALT key, I think, to temporarily disable snap to grid when moving or placing objects. Have they been removed or is that a bug? It was a really nice feature I think.

**Comment by bjorn** [comment]
It's the Ctrl key, except when resizing, then it is Alt (because while resizing, Ctrl means to keep the aspect ratio). Does it not work for you?

**Comment by X-Ray-Jin** [comment]
Some testing showed it does work kind of. The issue is we are using the fine grid all the time. In this case it seems it snaps to the full grid instead of the fine. Not sure how others think about that for me that is kind of weird behaviour. I think pressing a button should always have the same effect, for convenience. Not even sure if it is that useful this way. I mean if you are using fine grid you obviously don't use the full grid for detail reason...so why would you want to reduce that all over sudden. Despite the fact that you can easily snap to full grid with fine grid too. However if it is intentionally I wonder if we could have a hotkey for unsnapping temporarily in addition as it is really useful, I think.

**Comment by bjorn** [comment]
@X-Ray-Jin Sorry for the slow response on this one!

**Comment by X-Ray-Jin** [comment]
@bjorn :+1:
No worries I am glad that you have found the time to make it now. Thank you.
