### ISSUE TITLE
Update Check Doesn't Find v1.2.2

### ISSUE THREAD

**Issue by AntumDeluge** [bjorn/tiled#2063]
Using version 1.2.1 (Windows 10 64-bit) update check doesn't find current version 1.2.2:
![tiled_update_1 2 2](https://user-images.githubusercontent.com/3631473/52020158-24603780-24a5-11e9-8581-6bab0ed1b645.png)

Not sure, maybe this is fixed in 1.2.2?

**Comment by bjorn** [comment]
> Not sure, maybe this is fixed in 1.2.2?

Haha, very funny! :-)

Actually I need to manually update some files for that update system to notice the new release, and it really got too late yesterday, as it usually does when I push a new release.

I'm considering to replace the update system entirely by simply an icon that displays when there is a new release, which takes you to the release notes when clicked, from where you can click to download the new version. The currently employed system really does nothing more than automatically downloading and executing the installer, which is really not worth the extra maintenance (also, it's different for Windows than for macOS, and doesn't exist for Linux). Finally, for entirely painless and automated updates, you can install Tiled through the [itch.io app](https://itch.io/app).

**Comment by bjorn** [comment]
Closing this issue since the Windows appcast files are updated to Tiled 1.2.3 in the meantime.

macOS is still on 1.2.2, but I'll update that file now.
