### ISSUE TITLE
Changing maps in World shouldn't reset tileset and layer

### ISSUE THREAD

**Issue by RainingChain** [bjorn/tiled#2065]
I have a large world with many maps. They all share the same tilesets and layers. Let say I'm adding trees from tileset 2 on layer TreeLayer on the first map. Now, I want to do the same on another map. 

When I click the other map, the tileset is reset to tileset 1 and the layer is reset to something else. This forces me to change back the tileset and layer everytime. This is especially annoying because I sometime forget to change the layer and I start drawing on the wrong layer by mistake. 

Wanted behaviour:
When clicking on a new map in the world:
- If one of the layers on the new map as the same name as the current layer of the old map, change the layer to this one.
- If the new map has the same tileset as the current tileset of the old map, change the tileset to this one.

Thanks

**Comment by bjorn** [comment]
That makes total sense, thanks for opening such a detailed issue about it!

**Comment by bjorn** [comment]
@RainingChain I plan to push a new development snapshot next week that will include this improvement.
