### ISSUE TITLE
Freeze when locating missing tilesheet for tbin

### ISSUE THREAD

**Issue by Pathoschild** [bjorn/tiled#2068]
Tiled freezes when you locate a missing tilesheet for Stardew Valley `.tbin` maps.

## Repro steps
1. Download this map + tilesheets: [repro.zip](https://github.com/bjorn/tiled/files/2826316/repro.zip).
2. Open the `FarmCave.tbin` file in Tiled. It will report a missing `mine` file:
   > ![](https://user-images.githubusercontent.com/230581/52186134-61a12e00-27f3-11e9-9e20-ae1174c4ba52.png)
3. Double-click a tileset to open it:
   > ![](https://user-images.githubusercontent.com/230581/52186415-3a4b6080-27f5-11e9-9d42-c6cf6bf60087.png)
4. Double-click a file to open the choose-file dialogue:
   > ![](https://user-images.githubusercontent.com/230581/52186457-6ff04980-27f5-11e9-9d65-d3b83090c824.png)
5. Choose the `mine.png` file and click 'open'.
6. Tiled freezes indefinitely, and task manager shows it quickly consuming all available RAM (25+ GB).
   > ![](https://user-images.githubusercontent.com/230581/52186473-8b5b5480-27f5-11e9-9c06-2b294677fdd7.png)

## Environment
Reproduced on Windows 10 (Home 1809 build 17763.253) and multiple 64-bit Tiled versions from snapshot 2018.01.01 to 1.2.2.

**Comment by Dawilly** [comment]
Replicating the steps provided causes Tiled for freeze indefinitely for me as well. However, repeating the same procedure with a .tmx map in place of a .tbin map does not trigger the bug. So it appears to be .tbin exclusive.

**Comment by bjorn** [comment]
This only affected maps loaded through the tBIN plugin due to the way it was adding missing tiles to still be able to load the tile properties. Will be fixed in an eventual Tiled 1.2.3 or the next development snapshot (planned for tomorrow).

Thanks for the report!
