### ISSUE TITLE
Allow map nicknames in world regex

### ISSUE THREAD

**Issue by tomcashman** [bjorn/tiled#2071]
I'm trying to allow nicknames in the filenames for world maps, e.g. 0.0-petes_home.tmx

On latest Tiled version, I've been trying this regex unsuccessfully. Perhaps I'm doing something wrong?

```
{
    "patterns": [
        {
            "regexp": "(\\-?\\d+)\\.(\\-?\\d+)(\\-.+)?\\.tmx",
            "multiplierX": 640,
            "multiplierY": 384,
            "offsetX": 0,
            "offsetY": 0
        }
    ],
    "type": "world"
}
```

**Comment by bjorn** [comment]
You shouldn't be capturing the nickname part of the map.

Actually the code is checking for this, but for some reason I forgot to make these actually report as errors and instead they're printing out to the console:

https://github.com/bjorn/tiled/blob/f007042af47b333b4d57a8e2fe8e2481b58c0a55/src/libtiled/worldmanager.cpp#L141-L142

**Comment by tomcashman** [comment]
My understanding of regex was incorrect then - originally I had thought () was only used for grouping XD Thanks Bjorn! :)
