### ISSUE TITLE
Add the Castle Game Engine to frameworks list that support tmx format

### ISSUE THREAD

**Issue by tsr8** [bjorn/tiled#2074]
Add please a Castle Game Engine (Object Pascal language) to frameworks list.
https://castle-engine.io

**Comment by editgames-owner** [comment]
+1,+2000

**Comment by bjorn** [comment]
Alright, added to the list! I've also added it to https://www.mapeditor.org/libraries, which is a WIP replacement for this page in the documentation that I hope will be more consistent and easier to contribute to for others.
