### ISSUE TITLE
Missing XML Tile Layer Format under New Map

### ISSUE THREAD

**Issue by uweenukr** [bjorn/tiled#2078]
Since the option is missing in the drop down you must first create the map then change it to XML. Could this option be added to the dropdown?

Current options when making New Map:
-Base64 zlib compressed
-Base64 uncompressed
-CSV

Current options when editing the created Map properties:
**-XML**
**-Base64 gzip compressed**
-Base64 zlib compressed
-Base64 uncompressed
-CSV

Thank you!

**Comment by bjorn** [comment]
Those options aren't there because they are deprecated. Would it be possible for you to switch to one of the non-deprecated formats instead?

**Comment by uweenukr** [comment]
I know it's not your responsibility for this. But I'm trying to use XML for a Unity asset I purchased. It's missing many other Tiled features so I think I'll just stop using it after this reply. Thank you for the response. This can be closed.

**Comment by Seanba** [comment]
FWIW, @uweenukr. SuperTiled2Unity is free and handles all layer formats.

**Comment by uweenukr** [comment]
Do you know if it supports Map/Layer/Tile properties? And does it import into the native Unity Tilempa Grid?

**Comment by Seanba** [comment]
Yes to both questions. In full disclosure: I'm the author of SuperTiled2Unity.
