### ISSUE TITLE
%mapdir variable for external commands?

### ISSUE THREAD

**Issue by winstonwolff** [bjorn/tiled#208]
Would it be difficult to add a %mapdir variable to the external shell commands? That way we can run commands that are in the same directory as the .tmx file. E.g. if my map is in: ~/maps/foo.tmx and there is a script to run in the same folder ~/maps/script.py, then I can have Tiled run "%mapdir/script.py %mapfile"

**Comment by bjorn** [comment]
@ketanhwr reported the quotes did not actually cause problems in his tests, so the `%mappath` variable added by #1347 has resolved this issue.
