### ISSUE TITLE
Tiled crashes when creating a wang color without a wang set

### ISSUE THREAD

**Issue by BorisTheBrave** [bjorn/tiled#2083]
Steps to reproduce:
* Create a new tileset
* Open the wang tab, and switch to the colors sub-tab
* Press "Add Edge Color" or "Add Corner Color"

Behavior:
 * Tiled immediately crashes

Expected Behaviour
 * These buttons should be greyed out or the user prompted to create a wang set first.

Tested in Tiled 1.2.2, Windows.

**Comment by bjorn** [comment]
Thanks for the report! Will be fixed in Tiled 1.2.3.
