### ISSUE TITLE
Document external tilesets in JSON maps

### ISSUE THREAD

**Issue by TheRamenChef** [bjorn/tiled#2093]
They clearly work in JSON maps, but they aren't documented.

**Comment by DanTup** [comment]
I noticed this too and opened https://github.com/bjorn/tiled/pull/2114?

Doesn't look like the docs website has been generated with the updated info though, not sure if that's a manual job?

**Comment by bjorn** [comment]
> Doesn't look like the docs website has been generated with the updated info though, not sure if that's a manual job?

By default it shows the _stable_ version of the docs, which I believe is based on the last tagged release. Changes submitted to the "master" branch are available as the [_latest_ version of the docs](https://doc.mapeditor.org/en/latest/reference/json-map-format/#tileset).

**Comment by DanTup** [comment]
Aha! Good to know, thanks!
