### ISSUE TITLE
Tile collision editor - tiles limited to size of grid

### ISSUE THREAD

**Issue by lapamplemousse** [bjorn/tiled#2094]
In the tile editor I cannot make precise collision properties. for example, in the polygone tool I can only click in the corners and make a complete square of the grid. My grid size is 32px, even if I use the circle editor it will select the entire 32px grid square. I am using version 1.2.3.

![grab](https://user-images.githubusercontent.com/49071686/55243777-cbf4ae80-5237-11e9-814e-eca633a70633.JPG)

**Comment by lapamplemousse** [comment]
I was not holding ctrl while while using the tools

**Comment by bjorn** [comment]
> I was not holding ctrl while while using the tools

Right, or, if you don't want to hold Control all the time, you can disable the "Snap to Grid" option, or set it to snap to a finer grid or to pixels only. :-)

**Comment by lapamplemousse** [comment]
great thanks
