### ISSUE TITLE
Allow terrain tile rotation

### ISSUE THREAD

**Issue by tomcashman** [bjorn/tiled#2095]
Currently we have a lot of corner tiles in our tilesets that can be rotated but there is no way to mark them as rotatable when defining a terrain (?)

**Comment by bjorn** [comment]
Yeah, there is currently no way to do that. You'll need to put rotated versions of those tiles in your tileset to use it with the terrain tool.

Thanks for opening an issue about it!

**Comment by bjorn** [comment]
The Terrain Brush has been replaced by the Wang Brush on latest `master`, after the Wang Brush was improved so that it can do everything terrains did and more (see #2888).

Support for rotation isn't in yet, but it's being worked on and covered by issue #2833, so I'm closing this one. :-)
