### ISSUE TITLE
Corrupted map crashes Tiled on opening.

### ISSUE THREAD

**Issue by gnFur** [bjorn/tiled#2100]
I was working on my game, everything was (mostly) fine, and then suddenly Tiled decided to corrupt my map file - no idea, what caused it. Now it crashes Tiled every time I try to open it. Weird thing is -- Tiled crashes only if I open the file by double clicking .tmx file in Explorer. If I open file from Tiled itself with the button Open File, map loads normally.
Corrupt map:
[corrupt_map.zip](https://github.com/bjorn/tiled/files/3049337/corrupt_map.zip)

**Comment by seanb-22ct** [comment]
FWIW, I'm able to open your map in Tiled by double-clicking the file in Windows Explorer. My guess is that your file associations with Windows is trying to open a version of Tiled that is different than the one you or normally using. I'd check on that.

(I'm using Tiled 1.2.2 btw)

**Comment by gnFur** [comment]
The map was created today. I weren't updating anything. And... I've just checked and it works again for me too. No idea what's even happened. ._.

**Comment by bjorn** [comment]
I've also tested this on Linux and didn't crash. I'll close this issue since without further information there is nothing I can do to fix whatever problem you were running into. Please let us know if you ever run into it again!
