### ISSUE TITLE
Tilemap terrain bugs

### ISSUE THREAD

**Issue by Tokenyet** [bjorn/tiled#2104]
I record a video for two bugs: [Links](https://youtu.be/WuE-_qnEgek)

1. One the start of video, Terrain could not be used in the specified layer (Or I miss something?)
 2. <s>The last is, Animation tiles couldn't define terrain properly, even If It's as equal as unanimated terrain.</s>

Sorry the second is wrong animation definition.

If there is any unclear information, please let me know.

For now, If I need to correct the first bug, I need to add the opposite of origin terrain, and draw the grass properly, the everything works as expected, but this could cause animated tile bug on clear layer (as the first bug, again).

**Comment by Tokenyet** [comment]
Sorry, the first bug is your final words in the [documentation](https://doc.mapeditor.org/en/stable/manual/using-the-terrain-tool/). I miss It!
Please close It :(

> Currently the tool requires all terrain types to be part of the same tileset. You can have multiple tilesets with terrain in your map, but the tool can’t perform automatic transitions from a terrain from one tileset to a terrain in another tileset. This usually means you may have to combine several tiles into one image.

**Comment by bjorn** [comment]
Hey @Tokenyet, if there is nothing to fix after all feel free to close this issue. :-)

For sure it would be nice if we could support transitions between terrains from different tilesets. I imagine the tool could go through all used tilesets and combine the terrains by name.
