### ISSUE TITLE
wrong display of perspective in editor for iso map (linux)

### ISSUE THREAD

**Issue by piark** [bjorn/tiled#2105]
Have a problem, ISO perspective in map is show as flat top view, not a real iso perspective.
see screen capture and tutorial capture.
Result, cannot place some iso elements, and cannot place bloc of elements (multi select)

WRONG:
![image](https://user-images.githubusercontent.com/49122108/55792077-24417100-5ac0-11e9-912f-ac298cdf5589.png)

WRONG (multi select):
![image](https://user-images.githubusercontent.com/49122108/55792115-36231400-5ac0-11e9-8e53-929acf7f8247.png)

CORRECT:
![image](https://user-images.githubusercontent.com/49122108/55792148-4d620180-5ac0-11e9-8fc6-5288988dc60d.png)

**Comment by bjorn** [comment]
You need to adjust the tile size properties of the map to make your grid fit your tile size. At the moment it is too small, and too "pointy". Make your tiles larger and try setting the height to only half the width.

Place a few tiles before changing the values, to make it easier to find the right grid size for your tiles. You'll see the map view change as you change the tile size values.

**Comment by piark** [comment]
Yes,
ok, it's work.
But i think, not really intuitive, because the map settings must be do 128x64 for a 32x32 map.
ok with new settings.
thanks.
