### ISSUE TITLE
Crash when loading .tbin map with missing tilesheet in some cases

### ISSUE THREAD

**Issue by Pathoschild** [bjorn/tiled#2106]
When you open a Stardew Valley `.tbin` map, some missing tilesheets cause a crash to desktop before it's done opening. This only happens for some tilesheets, but it's consistent when it does happen.

Let me know if you need any other info!

## Repro steps
(See optional [video showing the issue](https://github.com/bjorn/tiled/files/3074247/repro.zip).)

1. Download [this map + tilesheets](https://github.com/bjorn/tiled/files/3074114/repro.zip).
2. Enable the tbin plugin in Tiled.
3. Open `SmallBeachFarm.tbin`. It should load fine with no missing tilesheets.
4. Exit Tiled.
5. Delete or rename `spring_beach.png` so Tiled doesn't find it.
6. Open `SmallBeachFarm.tbin`. Tiled crashes to desktop.

Behavior for that map's tilesheets:

tilesheet          | behavior if not found
:----------------- | :--------------------
`tilesheets/*`     | ✓ missing-tilesheet dialogue shown
`paths.png`        | ✓ missing-tilesheet dialogue shown
`spring_beach.png` | ✘ crash to desktop
`spring_outdoorsTilesheet.png` | ✘ crash to desktop
`spring_town.png`  | ✓ missing-tilesheet dialogue shown

## Environment
Reproduced on Windows 10 (Home 1809 build 17763.437) with Tiled 1.2.3 and Tiled snapshot 2019.04.03 (all 64-bit). Several other Stardew Valley modders ran into the issue, so it's not specific to my computer (though I only tested these repro steps on my computer).

## Event viewer data
The Windows event viewer shows this info for the Tiled crash (where exception code 0xc0000005 is apparently Access Violation).
```
Faulting application name: tiled.exe, version: 1.0.0.0, time stamp: 0x5c87c76d
Faulting module name: tiled.dll, version: 0.0.0.0, time stamp: 0x5c87c727
Exception code: 0xc0000005
Fault offset: 0x0000000000047736
Faulting process id: 0x359c
Faulting application start time: 0x01d4f14b3d14679f
Faulting application path: C:\Program Files\Tiled\tiled.exe
Faulting module path: C:\Program Files\Tiled\tiled.dll
Report Id: 84697a4e-4642-4e00-954d-7445056f273a
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by bjorn** [comment]
This only happens with some maps because it's a crash while reading animated tiles from a tileset for which the image failed to load. I'll look into fixing this soon.

Thanks for the detailed report and the files for reproducing this!
