### ISSUE TITLE
Add ability to select specific object on right click

### ISSUE THREAD

**Issue by Niphyr** [bjorn/tiled#211]
It would be nice when you right click on an object, part of the context menu gives you an option to select specific objects under where you have clicked. I'm not decided on if it should be specific only to the layer you're working on, or all objects.

I'm not really sure how to better word it, let me know if it's too vague and I will try to explain it further but it stems from my issue of having multiple objects in the one location, sometimes of the same shape and have to move them around to select the right one.
I am mostly using the "Insert Tile" object to place semi-transparent tiles into the object layer.

**Comment by bjorn** [comment]
This is now covered by the following:

* When clicking to select an object, holding the Alt modifier allows to iterate the selection over overlapping objects.

* When right-clicking while holding Alt, the context menu will show the list of objects at the target location.

This is documented at http://doc.mapeditor.org/en/latest/manual/objects/#selecting-and-deselecting
