### ISSUE TITLE
Add a "Point" type to JSON spec

### ISSUE THREAD

**Issue by DanTup** [bjorn/tiled#2116]
In the JSON spec there are some fields with descriptions like:

> A list of x,y coordinates in pixels

This is slightly ambiguous (for ex., it's not clear if those values are `double`s or `int`s - since other types seem to vary) and also means any code-gen needs to handle this specifically.

I think it might make sense to change these to `` Array of :ref:`Point <json-point>` `` and define a `Point` type?

**Comment by bjorn** [comment]
Yeah, that definitely makes sense. I did the same for the "Property" object already, and it should be done here too.

**Comment by DanTup** [comment]
Thanks! 👍
