### ISSUE TITLE
Tilesets view needs dynamic wrapping mode

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#2127]
Especially for image collection tilesets, the tilesets view needs a mode where the number of columns is dynamically adjusted to the size of the view. Currently, the default column count for such tilesets is hardcoded to 5, and it can be adjusted in the tileset properties.

It would be nice if this was implemented in a way that also enabled this as an option for tilesets based on a tileset image, even though in that case it's not generally as useful.

For the new mode, consider also to support dynamic sorting of the tiles (#1856) and displaying thumbnails to unify tile sizes (#1241).

**Comment by hepari** [comment]
I'm really sorry if this comes off as nagging, but I'd love to know if this feature being worked on :)
Especially the dynamic sorting. I'm still stuck with the old version due to the lack of it on the new versions (cries)

**Comment by bjorn** [comment]
@hepari No problem about the reminder. Let's put this on the Roadmap for Tiled 1.3. Maybe I'll find some time for it.

**Comment by hepari** [comment]
That would be great! Thank you very much :)
