### ISSUE TITLE
'tiled.Tiled.Tile' object has no attribute 'type'

### ISSUE THREAD

**Issue by sverx** [bjorn/tiled#2140]
I'm getting this while coding a simple Python exporter for Tilesets types:

```
    if len(tileMap.tilesetAt(t).data().tileAt(i).type())==0:
AttributeError: 'tiled.Tiled.Tile' object has no attribute 'type'
```
code is very simple as in

```
from tiled import *

class Example(Plugin):
    @classmethod
    def nameFilter(cls):
        return "my files (*.typedata)"

    @classmethod
    def shortName(cls):
        return "My data"

    @classmethod
    def write(cls, tileMap, fileName):
        fileHandle = open(fileName, 'wb')
        for t in range(tileMap.tilesetCount()):
            for i in range(tileMap.tilesetAt(t).data().tileCount()):
                # fileHandle.write(bytes([tileMap.tilesetAt(t).data().tileAt(i).id()]))
                if len(tileMap.tilesetAt(t).data().tileAt(i).type())==0:
                    fileHandle.write(bytes([0]))
                else:
                    fileHandle.write(bytes([ord(tileMap.tilesetAt(t).data().tileAt(i).type()[0].upper())+1-ord('A')]))

        fileHandle.close()
        return True
```

I can properly access id() ... but for some reason not type().

What am I doing wrong now? :|

**Comment by bjorn** [comment]
You hit a small hole in the API. It was fixed by #2124, but that change went to the `master` branch so the method is not available in Tiled 1.2.4. Please install a development snapshot if you need this functionality.

The snapshots also feature [JavaScript custom format support](https://doc.mapeditor.org/en/latest/reference/scripting/#script-registermapformat), though right now it doesn't support binary formats yet.

**Comment by sverx** [comment]
Indeed it works with a development snapshot (but not in any of the Ubuntu's snaps as the libpython plugin isn't even present there in the list of the available plugins...)
Thanks!

**Comment by bjorn** [comment]
> Indeed it works with a development snapshot (but not in any of the Ubuntu's snaps as the libpython plugin isn't even present there in the list of the available plugins...)

Alright, I've opened issue #2142 about the missing Python support in the snap.
