### ISSUE TITLE
Why are properties no longer keyed by name in JSON format?

### ISSUE THREAD

**Issue by hwaterke** [bjorn/tiled#2148]
They used to be e.g.

```json
"properties": {
  "text": "hello"
},
"propertytypes": {
  "text": "string"
},
```

But they are now stored as an array which makes it a bit more annoying to check in code (you have to loop)

```json
"properties":[
  {
    "name":"text",
    "type":"string",
    "value":"hello"
  }
],
```

Any reason for this particular change?

**Comment by bjorn** [comment]
See #1868. Though, also see https://github.com/bjorn/tiled/issues/2034#issuecomment-439184633 and finally https://github.com/bjorn/tiled/issues/2058#issuecomment-458975579.
