### ISSUE TITLE
Configurable keyboard shortcuts

### ISSUE THREAD

**Issue by Gornova** [bjorn/tiled#215]
I'd like to see a global configuration for tiled shortcuts, in preferences menus, a simple list with two columns
- shortcuts name
- shortcuts 

for example

Open a new file | CTRL-n 
Refresh tileset | CTR-R

and so on...

a bonus: a simple export in csv format and import from csv

**Comment by bjorn** [comment]
Requested [on the forum](https://discourse.mapeditor.org/t/can-you-remap-keys/3260).

**Comment by bjorn** [comment]
Made a bit of progress on the UI for this today. :-)

![Screenshot from 2019-04-19 17-12-55](https://user-images.githubusercontent.com/531764/56445078-b9800900-62fb-11e9-83d8-3caf7352046e.png)
