### ISSUE TITLE
When using a world, can't select the map immediately to the right of current map

### ISSUE THREAD

**Issue by gauauu** [bjorn/tiled#2163]
To reproduce:  Load a world with adjacent maps. Click to select a map. Then mouse-over or click the map immediately adjacent to the right of the current map. The new map will not highlight or be selected.

This started in commit c9047b4f236fc68a06d619f58dc8aa6f4ffd1d48 - it has something to do with the new map bounding rectangle logic. If I revert the changes to `updateBoundingRect` from that commit, the problem goes away. 

Thanks!

**Comment by bjorn** [comment]
Ah, forgot to close this. This was fixed in change 651c3d0b39d71780a8f1d9aecb6bb801c44ccdbf.
