### ISSUE TITLE
libtiled TMXMapReader loading maps from resources

### ISSUE THREAD

**Issue by mschroeder-github** [bjorn/tiled#2165]
I would like to load `*.tmx` files from maven's `src/main/resources` (java resources) instead of files on the disk. That is why I modified the `TMXMapReader` (version 1.0.2) code in my game engine project: https://github.com/mschroeder-github/jasgl/blob/master/jasgl/src/main/java/com/github/mschroeder/github/jasgl/CustomTMXMapReader.java
The images will also be loaded from resources. You may would like to add this feature also in your libtiled code. On some lines I added the check if `fromResources` is true.

**Comment by bjorn** [comment]
> You may would like to add this feature also in your libtiled code. On some lines I added the check if `fromResources` is true.

If this can be added without breaking leading from non-resources files, please do open a pull request so me and possibly other people knowing Java can review the changes!

**Comment by mschroeder-github** [comment]
Thanks. I created a pull request: https://github.com/bjorn/tiled/pull/2170
