### ISSUE TITLE
on OSX Tiled 2019.07.24 not starts  

### ISSUE THREAD

**Issue by justgook** [bjorn/tiled#2174]
macOS - 10.14.6 (18G84)

```
dyld: Library not loaded: /usr/local/lib/libzstd.1.dylib
  Referenced from: /Applications/Tiled.app/Contents/Frameworks/libtiled.dylib
  Reason: image not found
```

**Comment by bjorn** [comment]
@Oipo Ohoh, seems like we're not done with this yet...

**Comment by Oipo** [comment]
@bjorn Hrm, that's a pity. It's probably the same thing as on windows tho: travis.yml should be modified to build static only and see if it still links zstd. If not, then there's the culprit.

As it happens, I don't have time to look at it today.
