### ISSUE TITLE
How can I change compress status when export to lua via CLI

### ISSUE THREAD

**Issue by findstr** [bjorn/tiled#2176]
When use CLI to automatic exporting, how can i modify the tmx to uncompressed.

At first, I try to use 'gunzip' to uncompress, then I failed. 

So, is there other way to get around this problem? 

Thanks for point me.

**Comment by bjorn** [comment]
Hmm, at the moment changing the layer data format requires opening the map in Tiled, changing it in the Map Properties and then saving the map again. There is now way to change it as part of exporting a map to Lua.

So right now if you want uncompressed Lua export, then I'd suggest saving your TMX files uncompressed as well.

**Comment by findstr** [comment]
Maybe Tiled CLI can add one interface to modify the Map Properties and output to stdout.

If so, the problem can be solved by this: `tiled --compress-method="none" | tiled --export-maps ...`. 

Expecting...

**Comment by bjorn** [comment]
There's virtually no limit to the amount of options that could be added. Hence I think it may be better to extend the support for scripting (#949) to include running a particular script from the command-line. The script could then open the map, change the compression method and export it somewhere.

That said, currently the scripting relies very much on the UI being available, so it may take some effort to make it available without UI. Or we could in this case simply keep the main window hidden.
