### ISSUE TITLE
Zstandard compression data is invalid.

### ISSUE THREAD

**Issue by sgaxr** [bjorn/tiled#2178]
When saving a map with the zstd compression, it appears to not be saving correctly (or, at least not on my system).

My system: Ubuntu 18.04
Tiled version: 2019.07.31

Here are the simple steps to reproduce the issue for me:

1. Save any map (or create a new one) with zstandard compression.
2. Close tiled
3. Try to open it again.

Screenshot of the error when trying to open the file (brand new, empty map):
![image](https://user-images.githubusercontent.com/43509355/62622197-9db46900-b8d2-11e9-876b-45d8d1dc1046.png)

Running tiled in the console shows this error message:
> error decoding: Src size incorrect

I tried decompressing myself in ruby using a few different zstd wrappers, and they all gave a variation of the same error:
> error decompressing: Unknown frame descriptor

I also tried using the zstd command (zstd -V = `*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***`) and I got:
> unsupported format

This is potentially a pretty dangerous bug (if it is a bug and not just something wrong with my system setup), as it corrupts the data of the tiled map and is now possibly unrecoverable.

**Comment by bjorn** [comment]
Hmm, I believe I did test it but I may have missed to test the latest version. Indeed this is a pretty serious issue.

@alphaonex86, @Oipo: Did either of you experience issues loading maps saved with Zstandard compression?

**Comment by alphaonex86** [comment]
@bjorn with my original version no, I use it dailly. I look the git version to look what's happens

**Comment by alphaonex86** [comment]
@sgaxr where do you have this version?

**Comment by bjorn** [comment]
@alphaonex86 Tiled 2019.07.31 is the latest "snapshot" version, available at https://thorbjorn.itch.io/tiled.

**Comment by alphaonex86** [comment]
Hi,
I confirm this problem. My original zstd file can be open by this version.
But the corruption is at saving, zstd data is well present but with extra data concatenated at the end. I presume it's bug at compression output size or base64 size.

**Comment by alphaonex86** [comment]
https://github.com/bjorn/tiled/blob/master/src/libtiled/compression.cpp#L220
After this line, missing:
out.resize(cSize);

**Comment by alphaonex86** [comment]
@bjorn https://github.com/bjorn/tiled/blob/master/src/libtiled/compression.cpp#L220
After this line, missing:
out.resize(cSize);

**Comment by Oipo** [comment]
Hmm, the maps I've made miraculously avoid this bug. But good catch!

**Comment by sgaxr** [comment]
Wow, you guys tracked that down pretty fast. You all are the best, thanks!
