### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [bjorn/tiled#2180]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the function “QtButtonPropertyBrowserPrivate::propertyRemoved”](https://github.com/bjorn/tiled/blob/99e874e55069067dd9347815558e6ff550249212/src/qtpropertybrowser/src/qtbuttonpropertybrowser.cpp#L359 "Update candidate").

**Comment by bjorn** [comment]
Yeah, I know these checks aren't necessary, but this is 3rd party code. If you want to help remove it, please open a review to [change the code here](https://codereview.qt-project.org/gitweb?p=qt-solutions/qt-solutions.git;a=blob;f=qtpropertybrowser/src/qtbuttonpropertybrowser.cpp;h=293fbf6bfdb63d38ed9f7448f29104ec976e721b;hb=HEAD#l359).

You'd need to follow the [Qt Contribution Guidelines](https://wiki.qt.io/Qt_Contribution_Guidelines).

**Comment by elfring** [comment]
I am curious then if [the bundled software component will ever be improved another bit](https://codereview.qt-project.org/gitweb?p=qt/qttools.git;a=blob;f=src/shared/qtpropertybrowser/qtbuttonpropertybrowser.cpp;hb=a690022b7e56b2e36a95ef22b854af4c82c5fdc8#l328 "Update candidate: QtButtonPropertyBrowserPrivate::propertyRemoved()").

**Comment by bjorn** [comment]
@elfring That would depend on whether it is worth the effort. Regarding the removal of the unnecessary null pointer checks, since they make no difference at all* I doubt somebody else will do it.

*) They are just a few extra lines, which [GCC optimizes away at -O1 already](https://gcc.godbolt.org/z/eoGhYN).

**Comment by elfring** [comment]
I am also curious if [a development tool like “clang-tidy” will be used for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks") in affected class libraries.

**Comment by bjorn** [comment]
I'm sure they've already used such tools extensively. At least I know they've used it for Qt Creator sources and support for it is also built into Qt Creator. Of course, they made not have run that particular check and they made not have cared to run them on the Qt Solutions project yet. Are you interested in doing this?

**Comment by elfring** [comment]
Other programmers can pick such an adjustment opportunity also up.
They might get more software development attention (than me).

**Comment by bjorn** [comment]
You're right, but it's a matter of priorities. I was asking you because you brought it up.
