### ISSUE TITLE
Inconsistent encoding of color alpha

### ISSUE THREAD

**Issue by Phlosioneer** [bjorn/tiled#2192]
When a color is specified, sometimes the alpha value is omitted. However, the default value for the alpha channel varies based on context.

For example: if alpha is not specified in a `backgroundcolor` attribute of a `map` tag, then it defaults to 0 (opaque). However, if alpha is not specified in a `transparentcolor` attribute of an `image` tag, then it defaults to 255 (transparent).

This is a nightmare for parsing the colors correctly. A function that tries to parse a color from a tiled property needs to know what attribute in which tag is being parsed.

Edit: Additionally, the documentation doesn't say what the defaults are for various color attributes, so if nothing else, the documentation needs to be clearer.

**Comment by Phlosioneer** [comment]
Actually, I got my alphas backwards. Sorry!

**Comment by bjorn** [comment]
Right, when omitted, alpha always defaults to 255 (opaque). :-)

> Edit: Additionally, the documentation doesn't say what the defaults are for various color attributes, so if nothing else, the documentation needs to be clearer.

I believe none of the color values have a default. When unspecified, the color is simply invalid and the editor will choose a default based on context (like, map or tileset background color then comes from the theme, while for a transparent color it is then not used).
