### ISSUE TITLE
Crash when opening many files over the course of a single session

### ISSUE THREAD

**Issue by tdeeb** [bjorn/tiled#2195]
Tiled crashes consistently when I load many maps (~15) over the course of a single session. I always have about 6-7 maps open at all times, and I open new maps to modify them then close the maps when I'm done. It seems to happen more often when I load more maps at once through the file menu. I suspect there's might be a memory issue somewhere. All the maps have the same embedded tileset and the same types of objects in them, with no terrain or collisions on the tilesets.

More Info:
- Windows 10 64-bit
- Tiled 1.2.4
- Hardware acceleration is disabled
- Safe writing of files is disabled

 I can provide more information if needed.

**Comment by bjorn** [comment]
Hmm, do you see memory consumption going up until the crash happens?

For such crashes usually the quickest way to find out what's going on is to reproduce them while having a debugger attached. Would you be able to compile Tiled yourself and run it in the debugger from Qt Creator?

**Comment by tdeeb** [comment]
I'll look into doing that later this week.

**Comment by tdeeb** [comment]
I just tried it out, and I'm not getting this issue in a debug build using the latest code from develop. I've been working normally in this version for over 25 maps at this point and no crashes. Opening a lot of maps at once also does not cause a crash.

**Comment by tdeeb** [comment]
When I switched back to the 1.2.4 afterwards, I got the crashes again. Something on master looks to have fixed it, so I'll test again with the next stable release. Thank you!

**Comment by bjorn** [comment]
@tdeeb Thank you for testing! If you want to help making sure it's really fixed, it would be great if you could checkout `v1.2.4` tag, and run that in a debugger to see if you can reproduce the issue. If you can, we may also know what was broken and if you can't, we'll know that maybe the issue is somewhere else.

Also, it may still be worth doing a 1.2.5 release that fixes the particular issue you're running into.

**Comment by tdeeb** [comment]
Will do later; good point!

**Comment by tdeeb** [comment]
I unfortunately can't get it to crash in the debugger. I noticed that it loads maps much slower than release, but the crash normally always occurs after I've hit "Open" in the open file dialog.

**Comment by bjorn** [comment]
@tdeeb Hmm, that's unfortunate. Thanks for trying!
