### ISSUE TITLE
Segfault in tileset propery editor

### ISSUE THREAD

**Issue by jmdejong** [bjorn/tiled#2200]
I am getting a segmentation fault when setting the custom properties of tiles in a tileset.

When adding a property to a tile (that is on the map) with the same name as a string property on another tile (that is also on the map, that is before this tile in the order of the tileset and that has a nonempty string as value for that property) then the editor crashes with a segfault.

Steps to reproduce:

- Start tiled
- Create a new map (I didn't have any other maps open. The map was 64x64 tiles with tiles of 10x10 pixels. The map is orthagonal and tiles are saved as csv)
- Create a new tileset for that map based on a tileset image (I used http://rogueliketutorials.com/images/arial10x10.png)
- Draw at least 2 different tiles of that tileset on the map (I had the first tile (empty) and the second ('!'))
- Edit the tileset properties
- Take the first tile that is drawn of the map (in the order of the tileset, so the empty tile in my case), and add a custom property of type string (for example named "a")
- Give this property some nonempty value (for example "1")
- Take another tile that is drawn on the map, that is later in the ordering of the tileset ( so the '!' tile in my case)
- Give it a custom property with the same property name as the first (so that would be "a")
- As soon you click the Ok button of the Add Property window Tiled crashes with a segmentation fault

I can reliably reproduce the segfault this way.

I'm using Tiled 1.2.4 (installed from pacman repositories) on Archlinux 64 bit.

**Comment by bjorn** [comment]
Would have been nice to get that fix in 1.2.5 as well, but I forgot about this somehow. I actually wouldn't expect this crash to be so rare, but it seems to have been in since 1.0 and I think you're the first one to report it.

In any case the fix will be included in Tiled 1.3 (will try to announce the "beta" soon). Thanks for finding this one!
