### ISSUE TITLE
Drawing lines with the terrain tool

### ISSUE THREAD

**Issue by stefanbeller** [bjorn/tiled#221]
When drawing lines using the terrain type tool, there are some undesired tiles, see
http://dl.dropbox.com/u/6520164/tiled/Screenshot%20from%202012-06-09%2015%3A24%3A15.png

Can I notify @TurkeyMan by highlighting him here?

**Comment by bjorn** [comment]
In the upcoming Tiled release the Terrain Brush is going to be replaced by the Wang Brush, which inherited all of its functionality. In addition, the Wang Brush is able to draw lines a little bit better as of change fb22b94a45ab6882085b610b70cd19b2cd9611a4, so I think we can close this issue soon.
