### ISSUE TITLE
tiled.log() and tiled.alert() ... can't use CJK charsets

### ISSUE THREAD

**Issue by HonestQiao** [bjorn/tiled#2210]
tiled.log("保存成功");   //mean: save success

console's output is gibberish.

**Comment by bjorn** [comment]
Hmm, on Linux I can't reproduce this:
```
> tiled.log("保存成功")
保存成功
```
I'll try on macOS as well.

**Comment by bjorn** [comment]
Hmm, works for me on macOS as well, when compiled against Qt 5.13.1. Do you have any suggestion on how I could reproduce this problem?

If you have Qt Creator installed, could you run this through a debugger to see where it gets messed up? The string arrives from the script in this function:
```c++
void ScriptModule::log(const QString &text) const
{
    Tiled::INFO(text);
}
```
If it's already wrong there then it could be some issue in Qt between the JavaScript engine and the conversion to QString. But so far I can't see the problem.

**Comment by HonestQiao** [comment]
ENV:
MacOS: 10.15
QT: 5.13.1
QTCreator: 4.10.1

JS plugin file: 
charset: UTF-8
code: `tiled.alert('保存成功.');`

breakpoint:
```
void ScriptModule::alert(const QString &text, const QString &title) const
{
[b]    QMessageBox::warning(MainWindow::instance(), title, text);
}

```
watch value:
```
		text	"ä¿\235å\255\230æ\210\220å\212\237."	QString &
			[0]	'ä' 	228	0x00e4	QChar
			[1]	'¿' 	191	0x00bf	QChar
			[2]	    	157	0x009d	QChar
			[3]	'å' 	229	0x00e5	QChar
			[4]	    	173	0x00ad	QChar
			[5]	    	152	0x0098	QChar
			[6]	'æ' 	230	0x00e6	QChar
			[7]	    	136	0x0088	QChar
			[8]	    	144	0x0090	QChar
			[9]	'å' 	229	0x00e5	QChar
			[10]	    	138	0x008a	QChar
			[11]	    	159	0x009f	QChar
			[12]	'.' 	46	0x002e	QChar
		this	@0x115c124b0	Tiled::ScriptModule
		title	""	QString &

```

**Comment by HonestQiao** [comment]
tile.log also become gibberish:
```javascript
tiled.log("日志I'm loading.");
```
```python
		[statics]		
		text	"æ\227¥å¿\227I'm loading."	QString &
			[0]	'æ' 	230	0x00e6	QChar
			[1]	    	151	0x0097	QChar
			[2]	'¥' 	165	0x00a5	QChar
			[3]	'å' 	229	0x00e5	QChar
			[4]	'¿' 	191	0x00bf	QChar
			[5]	    	151	0x0097	QChar
			[6]	'I' 	73	0x0049	QChar
			[7]	''' 	39	0x0027	QChar
			[8]	'm' 	109	0x006d	QChar
			[9]	' ' 	32	0x0020	QChar
			[10]	'l' 	108	0x006c	QChar
			[11]	'o' 	111	0x006f	QChar
			[12]	'a' 	97	0x0061	QChar
			[13]	'd' 	100	0x0064	QChar
			[14]	'i' 	105	0x0069	QChar
			[15]	'n' 	110	0x006e	QChar
			[16]	'g' 	103	0x0067	QChar
			[17]	'.' 	46	0x002e	QChar
		this	@0x1191a9720	Tiled::ScriptModule
	检查器		
	表达式		
	返回值		
	工具提示		
		QMessageBox	<no such value>	 
		ScriptModule	<no such value>	 
		text	"================ 2 ==================\nhandle: onConnectHandler\ncaller: assetAboutToBeSaved"	QString
```

**Comment by bjorn** [comment]
Alright, sorry, I had not tested this from a script file, just ran the expression in the Console window. I guess it works fine for you there as well? If it only happens when running from a script file there may be an issue with loading the file. This code in particular:

https://github.com/bjorn/tiled/blob/e18d51a4040dd9b627ceecfdc0ed8d6746dd178b/src/tiled/scriptmanager.cpp#L155-L156

So I've used [`codecForUtfText`](https://doc.qt.io/qt-5/qtextcodec.html#codecForUtfText-1) in an attempt to support both various unicode formats and Latin-1 script files, but apparently it's not working in this case. Maybe we should use the [alternative overload](https://doc.qt.io/qt-5/qtextcodec.html#codecForUtfText) and pass UTF-8 explicitly as the fallback. Then no Latin-1 is supported, but that may be rather more rare than unicode at this point.

**Comment by HonestQiao** [comment]
I submitted a pull to solve this problem.
```c++
bool ScriptManager::checkFileUtf8(const QByteArray &ba)
{
    QTextCodec::ConverterState state;
    QTextCodec *codec = QTextCodec::codecForName("UTF-8");
    QString text = codec->toUnicode( ba.constData(), ba.size(), &state);

    if (state.invalidChars >0 ) //Not UTF-8
        return false;

    return true;
}

QJSValue ScriptManager::evaluateFile(const QString &fileName)
{
    QFile file(fileName);

    if (!file.open(QFile::ReadOnly | QFile::Text)) {
        Tiled::ERROR(tr("Error opening file: %1").arg(fileName));
        return QJSValue();
    }

    const QByteArray text = file.readAll();
    QString unistr;
    if(!checkFileUtf8(text)) {
        unistr = QTextCodec::codecForUtfText(text)->toUnicode(text);
    } else {
        unistr = QString::fromUtf8(text);
    }
    const QString script = unistr;

    Tiled::INFO(tr("Evaluating '%1'").arg(fileName));
    return evaluate(script, fileName);
}
```
