### ISSUE TITLE
Refreshing or opening map resets view to center of world

### ISSUE THREAD

**Issue by gauauu** [bjorn/tiled#2213]
If you have a large world loaded, then press Ctrl-R to reload, or open a map by using the file menu (file-> open) as opposed to clicking a map in the world view, the view will often reset to the center of the world instead of focusing on the map that you're working on.

As an example: In the attached 3-second video, the only human interaction is pressing Ctrl-R to reload a map.
![tiled-world-bug](https://user-images.githubusercontent.com/1113009/67625589-bcf1d100-f805-11e9-9f11-cd50c9b43295.gif)
I would expect it to stay centered on the map that I was working on.

**Comment by bjorn** [comment]
@gauauu Definitely expected to not change the view. The reload for maps is actually implemented by opening the file again and then replacing the previously open file, which is part of the reason why this changes the view. However, I should still try to find a way to keep the view stable (and eventually, I'd of course like to handle reload a bit better...). Thanks for opening the issue!

**Comment by bjorn** [comment]
Hmm, in testing I've noticed this doesn't appear to be related to the world feature. A single map also toggles between two camera views when pressing Ctrl+R repeatedly.

**Comment by bjorn** [comment]
So, I tried simply reversing the order (first closing the old document, then inserting the new one), but this leads to switching to another open document and then back, which is both bad for performance and it causes the file name in the title bar to flicker.

I will try to solve it by doing an explicit saving of the state before opening the reloaded document.
