### ISSUE TITLE
Support for clear the console

### ISSUE THREAD

**Issue by HonestQiao** [bjorn/tiled#2220]
The issue dock can be clear.
But the console can't.

**Comment by bjorn** [comment]
Yeah, I realized this as well, but the Console has no tool bar and I couldn't immediately think of another convenient place to put it. I'm not sure if a button next to the text input would be intuitive. Do you have suggestions?

Maybe Console should just get a tool bar as well. It could also feature a search filter.

**Comment by HonestQiao** [comment]
You can put it on the right side of the script input box of the console dock.
Two buttons:  [Execute] [Clear]

Or you can put it in the right-click menu of the console dock.

Example:
<img width="718" alt="WechatIMG1656" src="https://user-images.githubusercontent.com/696708/67918013-bed8dd00-fbd5-11e9-9379-eca66116b5fe.png">

**Comment by bjorn** [comment]
I implemented it exactly like you suggested in the screenshot. Thanks! :-)
