### ISSUE TITLE
Choose the background color of tilesets control

### ISSUE THREAD

**Issue by NinjaFighter** [bjorn/tiled#227]
Could be good, allow the user to set a background color for the tileset control, I have some problems to visualize my tiles when I have tiles that using only white pixels.

**Comment by voxoid0** [comment]
+1
The best work around I have is to use Windows high-contrast mode (keyboard shortcut Left-Alt + Left-Shift + PrtScn), but that puts other programs such as Eclipse and Gimp in a bad visual state.

**Comment by bjorn** [comment]
Until I've implemented an option for this, a somewhat better workaround would be to create a file with the following contents (say `style.qss`):

```css
QDockWidget#TilesetDock QAbstractItemView { background: grey }
```

And then run Tiled as follows:

```
tiled -stylesheet style.qss
```

This way, you just make the background of the tileset view gray without affecting other things.

**Comment by bjorn** [comment]
The above change implements a new tileset property for the background color, which defaults to the same gray as used for the map view. It is pushed to the `wip/tilesetdocument` branch, which I will merge as soon as possible but it will still be quite a bit of work.

**Comment by bjorn** [comment]
With Tiled 0.17, the theme can be set to dark, which will at least help those with light tilesets until the above configuration option is merged.

**Comment by reneaye** [comment]
In version 0.18.2 (Mac OS X) I do not have a background color property in the properties palette to the left. Or do I have to use a custom property?

**Comment by bjorn** [comment]
@reneaye That is because this feature was added on the `master` branch after Tiled 0.18 was branched off. If you're looking to configure the background color of your tileset, you need to install a development snapshot (or wait for Tiled 1.0, though that will still take 1-2 months).

**Comment by Bobjt** [comment]
The darker tileset background helps tremendously! Even better if I choose a dark theme color. Thumbs up.

**Comment by Julian-MJK** [comment]
SOLUTION:

Edit -> Settings -> Interface -> Theme
Set the "Style" setting to Native

(This disables Tiled's fancy theme, and enables the default windows theme for Tiled, which makes the tileset background color, grey)

**Comment by bjorn** [comment]
@Julian-MJK With Native theme, that color will depend on your system. But this solution is also a bit radical. Since Tiled 1.0, you can set a custom background color for your tileset in the Tileset properties, which will override the theme color when set.

**Comment by Julian-MJK** [comment]
Oh really? That would be great, because the default windows theme looks pretty rubbish, however I've never seen that option, where can you change that?

**Comment by Bobjt** [comment]
@bjorn, the new (as of Tiled 1.0) tileset background color literally made my day. Cheers.

**Comment by bjorn** [comment]
@Julian-MJK Open your tileset (clicking the small "Edit Tileset" button in the Tilesets view, or opening its file directly) and then choose _Tileset > Tileset Properties..._. Then, you can set the "Background Color" in the "Properties" view.

@Bobjt I'm glad to hear this feature was such a joy. :-)
