### ISSUE TITLE
Option to Relocate Moved Tilesets

### ISSUE THREAD

**Issue by ashes999** [bjorn/tiled#236]
I shuffle my tilesets around quite a lot, depending on how I want to organize it. Currently, if i create a map with a tileset, save, close it, move the tileset, and reopen it, I get an error message "Error loading tileset image: ..."

So far so good. However, at this point, the map doesn't load. I would like, instead of the map not loading, an option such as "would you like to try and relocate this file?" and the ability to browse locally and substitute the old path with a new one.

**Comment by bjorn** [comment]
Since a while I do have a bit of time for Tiled development again, and this issue was resolved in Tiled 0.15. :)
