### ISSUE TITLE
Polyline Objects aren't displayed if started from the edge

### ISSUE THREAD

**Issue by OniLink** [bjorn/tiled#239]
If you start a polyline object from the edge of a map, you can create it just fine, but it won't be displayed until you stop building it. This is troublesome, as I cannot see what I am doing.

**Comment by bjorn** [comment]
Hmm, seems like I forgot to respond to this. I've just tried starting a polyline from the edge of a map and it's displaying for me just fine. Maybe the issue is fixed in the meantime?

**Comment by bjorn** [comment]
No response and still not able to reproduce, assuming fixed.
