### ISSUE TITLE
Request: Scrolling over edges

### ISSUE THREAD

**Issue by Ablu** [bjorn/tiled#245]
Would be nice if you could scroll over the edges a bit (5 tiles should be enough). Is sometimes handy to have the current edited area not at the edge of screen

**Comment by T1mL3arn** [comment]
Just want to tell that I'd like to have this feature too.

**Comment by bjorn** [comment]
It's also definitely something I've long wanted to get around to. Now that I can give up some working time to work on Tiled instead, I'll be sure get to it in the coming months.

**Comment by bjorn** [comment]
I've made some progress with this by extending the minimum and maximum values of the scroll bar on demand. Unfortunately, QGraphicsView is making my life a bit hard by setting the range of the scroll bars in a private function, which makes implementing nice behavior when for example changing the zoom level or resizing the view rather difficult.

In any case, I'll probably push this change as soon as I got the maximum value restoring correctly when scrolling back.
