### ISSUE TITLE
Tiled 1.3.1: Cannot import .json objecttypes file

### ISSUE THREAD

**Issue by emilfilipdev** [bjorn/tiled#2682]
After updating to Tiled 1.3.1 (latest version), I have not been able to import a certain .json file which contained the object types for my Tiled map. This means that trying to import this file via the Object Types Viewer does not add the object types and properties to the viewer, and therefore I cannot use them in my map. Choosing, rather than importing, the file in Object Types Viewer does not work either. Here are the file contents:
```json
[
    {
        "color": "#ff0000ff",
        "name": "destructibleEnvironment",
        "properties": [
            {
                "name": "explosive",
                "type": "bool",
                "value": false
            }
        ]
    },
    {
        "color": "#ffff0000",
        "name": "enemy",
        "properties": [
            {
                "name": "alert",
                "type": "bool",
                "value": true
            },
            {
                "name": "alertRadius",
                "type": "float",
                "value": 10
            },
            {
                "name": "enemyType",
                "type": "string",
                "value": ""
            },
            {
                "name": "fixedRotation",
                "type": "bool",
                "value": true
            },
            {
                "name": "health",
                "type": "float",
                "value": 100
            },
            {
                "name": "linearDamping",
                "type": "float",
                "value": 4
            },
            {
                "name": "material",
                "type": "string",
                "value": "flesh"
            },
            {
                "name": "maxSpeed",
                "type": "float",
                "value": 5
            },
            {
                "name": "minSpeed",
                "type": "float",
                "value": 0
            },
            {
                "name": "pathfinding",
                "type": "string",
                "value": "dumb"
            },
            {
                "name": "timeToReachMaxSpeed",
                "type": "float",
                "value": 0.5
            }
        ]
    },
    {
        "color": "#ffffffff",
        "name": "player",
        "properties": [
            {
                "name": "allowSleep",
                "type": "bool",
                "value": false
            },
            {
                "name": "canMove",
                "type": "bool",
                "value": true
            },
            {
                "name": "fixedRotation",
                "type": "bool",
                "value": true
            },
            {
                "name": "health",
                "type": "float",
                "value": 100
            },
            {
                "name": "linearDamping",
                "type": "float",
                "value": 16
            },
            {
                "name": "material",
                "type": "string",
                "value": "flesh"
            },
            {
                "name": "maxSpeed",
                "type": "float",
                "value": 5
            },
            {
                "name": "minSpeed",
                "type": "float",
                "value": 0
            },
            {
                "name": "timeToReachMaxSpeed",
                "type": "float",
                "value": 0.1
            }
        ]
    },
    {
        "color": "#ff55ff00",
        "name": "staticEnvironment",
        "properties": [
            {
                "name": "material",
                "type": "string",
                "value": "metal"
            }
        ]
    }
]
```
This .json file was made with an older version of Tiled, although I cannot exactly remember which version it was made with. I think it was version 1.2.3. Maybe the problem is no backwards compatibility? Or maybe support for .json files was dropped.

**Comment by emilfilipdev** [comment]
Platform is Windows 10, 64-bit
Using Tiled version 1.3.1, 64-bit
This is for libgdx, if that's of any significance

**Comment by bjorn** [comment]
> This means that trying to import this file via the Object Types Viewer does not add the object types and properties to the viewer, and therefore I cannot use them in my map. Choosing, rather than importing, the file in Object Types Viewer does not work either.

Hmm, I tried to reproduce it with the contents you've pasted, but the import worked fine for me in Tiled 1.3.1. What exactly is happening when you import or choose this object types file?

Nothing should have changed regarding the object types file between 1.3 and 1.2. The only thing that changed recently (between 1.3.0 and 1.3.1) is that the object types file is now automatically reloaded when it is changed externally (see #2674). Just to make sure you could try with Tiled 1.3.0 to see if it still worked there.

**Comment by emilfilipdev** [comment]
> What exactly is happening when you import or choose this object types file?

Absolutely nothing happens. I open the Object Types Editor (which appears as being empty) and I choose/import my .json file by double-clicking. The Object Types Editor remains empty after the Windows Explorer prompt closes.

Also quick question, how can I find installers for older versions of Tiled? Other than the nightly build ones?

**Comment by bjorn** [comment]
> Absolutely nothing happens. I open the Object Types Editor (which appears as being empty) and I choose/import my .json file by double-clicking. The Object Types Editor remains empty after the Windows Explorer prompt closes.

Hmm, that's strange. If there was any error there should have been a popup.

> Also quick question, how can I find installers for older versions of Tiled? Other than the nightly build ones?

You can get older versions either by selecting them in the itch.io app, or downloading the respective release at https://github.com/bjorn/tiled/releases.

**Comment by emilfilipdev** [comment]
Using Tiled 1.2.3 has the same broken result. I have no idea what could be causing this.

**Comment by emilfilipdev** [comment]
I have just re-installed Tiled 1.3.1 for the fourth time and now the issue has been resolved. Thanks for the help!

**Comment by bjorn** [comment]
Wow, that's really strange! If you ever run into it again, please let me know if there's any further indication of what may be going wrong here. I'll close this issue for now.
