### ISSUE TITLE
Feature: Allow assigning a tint color to a layer

### ISSUE THREAD

**Issue by Gnumaru** [bjorn/tiled#2683]
Feature Description:
It would be useful to have a functionality that allows tinting each individual layer with a chosen color, in a similar way to what some game engines do. This could replace the opacity setting for each layer (since a tint color will already have an alpha channel), could be another widget unrelated to the opacity slider or could be a property of the layer. Tint colors in a group layer would stack with the ones of the child layers, in the same manner it works with the opacity setting.

Problem:
Godot, Unity and Unreal (and I suppose many other game engines) provide default shaders that allow tinting sprites with a given color by multiplying the tint color with the fragment shader output color. This is usefull to tweak map layer colors without changing the asset itself and is also useful for effects like having transparency in foreground layers or darkening background layers.

In a personal project I'm using the layer's custom properties to define this tint color which I assign to the tint color of the layer in the engine uppon importing the tmx file. Although this works fine, It would be more convenient to see the layers tinted in tiled instead of having to tint them in the engine and then copying back the color value to tiled.

I'm willing to try to implement this myself and make a pull request but since I'm very new to Qt and I'm also not familiar with tiled's codebase I just couldn't find yet where things are and what I must do.

After some messing with the codebase I stumbled upppon src/libtiled/maprenderer.cpp wich seems to hold the rendering logic. At first I thought I should modify CellRenderer::render to change the tile rendering. I googled a bit to found that there is a QPainter::setCompositionMode which would make the multiplying effect I want. If I understood right, after drawing the tile
```
mPainter->drawPixmap(target, image, source);
```
I should change the composition mode and draw again another thing on top of it.
```
mPainter->drawPixmap(target, image, source);
mPainter->setCompositionMode(QPainter::CompositionMode_Multiply);
QImage tintColor(imageSize.width(), imageSize.height(), QImage::Format_ARGB32);
QPixmap tintPix = QPixmap::fromImage(tintColor);
tintColor.fill(0XFFFFFF00);
mPainter->drawPixmap(target, tintPix, source);
```
But this change simply does not seem have any effect.

It could be because I'm doing the wrong thing in the right place, or the right thing in the wrong place or the wrong thing in the wrong place. Anyways I would appreciate any tip as to how make this change.

**Comment by bjorn** [comment]
I agree this feature would be pretty nice, though I'm afraid QPainter does not support tinting. The workaround you found based on drawing again with a composition mode assumes we're tinting an entirely opaque image that was drawn with opacity 1. In all other cases the effect will not look the same as tinting. Besides it will be a rather slow method.

However, I think it should have worked. But in the code you're filling the `tintColor` image after having created the `tintPix`. You should swap this, or get rid of the `QPixmap::fromImage` entirely and just use `mPainter->drawImage`.

On the long run, I would like to switch to a new renderer based on the [Qt Quick Scene Graph](https://doc.qt.io/qt-5/qtquick-visualcanvas-scenegraph.html). It's partly implemented in `src/tiledquickplugin` and used by `src/tiledquick`, but there are still many features lacking. It would trivially enable such features with great performance.

**Comment by Gnumaru** [comment]
The fill call should be before creating the pixmap, that was really a dumb mistake. But correcting this was not enough to make it work. It seems I should be modifying CellRenderer::flush. Afther modifying It I managed to make it work. After messing with other source files I managed to also create a new editable property in the properties inspector.

https://www.youtube.com/watch?v=ieaf-2ONWkk

But it seems I should modify other places as well. I took the care to hide several bugs in the above video. For example if I draw a different tile only the current tile get tinted. Also the color picker only sets the color correctly if, for the first time, I set manually each color channel.

If the porting to a new rendering scheme is too far away, would you consider this for the time being? You can find my fork here

https://github.com/Gnumaru/tiled

**Comment by bjorn** [comment]
> The fill call should be before creating the pixmap, that was really a dumb mistake. But correcting this was not enough to make it work. It seems I should be modifying CellRenderer::flush. Afther modifying It I managed to make it work.

Right, you'd need to modify both places where the image gets drawn. Sometimes single tiles get drawn in `render` but generally tiles get drawn in `flush` (see comment about negative scaling factors).

> If the porting to a new rendering scheme is too far away, would you consider this for the time being? You can find my fork here

Please open a pull request, then I can review and test the code more easily and can consider whether it can be merged. For this it's important that there isn't a big performance hit for those not using the feature. I can also help with fixing remaining issues. Thanks!

**Comment by Gnumaru** [comment]
I made the pull request:

https://github.com/bjorn/tiled/pull/2687

On the matter of performance, it should not impact those who do not use the functionality. The logic only applies if the user have chosen a tint value different from QColor(255, 255, 255, 255) wich is the default value.

**Comment by Gnumaru** [comment]
Also, there are modified files wich I havent modified myself, for example src/tiled/abstractobjecttool.cpp. I suppose this should be some automatic code modifications made by qtcreator or qmake so I just ignored them.

**Comment by bjorn** [comment]
> Also, there are modified files wich I havent modified myself, for example src/tiled/abstractobjecttool.cpp. I suppose this should be some automatic code modifications made by qtcreator or qmake so I just ignored them.

Actually those changes are reverting some of my recent changes, for example commit 2e53f9639e155ae711c17c332d5fcd39bd72b92d, so something probably went wrong when updating your fork. Please remove those changes from your commit.

**Comment by Gnumaru** [comment]
Done. Now there are only changes I know where done by myself. I'm sorry for this mistake.

**Comment by Gnumaru** [comment]
I have just updated my fork with the recent upstream changes.

**Comment by Gnumaru** [comment]
I have just updated my fork with the recent upstream changes.
