### ISSUE TITLE
Tile GID and costume collision don't tie up ID

### ISSUE THREAD

**Issue by RossPavey** [bjorn/tiled#2686]
Hello I download the new tiled 131 I was just getting round to figuring out the tile GID and costume collision in  txml file and noticed that the GID is -1 for Collision  sprite should they not tie up to same number  here is my txml file. you can see  <tile id="273"> but object GID's are one less <object id="3493" gid="272" x="191.477" y="146.931" width="64" height="64"/> I know its the old computers count Zero as a number and its just a ++ on save anyway many thanks my project has come alive because of your editor I love it and  supporting the project.

<objectgroup draworder="index" id="2">
    <object id="1" x="-1" y="27">
     <polygon points="0,0 20,-30 72,-19 50,43 8,41"/>
    </object>
   </objectgroup>
  </tile>
  <tile id="273">
   <objectgroup draworder="index" id="2">
    <object id="1" x="17.8725" y="11.0112">
     <polygon points="4.61203,-3.24089 21.2549,-2.38236 43.9944,31.3543 47.0056,40.2409 26.1499,52.8557 -17.1246,51.2437 -17.8697,30.3739"/>
    </object>
   </objectgroup>
  </tile>
 </tileset>
 <layer id="61" name="Tile Layer 1" width="12" height="9">
  <data encoding="base64" compression="gzip">
   H4sIAAAAAAAEE+XOOREAIAwF0cygLIARDiMcRjiEsg4igOIVO/lF1Il4BESo0Yl7RkGF1Y1Nx8CE1YvNxsGF1crmp/8f8M0YMbABAAA=
  </data>
 </layer>
 <objectgroup id="64" name="Object Layer 1">
  <object id="3491" gid="274" x="187.057" y="62.4519" width="64" height="64"/>
  <object id="3492" gid="274" x="258.766" y="59.0138" width="64" height="64"/>
  <object id="3493" gid="272" x="191.477" y="146.931" width="64" height="64"/>
 </objectgroup>
</map>

**Comment by RossPavey** [comment]
Scarp that mistake done new file all is fine very sorry.

**Comment by bjorn** [comment]
I'm afraid I don't really understand what issue you were having, but I'm glad to hear it has been resolved. Good luck with your project and please do report any further issues you find!
