### ISSUE TITLE
Snapshot 2019.12.04 from itch.io does not boot on macOS

### ISSUE THREAD

**Issue by tcannonfodder** [bjorn/tiled#2689]
The snapshot in question is tied to https://github.com/bjorn/tiled/pull/2685

Steps to reproduce:

1. Download the 2019.12.04 snapshot from https://thorbjorn.itch.io/tiled
2. Observe that the following error message is returned:
![image](https://user-images.githubusercontent.com/877224/70199200-17bcf900-16df-11ea-8595-e3d95afe8f2b.png)

Version: MacOS Catalina 10.15.1

**Comment by bjorn** [comment]
Thanks for the report!

It seems like something went wrong with shipping the full set of libraries Tiled needs. When I try to launch the Tiled binary inside the bundle it complains about not finding QtNetwork, which is indeed missing.

I have no idea at the moment what changed to cause this problem. I'll need to find some time to investigate.

**Comment by bjorn** [comment]
When trying to run through itch.io I get the following output in the Problem Report:

```
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtNetwork.framework/Versions/5/QtNetwork
  Referenced from: /Users/USER/Library/Application Support/itch/*/Tiled.app/Contents/MacOS/Tiled
  Reason: image not found
```

**Comment by bjorn** [comment]
Hmm, this already affected Tiled 2019.11.26 as well, but 2019.11.20 is not affected. So it may have something to do with the update of Qt from 5.12.5 to 5.12.6.

**Comment by bjorn** [comment]
Downgrading to Qt 5.12.5 did not fix it, so there's something else going wrong. :-/

**Comment by bjorn** [comment]
Was fixed by the above commit. The following change in `.travis.yml` appears to break the macOS packaging:
```diff
-  - QTCREATOR_VERSION=4.10.1
+  - QTCREATOR_VERSION=4.10.2
```
Will need to investigate why before increasing that version number in the future.
