### ISSUE TITLE
Right-click issue with context menu on map objects

### ISSUE THREAD

**Issue by colin29** [bjorn/tiled#2693]
Steps to duplicate: 
1. Right-click an object on the object layer while using the Select Objects or Edit Polygons Tool. On right mouse button-up, the program will always select any option that was under your cursor.

If you drag the mouse away and let go of the RMB, most of the time the context menu will disappear, but not always.

Happened to me on Win10, haven't confirmed with any other machine, but I'm pretty sure my mouse is working properly.

Work around: When selecting objects, you need to hold the right key down, find what option you are looking for, then let go of the right mouse button.

**Comment by bjorn** [comment]
> 1. Right-click an object on the object layer while using the Select Objects or Edit Polygons Tool. On right mouse button-up, the program will always select any option that was under your cursor.

This is the expected behavior for context menus as well as normal menus, so I think there might be some other issue. Could it be that the first option is already under the cursor when the menu opens? If so that'd be a bug.

> If you drag the mouse away and let go of the RMB, most of the time the context menu will disappear, but not always.

The menu is not expected to disappear just by dragging the mouse away. Is that really happening? Normally a context menu closes when you click outside of the menu, not when releasing the mouse (unless you release while hovering one of the options).

**Comment by colin29** [comment]
> This is the expected behavior for context menus as well as normal menus, so I think there might be some other issue. Could it be that the first option is already under the cursor when the menu opens? If so that'd be a bug.
Oh, I see. Yeah, that's the problem then. The first option is frequently already underneath the cursor.

>The menu is not expected to disappear just by dragging the mouse away. Is that really happening? Normally a context menu closes when you click outside of the menu, not when releasing the mouse (unless you release while hovering one of the options).
Yeap. I tested it again, and it seems like the menu disappears if any menu option was ever highlighted.

**Comment by bjorn** [comment]
Alright, just wondering, but is Tiled 1.2 also affected by this issue or is it new in Tiled 1.3? Tiled 1.2 was using Qt 5.9 whereas Tiled 1.3 uses Qt 5.12, and it sounds like it may be an issue in Qt.

**Comment by bjorn** [comment]
I see this problem as well on Windows and noticed that it doesn't appear to happen when using the "Native" style (see _Edit > Preferences > Theme > Style_).

So there may be an issue with the "Tiled Fusion" style causing this. I'll look into it next week.

**Comment by bjorn** [comment]
I've looked into this issue and Qt's own "Fusion" style is showing the same issue on Windows. I think it's related to the DPI scaling, but looking through the relevant code I couldn't find out what could be causing it.

So I've added a workaround instead. The menus now have a 2 pixel margin, which prevents the first item from sometimes being right below the mouse.
