### ISSUE TITLE
Everything is greyed out totally unusable?

### ISSUE THREAD

**Issue by hasen6** [bjorn/tiled#2697]
I downloaded 1.3.1 and can't seem to do anything. The stamp brush and all tools next to it are greyed out and un-selectable. If I click the tools like rectangle, ellipse etc they all become darker as if selected but why are they ALL selected? Also more clicks makes them darker still. Only deselecting Tiled completely and returning resets them back.

Obviously without the stamp brush etc I can't do anything. I'm using Macos 10.13.6.

![屏幕快照 2019-12-14 下午2 55 34](https://user-images.githubusercontent.com/15882674/70844868-4d51a700-1e82-11ea-9d78-ef0f71db6078.png)

I would have thought clicking them again would deselect them but instead it just makes them darker and darker?

With a new project the opposite happens. All the right most tools are greyed out and the leftmost tools can be selected but somehow again can all be selected at the same time.

![屏幕快照 2019-12-14 下午3 06 27](https://user-images.githubusercontent.com/15882674/70844921-6575f600-1e83-11ea-8cdc-851d95a2d04a.png)

**Comment by hasen6** [comment]
There is no problem with 1.2.5 however.

**Comment by bjorn** [comment]
Which set of tools is grayed out depends on the type of layer you have selected. If you select a tile layer, the tile layer tools are enabled. If you select an object layer, the object tools are enabled.

The darker background color is just a repainting issue that indeed appears to be a regression (in Qt 5.12 vs. Qt 5.6, which was used for Tiled 1.2.5 on macOS). See issue #2667 about that.

**Comment by hasen6** [comment]
Issue #2667 is closed but the problem is clearly not fixed. Don't see the reasoning in closing issues that aren't fixed.

**Comment by bjorn** [comment]
@hasen6 I closed this issue, not #2667.

**Comment by hasen6** [comment]
Ok you're right, seeing the 'closed' label at the bottom of the thread makes it look like it's closed. Github is pretty weird that way. This thread is closed so it has a red label but that thread is NOT closed but it has an _even_ bigger red label with 'closed' in it. It looks more closed that this thread lol. 

Anyway no problem.
