### ISSUE TITLE
Image layers cannot load images from Qt resource files

### ISSUE THREAD

**Issue by obeezzy** [bjorn/tiled#2700]
Images embedded in Qt resource files would produce a null QPixmap when loaded from a TMX file. I tried pushing a change, but I kept getting denied access. (I'm new to this and therefore clueless lol.)

Below is my proposed fix for the issue:

**tiled/src/imagelayer.cpp:**
```cpp
bool ImageLayer::loadFromImage(const QUrl &url)
{
    QString urlAsString;
    if (url.url().startsWith("qrc:/"))
        urlAsString = url.url().replace(QString("qrc:/"), QString(":/"));
    else
        urlAsString = url.toLocalFile();

    return loadFromImage(ImageCache::loadImage(urlAsString), url);
}
```

**Comment by Phlosioneer** [comment]
In the upper-right corner of the github website, while looking at this project, there's a "fork" button. Click that. That will create a copy in your name.

Push your modifications to that copy of the project.

Then return here to this project, look at the code tab, and you'll be prompted to create a "pull request". Click that green button.

For a one-commit change, it'll paste your commit message straight into the pull request, and the name of the pull request will be the name of the branch. Click the green button on that page to submit it. Your changes will now appear in the Pull Request tab, which we can comment on, discuss, etc. You can even continue to push new changes (for example, if we request a change or spot a bug).

Some automated tests will run. Check back a few hours or a day later and see if any of the tests failed. If they did, you can click on them, and see the error logs. The tests compile on multiple platforms (linux, windows, osx) and with different versions of Qt (5.6 and 5.12 at least, possibly more). If there's any failures on those tests, please fix them in your local copy and push the changes. The tests will automatically restart when you push new changes. If you have questions about what the tests say or why they're failing, leave a message on a PR and you'll get a response when someone, probably bjorn, has the time to look at it.

When the tests pass and Bjorn reviews the code, he can merge the pull request. At that point your code is now in the official repository, and you can safely delete your branch, your copy of the project, etc. if you want.

PR's can take some time; a short one goes faster, but it can easily take over a week. Bjorn has another job, and I believe he works one full day per week on tiled. During that time, he's not just reading PR's and issues, he's also coding, so expect the process to take some time.

**Comment by bjorn** [comment]
Thanks for the elaborate introduction @Phlosioneer!

@obeezzy Would be great if you could open a pull request for his change! Also, @mitchcurtis will want to have a look at this change, because he made several similar changes in the past (see d0b189e89dea5f9ad1c19b956b86e024b49eea49). Probably we should use the `urlToLocalFileOrQrc` helper function here as well.

**Comment by obeezzy** [comment]
@Phlosioneer and @bjorn, thanks for your rapid replies! I'd create the pull request once I return home in a couple days.

**Comment by bjorn** [comment]
> Bjorn has another job, and I believe he works one full day per week on tiled.

Just a small correction, I'm working two full days per week on Tiled! Unfortunately that means I'm only half as productive as you thought I was. :-/
