### ISSUE TITLE
JavaScript API can't get tileset's image size

### ISSUE THREAD

**Issue by Noah2610** [bjorn/tiled#2733]
__TL;DR__
With the JS API, is there a way to get a tileset image's size in pixels?

---

Before `v1.3` and the JS API / extensions feature, I was using python export scripts to create custom export formats.
I noticed a missing feature/property with the JS API, that was available with the python scripts:
__Getting a tileset's real image size in pixels__
You could do this with python scripts with ...
```python
width = tileset.imageWidth()
height = tileset.imageHeight()
```
(see https://github.com/bjorn/tiled/blob/master/src/plugins/python/tiledbinding.py#L139)

The JS API doesn't seem to provide that information...
So I'm asking, is there a way to get this currently? If not, is this maybe a feature worth implementing?

Sadly I need this functionality to generate custom config files for the tilesets.
It would be very convenient for me to have this feature in the JS API,
otherwise I'll probably need to generate those files outside of the Tiled extension.

Thanks!

**Comment by Noah2610** [comment]
Used Tiled version: `1.3.1`
Although I'm primarily going off of the information on the docs:
https://doc.mapeditor.org/en/stable/reference/scripting/#tileset

**Comment by bjorn** [comment]
No problem adding it, just needs to be considered if we want to match the Python API or whether we want to export the image explicitly in some form, like `tileset.image.width`.

**Comment by Noah2610** [comment]
Good point.
As you mentioned, I feel like the better way to do this is to make the `image` property be a new class, but I guess this would have to wait until the next minor release?

I think it would also be OK to just add the property `imageSize`, because the `Tileset` already has a `tileSize` property, so it would fit the API style (at least in this specific case).

Thanks for your time! Awesome, clean app, btw :)
