### ISSUE TITLE
Setting custom properties on tileset through scripting crashes Tiled

### ISSUE THREAD

**Issue by EJlol** [bjorn/tiled#2747]
Running the following js script crashes Tiled:
`new Tileset().setProperty('key', 'value');`

Tiled crashes without any error message.

**Comment by bjorn** [comment]
Thanks for the report @EJlol, that's pretty bad!

**Comment by bjorn** [comment]
It was trying to use a `nullptr` as undo stack, because the condition to check for undo stack availability was outdated... Hopefully it all works fine now.
