### ISSUE TITLE
Preferences: Extension directory cannot be changed

### ISSUE THREAD

**Issue by RainingChain** [bjorn/tiled#2748]
Right now, the extension directory is hardcoded to:

Windows | C:/Users/<USER>/AppData/Local/Tiled/extensions/
macOS | ~/Library/Preferences/Tiled/extensions/
Linux | ~/.config/tiled/extensions/

I'd like to be able to change the directory to a custom location (ex: C:/MyProject/tiledExtensions).

Doing so will permit putting the extensions under source code control.

**Comment by bjorn** [comment]
I'm planning to allow specifying a project-specific extensions directory. Do you think it would still be useful to allow changing the global extensions folder?

**Comment by RainingChain** [comment]
@bjorn That would be even better. If I can specify the extension directory in the project settings, I would no longer need to be able to change the global extensions folder.

**Comment by bjorn** [comment]
A project-specific addition extensions directory was added in [the development snapshot](https://thorbjorn.itch.io/tiled/devlog/137656/progress-on-projects-and-sessions) earlier this month.
