### ISSUE TITLE
[BUG]Change the object-order in the tree , but the render-order doesn't changed.

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#2751]
![image](https://user-images.githubusercontent.com/288367/74154388-87a2af00-4c4d-11ea-8443-87eb6e33183e.png)
Whatever  How I changed the node order of the object tree , the render order in the editor zone not changed .

(Sorry for my bad English, I hope you can understand me)

**Comment by finscn** [comment]
My fault.

**Comment by bjorn** [comment]
Ah, I don't think it's your fault... I think the default object drawing order is not the most intuitive one. I should probably introduce a project setting to change that default.
