### ISSUE TITLE
Compression level defaults to 0 when opening older tmx files

### ISSUE THREAD

**Issue by bjornenalfa** [bjorn/tiled#2753]
The map property "compressionlevel" is set to -1 when creating new maps, which makes it default to Z_DEFAULT_COMPRESSION when compressing the tile layers. However when opening tmx files that were made before the compressionlevel property was introduced will have the compression level defaulted to 0, making them use the lowest amount of compression instead of the Z_DEFAULT_COMPRESSION level they used to use.

**Comment by bjorn** [comment]
Ouch, thanks for finding that! Will get fixed soon.
