### ISSUE TITLE
delete or backspace not working on mac osx

### ISSUE THREAD

**Issue by HawkenKing** [bjorn/tiled#2757]
currently need to go through file menu or click trashcan

**Comment by bjorn** [comment]
Was #1296 never fixed or is it happening again?

Unfortunately, this report is very rare and I haven't been able to reproduce it. The shortcut should be handled by Qt. At the moment I have no idea what could be done to fix this.

**Comment by HawkenKing** [comment]
as far as I can tell, it's never been fixed. Happens on every mac I've used Tiled on (4 macs in total)

**Comment by bjorn** [comment]
@HawkenKing Alright, no problem! Which version were you on?
