### ISSUE TITLE
Inconsistency between ids and indexes in exported files

### ISSUE THREAD

**Issue by Fr33maan** [bjorn/tiled#2762]
Hi,
In the map composition file, the `layers` properties uses the index instead of ids. It seems counter intuitive for me as I have to keep tiles in a certain order.

This issue is here because ids starts at 0 and because no tile is treated as 0.
Either id should start at 1, either no tile should be null (but I'm not sure about csv export with a null.)

I think it's a feature, not a bug but it's quite misleading.

```
{ "columns":0,
 "grid":
    {
     "height":1,
     "orientation":"orthogonal",
     "width":1
    },
 "margin":0,
 "name":"issue",
 "spacing":0,
 "tilecount":3,
 "tiledversion":"1.3.2",
 "tileheight":85,
 "tiles":[
        {
         "id":0,
         "image":"herbe haute\/herbe haute centre fleurs.png",
         "imageheight":85,
         "imagewidth":142
        }, 
        {
         "id":1,
         "image":"herbe haute\/herbe hautecoin bas.png",
         "imageheight":85,
         "imagewidth":142
        }, 
        {
         "id":2,
         "image":"herbe haute\/herbe hautecoin dte.png",
         "imageheight":85,
         "imagewidth":142
        }],
 "tilewidth":142,
 "type":"tileset",
 "version":1.2
}
```

```
{ "compressionlevel":-1,
 "height":6,
 "infinite":false,
 "layers":[
        {
         "data":[3, 3, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 1, 1, 0, 0, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0],
         "height":6,
         "id":1,
         "name":"Tile Layer 1",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":6,
         "x":0,
         "y":0
        }],
 "nextlayerid":2,
 "nextobjectid":1,
 "orientation":"isometric",
 "renderorder":"left-up",
 "tiledversion":"1.3.2",
 "tileheight":85,
 "tilesets":[
        {
         "firstgid":1,
         "source":"issue.json"
        }],
 "tilewidth":142,
 "type":"map",
 "version":1.2,
 "width":6
}
```

**Comment by bjorn** [comment]
That is because the first tile in the first tileset gets the global ID 1, which is saved as the `tilesets[0].firstgid` property. Even if we would use -1 or null for "empty" then the global IDs would only match up with the local tile IDs for the first tileset.

A map can contain any number of tilesets and their tiles are mapped to a global ID namespace based on the `firstgid` property. See the last paragraph at https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#data and the example code below.

**Comment by Fr33maan** [comment]
@bjorn How to correctly map values in `data` (eg. ` "data":[3, 3, 0, 0, 0, 0, 3, 3, 3, 3, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 1, 1, 0, 0, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0],`) with ids ?

**Comment by Fr33maan** [comment]
Here, `0` refer to no tile, `1` refer to first tile in tileset which has `id = 0` and `index=0`

**Comment by bjorn** [comment]
Yes, according to the documentation I just linked:

> In order to find out from which tileset the tile is you need to find the tileset with the highest firstgid that is still lower or equal than the gid. The tilesets are always stored with increasing firstgids.

The C++ pseudo-code implements the logic as follows:

```c++
    // Resolve the tile
    for (int i = tileset_count - 1; i >= 0; --i) {
      Tileset *tileset = tilesets[i];

      if (tileset->first_gid() <= global_tile_id) {
        tiles[y][x] = tileset->tileAt(global_tile_id - tileset->first_gid());
        break;
      }
    }
```

Here, `global_tile_id` is a number from the data array and `global_tile_id - tileset->first_gid()` is a local tile ID that you find associated with each of your images.

**Comment by Fr33maan** [comment]
So if I understand correctly the real global id of a tile is `firstgid + tile.id` ?
But we don't have the `firstgid` property in exported tileset. 

Can't we have the globalId in the `tileset.tiles` ? 
If I udnerstand correctly, right now we have to derive it from `tileset.tiles[index].id +  map.tilesets[index].firstgid` ?

**Comment by bjorn** [comment]
> But we don't have the `firstgid` property in exported tileset.

This is not possible, because the tileset may be used by multiple maps, and each map can have its own list of tilesets. A tileset can and will often have different global IDs depending on the size of the tilesets referenced in a map's tilesets array before it.

**Comment by Fr33maan** [comment]
Forgive me but I still don't understand how to map numbers from `map.layers.data` to tiles in `tileset.tiles`.
Right now I feel I need to have only one tileset and use order of appearance.

**Comment by bjorn** [comment]
So, you need to perform two steps:

* First, you need to figure which tileset  is being referenced by a given number in `map.layers.data`. You can do this with a loop like I pasted above, going backwards over the tilesets array to find the last one that has a "firstgid" lower or equal to the number in `map.layers.data`.

* Once you have found this tileset, you subtract its "firstgid" from the number in `map.layers.data` to get the local ID of the tile you're looking for. This tile can then be found by this local ID in the `tileset.tiles` array.
