### ISSUE TITLE
"flat" Rectangles in object layers does not generate a width or height attribute in tmx

### ISSUE THREAD

**Issue by Madour** [bjorn/tiled#2764]
Tiled 1.3.1

When i create a "flat" rectangle in an object layer like this :
![image](https://user-images.githubusercontent.com/11854124/76124372-cdf3ef80-5ffa-11ea-9ec3-8d2ed82012c6.png)
The resulting tmx does not have a height attribute
![image](https://user-images.githubusercontent.com/11854124/76124434-f0860880-5ffa-11ea-95ee-63294ed89dc3.png)
I don't know if this is on purpose, but it feels unconsistent, i expected the object to have a height attribute equals to 0. Would make parsing easier without having to check if the width and height attributes exist beforehand.

**Comment by bjorn** [comment]
In fact, all attributes on the `object` element, and most attributes in general, are optional. For `width` and `height`, this is indicated in the documentation by stating that the default value is 0. It means, when no value is specified, it should be 0.

The only situation in which you will see these attribute being written, is when the object is a template instance, which normally inherits its size from the template, but then overrides those values for this instance.
