### ISSUE TITLE
Incorrect API documentation concerning Layer.isObjectGroup

### ISSUE THREAD

**Issue by LexouDuck** [bjorn/tiled#2765]
The documentation states that the Layer type has a field called "isObjectGroup" (boolean) - however after testing this seems to be erroneous (always gives an 'undefined' value). The actual field name is rather "isObjectLayer" (which behaves as expected).

I therefore post this issue to ask that the JS API doc be updated to avoid having others falling into the same pitfall I did.

**Comment by bjorn** [comment]
Hmm... I was undecided about whether to call this `isObjectLayer` (which matches with what this layer is called in the UI) or `isObjectGroup` (which matches was this layer is called in the code and the TMX map format). I guess it's easier to adjust the documentation at this point.

Thanks for pointing out this inconsistency!
