### ISSUE TITLE
Reproduce crash using rules

### ISSUE THREAD

**Issue by MadeBySaints** [bjorn/tiled#2766]
(Working with a project that has multiple maps)

**Steps to reproduce:**
1. Open a map, and place tiles with rules, press ctrl+m to autotile. save or don't, up to you. - _works just fine_
2. Open another map, place more tiles with rules, press ctrl+m to autotile, _editor crash._

**Notes**
If more than one map is opened in the same session, and both have ruled tiles, trying to apply rules to either map will crash the editor

Sometimes even on a fresh map, when there are more than 5-10 tiles with rules, you have to press ctrl+m multiple times to apply the rules to every tile that uses the rules. Fresh maps have not crashed the editor for me, but I thought these 2 issues may be related.

Added a few photos to show that I have everything set up correctly.

If they are not related, I'll be happy to create a separate issue.

![image](https://user-images.githubusercontent.com/3265397/76163751-40f68680-611f-11ea-900e-9ca90c735a44.png)
![image](https://user-images.githubusercontent.com/3265397/76163798-a77ba480-611f-11ea-8e6a-8e6610c1543a.png)
![image](https://user-images.githubusercontent.com/3265397/76163805-b4989380-611f-11ea-9860-0dc2de2411f7.png)
![image](https://user-images.githubusercontent.com/3265397/76163816-d8f47000-611f-11ea-9c50-6ef17d98556e.png)

**Comment by bjorn** [comment]
I could reproduce this crash. The `AutoMapper` instance is re-used for the other map while it still has a `mMapWork` pointer pointing at the first map it was instantiated for. This member will either need to be removed or updated before applying the automapping rules to the other map.
