### ISSUE TITLE
Object types editor strings broken

### ISSUE THREAD

**Issue by MattDurajka** [bjorn/tiled#2768]
#### Steps to reproduce

- Open object types editor
- Create a new string property
- Try to set a default value

#### Expected behavior

- Being able to type normally

#### What actually happened

- The textbox loses focus and the first object type gets selected

#### Info

- Tiled version: **1.3.3**
- Operating system: **Windows 10**

![tiled_object_types_editor_broek_ono](https://user-images.githubusercontent.com/28161629/76679881-73532880-65e4-11ea-94ff-8502b8faf66d.gif)

**Comment by MattDurajka** [comment]
This problem came with the 1.3.1 update. Doesn't happen on 1.3.0

**Comment by bjorn** [comment]
Hmm, in Tiled 1.3.1 we added reloading of object types when changed externally (#2674). This must be due to the autosave triggering an autoreload. I'll look into fixing it soon, thanks for the report!

In the meantime, you could use Tiled 1.3.0 or manually edit the object types file.
