### ISSUE TITLE
Tiled Quick: rendering only visible tiles in isometric maps

### ISSUE THREAD

**Issue by mitchcurtis** [bjorn/tiled#2769]
Support for isometric maps in tiledquickplugin was added in #1535, but all tiles in the map are rendered, rather than only those tiles within the MapItem's visibleArea.

**Comment by mitchcurtis** [comment]
@bjorn, can you please give some guidance about which parts of the code would need to be modified to fix this? I'd like to have a go at fixing it, but am unsure where to start. From what I can see:

This

https://github.com/bjorn/tiled/blob/master/src/tiledquickplugin/tilelayeritem.cpp#L333-L334

should become:

    const` QRect rect = mapItem->visibleTileArea(mLayer);

There's also a comment here so I assume this needs to be changed too:

https://github.com/bjorn/tiled/blob/master/src/tiledquickplugin/tilelayeritem.cpp#L254-L288

And this:

**Comment by mitchcurtis** [comment]
With this patch, I see that visibleTileArea() needs to account for the different "shape" of an isometric map:

```
diff --git a/src/tiledquick/qml/main.qml b/src/tiledquick/qml/main.qml
index d67909ea..67de1c5d 100644
--- a/src/tiledquick/qml/main.qml
+++ b/src/tiledquick/qml/main.qml
@@ -14,7 +14,7 @@ ApplicationWindow {
     height: 720
     minimumWidth: 480
     minimumHeight: 320
-    title: qsTr("Tiled Quick")
+    title: qsTr("Tiled Quick | %1").arg(mapItem.visibleArea)
     visible: true
 
     FontLoader {
diff --git a/src/tiledquickplugin/tilelayeritem.cpp b/src/tiledquickplugin/tilelayeritem.cpp
index 2aebc089..b128f3bb 100644
--- a/src/tiledquickplugin/tilelayeritem.cpp
+++ b/src/tiledquickplugin/tilelayeritem.cpp
@@ -330,8 +330,8 @@ QSGNode *TileLayerItem::updatePaintNode(QSGNode *node,
 void TileLayerItem::updateVisibleTiles()
 {
     const MapItem *mapItem = static_cast<MapItem*>(parentItem());
-    const QRect rect = mLayer->map()->orientation() == Map::Orthogonal
-            ? mapItem->visibleTileArea(mLayer) : mLayer->bounds();
+    const QRect rect = mapItem->visibleTileArea(mLayer);
+    qDebug() << mapItem->visibleArea() << rect;
 
     if (mVisibleTiles != rect) {
         mVisibleTiles = rect;
```

but at worst this should just mean that too little of the map is rendered. A more important issue is the glitch in rendering:

<img width="1136" alt="Screen Shot 2020-03-15 at 5 52 41 pm" src="https://user-images.githubusercontent.com/6002340/76706170-d4165a00-66e5-11ea-865f-76b2fb15f6a9.png">

I wonder where this issue comes from. I'm looking at IsometricRenderHelper::addTilesToNode(), and it just works with the given rect, so I don't see how it could be causing this issue. Perhaps that TODO comment is wrong.

TilesNode::processTileData() seems to just be responsible for drawing individual tiles, so I don't see it causing this...

**Comment by bjorn** [comment]
Well, one problem is that `visibleTileArea` expects to return a rectangular area in tile coordinates. However, on an isometric map, the visible tiles do not form a rectangular area. We can still use a `QRect`, but we'd need to interpret it differently in the renderer.

Alternatively, we'd pass the visible area in pixels to the renderer and then the renderer can only draw the visible tiles (this is how it works with the current `MapRenderer` implementations). Then you can check the code in the `IsometricMapRenderer` to see how it draws just the tiles in the given rectangle.

I can't currently explain that glitch either though. I'd also expect a different result. Maybe I can play with it a bit tomorrow.

**Comment by bjorn** [comment]
@mitchcurtis I've fixed that rendering issue in your screenshot in change 0712c206. I need to stop for today. Feel free to see if you can improve the rendering by expanding that rectangle until it fills the viewport (the rectangle would have to be based on which tiles are visible in the corners).

**Comment by mitchcurtis** [comment]
> Well, one problem is that `visibleTileArea` expects to return a rectangular area in tile coordinates. However, on an isometric map, the visible tiles do not form a rectangular area. We can still use a `QRect`, but we'd need to interpret it differently in the renderer.
> 
> Alternatively, we'd pass the visible area in pixels to the renderer and then the renderer can only draw the visible tiles (this is how it works with the current `MapRenderer` implementations). Then you can check the code in the `IsometricMapRenderer` to see how it draws just the tiles in the given rectangle.

It sounds like you'd prefer this approach. Do I understand correctly that this work would be done in IsometricRenderHelper::addTilesToNode() in that case?

> I can't currently explain that glitch either though. I'd also expect a different result. Maybe I can play with it a bit tomorrow.

Thanks for fixing that!

**Comment by mitchcurtis** [comment]
Well that was easier than I expected... copying the code from IsometricRenderer::drawTileLayer() worked well. With https://github.com/mitchcurtis/tiled/commit/bd119e643cea4c294679b20fa59ae69a8acadd0b it's almost perfect.

![tiled-2769-tiny](https://user-images.githubusercontent.com/6002340/76790849-e795f380-67bf-11ea-9e3b-a7c73aa1b9bd.gif)

There is still some red showing through when moving the map from left to right and vice versa.

**Comment by bjorn** [comment]
> Well that was easier than I expected... copying the code from IsometricRenderer::drawTileLayer() worked well. With [mitchcurtis@bd119e6](https://github.com/mitchcurtis/tiled/commit/bd119e643cea4c294679b20fa59ae69a8acadd0b) it's almost perfect.

Ah, nice work!

> There is still some red showing through when moving the map from left to right and vice versa. Do you know where I'd fix that? Or why it's not a problem for the widget-based rendering path?

Could it just be an updating issue? The `update()` call only happens when `mVisibleTiles` changes, but this member is not used for the isometric rendering case.

Of course, this was also an optimization, which will not work when we work with the visible area in pixels.

**Comment by bjorn** [comment]
Btw, I wonder if it would make sense to adjust the `MapRenderer::drawTileLayer` signature so that it would take an abstracting interface or callback through which tiles are rendered, which would have scene graph and QPainter implementations. This could even help enabling export of isometric maps to GameMaker 1.4 format, which needs to write out XML elements representing each tile.

**Comment by mitchcurtis** [comment]
> Btw, I wonder if it would make sense to adjust the `MapRenderer::drawTileLayer` signature so that it would take an abstracting interface or callback through which tiles are rendered, which would have scene graph and QPainter implementations. This could even help enabling export of isometric maps to GameMaker 1.4 format, which needs to write out XML elements representing each tile.

Yeah it seems a bit silly to duplicate the code. I can try, but no guarantees. :p

**Comment by mitchcurtis** [comment]
Before I spend any more time on this, is that what you had in mind?

https://github.com/bjorn/tiled/commit/196ae9d811004d0a236696b79e65531e87a7320f

**Comment by bjorn** [comment]
> Before I spend any more time on this, is that what you had in mind?

Yeah, exactly! Two things which come to mind:

* The `QPainter` argument should be removed.
* To avoid having to update a lot of existing code like `tmxviewer.cpp` and various places in Tiled, you should keep the version with the current signature that routes the calls to the `CellRenderer`.

In addition, there is a bunch of logic in `CellRenderer` that handles the various flipping flags, which would be nice to share as well somehow. But let's do this one step at a time. The `CellRenderer` also handles rendering of missing tiles and tile collision shapes. We'll have to see how to best handle those things later. :-)

**Comment by mitchcurtis** [comment]
Is it OK to call CellRenderer::flush() if the overload of OrthogonalRenderer::drawTileLayer() that takes the RenderTileCallback returns early (i.e. nothing was drawn)?

**Comment by mitchcurtis** [comment]
Almost there, but I have an issue:

https://github.com/bjorn/tiled/commit/55572e6a1315ca830611ce95da31b3b8c7e35397#diff-549a459c3d8ce7cb85758e9418548567R262

Do you know how I can get the tile pos? Converting there feels inefficient and the visual result is also wrong... the map is rendered in an incorrect position...

**Comment by bjorn** [comment]
> Is it OK to call CellRenderer::flush() if the overload of OrthogonalRenderer::drawTileLayer() that takes the RenderTileCallback returns early (i.e. nothing was drawn)?

Sure, then it should exit early:
```c++
    if (!mTile)
        return;
```

However, you can remove that call entirely, since `~CellRenderer()` already calls `flush()`.

> Do you know how I can get the tile pos? Converting there feels inefficient and the visual result is also wrong... the map is rendered in an incorrect position...

You should not need the tile pos. Just change `appendTileData` to take the `const Cell &cell` and `const QPointF &screenPos`, replacing the local variables it has for this.

**Comment by mitchcurtis** [comment]
Hmm... I've made those changes you suggested but it still renders weirdly...

**Comment by bjorn** [comment]
@mitchcurtis Can you please open a pull request? It would make collaboration a bit easier. :)
