### ISSUE TITLE
[Windows 10] missing DLLs/symbols on Windows - Crash on startup

### ISSUE THREAD

**Issue by freds72** [bjorn/tiled#2770]
Installed Tiled 1.3.3 from Itch on Windows 10
Launching from Start Menu or command gives unable to find symbol errors:
- setDtdEnabled@MapWriter@Tiled@@QEAAX_N@Z
- staticMetaObject@QGraphicsEffect@@2UQMetaObject@@B

Tried launching with --disable-opengl, same error.

**Comment by bjorn** [comment]
That is probably caused by an issue in the installer, which can cause a mismatch between the Tiled executable and `tiled.dll`. Please try to uninstall all versions of Tiled and then install Tiled 1.3.3 again.

**Comment by freds72** [comment]
Indeed - I had a very old version that has not been detected by recent installer.
