### ISSUE TITLE
The link to the tmx-map-format page is broken

### ISSUE THREAD

**Issue by maxymoo22** [bjorn/tiled#2776]
On [this](https://github.com/bjorn/tiled/wiki/TMX-Map-Format) page, the link to the [tmx map format](http://doc.mapeditor.org/reference/tmx-map-format/) is broken. Is this an actual issue or am I just looking for the wrong thing?

**Comment by bjorn** [comment]
It appears the DNS server on the domain got turned off due to my funds running out (it's prepaid), so all `mapeditor.org` lookups are broken. I'll get it back as soon as possible...

**Comment by bjorn** [comment]
Alright, it should be working again since about 4 hours now. Thanks for opening an issue about it!
