### ISSUE TITLE
Map not centered in view after closing and reopening the application

### ISSUE THREAD

**Issue by theNestruo** [bjorn/tiled#2779]
Hi @bjorn !

Working on a map (nothing special, 32x24 tiles of 8x8 pixels, no objects). The maps is centered in the window (Ctrl+/, Ctrl+- a couple of times):
![tiled-bug-0](https://user-images.githubusercontent.com/12213477/79640425-d90d7400-8191-11ea-986c-1787dd8bb850.png)

If I close Tiled, the next time I open it, the map is not centered anymore (and by a fair amount). The only user interaction has been closing Tiled, and opening it again:
![tiled-bug-1](https://user-images.githubusercontent.com/12213477/79640435-e0348200-8191-11ea-8f1b-299a5a79c77d.png)

Issue #2213 was apparently similar, but it is closed and, actually, CTRL+R works fine.
Also, at first I suspected about the lower right corner of the map being centered in the window, but the displacement is actually accumulative. If I close and open Tiled again:
![tiled-bug-2](https://user-images.githubusercontent.com/12213477/79640437-e591cc80-8191-11ea-8744-6afc560929fe.png)

This is my setup:
- Windows 10, Version 1909
- Tiled Map Editor 1.3.4 (but the issue has been happening a few months already)

_(This is not a particularly serious bug (Ctrl+/ kinda "solves" it)... but a little annotance. So feel free to de-prioritize it against other issues.)_

**Comment by bjorn** [comment]
@theNestruo Hmm, that's an annoying issue! I'll need to investigate, but in the meantime, can you check whether this is also broken for you in the "snapshot" version available on itch.io?

**Comment by theNestruo** [comment]
Yes, "Tiled-2020.04.10-win64" still exhibits the bug.
I'm going to try different snapshots to try to pinpoint the exact version, if that helps.

**Comment by bjorn** [comment]
> I'm going to try different snapshots to try to pinpoint the exact version, if that helps.

Hmm, might help, but I think I can already reproduce the issue, or at least a related problem. On latest master, each time I open Tiled the view has scrolled up a bit from where it was when I closed Tiled. Will need to investigate.

**Comment by theNestruo** [comment]
Something is very odd... I tried "Tiled-2018.01.01-win64.7z" (first 7z), "Tiled-1.2.4009-win64.msi" (latest 1.2), "Tiled-1.1.3413-win64.msi" (latest 1.1), and "Tiled-1.1.2977-win64.msi" (oldest snapshot available), and all of them are exhibiting the bug.

But I'm pretty sure I've used Tiled without this bug!

So I've started up my old computer with the latest 32bit snapshot available ("Tiled-2019.07.31-win32.7z")... and, despite the map is still moving around, it is almost unnoticeable (the displacement is (+18,+2) pixels). The same 32bit build, when executed in the current computer, exhibits the quite-noticeable version of the bug.

A composition using two screenshots to illustrate the displacement:
![Untitled](https://user-images.githubusercontent.com/12213477/79690524-27d31080-825b-11ea-8e0f-0b5ccf0e151e.png)

Main differences between both computers (in case it helps to locate the source of the issue):

- Windows 10 vs Windows 7 Starter
- AMD vs Intel; namely AMD Ryzen 3 (64bit) vs Intel Atom (32bit)

**Comment by bjorn** [comment]
Ok, that's rather strange. So there's no difference in DPI or window state or something like that which may affect this issue?

I expect to have time to dig into this issue on Tuesday.

**Comment by theNestruo** [comment]
No. Both computers are rather basic laptops without high DPI displays (1024x600? the old laptop and 1366x768 the new one), so the zoom is always set to 100%. And the issue happens either with a second monitor attached or just using the laptop display.
Neither laptop has applications that can interfere the window manager (such as PowerToys' FancyZones). Windows animations are disabled (I don't like them)... And I can't think of anything else that may affect windows metrics and/or state... :-/

I've just tested the latests snapshot in a different laptop (HP ZBook Worstation) where Tiled has never been installed, and the issue is not present (!?). I'm playing around with the preferences and the layout... but I cannot reproduce the isuse.

Where does Tiled stores the view on each particular map (so it is open with the same view it had when was closed)? Maybe that files/cache/etc. got corrupt?

**Comment by bjorn** [comment]
> I expect to have time to dig into this issue on Tuesday.

Hmm sorry, too many things came up, so it'll take a bit still. I should try harder not to make such predictions...

**Comment by theNestruo** [comment]
Don't worry! This is a little annoyance in an awesome application, and doesn't prevent me to work with it :)

**Comment by bjorn** [comment]
Found a fix for this issue yesterday. Note that it appeared to mostly affect maximized windows, so until a new release is out you could probably reduce the problem by not maximizing Tiled. :-)

**Comment by theNestruo** [comment]
Thanks! I hadn't even though about maximized windows, but you are right!!
