### ISSUE TITLE
Tiled Object 'rotation' attribute not accurate between docs and implementation

### ISSUE THREAD

**Issue by Beefy-Swain** [bjorn/tiled#2784]
https://doc.mapeditor.org/en/stable/reference/tmx-map-format/#object says:
>rotation: The rotation of the object in degrees clockwise around (x, y) (defaults to 0).

This is inaccurate. By default, the `rotation` attribute is absent for ALL object types. It only appears if the rotation is set to something other than `0`.

I understand (and probably agree) with the decision to handle the attribute this way, but it does not appear to me that the documentation is accurate, or at least is very misleading.

**Comment by bjorn** [comment]
If a default value is specified for an attribute, it implies that it is optional. When the `rotation` attribute is absent, its value defaults to 0. When an attribute is required, then there would be no point in specifying a default value.

Maybe it is worth noting this somewhere at the start of the specification.

**Comment by bjorn** [comment]
Ah, a note is already there:

> "All optional attributes are either marked as optional, or have a default value to imply that they are optional."

**Comment by Beefy-Swain** [comment]
@bjorn what page is that text present on? I was unable to find it.

**Comment by Beefy-Swain** [comment]
Found it: https://doc.mapeditor.org/de/latest/reference/tmx-map-format/#
