### ISSUE TITLE
Suggestion: Support right-click menu to add custom properties

### ISSUE THREAD

**Issue by pvcraven** [bjorn/tiled#2796]
On large screens, this '+' button can end up being far down from the custom properties bar, making it hard to figure out:

<img width="472" alt="add_custom_properties" src="https://user-images.githubusercontent.com/1463116/81831591-25cf3b00-9503-11ea-910d-c361d611d9f0.png">

I'd suggest also supporting the ability to right-click on the custom properties bar and white space for a pop-up menu to add custom properties.

**Comment by bjorn** [comment]
Thanks for the suggestion, the action will be available in the next release and development snapshot!
