### ISSUE TITLE
Scripting API cannot get default value for inherited property from typed tile for tile object

### ISSUE THREAD

**Issue by laqieer** [bjorn/tiled#2798]
![image](https://user-images.githubusercontent.com/8841957/81912675-7c22a380-9601-11ea-9e49-1d7d756e01b8.png)
Grey values such as AI4 are not accessible via API: object.property("AI4"). Only black values (changed) such as AI2 are accessible.

**Comment by bjorn** [comment]
This was added with change a838c492c58f4a317ddc536c8cb2cb7e31d77da6 (PR #2813), API is available in Tiled 1.4.
