### ISSUE TITLE
[feature] REST calls through JS API

### ISSUE THREAD

**Issue by alaa-eddine** [bjorn/tiled#2799]
Hi,
I just seen that Tiled now provides a JS API and that's awesome !
I was wondering if some network extensions are planed, to allow GET/PUT request through JS API ?
I think that such feature could open many possibilities like communication with a local nodejs server or a remote server to update game information live while editing... 

anyways, I played a little bit with the source code and was able to add a simple command to the api that fetches a url and returns a result.
it's a quick and dirty code, just added it to tiled ScriptModule it works fine with http requests but not https.

I can maybe send a contribution, but I'd like to know if it makes sens to add such feature directly to "tiled" object (tiled.fetch ? tiled.get ?), or create a new object : for example an http like nodejs ?

my Qt skills are very (very) limited, but such code is quite simple to implement.

if you think that this feature could help Tiled users, and is not planed, just tell me where I should add it, and I'll send a PR :)

**Comment by bjorn** [comment]
Actually this should already work through the `XMLHttpRequest`. Did you give that a try?

**Comment by alaa-eddine** [comment]
oh I didn't know that XHR is available :D 
yeah it works fine thank you !

I just realized that it's using an ES7 engine, that's awesome !

**Comment by bjorn** [comment]
@alaa-eddine Yep, actually the JavaScript engine used by Qt is V8. :-)
