### ISSUE TITLE
Scripting:  BinaryFile in WriteOnly mode gives `IODevice is not open`

### ISSUE THREAD

**Issue by geoo89** [bjorn/tiled#2801]
Trying to commit changes to a `BinaryFile` that was opened in `WriteOnly` mode gives a warning `QFileDevice::seek: IODevice is not open`. At least on my Linux machine, it does seem to write to the file anyway, but apparently in Windows it does not (or at least not always).

TextFiles in WriteOnly mode and BinaryFiles in ReadWrite mode seem to work without warnings or problems.

The code below provides a minimal example. I tested this with the snap version snapshot 1506, as well as the precompiled Linux snapshot version 2020.05.07. OS is Ubuntu 18.04. Apparently it also happens on Windows with the 2020.05.07 version (cannot test myself though).

To run the example, save the code as test.js and put it in Tiled's extension folder.
Create a blank (or any) file with a .test extension (its contents are ignored), and try to open it in Tiled. The script will try to save 3 files in the same folder as the .test file; a TextFile in WriteOnly mode, a BinaryFile in ReadWrite mode, and a BinaryFile in WriteOnly mode. The first two succeed while the last one give the aforementioned warning.

```
var testMapFormat = {
    name: "Test format",
    extension: "test",

	// Script that is executed when opening a file with a .test extension,
	// and that creates three new files with .test1, .test2 and .test3 extension.
	read: function(fileName) {
		data = new Uint8Array(2);
		data[0] = 0x33;
		data[1] = 0x99;

		tiled.warn("Writing TextFile.")
		var file1 = new TextFile(fileName + "1", BinaryFile.WriteOnly);
		file1.write("Test");
		file1.commit(); // Works fine

		tiled.warn("Writing ReadWrite BinaryFile.")
		var file2 = new BinaryFile(fileName + "2", BinaryFile.ReadWrite);
		file2.resize(0);
		file2.write(data.buffer);
		file2.commit(); // Works fine

		tiled.warn("Writing WriteOnly BinaryFile.")
		var file3 = new BinaryFile(fileName + "3", BinaryFile.WriteOnly);
		file3.write(data.buffer);
		file3.commit();  // Gives QFileDevice::seek: IODevice is not open

		return new TileMap();
	},

	write: function(map, fileName) {
	}
}

tiled.registerMapFormat("test", testMapFormat)
```

**Comment by geoo89** [comment]
Could it be related to the use of QSaveFile in 
https://github.com/bjorn/tiled/blob/a82eca638840d8c37db6fa8f44fa0318fe7999bb/src/tiled/scriptfile.cpp ?

For binary files, QSaveFile is only used in WriteOnly mode.
For text files, I assume it is never used, because the condition for its use is
```m == (QIODevice::WriteOnly & QIODevice::Text)```
and I assume `QIODevice::WriteOnly & QIODevice::Text` evaluates to 0. (Is the `&` meant to be a `|`?)

**Comment by bjorn** [comment]
> For text files, I assume it is never used, because the condition for its use is
> `m == (QIODevice::WriteOnly & QIODevice::Text)`
> and I assume `QIODevice::WriteOnly & QIODevice::Text` evaluates to 0. (Is the `&` meant to be a `|`?)

Whoops, good catch!

So then, it remains to be investigated what we're doing wrong with `QSaveFile` that causes this issue.
