### ISSUE TITLE
v1.3.5 is damaged on macOS; damaged bundle-identifier; all Info.plist values full of unreplaced placeholders

### ISSUE THREAD

**Issue by core-code** [bjorn/tiled#2811]
something didn't work at all with the macOS portion of this release:

<img width="490" alt="Screenshot 2020-05-28 at 11 17 08" src="https://user-images.githubusercontent.com/1261954/83123073-d11bea80-a0d4-11ea-8f68-cb26f3431ce0.png">

**Comment by core-code** [comment]
<img width="254" alt="Screenshot 2020-05-28 at 11 18 00" src="https://user-images.githubusercontent.com/1261954/83123173-e8f36e80-a0d4-11ea-922c-cbdcb2a93f64.png">
![Uploading Screenshot 2020-05-28 at 11.17.08.png…]()

**Comment by core-code** [comment]
it cannot even be launched because the "Executable file" entry in the Info.plist is also damaged

**Comment by bjorn** [comment]
I'm sorry for the trouble! Indeed it appears the package broke entirely due to an upgrade in the build system. I'll need to figure out if there's something on Tiled's side that should be updated or whether it's better to just downgrade the build tool again for now.

**Comment by core-code** [comment]
no problem thanks for the quick turnaround with pulling the release.

**Comment by bjorn** [comment]
Issue should be fixed in updated release build: https://github.com/bjorn/tiled/releases

I've reverted back to using Qbs 1.14 for now because I couldn't immediately figure out why this is breaking with 1.16 (2a38b6accb23e465bc1bd8796735fa2a031f90ef).
