### ISSUE TITLE
Add Tiled to WinGet Repository

### ISSUE THREAD

**Issue by MikuAuahDark** [bjorn/tiled#2816]
It would be a good idea to add Tiled to WinGet [repository](https://github.com/microsoft/winget-pkgs).

If you don't know, [WinGet](https://github.com/microsoft/winget-cli) is Windows's package manager. It's currently in preview but it looks promising.

So, why not?

**Comment by bjorn** [comment]
I don't see any reason not to have it there. Would you like to help set it up?

The entry for Tiled should probably be something like this:

**`manifests/Tiled/Tiled.yml`**
```
Id: Tiled.Tiled
Publisher: Tiled
Name: Tiled
AppMoniker: tiled
Version: 1.3.5
License: GPL 2.0 or later
Tags: "tiled, tilemap, editor, foss, cross-platform, gamedev, graphics"
FileExtensions: "tmx, tsx"
Description: Free, easy to use and flexible level editor.
Homepage: https://mapeditor.org/
InstallerType: msi
Installers:
  - Arch: x64
    Url: https://github.com/bjorn/tiled/releases/download/v1.3.5/Tiled-1.3.5-win64.msi
    Sha256: f60fdca64b54ce22697cd6d254de6fd89112486dd8fbe24f4dbfb0c529e11af1
ManifestVersion: 0.1.0
```

**Comment by bjorn** [comment]
Note that in the meantime, Tiled is also available on [Chocolatey](https://chocolatey.org/packages/tiled).

**Comment by MikuAuahDark** [comment]
Yep, that looks like pretty much it.

**Comment by bjorn** [comment]
Alright, I've submitted the file, had to fix two problems that only their CI system reported and now it's awaiting manual review.

**Comment by bjorn** [comment]
Done. :-)
