### ISSUE TITLE
'infinite' attribute missing from map object in TMX Map Format documentation

### ISSUE THREAD

**Issue by ThirdPartyNinjas** [bjorn/tiled#2817]
I was updating my tmx importer to 1.3, and I noticed that the documentation on the web doesn't have the attribute for infinite that I'm seeing in the saved file.

Let me know if you need anything else. Thanks!

**Comment by bjorn** [comment]
Ah, actually this attribute has been documented in the meantime, but it is only available in [the latest version of the documentation](https://doc.mapeditor.org/en/latest/reference/tmx-map-format/#map). The "stable" only updates when I push a new tag (so it will soon update when I tag `v1.4.0`).
