### ISSUE TITLE
Wrong encoding in session file path

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#2819]
I noticed right now that Tiled writes the session to the path [...]/Arbeitsfl�che (invalid encoding)/[...] instead of [...]/Arbeitsfläche/[...]. It seems it handles umlauts and maybe other non-ASCII-characters in the session save path wrongly ($ls says the directory name is 'Arbeitsfl'$'\344''che') . It did work properly in snapshot-2020.04.10. Tiled recreates the original directory structure (only folders, all empty but **the** session file).

_Originally posted by @paaaav in https://github.com/bjorn/tiled/issues/2809#issuecomment-634905644_

**Comment by bjorn** [comment]
@paaaav So this issue happens on Windows? I wonder why it tries so save to a folder named "Arbeitsfläche" at all, since normally the default file name for the session is `C:\Users\USER\AppData\Roaming\Tiled`.

Or is this a session saved alongside a project on your desktop?

I'm also a little confused by your usage of Linux tools like `valgrind` and `ls` on Windows. Could that be related to this issue? Or is the problem happening with Tiled also outside the context of these tools?

**Comment by paaaav** [comment]
Thanks for the issue. 
Sorry, no, this is on Linux, I should have been more specific. The path starts with `/home/pav/Arbeitsfläche/Projekt/xxx`. In the project directory the files xxx.tiled-project and xxx.tiled-session exist alongside the tmx-map.

$ls would say, that Tiled creates the path /home/pav/Arbeitsfl'$'\344''che'/Projekt/xxx instead when saving the session file (all other files are in the correct directory). Mate Desktop Environment would interpret this folder name as "Arbeitsfl�che (invalid encoding)".

I've seen the issue once in another machine not at home, when a Windows network drive was mounted strangely on Linux. But on this machine, no, there are no such encoding issues. Everything afaik is UTF-8 here.

$cat /etc/issue
Ubuntu 20.04 LTS \n \l

**Comment by bjorn** [comment]
Well, I also see this issue on my own Ubuntu 20.04 install. Strange enough, it created the session file both with the right encoding and with the wrong encoding. And it seems to read the correct one but write the wrong one. :-S

I added the following code to debug this to the constructor:
```c++
    qDebug() << Q_FUNC_INFO;
    qDebug() << fileName;
    qDebug() << this->fileName();
```

Then the following to the destructor:

```c++
    qDebug() << Q_FUNC_INFO;
    qDebug() << this->fileName();
```

The output was:
```
Tiled::Session::Session(const QString&)
"/home/bjorn/Arbeitsfläche/test-encoding.tiled-session"
"/home/bjorn/Arbeitsfläche/test-encoding.tiled-session"
Tiled::Session::~Session()
"/home/bjorn/Arbeitsfl�che/test-encoding.tiled-session"
```
So, somewhere in between, the file name's encoding is getting messed up. At the moment I have no idea why. :-/

**Comment by paaaav** [comment]
Well, thank you. I'm sure some time you will find out. I'm very happy that you could reproduce it.

**Comment by bjorn** [comment]
It appears to be related to the moment on which the session is deleted, which is likely after Qt already de-initialized some encoding-related stuff. Fix is probably to destroy the session before the application.

**Comment by bjorn** [comment]
Should be fixed now. Thanks for trying out the snapshot and reporting this issue!
