### ISSUE TITLE
JSON Map renderorder is not only for "orthogonal maps"

### ISSUE THREAD

**Issue by LazyMechanic** [bjorn/tiled#2827]
In docs for JSON Map format `renderorder` is "orthogonal maps only", but if I create any type of map this field will exist. It is in docs mistake or in app?

![image](https://user-images.githubusercontent.com/10794989/84376867-6a292600-abea-11ea-8cc7-79343a2cdd55.png)

**Comment by bjorn** [comment]
The documentation could definitely be more clear about this.

What is meant, is that the property is currently only supported for orthogonal maps. It will not affect the rendering order for tile layers on maps of other orientations. That doesn't mean the property isn't saved at all.
