### ISSUE TITLE
defining objects and placing them

### ISSUE THREAD

**Issue by BBQGiraffe** [bjorn/tiled#2830]
it would be nice if there was a window where you could create objects such as a  Zombie and assign it a sprite so you can visualize it in the editor, then you could select that object in the window and place it, this would make placing objects much more efficient

**Comment by Mattincho** [comment]
What about tilset objects?
You can create a tileset using several images (sprites) or a spritesheet image. Then, using the Tileset Editor (similar to the 'window' you described) you can add properties, a custom type, colliders, and you even can use the 'Tile Animation Editor', to visualize an animation, for the object, when you are placing it on the map.
Once you have your tileset created, you can go back to your map, select your tile object, and place them in an object layer.

Is that what you are looking for?

**Comment by BBQGiraffe** [comment]
ah yes,  I had no idea this was a feature, thanks mate
