### ISSUE TITLE
Tiled program firstpage is not translated.

### ISSUE THREAD

**Issue by lahtis** [bjorn/tiled#2831]
The program has been translated 100% into Finnish and will not change on these front pages.
Maybe bug in the code. 

attacment in first page. 
![Kuvakaappaus 2020-06-15 19-14-31](https://user-images.githubusercontent.com/1613549/84681349-a89d4880-af3c-11ea-8c00-e0b4470279cb.png)

**Comment by bjorn** [comment]
I think I probably affected the translation context for these strings without realizing it. In the code it's currently `NoEditorWidget` whereas the translations are in `Tiled::NoEditorWidget` context.

In addition, there is a call to `retranslateUi` missing in the constructor, causing half of the strings to not be translated on startup at all.

Thanks for bringing this up!
