### ISSUE TITLE
static build with 5.14.2 error Win7 VS2017

### ISSUE THREAD

**Issue by warsark** [bjorn/tiled#2834]
System:Win7 X64
Compiler:VS2017
Target Platform:32 bit
1.I compiled qt 5.14.2 with 32bit static
2.QtCreator add new kits with the new static library
3.build tiled with new kit,error(when use the new kit build new project will success)
error  occur in build libtiled:
\libtiled.080f31f8\Qt5Cored.lib(qglobal.obj): error: LNK2038: detected “RuntimeLibrary” is not matching: value“MTd_StaticDebug” not matching value “MDd_DynamicDebug”(compression.cpp.obj)

**Comment by bjorn** [comment]
Hmm, I've never tried doing a static build myself. It looks like the error is about a mismatch between the runtime library used when compiling Qt vs. the one used when compiling Tiled. However, I have no idea how one would fix this error.

If you're interested in helping to get this working, I would suggest you first try to get a simple example program compiling against the static Qt (using Qbs). If that works, you can try to find out how Tiled is different from your simple example.

**Comment by warsark** [comment]
read qbs doc,I find the solution,add below text to all qbs file!
    Properties 
    {
        condition: Qt.core.staticBuild
        cpp.runtimeLibrary: 'static'
    }

**Comment by bjorn** [comment]
@warsark Ah, that's interesting. I wonder if there's a reason this setting doesn't change automatically.

Would you like to open a pull request for this change?
