### ISSUE TITLE
Composite tile sets

### ISSUE THREAD

**Issue by craxal** [bjorn/tiled#2837]
I'd like to be able to make composite tile sets using tiles from other sets.

This feature would reduce the tedium of drawing a full set of terrain boundary tiles (as an example). Similarities in parts of such tiles suggest they can be build from a more "atomic" set of tiles. A smaller set of tiles often makes a great starting point for building more complex tiles with less raw image data.

A good example of a game that takes this approach to tile building is the classic _The Legend of Zelda: A Link to the Past_. That game is built from 16x16 tiles, but each of those tiles are composited from four 8x8 tiles.

I imagine a composite tile set could be created similarly to a tile set that is built from collections of source images. But rather than having a source image, it could have source _tile sets_. You can add a tile, specify its dimensions, and paint the tile using tiles from source sets similarly to maps.

**Comment by bjorn** [comment]
In Tiled 1.4, you can use a map as the source image of a tileset. I think that should cover your needs. This was the resolution to the metatile issue #1421, though unfortunately it is not documented yet (#2744).

**Comment by craxal** [comment]
Wow, just released! The feature is looking promising, so I'll play around with it. It looks like my feature requests is a duplicate of #1421, so you can close this if you want.

**Comment by bjorn** [comment]
Sure, I'll close this one then.

And please let us know how it goes! I haven't received any feedback yet from users of this feature, apart from a small bug report today, since apparently some pixels can get lost.
