### ISSUE TITLE
Lua export object property syntax error

### ISSUE THREAD

**Issue by IoriBranford** [bjorn/tiled#2839]
```lua
properties = {
  "fleetriggerid" = { id = 582 }
}
```

It should be
```lua
properties = {
  ["fleetriggerid"] = { id = 582 }
}
```
or
```lua
properties = {
  fleetriggerid = { id = 582 }
}
```

Other property types are written correctly.

**Comment by bjorn** [comment]
Arg, I wasn't paying enough attention here apparently! This was a last minute change I made to close https://github.com/bjorn/tiled/issues/2812#issuecomment-636381463 before making the release. I'll make sure to fix it asap.
