### ISSUE TITLE
Metatile Alignment Issue

### ISSUE THREAD

**Issue by Phlosioneer** [bjorn/tiled#2843]
Hey, having a weird issue with the metatile feature. When using the tmx file as the base image, it's drawing the tiles incorrectly.

I made a "ruler" texture to see which pixel is being left out. This is how it renders, compared to the original ruler.
![Untitled](https://user-images.githubusercontent.com/4657718/85348183-cfbdc200-b4c8-11ea-867c-e1aaeff4a8dd.png)
It's deleting a column in the middle of the second sub-tile, which is really strange.
I'm using version 2020.06.12, the current latest build available from the website.

I've attached the files to reproduce this error below. I've checked and double-checked that the width and height properties are correct; I've tried re-importing it, too.

The same issue was present on the 2020.02.?? build, don't remember the day part of the build date.

Exporting the map file to an image and using that as a tileset works correctly, and that's my current work-around.
[test_case.zip](https://github.com/bjorn/tiled/files/4816272/test_case.1.zip)

**Comment by bjorn** [comment]
Thanks for the report! With your test case I was quickly able to find out what was going wrong. :-)
