### ISSUE TITLE
Tiled crashes when cutting or deleting two or more objects

### ISSUE THREAD

**Issue by squishyu** [bjorn/tiled#2844]
#### Steps to reproduce

- Select an object layer *with a manual drawing order*
- Select at least two objects by clicking on them while holding ctrl
- Delete or cut them (del or ctrl+x)

#### Expected behavior

- Well, delete and cut

#### What actually happened

- Tiled crashed.

#### Info

- Tiled version: **2020.06.20**
- OS: Deepin 20 Beta (Debian based Linux distro)

**Comment by squishyu** [comment]
My girlfriend just confirmed the same happens on Windows 10.

**Comment by bjorn** [comment]
Thanks for the report! Apparently this was broken even in Tiled 1.3, which goes to show how few people discover the manual drawing order feature (and how little testing it gets, also from me...).

I plan to release a Tiled 1.4.1 today that will include the fix.

**Comment by UliAbo** [comment]
I did also experience that bug because I used manual drawing order (it's really important to me). I'm just writing this to confirm that I'm one of those few people loving this feature to have manual drawing order^^
