### ISSUE TITLE
JSON Export from Command Line in 1.4 broken

### ISSUE THREAD

**Issue by rwetzold** [bjorn/tiled#2847]
I updated from 1.3.5 to 1.4.0 and in there the JSON export through the command line does simply do nothing. The same command line executed for 1.4 gives no output and no file. Switching back to 1.3.5 makes it work again.

"C:\\Program Files\\Tiled\\tiled.exe" --export-map JSON --embed-tilesets --resolve-types-and-properties "c:\\unity\\SDKTest\\Assets\\Levels\\HelloWorld\\Data\\Intro.tmx" "c:\\unity\\SDKTest\\Assets\\Levels\\HelloWorld\\Data\\Intro.tmx.json"

**Comment by bjorn** [comment]
Yeah, that was some serious breakage, sorry about that! It's already fixed (see #2842) and a Tiled 1.4.1 will be out as soon as possible. Thanks for using Tiled!
