### ISSUE TITLE
Zooming in sometimes changes position of view

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#2853]
Reporting this here because I think the bug is still there, though though the cause may be different.

## Version

Using Tiled 1.2.4. Windows 7 SP1.

## Problem
Zooming in on mouse cursor works between 5% up to 50% zoom. Beyond 50%, the zoom focus tends to go *upper-left* corner.

However, if the current view includes the upper-left corner of the map, then zooming works as expected

## Video
Please see this [video](http://faulknermano.com/pub/tiled/zoom_bug_2019_06_25_1.mp4)

- No offset applied to map.
- First part of video demonstrates zooming around the center of the map (i.e. upper-left corner of map is not visible). Notice it works when zooming between 5% to 50%.
- Second part of video demonstrates when zooming around the upper-left corner of map (corner is visible). Zooming to any zoom level works.
- This happens both with mouse wheel zoom or keyboard shortcut zoom.

---

Hope this helps. Thanks!

_Originally posted by @faulknermano in https://github.com/bjorn/tiled/issues/2090#issuecomment-505257487_

**Comment by bjorn** [comment]
@faulknermano I've created a new issue because I just ran into your comments on #2090 and I think this is better than reopening that issue, because I'm pretty sure something else is going wrong here.

I'm also wondering, if this issue is still happening for you in Tiled 1.4.1?

**Comment by faulknermano** [comment]
Hi @bjorn pardon late reply. It seems -- happily -- that the zoom view bug is no longer present (at least from the pov of my own report) using 1.4.1. :-D Thanks!

**Comment by bjorn** [comment]
@faulknermano Alright, thanks for testing! Please feel free to reopen this issue if it turns out it still happens sometimes. I don't know right now what might have fixed it, but let's hope it's gone. :-)
