### ISSUE TITLE
Keep imported image IDs

### ISSUE THREAD

**Issue by diogoeichert** [bjorn/tiled#2887]
When importing image collections for a new tile set, sequential IDs are attributed, e.g. 0, 1, 2, etc. But when the original image files already have the correct IDs the game engine expects, e.g. 10.png, 20.png, etc. it would be more convenient to keep those. It would be nice in these cases to have the option to keep the ID based on the file names, so that when the map is exported, it already contains the final correct IDs, without having to cross-reference with the tile set again.

Just for more clarification, the final map format I need is a plain matrix, e,g.

```
const map = [
	["12", "12", "12", "12", "01", "26", "23", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12"],
	["12", "12", "12", "12", "01", "26", "23", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12"],
	["01", "34", "12", "12", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01"],
	["31", "22", "23", "01", "01", "32", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31"],
	["12", "12", "12", "33", "01", "26", "23", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12"],
	["01", "34", "12", "12", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01"],
	["31", "22", "23", "01", "01", "32", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31"],
	["12", "12", "01", "01", "01", "26", "23", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12"],
	["01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01", "01"],
	["31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31", "31"],
	["12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12", "12"],
	["00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00", "00"]
],
```

So I'm still trying to find Tiled's best export format to do minimal post conversion.

**Comment by bjorn** [comment]
> So I'm still trying to find Tiled's best export format to do minimal post conversion.

In this case, the best export format will be the one you implement yourself, which you can do by [writing an extension in JavaScript](https://doc.mapeditor.org/en/latest/reference/scripting/). In particular, check out the example for [`tiled.registerMapFormat`](https://doc.mapeditor.org/en/latest/reference/scripting/#script-registermapformat). This way, you will not need any post conversion.

**Comment by diogoeichert** [comment]
Fantastic! I'll have a look on those. Closing the issue now, thanks.

**Comment by diogoeichert** [comment]
One more question, please. In [this particular example](https://doc.mapeditor.org/en/latest/reference/scripting/#script-registermapformat), how can I get the Image name from the tile used in the cell? Thanks again.

**Comment by bjorn** [comment]
@diogoeichert Ah, right, for getting the image name you first need to get the tile object, which you can currently get using `TileLayer.tileAt` instead of `TileLayer.cellAt` (unfortunately there's no way to get the tile reference from the cell currently, hence the additional function). One you have the tile reference you can get its `imageFileName` property and use `FileInfo.baseName` on it.

**Comment by diogoeichert** [comment]
Splendid! Thank you very much!
