### ISSUE TITLE
Template instances's width and height "reset" itself after relaunch 

### ISSUE THREAD

**Issue by Pordrack** [bjorn/tiled#2889]
Hello, I use templates in a project to create NPC's and platforms elements, and then changes their tiles to my liking. When I do that, the resulting object has a sprite, and a perfectly normal width and height, however after a relaunch, the object is "deformed" to have the width and height of the original template's sprite. Sure, I can detach every instances I create, or manually changes their width and height, but it's a little tedious and annyoing over time. I don't know if it's really an issue, but still think it would be nice to have templates with "dynamic dimensions".

**Comment by bjorn** [comment]
Hmm, this seems to be because the template's size is based on the original tile, and when you change the tile of an instance it only remembers that the tile has been overridden, but then it still inherits the size from the template.
