### ISSUE TITLE
Changing object stacking order

### ISSUE THREAD

**Issue by batblaster** [bjorn/tiled#289]
When i have 2 objects one up to another and consider that 1 is larger than the other there is a way to change the priority ? to change the position of the lowest i need to move the one in front and after i can move or edit the second, there is a way to bring it to front or is possible to add a way to move in front or back to another ?

Thanks.

**Comment by bjorn** [comment]
Support for manually controlled the object stacking order was added back in Tiled 0.10, so I'll close this issue. To use this feature, you do need to change the "Drawing Order" to "Manual" in the object layer properties.
