### ISSUE TITLE
Clear console not redrawing console area under MacOS

### ISSUE THREAD

**Issue by elmm** [bjorn/tiled#2908]
When "Clear console" is pressed in the editor in 90% of cases console area is not updated.
A content of the console is removed - so text selection not possible, but in the console area, a previously visible part of the log is drawn.
Minimizing/maximizing, extending the editor window, or dragging the console tab is forcing that area to be redrawn to an empty state.

Editor version: 1.4.2.
Platform: MacOS Catalina 10.15.7

**Comment by bjorn** [comment]
Since this is likely an issue in Qt rather than Tiled, could you please try whether Tiled built against Qt 5.15 (rather than 5.12, like the current releases) still has this issue? You can download a recent build at https://github.com/bjorn/tiled/actions/runs/292305150. Thanks!

**Comment by elmm** [comment]
The issue isn't observed any more with the build based on Qt 5.15
