### ISSUE TITLE
Import tile map from command line

### ISSUE THREAD

**Issue by elmm** [bjorn/tiled#2919]
Some small feature request.

I have a custom map format and want to make some integration with Tiled in my game editing pipeline.
It would be nice to be able to open in Tiled a map in custom format from a command line.
At this moment I didn't find options for this purpose.

**Comment by bjorn** [comment]
Hmm, files mentioned on the command line are loaded after the plugins and extensions are loaded, so if you have written a custom format it should generally work automatically just by running `tiled mymap.customformat`.

Did you try it? If so, what problem did you run into?

**Comment by elmm** [comment]
I can't find in documentation or editor's command line help a way how to say to the editor which plugin should be used to read map format.
PS: I use my custom JSON format so a map file has a ".json" extension and can't be used to distinguish from other map formats.

**Comment by bjorn** [comment]
@elmm Ah, in case of ambiguous extension there is currently no way to force a certain format from the command-line. If it is an option for you, consider disabling the native JSON plugin to make the extension no longer ambiguous. Then you can also more easily open your files from the Project view.

Looking at the code, actually the native JSON plugin does the following checks to see if it supports the .json file:

```c++
        const QJsonObject object = QJsonDocument::fromJson(contents).object();

        // This is a good indication, but not present in older map files
        if (object.value(QLatin1String("type")).toString() == QLatin1String("map"))
            return true;

        // Guess based on expected property
        if (object.contains(QLatin1String("orientation")))
            return true;
```

So, you could probably also avoid this plugin from loading your format if you make sure that it does not have `"type": "map"` property nor an `"orientation"` property.

**Comment by elmm** [comment]
Thank you 👍 

It works as you proposed!

**Comment by bjorn** [comment]
That's great!

I don't think it would help to introduce some kind of "open as format" option for the command-line since in general the right solution is to make the format not ambiguous, so I'll close this issue now.
