### ISSUE TITLE
Add support for Retina Display

### ISSUE THREAD

**Issue by memmaker650** [bjorn/tiled#295]
Hi

I'm new using the app but actually it looks a little bit weird in my Retina Display. I think it's not so difficult to make the icons with a bigger size to adapt the app for the Retina Display resolution.

Thanks in advance.

**Comment by bjorn** [comment]
Small update on this: I'm finally getting a 4K / UHD screen and will be making sure to fix any remaining issues when I see them. :-)

**Comment by bjorn** [comment]
Hmm, seems I forgot this issue pretty much after assigning it to myself. In any case, I had a quick look and at least having a 4K screen has helped me address a large amount of DPI issues:

bf136361ad332c1a5db9df0416a2dd1d6e01a2d9, bc31ee6177fb0513fe641df17d1e6d25b1d6e6f9, 1266d348c090c8ec674b52706709a2766a85d30a, 80a7317106e49baa5f97b458b72437a8fb3158a0, 27d89b1e4519eff5c565d44d3485754d9ea6c560, d0256874f57904f6638b19f2dcf0159d6e127b13, 341ebf5cbbc5b16173d022b583e51cfbc0f32be3, 468e6067e08e0b39355597b0cef311071df45df3, 6db4285f10872c747b8ce99493f893f30827038a, a8a0e9bac4bd6b680ca0fc57169e71fa97be9723, 1b45c7cff56183873feed15c771068f144a11782, c6cfaa074e6f6b1b8039b9d561a3e875aca4594e, 11c4e69b172e97f6c361aac6be304633a5b091e1, 2122d50377f6609855658ea0778b666bc5b821c0, 5c9b6d50751ba1e511d94dea18bbfc46aeacc4ed, 0886dea9dee6d127093dbf1625a4b462293e64a3, 0353a207d229ae3a803da3f8023f6dcd4791e70b, 5e338bc69928ed7159752bcbc1cad23eaa94bc28, 58995f7dbd1aa97c847ca24b875307608c74de3f

Unfortunately, there are still many icons without larger or scalable versions. There's a new issue #2835 about the icon sizes in particular, so I'll close this issue now.
