### ISSUE TITLE
More plugin interaction for new created maps

### ISSUE THREAD

**Issue by ufoai** [bjorn/tiled#299]
It would be nice if a plugin could hook into the creation of a new map. 

I would like to extend my plugin to be able to fill the world with random background tiles from my tileset

I would also like to set some map properties on map creation.

And last but not least i would like to create some default layers whenever someone creates a new map with my plugin installed.

It would really help me a lot if the plugin api would be a little bit more .... open or extendable.

**Comment by bjorn** [comment]
The current plugin approach is very limited and it will be hard to extend this approach much further. Instead, the plan is to make Tiled scriptable (issue #949). The following two things would need to be possible to resolve this issue:

* Ability to execute a script that fills the world with random background tiles.
* Ability to hook into a "New Map" event in a script, which sets some properties on the map and creates default layers.

**Comment by bjorn** [comment]
The [scripting API](https://doc.mapeditor.org/en/stable/reference/scripting/) that was added in Tiled 1.3 enables both of the above actions, so closing this issue.
