### ISSUE TITLE
Import/export tileset in any supported format

### ISSUE THREAD

**Issue by parasyte** [bjorn/tiled#381]
This is a feature request, now that JSON format maps are in development for melonJS. See: https://github.com/obiot/melonJS/issues/140

There's a little button on the Tilesets pane for exporting a tileset to a TSX file (XML). There's another little button for importing these files, as well. It would be handy if these features were backed by the plugin interface, to allow import/export of tilesets in any of the supported formats. Especially JSON. ;)

FYI, here's the tileset export function: https://github.com/bjorn/tiled/blob/master/src/tiled/tilesetdock.cpp#L650 Notice it uses a `TmxMapWriter` object directly.

Contrast with the map "Save As..." function: https://github.com/bjorn/tiled/blob/master/src/tiled/mainwindow.cpp#L734 which uses the plugin interface to export any supported format!

**Comment by bjorn** [comment]
Oh, this one was also closed by commit d6169b1e67192b1dd7cd0d026870afddbfef055b. :-)

So external tilesets in JSON format coming in Tiled 0.14!
