### ISSUE TITLE
SEGV on map close

### ISSUE THREAD

**Issue by o11c** [bjorn/tiled#385]
System: Debian wheezy amd64
Version: tiled 0.9.0-1 from experimental

After opening several maps and saving changes to one of them, I pressed ^W to close that map, and got this SEGV:

https://gist.github.com/anonymous/5145929

I have the coredump, but there are no debugging symbols available for the Debian package, and I am unable to reproduce casually.

**Comment by bjorn** [comment]
I'm going to assume this was fixed at some point in the past years, especially since I don't recall any similar reports.
