### ISSUE TITLE
libtiled-java and tmxviewer-java not in maven repository

### ISSUE THREAD

**Issue by jjYBdx4IL** [bjorn/tiled#397]
Hello!

Could you please put those two libraries into the maven repository? Would make handling licensing and dependencies much easier :-).

If you need me to write the pom.xml file, I'd be glad to help out.

Regards,
Mark

**Comment by tomcashman** [comment]
@bjorn or @mikepthomas I saw Maven Central publishing was merged in but seems like it's still not published with each release?

**Comment by bjorn** [comment]
@tomcashman I'm actually not sure what's required for this. I hope @mikepthomas can help.

**Comment by mikepthomas** [comment]
No releases have yet been made to maven central repository as of yet...
You are able to get a snapshot of release 0.17-SNAPSHOT from when I implemented on Oct 17 by adding the following to your maven pom: 
```
    <dependencies>
        <dependency>
            <groupId>org.mapeditor</groupId>
            <artifactId>libtiled</artifactId>
            <version>0.17-SNAPSHOT</version>
            <type>jar</type>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>sonatype-oss</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```
Ideally the java libs should be built out as part of the ci process using maven but but am unfamilliar with the current process (using Travis I believe...) also the assets deployed to the oss snapshots repository are currently signed using my personal pgp key, I'm not too sure if @bjorn would be happy with this as I'd expect that he would want them to be signed with his own...

**Comment by tomcashman** [comment]
What mvn commands are needed to deploy to Maven Central?

**Comment by bjorn** [comment]
Hmm, I'd have to set up PGP again. I did this several times now, but I keep locking myself out of my own keys by forgetting their passphrase, since I'm inclined to pick a long one and then never use it.

Regarding the CI system, it could be integrated with either Travis CI (Linux or macOS) or AppVeyor (Windows), depending on what would be the easiest. Both Travis CI and AppVeyor seem to have Maven preinstalled on their build image.

**Comment by mikepthomas** [comment]
Deploying to snapshots can easilly be done manually, I would have to look into how it integrate with the CI server (whichever is easiest) as for releasing to central this can be done with any of the deployed snapshots [using this guide](http://central.sonatype.org/pages/releasing-the-deployment.html).

**Comment by bjorn** [comment]
Requested [on the forum](http://discourse.mapeditor.org/t/is-libtiled-java-available-on-any-maven-server/2491).

**Comment by mikepthomas** [comment]
The libtiled and tmxviewer jars are now available in maven central:
http://central.maven.org/maven2/org/mapeditor/

You should now be able to request the jar using the following:

<dependency>
    <groupId>org.mapeditor</groupId>
    <artifactId>libtiled</artifactId>
    <version>0.17</version>
</dependency>

**Comment by jjYBdx4IL** [comment]
Cool. TY!
