### ISSUE TITLE
Add configurable layer height offset

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#4]
Some tilesets allow layers to be stacked to create varying heights. An example of such a tileset can be seen on Lost Garden:

http://www.lostgarden.com/2007/05/dancs-miraculously-flexible-game.html

Or for example this isometric outside tileset:

http://opengameart.org/content/isometric-64x64-outside-tileset

It would be nice if Tiled supported these kind of tilesets, by allowing maps to define a height offset between (tile) layers.

This issue replaces the following issue from the old issue tracker:
http://sourceforge.net/apps/mantisbt/tiled/view.php?id=88

**Comment by therahedwig** [comment]
Awesome! Next version is gonna be exciting!
