### ISSUE TITLE
Allow to close a poly line

### ISSUE THREAD

**Issue by wolfscaptain** [bjorn/tiled#404]
If an end point of a poly line is next to the starting point, it should snap to it to form a closed shape.

In addition, allow to join the starting and ending points of an already constructed poly line.

**Comment by bjorn** [comment]
In the current `master` version it is possible to close a polyline to make a polygon, either while creating it or while extending it (change aa8d7317c0e89da0a37fe020102db4dac361ee93). These improvements are scheduled to be released as part of Tiled 1.2, and are already available in the development snapshots.
