### ISSUE TITLE
Fix object name views

### ISSUE THREAD

**Issue by wolfscaptain** [bjorn/tiled#405]
1) Polylines and polygons don't show their name at all.

2) Names are transformed together with the objects, not sure if this is the desired effect (it's quite odd to see the name rotated with a rotated rectangle, for example).

**Comment by bjorn** [comment]
Issue closed by change cecf725d17e2592f48dbc6a9c0791f6fff64b92c, to be included in the next Tiled release. Options for when to show the names are still to be implemented, for now it shows the names of all selected objects.
