### ISSUE TITLE
Remember the tileset zoom level in the Edit Terrain Information dialog

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#408]
Not remembering the zoom level leads to a minor annoyance for those who need to change it to be able to comfortably edit the terrain information.

**Comment by Sharganov** [comment]
Is there some file with default settings for Tiled Editor? Where zoom value can be saved between executions?

**Comment by bjorn** [comment]
@Sharganov Check out the `Preferences` class and `QSettings`, and their various usages throughout the program.

**Comment by Sharganov** [comment]
@bjorn Thanks!

**Comment by Sharganov** [comment]
#1479
