### ISSUE TITLE
Change tile after inserting a tile object.

### ISSUE THREAD

**Issue by mimpedro** [bjorn/tiled#409]
When creating a new object with the "Insert Tile Objects" tool, you can't change its tile anymore. 

In the game I am currently making, there is a huge amount of objects that take appearance of different terrain tiles, but they all have the same properties inside. It would be a big hassle to create each individual object with the Insert Tile Object tool and then write all of its properties by hand, as opposed to simply copying and pasting one of them and changing its corresponding tile.

Anyway, I've already solved this by using a tile layer, but I believe this issue could be easily fixed and would be very useful for other developers.

Sorry if it sounded confusing, English is not my first language.

**Comment by bjorn** [comment]
Also [suggested on the forum](http://discourse.mapeditor.org/t/how-can-i-get-image-names-on-objects/1964/2?u=bjorn), with the menu item in the context menu of the tile:

> 1. selecting the Image Object/s
> 2. selecting the Tile in the tileset window
> 3. RMB > Replace image in selected object/s

**Comment by thabetx** [comment]
I started working on this issue, I'm implementing the workflow in the previous comment.

The basic functionality is done, but it still needs some adjustments when changing multiple objects.
