### ISSUE TITLE
isometric terrain overlays

### ISSUE THREAD

**Issue by jrz** [bjorn/tiled#419]
The current blue overlays in the terrain editor are tile-based. They should be updated for use in isometric mode. (afaik it's an overlay image)

**Comment by bjorn** [comment]
@Ablu explained how to work with isometric tiles while this issue remains [on the forum](http://forum.mapeditor.org/t/isometric-terrain/192/3).

**Comment by Ablu** [comment]
My workaround unfortunately only seems to work for non staggered isometric maps. Staggered ones do not work.

**Comment by bjorn** [comment]
Right, staggered maps need more complicated neighbour-logic.

**Comment by bjorn** [comment]
The rendering of the terrain overlay and related mouse handling now works based some new properties on the tileset:

![-isometric_grass_and_water tmx-isometric_grass_and_water tiled_137](https://cloud.githubusercontent.com/assets/531764/21783969/e6722cf2-d6b9-11e6-9cb0-ba4d16c236b2.png)

The remaining issue of using the terrain tool on staggered isometric maps is covered by #427.
