### ISSUE TITLE
Map -> Add External Tileset doesn't remember last used folder

### ISSUE THREAD

**Issue by leiradel** [bjorn/tiled#453]
Every time an external tileset is added, the file open dialog starts in the same directory where the last map was opened.

I think it would be nice if that dialog started in the same directory where the last external tileset was added from.

**Comment by bjorn** [comment]
@HenryJia maybe you'd like to tackle this one.

My idea would be to store a separate directory for external tilesets in the Preferences. The preferences already has a mechanism for remember the last used directory for different purposes, so you can extend the `Preferences::FileTypes` enum with an `ExternalTileset` entry and use that similar to how the other entries are used when external tilesets are being added.
