### ISSUE TITLE
Minor: backgroundColor.alpha in Map Properties is not saved

### ISSUE THREAD

**Issue by LearnCocos2D** [bjorn/tiled#466]
To reproduce:
- change map's backgroundColor property to a color with low alpha value
- save the map
- close tiled
- open tiled and the map
- notice the alpha is reset to 255

The backgroundColor="#AABBCC" string in the TMX file does not store the alpha channel.

**Comment by bjorn** [comment]
I noticed that `QColor::setNamedColor` supporst `#AARRGGBB` since Qt 5.2. This means Tiled already supports loading such values, so we can resolve this issue by implementing this in the saving.

**Comment by bjorn** [comment]
Turned out Qt 5.2 also added an easy way to construct such values by doing `color.name(QColor::HexArgb);` :)
