### ISSUE TITLE
Tile properties is disabled in desert example map.

### ISSUE THREAD

**Issue by jakerr** [bjorn/tiled#493]
In the desert example map, right clicking on a tile in the Tilesets>Desert tab on the right shows `Tile Properties...` in the context menu but it is grayed out and disabled. The same feature is enabled for the sewer example map, and I couldn't find an obvious reason why it should work there and not for the desert map.

If there is actually a good reason for the disabled state, it would be nice if clicking or hovering said why it is disabled; this suggestion goes for any disabled menu item.

**Comment by bjorn** [comment]
Tile properties are now always edited in the tileset editor, which can be opened using the small "Edit Tileset" button below the tileset view. While editing maps, a read-only view on the tile properties is provided, both for embedded and external tilesets.
