### ISSUE TITLE
Allow the copying and pasting of custom properties

### ISSUE THREAD

**Issue by rcbuse** [bjorn/tiled#515]
It would be a really nice feature if the all the custom properties of maps, layers, tilesets, tiles, objects, etc could be copied and pasted to and from each other in groups.  An example being, select multiple properties of one tile, copy properties, select another tile, paste the properties.

**Comment by coco-napky** [comment]
this!

**Comment by afaucher** [comment]
+1

**Comment by locknic** [comment]
+100 PLEASE

**Comment by bjorn** [comment]
Also [requested on the forum](http://discourse.mapeditor.org/t/copy-paste-tile-level-custom-properties/1071). I'll be sure to look into this for Tiled 1.0.

**Comment by bjorn** [comment]
Related issue: #438

**Comment by bjorn** [comment]
[Requested on the forum](http://discourse.mapeditor.org/t/make-custom-properties-of-layers-copy-paste-able/2296) again.

**Comment by TannerMoore** [comment]
:+1: This feature would have saved me a substantial amount of time and annoyance on a game jam I did this weekend.

**Comment by bjorn** [comment]
@TannerMoore I'm sorry to hear that. Rest assured, it is one of the few issues remaining before I can release Tiled 1.0 next month.

**Comment by bjorn** [comment]
The above change makes some progress, though it's only halfway towards closing this issue since there is no multi-selection support yet. Currently I have no idea how difficult this will be to add, but it could be non-trivial since we're relying on the rather complex QtPropertyBrowser solution.

**Comment by bjorn** [comment]
Please test out the feature in the latest development snapshot. :-)

**Comment by X-Ray-Jin** [comment]
i face an issue with copy-pasting properties (tiled v1.2.2). very often it just doesnt work. so i select a property press ctrl-c go to another object/tile etc and press ctrl-v but it doesnt insert it. same for multi select. not sure if copy or paste is the actual problem but it seems that it doesnt get copied in the first place as pasting somewhere else in textedit or something is empty.
to fix it i then select various properties, also multiple, a few times. then select the one i want again hit a trillion times ctrl-c and then it eventually works.
