### ISSUE TITLE
JSON format support on linux

### ISSUE THREAD

**Issue by viliamjr** [bjorn/tiled#595]
There are any limitation (or additional configuration) to work with JSON on linux?

For instance, there is no "JSON files" option in the save screen. And when I tried to open a JSON file the Tiled informs "Not a map file".

**Environment**

Tiled: 0.9.1
Qt: 4.8.5
on Fedora 20

Same version (tiled and qt) works fine on Windows 7.

**Comment by viliamjr** [comment]
Yes! Related to #269. Thanks.

**Comment by bjorn** [comment]
Somebody is cleaning up his inbox? :-D

**Comment by viliamjr** [comment]
:mailbox: :watch: :sob:

**Comment by bjorn** [comment]
Tell me about it...
