### ISSUE TITLE
Saving in Tiled causes me to lose all previous work

### ISSUE THREAD

**Issue by CloneWarrior** [bjorn/tiled#641]
Hello, been working with Tiled for a while and haven't run into this problem, and don't know if it has already been solved.

I was doing some work today and I got a few levels done and when I saved all the pages I thought they were good. When I came back to them and reopened them with Tiled none of my progress was there. Could it be a problem with Tiled that a reinstall might fix? Or is it something different? Any help is greatly appreciated, thank you for you time.

**Comment by bjorn** [comment]
Closing this issue since I can't do anything without more information.

**Comment by CloneWarrior** [comment]
Yeah, sorry. I figured it out.

**Comment by bjorn** [comment]
@CloneWarrior If you figured it out, I would still be interested to know what was causing the problem. :-)

**Comment by CloneWarrior** [comment]
It ended up getting fixed but im pretty sure the issue was trying to save over a file that needed permission to save.

**Comment by bjorn** [comment]
Alright, thanks for letting me know. :-)
