### ISSUE TITLE
Add autocrop

### ISSUE THREAD

**Issue by alphaonex86** [bjorn/tiled#642]
Hello,
As gimp, can you add auto crop to crop the empty (no object, no tile, no image, ...) and useless border.
It's more fast to map than select only the util zone and crop the selected zone.
Cheers,

**Comment by ketanhwr** [comment]
The simple solution would be to resize the map based on (minX,minY) to (maxX,maxY), right? (Where min and max would be based on extreme coordinates of any placed tile.)

Altough I'm a bit confused as in how this would work when we're using multiple layers.

**Comment by bjorn** [comment]
> Although I'm a bit confused as in how this would work when we're using multiple layers.

You could just go through all layers and compute min/max based on that, but that won't work very nicely when in the future we decouple layer size and tile size from the map.

But, I just checked what GIMP does and actually it crops the image only based on the currently selected layer. So, surely that is acceptable behavior as well.

Then, the only remaining question is how to treat object layers. We could either just not support this option for now, or determine the boundaries of the objects on the current object layer and then somehow mapping that also to any potential tile layers. I think at first we could just disable this action when an object layer is selected.

**Comment by ketanhwr** [comment]
Yes, alright. So I'll add an `Autocrop` option in the same menu where the resize menu is placed. What should be the suitable shortcut key for this, if needed?

**Comment by bjorn** [comment]
> What should be the suitable shortcut key for this, if needed?

I think it is a quite specific and rare action, so no shortcut is needed. GIMP also doesn't have a shortcut for it.
