### ISSUE TITLE
fresh install segfaults on open file (ubuntu 13.10, 14.04)

### ISSUE THREAD

**Issue by imposeren** [bjorn/tiled#649]
I've tried installing tiled on Ubuntu 13.10. It segfaulted when i trid to click on "open file" button. Then I tried tiled-daily with same result.

Then I updated to 14.04 and tried daily and stable versions again. Both segfaulted

stable version:
Tiled 0.9.1

daily version:
Tiled 2014-04-24

And I use "customized" ubuntu installation where ubuntu-desktop is not installed. Maybe tiled requires some libraries that are not present in package requirements but are required at runtime?

Is there a way to provide additional information on this issue?

**Comment by imposeren** [comment]
can't reproduce problem anymore. I had similar problem with some i386 app on x64 system. And it was solved by installing i386 version of gtk style:
```
apt-get install gtk2-engines-qtcurve:i386
```

did tiled for x64 ubuntu use any i386 libs?

**Comment by bjorn** [comment]
> did tiled for x64 ubuntu use any i386 libs?

I'm pretty sure it didn't.

But, since you can no longer reproduce this issue and I haven't heard about it from anybody else in the meantime, I guess it's time to close this issue.
