### ISSUE TITLE
No image-object's preview at the position of mouse-cursor in Object-Layer

### ISSUE THREAD

**Issue by finscn** [bjorn/tiled#670]
No image-object's preview at the position of mouse-cursor in Object-Layer.

1) select a Object-Layer
2) I select a image in tileset .
3) click "insert tile" button
4) move mouse at edit-area,  there is no image-object's preview at the position of mouse-cursor. (But I can put image)

if I select Tile-Layer,  there is a image-object's preview at the position of mouse-cursor.
I think it's a good UX. I hope it can be implemented for Object-Layer.

**Comment by bjorn** [comment]
Duplicate of #537
