### ISSUE TITLE
Change Object Location Format

### ISSUE THREAD

**Issue by GymbylCoding** [bjorn/tiled#683]
I think the current angle/position mode in the newest version is a little counter-intuitive. When you create an object and rotate it, the angle and the position changes to reflect the original top-left corner. Then, when you reposition it by setting the X,Y locations directly, that corner is what is positioned (which is, maybe, definite, like my title says, but it doesn't feel "right" to me, if you know what I mean `:)`). I think a better approach would be to set the X,Y location to the top left bounding box corner of the object, or even the center point of the object, instead of the top left object corner.

**Comment by bjorn** [comment]
> I think a better approach would be to set the X,Y location to the top left bounding box corner of the object

I think this would make things very complicated, at least if you mean this "bounding box" would expand based on the rotation.

> or even the center point of the object, instead of the top left object corner.

That is a change of object origin and definitely something I wouldn't mind supporting at some point. At the moment, the object origin can't be changed and is always top-left for rectangles / ellipses and bottom-left for tile objects (an inconsistency I'm really not happy with either).

**Comment by bjorn** [comment]
I'll close this since a configurable object origin is somewhat implied in the fix for issue #91.
