### ISSUE TITLE
Object templates

### ISSUE THREAD

**Issue by zamp** [bjorn/tiled#70]
Would be nice if you could set up object templates so when you create new objects you could just pick one from a list and drag n drop it on the map.
Maybe double click on list to edit a template.
The templates should have the object type and properties with default values.
http://juvo.se/tbb3.jpg here's a mashup of what it could look like.

**Comment by downstroy** [comment]
Damn I would love to see this feature implemented!

Imagine you define an object (eg: a platform), you give it some basic properties (like minX, minY, maxX, maxY) to what you want it to do. 

Now imagine you are doing a platformer, you will probably use dozen if not hundred of those objects.

And after using lots of them, you have the idea of adding custom collision to your platform (like it should collide from above but not from under. You will have to cycle through all your platform object and edit them all to add the collision : top / collision : bottom / collision : both custom property. What a hassle to maintain!

Of course you could just do it in your code, checking the id of the object and adding the behaviour, but it would really be a mess and not faster.

I think having template of object (aka prefab (cf unity3D)) would really be a neat feature for any "medium to big" sized project.

**Comment by bjorn** [comment]
@zamp Is there any chance you would be able to restore the mashup you linked to in your original request? I think it could be very helpful for anybody who could be interested to work on this feature (which could be this summer, as a Google Summer of Code project).

**Comment by i-ka** [comment]
In Unity, unchanged instance properties synchronizes with prefab properties. I think tracking prefab property changes will good feature. In addition it can reduce file size a little bit, by saving only changed properties.

**Comment by zamp** [comment]
@bjorn sorry. I don't have the file anymore nor can I recall what it looked like.

**Comment by bjorn** [comment]
@zamp Alright, no problem. Thanks for letting us know!

**Comment by bjorn** [comment]
I'm closing this issue since the feature is now implemented, thanks to @thabetx's Google Summer of Code project! Check out [the documentation](http://doc.mapeditor.org/en/latest/manual/using-templates/) and be sure to try it out by using a development snapshot (available [at itch.io](https://thorbjorn.itch.io/tiled)).

Any feedback would be very welcome as we will now be working towards the Tiled 1.1 release.

**Comment by bjorn** [comment]
For reference, here are the issues I've already opened covering remaining tasks:

* Allow replacing existing objects with template instances #1722
* Allow deleting object templates from a template group #1723
* Allow unloading a template group #1724
* Allow resetting overridden properties individually for template instances #1725
* Allow locking template properties #1726
