### ISSUE TITLE
Ability to lock layers

### ISSUE THREAD

**Issue by xerosugar** [bjorn/tiled#734]
I think this should be added to prevent the user from working on the wrong layer.

**Comment by ncareau** [comment]
+1, currently our game has multiple layer and i throw an error when wrong tile are inserted into the special layer. Being able to lock the layer would be nice to prevent any unwanted tile inserted in that layer.

**Comment by superqix** [comment]
I don't usually +1 something, but now that we have scaleable objects, this feature is getting more important. We use lots of gradients on the topmost and bottommost layers that make it hard to nudge other objects in a map.

**Comment by bjorn** [comment]
Alright, I've added it to the [roadmap](https://trello.com/b/yl3PAtN0/tiled-roadmap). You can vote on it there. I'm still trying to find out how to prioritize features against each other. I definitely agree this would be a good to have feature, no question about it.

Sometimes I tell people they can support me on [Patreon](http://www.patreon.com/bjorn) to help me get around to more features sooner, but I see you already are @superqix, so thanks a lot for your support! And to @kheftel as well of course!

**Comment by superqix** [comment]
Thanks for adding to the roadmap. I've been super impressed with updates since you went with Patreon funding, so keep up the good work.

I'm working toward releasing a new Lua loader for CoronaSDK/Love2D so hopefully that will open you up to a new group of Patreons.

**Comment by bjorn** [comment]
That's great to hear, thanks!

As for growing the funding, this seems really hard from the current level. The pace rather stopped once the first goal was reached, but I'd still like to reach the second goal as well. I've opened up issue #1064 for this. :-)

**Comment by EdenIndustries** [comment]
I've actually already implemented layer locking in our local version of Tiled. Do you want me to try a pull request for it? Or did you have a plan in mind for it already?

**Comment by bjorn** [comment]
@EdenIndustries This is one of those features I'd like to get around to sooner rather than later, but I did not do any work on it yet since there are many other things I'd like to get done as well. So feel free to open a pull request for it, I'm looking forward to see your changes!

**Comment by EdenIndustries** [comment]
@bjorn Ok I'll see what I can do! To my embarassment, I admit Git's notion of branches and pulling and forking and such is not something I'm all that familiar with yet (I've only really used SVN and Perforce), but I'll try to figure it out and get the pull request sorted out :)

**Comment by bjorn** [comment]
@EdenIndustries Good luck and feel free to ask questions! No need to be embarrassed!

**Comment by JesseTG** [comment]
@EdenIndustries Try this, it's interactive and very helpful http://pcottle.github.io/learnGitBranching/

**Comment by EdenIndustries** [comment]
@JesseTG Wow, very cool, thanks!

**Comment by JesseTG** [comment]
:+1:

**Comment by superqix** [comment]
@EdenIndustries Did you ever get a branch or PR organized for this?

**Comment by EdenIndustries** [comment]
Sorry, no. It's been a really busy time for us prepping for GDC and now E3. I can see if I have time to get around to it though. Or if you build Tiled locally, I can just send you the relevant files maybe?

**Comment by superqix** [comment]
I'd be willing to give it a look. wilson at no2games dot com is probably the easiest way to send it along. Thanks!

**Comment by EdenIndustries** [comment]
No problem! I'll try to send it along shortly

**Comment by damienleroux** [comment]
+1 :)

**Comment by harrisyu** [comment]
+1
Waiting for this for a long time.
Now I need to hide other layer to prevent false selecting.
👍

**Comment by ketanhwr** [comment]
What exactly will be the features? A layer locked means that we won't be able to edit it, right?

**Comment by bjorn** [comment]
> What exactly will be the features? A layer locked means that we won't be able to edit it, right?

Exactly. Also, a locked group layer means the lock applies to the child layers as well, recursively. See for example `Layer::isHidden`, which behaves similarly.

One of the things you'll need to do is to find a way to add another interactive icon to each layer in the layers view. We used the checkable state for the visibility, and first of all we could try to do the same by adding another checkable column.

**Comment by UliAbo** [comment]
Locking Layers would be really great! And entirely Layer Groups of course. All like in Photoshop. 
+1 :)

**Comment by bjorn** [comment]
@UliAbo Well, this issue was closed back in 2017 because locking of layers was added in Tiled 1.1, including locking of layer groups (when a group layer is locked, all its children are also considered locked, even though this is not visualized in the Layers view). What are you missing?

**Comment by UliAbo** [comment]
@bjorn I'm sorry, you are totally right, this is all implemented (and I already used it...). 
I don't know how, but while reading / typing my previous post, I was thinking about this issue here: https://github.com/mapeditor/tiled/issues/2807 and I kind of mixed it in my head with locking layers. So I wish to just deactivate / lock this Offset tool, because it keeps regularly crashing my work (because I notice some little pixel shifts done through the offset tool only later), when accidentally this Offset tool is auto-selected by clicking on the layer group.
Sorry again for the confusion!
