### ISSUE TITLE
command-line option to save as image

### ISSUE THREAD

**Issue by o11c** [bjorn/tiled#74]
There should be an option to export.
One particular use case is for minimaps (which would require extra manipulation e.g. via imagemagick) and/or wiki maps (as is).

Thoughts about how it might be implemented:
* There should be an option to control which layers are visible/opaque (which appears to be the same thing in this context, but not in general)
** (what about layers not mentioned? Maybe, don't show them? But, if no visibility/opacity options are given, layers should be displayed as given in the map file ... for consistency that shouldn't be changed. So, I think another option --default-visibility 0|1 and/or --default-opacity 0.50 )
* The option to scale should probably be independent, i.e. if --scale 0.25 is used without --export-image, it should open the map for editing at that zoom level. Note, even though it should look like a float it should probably be parsed via string lookup (after stripping leading/trailing zeroes, if on the appropriate side of the decimal point) since tiled only supports discrete zoom levels and we don't want to have to deal with float rounding.

Complete examples:
tiled --default-visibility 0 --layer-opacity Ground 1 --layer-opacity Ground2 1 --layer-opacity Fringe 0.75 --layer-opacity Over 0.5 --layer-opacity Collision 0.25 --export-images maps/*.tmx
tiled --default-visibility 1 --layer-visibility Collision false --layer-visibility Object no maps/001-1.tmx --export-image maps/001-1.png

(Hm, we at TMW should probably update our collision tileset to not use partial transparency and instead depend on tiled's opacity= tag ... it would probably be nice to do this via script. Also, it would be nice if a layer could specify a tile other than "transparent" to be shown when tile ID 0 is given ...)

Hm, the layer names should probably accept either a glob or a regex, otherwise we'll end up implementing it in the script that calls this.
Hm, should there be separate ways of indicating tile vs object layers? Should object layers be ignored by default?

**Comment by bjorn** [comment]
This issue was largely resolved by the addition of the `tmxrasterizer` command-line tool.
