### ISSUE TITLE
The whole map gets messed up when you change the canvas size of your tileset

### ISSUE THREAD

**Issue by cheesewhiz999** [bjorn/tiled#742]
I use Paint.net to make my tilesets, and whenever I change the canvas size of my tileset, the whole map in tiled gets messed up.
![tiled bug](https://cloud.githubusercontent.com/assets/8650110/4144209/faeb0034-33da-11e4-81e6-9c2eb9ca89ca.png)

**Comment by IoriBranford** [comment]
> Alternatively, when you want to change the width of your tileset, close Tiled first and only reopen it after you have saved the tileset with its new width. Because in this case special logic to keep the map intact is applied, which is unfortunately missing for the automatic reloads.

Unfortunately this feature applies to external TSX tilesets only.

In all other cases - internal tilesets or external JSON tilesets - you first have to save as TMX and export all tilesets as TSX.

**Comment by bjorn** [comment]
@IoriBranford I'll have to do some testing on that. This is definitely an area that should be improved, and now is probably the right time for it.
