### ISSUE TITLE
Collision Objects are not projected while in Isometric Mode

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#757]
When I create an Isometric map and place objects, the "rectangle" object tool, for instance, is oriented with an isometric projection. Which is to say, I can place diamonds. When I try to use the Collision Editor, the objects are not projected isometrically and the rectangle tool ends up creating orthogonal rectangles, not isometric diamonds.

**Comment by bjorn** [comment]
Tilesets now have some properties that allow you to configure isometric projection, which will then be used by the Tile Collision Editor:

![-isometric_grass_and_water tmx-isometric_grass_and_water tiled_136](https://cloud.githubusercontent.com/assets/531764/21782809/1632f192-d6b5-11e6-8af5-c274accee1a3.png)

This feature is available in snapshot builds now. Let me know if you find any problems!
