### ISSUE TITLE
Toggling grid lock on object creation

### ISSUE THREAD

**Issue by karai17** [bjorn/tiled#767]
In both Orthogonal and Isometric map-types, object creation has no grid lock. In staggered maps, object creation is forced into grid lock. I propose that all three map types have the same default functionality with the ability to toggle grid locking and snapping to grid while moving objects.

**Comment by bjorn** [comment]
This was fixed in Tiled 0.12, commit 4aad4d3d750b6e28448dead14761059e6102caf6.
