### ISSUE TITLE
Missing Object Properties in Tile Collision Editor mode

### ISSUE THREAD

**Issue by wyemun** [bjorn/tiled#778]
When in Tile Collision Editor window, right clicking on the object created shows "Object Properties" option but clicking it does nothing. It should popup another object properties window or reflect in the parent window's "Properties" section.

**Comment by Seanba** [comment]
I think I may be converging on a fix for this as I need this feature too.

I just wanted to make sure someone else hasn't been working on it first. Don't want to step on any toes.

**Comment by bjorn** [comment]
@Seanba Thanks for working on this, I'm looking forward to see your patch!

**Comment by stuntmania** [comment]
@Seanba Do you think you can tell me when you're done? I need this fixed so that I can follow https://www.youtube.com/watch?v=EXiSpt-dLKg

**Comment by Seanba** [comment]
It wasn't too hard once I studied the properties dock for a bit. I'm not too experienced with Qt but I think I got it.

There are some issues that remain with selection when the tileset is external as it would still be nice to view object properties in that case but I explain how that got me off the rails in my pull request.

https://github.com/bjorn/tiled/pull/939

**Comment by solewalker** [comment]
+1 For this, if at least there was a way to name individual object in collision editor, it would make some task easier. Like having a collision box as solid/collider object, another as sensor/trigger object. As tiled has no object parent/child system, it can be used to define some object position in child space easily, like demostrated below. 
![tiled-feat-annot](https://cloud.githubusercontent.com/assets/2183770/11121476/46ce3614-8980-11e5-97f2-df97d7a4ff49.png)

**Comment by bjorn** [comment]
I've added this to the 1.0 milestone to make sure I don't forget to look at cleaning up and merging #939 before that release.

**Comment by solewalker** [comment]
Thanks a lot! That would be great :)

**Comment by bjorn** [comment]
Implemented now that pull request #939 is merged!
