### ISSUE TITLE
Object visual sizing

### ISSUE THREAD

**Issue by OrenjiAkira** [bjorn/tiled#783]
Hi.
I'd like to size objects with a visual guide. I mean, I'd like to set an object's size with some sort of visual interaction instead of guessing its sizing in pixels. That would be of great help.

Would that be possible?

**Comment by bjorn** [comment]
@OrenjiAkira Since #593 was merged and further improved before releasing it in Tiled 0.12, did you get a chance to try it out?

**Comment by bjorn** [comment]
Closing this issue since it was implemented.
