### ISSUE TITLE
Version 10.1 Mac version focus issues

### ISSUE THREAD

**Issue by plangworthy** [bjorn/tiled#789]
In version 10.1, dockable windows lose focus when editing the map or while selecting other windows. The problem with this is that, for example, in the unfocused Layers window the checkmarks showing which layers are visible are almost impossible to discern. Not to mention that the flickering of focus off when cycling between cycling layers and drawing on the map is distracting.

This was not an issue with 9.1.

![screen shot 2014-10-07 at 3 11 58 pm](https://cloud.githubusercontent.com/assets/1587983/4548533/d70ae4fa-4e55-11e4-96b3-28020b407415.png)

**Comment by bjorn** [comment]
This seems fixed in Qt 5.5, judging by the screenshot in [my tweet about the upgrade](https://twitter.com/thorbjorn81/status/623246632889548800).
