### ISSUE TITLE
Eyedrop / Fill tool tweaks

### ISSUE THREAD

**Issue by plangworthy** [bjorn/tiled#790]
It should be possible to use the eyedrop tool (right click) while the fill tool is selected. Right now the eyedrop tool only appears to be available when using the Stamp Brush.

Also in earlier versions of Tiled it was possible to eyedrop a null tile and then use the fill tool to fill an area with null tiles. It is already still possible to eyedrop a null tile and brush null tiles. I would like to request this feature be re-integrated.

**Comment by bjorn** [comment]
Also [requested on the forum](http://discourse.mapeditor.org/t/feature-request-bucket-fill-tool-is-active-right-click-on-canvas-changes-active-tile/2413). I'll try to get around to this soon.
