### ISSUE TITLE
about dialog needs a maximum size

### ISSUE THREAD

**Issue by zigal** [bjorn/tiled#795]
An little "bug" I have found by exploring Tiled.

![settinganlimit](https://cloud.githubusercontent.com/assets/9049287/4616685/28c51c12-52f6-11e4-8138-244cb1a2b9c8.PNG)

This can be fixed by setting an maximum size I think.

**Comment by RyanSchmittDev** [comment]
This has been fixed, at least on windows 7.

**Comment by bjorn** [comment]
Right, this was fixed in the above referenced commit. Thanks for mentioning it!
