### ISSUE TITLE
Internal Restructuring: Remove file I/O from Mainwindow class

### ISSUE THREAD

**Issue by stefanbeller** [bjorn/tiled#8]
Move all file operations such as 'Open file', 'Save file', 'Export as Image'... 
(basically all operations containing a file dialog)
to either MapDocumentManager or another new FileIO class.

This will be for features later on, such as project view.
(Calls to open files and such shall not be calls to mainwindow)

**Comment by Phlosioneer** [comment]
This issue seems to have been resolved over time. The mainwindow class currently does no file I/O, only filename stuff.

**Comment by bjorn** [comment]
Yeah, while I don't think the design is very clean still, it is true that many of this stuff has already been moved away from the MainWindow and into classes like MapDocument and the DocumentManager. 

Also, the actions are now registered with the ActionManager, which the Project view and a few other places use to trigger actions that are set up in the MainWindow.

So let's close this issue.
