### ISSUE TITLE
Polygon/polyline SRT bake

### ISSUE THREAD

**Issue by wayfu** [bjorn/tiled#816]
Rectangles and ellipses have a very handy resize handle that polygons and polylines currently seem to lack – it would be great to have that there as well. 

While rotation and translation work great, they currently fill object properties with SRT values. I think it would make sense to add a "bake" option for polygons and polylines to convert vertices to absolute values.

**Comment by bjorn** [comment]
#593 was merged and the improved resizing features were released as part of Tiled 0.12. I still don't see a real value in manually baking such objects as opposed to doing this on loading the map, so I'll close this issue.

If baking in Tiled is important, I would suggest to solve this with a user script once #949 is implemented.
