### ISSUE TITLE
No way to exit fullscreen in Yosemite

### ISSUE THREAD

**Issue by reneaye** [bjorn/tiled#817]
As the title says: after switching to fullscreen in Yosemite there is no way of Leaving the fullscreen mode.
No green button, CTRL+CMD+F or Escape key does work.
Quitting and re-start the app does not help either. Tiled rembers the fullscreen mode somewhere.

**Comment by b005t3r** [comment]
It also worked for me. Maybe it's not a bad idea to disable it by default?

**Comment by bjorn** [comment]
> It also worked for me. Maybe it's not a bad idea to disable it by default?

Yeah, I should consider doing that before packaging the Tiled 0.11 release and leave it disabled until it is fixed in Qt...
