### ISSUE TITLE
Show/Hide Object Names

### ISSUE THREAD

**Issue by python50** [bjorn/tiled#82]
It would be nice to have a new menu entire under view, view->show names/object names. When enabled the names of objects would be drawn over top their respective objects. The name would be drawn on the top left corner of the object and the font size should be selectable, though a small/large option would do just fine.

**Comment by bjorn** [comment]
As of change cecf725d17e2592f48dbc6a9c0791f6fff64b92c, objects names are displayed for all selected objects. Options to hide or show all names are still to be added. The labels are top-center rather than top-left.
