### ISSUE TITLE
Automap shortcut "A" doesn't work on Mac OS X

### ISSUE THREAD

**Issue by arthurferrai** [bjorn/tiled#820]
I'm trying to use automap shortcut, but it seems to be broken, at least on Mac OS X Yosemite.

Tried hitting "a" key with and without shift and Caps Lock pressed, without result. If I select the option on Menu, it works great.

I'm on a MacBook Pro (Retina, 13-inch, Late 2013) with Mac OS X Yosemite (10.10).

**Comment by bjorn** [comment]
If this bug still existed, it is likely fixed by the [recent upgrade to Qt 5.5](https://twitter.com/thorbjorn81/status/623246632889548800), since it also fixed the Delete shortcut. Will close this after confirmation.

**Comment by arthurferrai** [comment]
Just downloaded the today's daily build, and I can confirm that it works correctly.

**Comment by bjorn** [comment]
@arthurferrai Yay, thanks for testing!
