### ISSUE TITLE
Corrupted Source Path causing Ctrl-C to not work

### ISSUE THREAD

**Issue by RainingChain** [bjorn/tiled#834]
For my application, I absolutely need absolute paths to link to the tileset images.
I'm using path that looks like:
../../../../../../../../../../../../../../../Users\Sam\Documents\Resource/1.png
With an arbitrary amount of ../

Doing that, Tiled loads the tilesets correctly. However, there are 2 issues:
-Ctrl-C and Ctrl-X does not work.
-Tiled will save the file with a non-functional path:
Ex: ../../../../../../Users/Sam/Documents\Resource/1.png
This means, if I open the .tmx file, change nothing and save, I am unable to open the .tmx file again.

**Comment by bjorn** [comment]
@RainingChain Is this still an issue?

**Comment by RainingChain** [comment]
It is no longer an issue. The issue can be closed.

Saving a .tmx file no longer alters the source of the images. 
Ex: `source="../../../../../../../../../../../../../../../rc/rainingchain/server/tileset/v1.3/1.png"` is kept as is.
