### ISSUE TITLE
It should not be possible to set the alpha value for the map background color

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#840]
It does not make sense for the background color of a map to have an alpha value, since as a background color it is expected to be opaque.

**Comment by stubb** [comment]
I make also use of the opacity for the map background. The idea is to create a parallax scrolling effect with additional layers which are not part of the tiled map.

**Comment by bjorn** [comment]
@stubb How can you make use of it, given that it isn't saved as per issue #466?

**Comment by stubb** [comment]
After I loaded the map, iam using the background colour information of the map. R,G,B works but opacity not. Same as you said. To get the intended result I add the opacity value within the code. I would be great to get this value from the map itself. To correct my statement, I would use it, but right now iam using a work around ;-)

**Comment by bjorn** [comment]
@stubb Hmm, since there is nothing meaningful Tiled can do with this alpha value, why not just use a custom "backgroundalpha" property for this instead?

**Comment by bjorn** [comment]
Closing this. I reopened #466 instead.
