### ISSUE TITLE
Better use of object types

### ISSUE THREAD

**Issue by onpon4** [bjorn/tiled#851]
I'm currently using Tiled for a game, and I think it would be very helpful if Tiled extended the ways it could use object types in two ways:

1. I find it rather inconvenient to have to set the types of all my objects *after* placing them. It would be a lot nicer if I could tell Tiled to give any new objects I place in the map a particular type, especially if I want to place several objects of the same type in a row.

2. It would be nice if tile types could be associated with images rather than colors. It doesn't need to be especially fancy; just display that image instead of the rectangle or ellipse, and automatically size it; when placing objects of that type, do it like placing an object that uses a tile.

With these two enhancements, I'm imagining, say, having a "coin" type that I can put into a map very easily. As it is, I have to either look at low-level tile details in the game, define object types the current way (and face not only a huge number of inconvenience when I have a lot of objects, but also the risk of forgetting to do so and messing up the map as a result), or use some other detail, such as the layer name, to identify the objects as coins instead. Currently I'm using the third option, but it would be much nicer if I could efficiently use object types the way I've described.

**Comment by bjorn** [comment]
I think issue 1 is already covered by #70 and #367.

I don't fully understand issue 2. Basically, if you can represent your object with an image, like with the coin, why not just use a tile object for this and set some custom properties on that tile so you can recognize it? It would mean ignoring the empty "name" and "type" attributes and instead looking at the properties of the tile.

**Comment by onpon4** [comment]
OK, I didn't notice those issues. Indeed, they seem to cover the first part.

> I don't fully understand issue 2. Basically, if you can represent your object with an image, like with the coin, why not just use a tile object for this and set some custom properties on that tile so you can recognize it? It would mean ignoring the empty "name" and "type" attributes and instead looking at the properties of the tile.

I suppose it's pretty minor, but most of my images are stored in separate files, and to use a tileset to represent objects efficiently (i.e. not giving each object its own tileset), I need to have special tileset images for these objects. It's a bit of a waste of space and a small invonvenience.

**Comment by kheftel** [comment]
There is a type of tileset called a "collection of images". Have you tried that?

**Comment by onpon4** [comment]
Ah, OK. I'll have to check that out.

**Comment by onpon4** [comment]
Alright, I've installed the latest version of Tiled so I could check out that feature, and indeed, it seems to be sufficient.

**Comment by bjorn** [comment]
Thanks for the update! Since the remaining suggestions for improvement are I think already covered by other issues, I'll close this one now.
