### ISSUE TITLE
Tiled eats all of memory when adding a typoed external tileset

### ISSUE THREAD

**Issue by tcoxon** [bjorn/tiled#862]
I'm using the daily from the ubuntu ppa: Version 2015-01-12

When I attempted to add the .tsx file http://pastebin.com/RGrFKJuP to a map, tiled quickly started to eat all of memory and CPU. The file is typo'd of course, but I feel like the penalty for misspelling 'tileheight' as 'tileHeight' should be lower.

This also happened in 0.9.1, so it's not new.

**Comment by HenryJia** [comment]
@tcoxon I've tested this. When there is a typo the program just seems to hit a SIGABRT in line 450 of mapreader.cpp and crash the program not chew up all the RAM and CPU.

**Comment by tcoxon** [comment]
Maybe it's the crash handler in Ubuntu going wonky. It wouldn't surprise me.

But still, SIGABRT?

**Comment by HenryJia** [comment]
Well it hits a runtime error.

**Comment by bjorn** [comment]
Thanks for the report, @tcoxon!

@HenryJia The reason you got `SIGABRT` is because you were running Tiled in debug mode. In release mode, Tiled was doing an infinite loop due to not making any progress trying to cut the tileset image in infinite 0x0 pieces until you run out of memory.

**Comment by HenryJia** [comment]
OK, thanks, @bjorn 

I'll remember that.

**Comment by tcoxon** [comment]
Awesome, thanks for the fix!
