### ISSUE TITLE
Join polylines

### ISSUE THREAD

**Issue by T1mL3arn** [bjorn/tiled#870]
I don't found any options for this. But I think it will be useful. 
Option may looks like this:
"Joins all selected lines where each endpoint has joined with start point of the next line."

**Comment by bjorn** [comment]
Interesting suggestion, though the tricky bit may be how to determine the “next line”.

**Comment by T1mL3arn** [comment]
The order of polylines can depends on order of selection of this lines. Then next line which was added into selected group by Ctrl+click will be the "next line". But here another issue: what if we select all lines without ctrl-key? Then order can depends on polyline id, but it is not a good idea.

**Comment by ketanhwr** [comment]
Maybe while extending the polyline, apart from snapping it into a polygon, we can combine two polylines. The opposite of this would be deleting segments from polyline/polygon to create multiple polylines.

**Comment by bjorn** [comment]
> Maybe while extending the polyline, apart from snapping it into a polygon, we can combine two polylines. The opposite of this would be deleting segments from polyline/polygon to create multiple polylines.

Yeah, I think that would be the way to go for this feature!

**Comment by bjorn** [comment]
This is now possible as of change aa8d7317c0e89da0a37fe020102db4dac361ee93. The process is:

* Select the polylines you want to join
* Select the "Create Polygon" tool
* Click on either end of one polyline and then on either end of another polyline, to join them at those locations
