### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by entangledloops** [bjorn/tiled#872]
The link  to [libtiled-java port](http://bci.im/devnewton/fossils/libtiled-android/home) under the heading [Android-java](https://github.com/bjorn/tiled/wiki/Support-for-TMX-maps#android-java) is dead on [this](https://github.com/bjorn/tiled/wiki/Support-for-TMX-maps) page.

I believe it should be updated to: [http://chiselapp.com/user/devnewton/repository/libtiled-android/index](http://chiselapp.com/user/devnewton/repository/libtiled-android/index)

**Comment by bjorn** [comment]
Alright, I updated the URL. Thanks!
