### ISSUE TITLE
Error python27_d.lib

### ISSUE THREAD

**Issue by hammeron-art** [bjorn/tiled#874]
I'm getting a error when a try to build using Qt in Windows.
I just cloned the source and build.
LINK : fatal error LNK1104: cannot open file 'python27_d.lib'

**Comment by bjorn** [comment]
Are you trying to build with `tiled.qbs` or `tiled.pro`? When you use `tiled.pro` it should detect that you have no Python installed (to the expected location, at least) and skip that plugin. In `tiled.qbs` there is no such check yet, so to build Tiled successfully with Qbs you need to install Python 2.7 to its standard location.

**Comment by hammeron-art** [comment]
I'm using tiled.pro and I have Python27 instaled and path variable working.

**Comment by bjorn** [comment]
Hmm, ok then maybe try to compile/run in Release mode instead of Debug mode for now. I'll have to look into the Debug mode build.

**Comment by hammeron-art** [comment]
Compiling in Release mode I get a lot of unresolved symbol erros in the pythonbind and plugin obj.

Creating library ..\..\..\plugins\tiled\python.lib and object ..\..\..\plugins\tiled\python.exp
Then the errors

**Comment by hammeron-art** [comment]
This line:
link /NOLOGO /DYNAMICBASE /NXCOMPAT /LARGEADDRESSAWARE /INCREMENTAL:NO /DLL /SUBSYSTEM:WINDOWS /OUT:..\..\..\plugins\tiled\python.dll @stuff\AppData\Local\Temp\python.dll.8784.31.jom

Is looking for the python dll in my temp folder?
Is that right?

**Comment by bjorn** [comment]
That does not look right. Please tell me exactly with what you are trying to compile Tiled, then I may be able to reproduce the problem once I have some time.

**Comment by hammeron-art** [comment]
I just open tiled.pro from the root folder and press Ctrl+R.
With Qt Creator 3.3.0 compiling with Qt 5.4.0 MSVC2013 64bit-Release.

Well, there is the output from where start compiling the python plugin:

link /NOLOGO /DYNAMICBASE /NXCOMPAT /LARGEADDRESSAWARE /INCREMENTAL:NO /DLL /SUBSYSTEM:WINDOWS /OUT:..\..\..\plugins\tiled\tengine.dll @C:\Users\CHRIST~1\AppData\Local\Temp\tengine.dll.9744.1514.jom
   Creating library ..\..\..\plugins\tiled\tengine.lib and object ..\..\..\plugins\tiled\tengine.exp
	cd python\ && ( if not exist Makefile C:\Qt\5.4\msvc2013_64\bin\qmake.exe C:\CHRISTIAN\Sources\tiled\src\plugins\python\python.pro -spec win32-msvc2013 -o Makefile ) && C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
	cl -c -nologo -Zm200 -Zc:wchar_t -FS -IC:/Python27/include/ -O2 -MD -Zc:strictStrings -GR -W3 -w34100 -w34189 -EHsc -DUNICODE -DWIN32 -DWIN64 -DPYTHON_LIBRARY -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I"..\..\..\..\tiled\src\libtiled" -I"C:\Qt\5.4\msvc2013_64\include" -I"C:\Qt\5.4\msvc2013_64\include\QtWidgets" -I"C:\Qt\5.4\msvc2013_64\include\QtGui" -I"C:\Qt\5.4\msvc2013_64\include\QtANGLE" -I"C:\Qt\5.4\msvc2013_64\include\QtCore" -I"release" -I"." -I"C:\Qt\5.4\msvc2013_64\mkspecs\win32-msvc2013" -Forelease\ @C:\Users\CHRIST~1\AppData\Local\Temp\pythonplugin.obj.8056.15.jom
pythonplugin.cpp
	cl -c -nologo -Zm200 -Zc:wchar_t -FS -IC:/Python27/include/ -O2 -MD -Zc:strictStrings -GR -W3 -w34100 -w34189 -EHsc -DUNICODE -DWIN32 -DWIN64 -DPYTHON_LIBRARY -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I"..\..\..\..\tiled\src\libtiled" -I"C:\Qt\5.4\msvc2013_64\include" -I"C:\Qt\5.4\msvc2013_64\include\QtWidgets" -I"C:\Qt\5.4\msvc2013_64\include\QtGui" -I"C:\Qt\5.4\msvc2013_64\include\QtANGLE" -I"C:\Qt\5.4\msvc2013_64\include\QtCore" -I"release" -I"." -I"C:\Qt\5.4\msvc2013_64\mkspecs\win32-msvc2013" -Forelease\ @C:\Users\CHRIST~1\AppData\Local\Temp\pythonbind.obj.8056.31.jom
pythonbind.cpp
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(344) : warning C4068: unknown pragma
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(451) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(629) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(737) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(968) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(1374) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(1512) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(1560) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(1668) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(1762) : warning C4100: 'dummy' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(1815) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(2725) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(3106) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(3500) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(3624) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(4342) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(4426) : warning C4100: 'closure' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(4500) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(4695) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(4869) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(5017) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(5540) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(5783) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(5908) : warning C4100: 'self' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(6131) : warning C4100: 'dummy' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(6152) : warning C4100: 'dummy' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(6174) : warning C4100: 'dummy' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(6203) : warning C4100: 'dummy' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(6224) : warning C4100: 'dummy' : unreferenced formal parameter
..\..\..\..\tiled\src\plugins\python\pythonbind.cpp(6303) : warning C4100: 'self' : unreferenced formal parameter
	C:\Qt\5.4\msvc2013_64\bin\moc.exe -DUNICODE -DWIN32 -DWIN64 -DPYTHON_LIBRARY -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -D_MSC_VER=1800 -D_WIN32 -D_WIN64 -IC:/Qt/5.4/msvc2013_64/mkspecs/win32-msvc2013 -IC:/CHRISTIAN/Sources/tiled/src/plugins/python -IC:/CHRISTIAN/Sources/tiled/src/libtiled -IC:/Qt/5.4/msvc2013_64/include -IC:/Qt/5.4/msvc2013_64/include/QtWidgets -IC:/Qt/5.4/msvc2013_64/include/QtGui -IC:/Qt/5.4/msvc2013_64/include/QtANGLE -IC:/Qt/5.4/msvc2013_64/include/QtCore -I. ..\..\..\..\tiled\src\plugins\python\pythonplugin.h -o release\moc_pythonplugin.cpp
	cl -c -nologo -Zm200 -Zc:wchar_t -FS -IC:/Python27/include/ -O2 -MD -Zc:strictStrings -GR -W3 -w34100 -w34189 -EHsc -DUNICODE -DWIN32 -DWIN64 -DPYTHON_LIBRARY -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -I"..\..\..\..\tiled\src\libtiled" -I"C:\Qt\5.4\msvc2013_64\include" -I"C:\Qt\5.4\msvc2013_64\include\QtWidgets" -I"C:\Qt\5.4\msvc2013_64\include\QtGui" -I"C:\Qt\5.4\msvc2013_64\include\QtANGLE" -I"C:\Qt\5.4\msvc2013_64\include\QtCore" -I"release" -I"." -I"C:\Qt\5.4\msvc2013_64\mkspecs\win32-msvc2013" -Forelease\ @C:\Users\CHRIST~1\AppData\Local\Temp\moc_pythonplugin.obj.8056.2246.jom
moc_pythonplugin.cpp
	link /NOLOGO /DYNAMICBASE /NXCOMPAT /LARGEADDRESSAWARE /INCREMENTAL:NO /DLL /SUBSYSTEM:WINDOWS /OUT:..\..\..\plugins\tiled\python.dll @C:\Users\CHRIST~1\AppData\Local\Temp\python.dll.8056.3323.jom
   Creating library ..\..\..\plugins\tiled\python.lib and object ..\..\..\plugins\tiled\python.exp
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyObject_GetAttrString referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyObject_HasAttrString referenced in function "private: bool __cdecl Python::PythonPlugin::checkFileSupport(struct _object *,char *)const " (?checkFileSupport@PythonPlugin@Python@@AEBA_NPEAU_object@@PEAD@Z)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyObject_GetAttr referenced in function "private: struct _object * __cdecl Python::PythonPlugin::findPluginSubclass(struct _object *)" (?findPluginSubclass@PythonPlugin@Python@@AEAAPEAU_object@@PEAU3@@Z)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyObject_IsTrue referenced in function "private: bool __cdecl Python::PythonPlugin::checkFileSupport(struct _object *,char *)const " (?checkFileSupport@PythonPlugin@Python@@AEBA_NPEAU_object@@PEAD@Z)
pythonbind.obj : error LNK2001: unresolved external symbol __imp_PyObject_IsTrue
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyCallable_Check referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyObject_Dir referenced in function "private: struct _object * __cdecl Python::PythonPlugin::findPluginSubclass(struct _object *)" (?findPluginSubclass@PythonPlugin@Python@@AEAAPEAU_object@@PEAU3@@Z)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyString_AsString referenced in function "public: virtual class QStringList __cdecl Python::PythonPlugin::nameFilters(void)const " (?nameFilters@PythonPlugin@Python@@UEBA?AVQStringList@@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyList_Size referenced in function "private: struct _object * __cdecl Python::PythonPlugin::findPluginSubclass(struct _object *)" (?findPluginSubclass@PythonPlugin@Python@@AEAAPEAU_object@@PEAU3@@Z)
pythonbind.obj : error LNK2001: unresolved external symbol __imp_PyList_Size
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyList_GetItem referenced in function "private: struct _object * __cdecl Python::PythonPlugin::findPluginSubclass(struct _object *)" (?findPluginSubclass@PythonPlugin@Python@@AEAAPEAU_object@@PEAU3@@Z)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyErr_Occurred referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyErr_Clear referenced in function "private: void __cdecl Python::PythonPlugin::reloadModules(void)" (?reloadModules@PythonPlugin@Python@@AEAAXXZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_Py_Initialize referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_Py_Finalize referenced in function "public: virtual __cdecl Python::PythonPlugin::~PythonPlugin(void)" (??1PythonPlugin@Python@@UEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_Py_IsInitialized referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyRun_SimpleStringFlags referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyErr_Print referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyEval_CallFunction referenced in function "public: virtual class QStringList __cdecl Python::PythonPlugin::nameFilters(void)const " (?nameFilters@PythonPlugin@Python@@UEBA?AVQStringList@@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PySys_SetObject referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PySys_WriteStdout referenced in function "private: void __cdecl Python::PythonPlugin::reloadModules(void)" (?reloadModules@PythonPlugin@Python@@AEAAXXZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PySys_WriteStderr referenced in function "private: bool __cdecl Python::PythonPlugin::checkFileSupport(struct _object *,char *)const " (?checkFileSupport@PythonPlugin@Python@@AEBA_NPEAU_object@@PEAD@Z)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyImport_ImportModule referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyImport_ReloadModule referenced in function "private: void __cdecl Python::PythonPlugin::reloadModules(void)" (?reloadModules@PythonPlugin@Python@@AEAAXXZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyObject_CallMethod referenced in function "private: bool __cdecl Python::PythonPlugin::checkFileSupport(struct _object *,char *)const " (?checkFileSupport@PythonPlugin@Python@@AEBA_NPEAU_object@@PEAD@Z)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_PyObject_IsSubclass referenced in function "private: struct _object * __cdecl Python::PythonPlugin::findPluginSubclass(struct _object *)" (?findPluginSubclass@PythonPlugin@Python@@AEAAPEAU_object@@PEAU3@@Z)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_Py_NoSiteFlag referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonplugin.obj : error LNK2019: unresolved external symbol __imp_Py_NoUserSiteDirectory referenced in function "public: __cdecl Python::PythonPlugin::PythonPlugin(void)" (??0PythonPlugin@Python@@QEAA@XZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyType_Ready referenced in function "struct _object * __cdecl inittiled_Tiled(void)" (?inittiled_Tiled@@YAPEAU_object@@XZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyType_GenericAlloc referenced in function "void __cdecl `dynamic initializer for 'PyPythonPythonScript_Type''(void)" (??__EPyPythonPythonScript_Type@@YAXXZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyType_GenericNew referenced in function "void __cdecl `dynamic initializer for 'PyPythonPythonScript_Type''(void)" (??__EPyPythonPythonScript_Type@@YAXXZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyObject_Str referenced in function "int __cdecl _wrap_PyQImage__tp_init(struct PyQImage *,struct _object *,struct _object *)" (?_wrap_PyQImage__tp_init@@YAHPEAUPyQImage@@PEAU_object@@1@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp__PyObject_New referenced in function "struct _object * __cdecl _wrap_PyTiledTile_image(struct PyTiledTile *)" (?_wrap_PyTiledTile_image@@YAPEAU_object@@PEAUPyTiledTile@@@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp__PyObject_GC_New referenced in function "struct _object * __cdecl _wrap_PyQVector__lt__QRgb__gt____tp_iter(struct PyQVector__lt__QRgb__gt__ *)" (?_wrap_PyQVector__lt__QRgb__gt____tp_iter@@YAPEAU_object@@PEAUPyQVector__lt__QRgb__gt__@@@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyBool_FromLong referenced in function "struct _object * __cdecl _wrap_PyTiledMap_isTilesetUsed(struct PyTiledMap *,struct _object *,struct _object *)" (?_wrap_PyTiledMap_isTilesetUsed@@YAPEAU_object@@PEAUPyTiledMap@@PEAU1@1@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyLong_FromLong referenced in function "struct _object * __cdecl inittiled_Tiled(void)" (?inittiled_Tiled@@YAPEAU_object@@XZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyList_New referenced in function "int __cdecl _wrap_PyQImage__tp_init(struct PyQImage *,struct _object *,struct _object *)" (?_wrap_PyQImage__tp_init@@YAHPEAUPyQImage@@PEAU_object@@1@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyDict_SetItemString referenced in function "struct _object * __cdecl inittiled_Tiled(void)" (?inittiled_Tiled@@YAPEAU_object@@XZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyErr_SetNone referenced in function "struct _object * __cdecl _wrap_PyQVector__lt__QRgb__gt__Iter__tp_iternext(struct PyQVector__lt__QRgb__gt__Iter *)" (?_wrap_PyQVector__lt__QRgb__gt__Iter__tp_iternext@@YAPEAU_object@@PEAUPyQVector__lt__QRgb__gt__Iter@@@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyErr_SetObject referenced in function "int __cdecl _wrap_PyQImage__tp_init(struct PyQImage *,struct _object *,struct _object *)" (?_wrap_PyQImage__tp_init@@YAHPEAUPyQImage@@PEAU_object@@1@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyErr_SetString referenced in function "int __cdecl _wrap_PyTiledObject__tp_init(void)" (?_wrap_PyTiledObject__tp_init@@YAHXZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyErr_Fetch referenced in function "int __cdecl _wrap_PyQColor__tp_init__0(struct PyQColor *,struct _object *,struct _object *,struct _object * *)" (?_wrap_PyQColor__tp_init__0@@YAHPEAUPyQColor@@PEAU_object@@1PEAPEAU2@@Z)
jom: C:\CHRISTIAN\Sources\build-tiled-Desktop_Qt_5_4_0_MSVC2013_64bit-Release\src\plugins\python\Makefile.Release [..\..\..\plugins\tiled\python.dll] Error 1120
pythonbind.obj : error LNK2019: unresolved external symbol __imp__PyArg_ParseTuple_SizeT referenced in function "int __cdecl _wrap_convert_py2c__QRgb(struct _object *,unsigned int *)" (?_wrap_convert_py2c__QRgb@@YAHPEAU_object@@PEAI@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp__PyArg_ParseTupleAndKeywords_SizeT referenced in function "struct _object * __cdecl _wrap_PyTiledMap_isTilesetUsed(struct PyTiledMap *,struct _object *,struct _object *)" (?_wrap_PyTiledMap_isTilesetUsed@@YAPEAU_object@@PEAUPyTiledMap@@PEAU1@1@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp__Py_BuildValue_SizeT referenced in function "struct _object * __cdecl _wrap_PyTiledMap_isTilesetUsed(struct PyTiledMap *,struct _object *,struct _object *)" (?_wrap_PyTiledMap_isTilesetUsed@@YAPEAU_object@@PEAUPyTiledMap@@PEAU1@1@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyModule_AddObject referenced in function "struct _object * __cdecl inittiled_Tiled(void)" (?inittiled_Tiled@@YAPEAU_object@@XZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_Py_InitModule4_64 referenced in function "struct _object * __cdecl inittiled_Tiled(void)" (?inittiled_Tiled@@YAPEAU_object@@XZ)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyObject_IsInstance referenced in function "struct _object * __cdecl _wrap_PyTiledTile__tp_richcompare(struct PyTiledTile *,struct PyTiledTile *,int)" (?_wrap_PyTiledTile__tp_richcompare@@YAPEAU_object@@PEAUPyTiledTile@@0H@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp__Py_NoneStruct referenced in function "struct _object * __cdecl _wrap_PyTiledTile_setImage(struct PyTiledTile *,struct _object *,struct _object *)" (?_wrap_PyTiledTile_setImage@@YAPEAU_object@@PEAUPyTiledTile@@PEAU1@1@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp__Py_NotImplementedStruct referenced in function "struct _object * __cdecl _wrap_PyTiledTile__tp_richcompare(struct PyTiledTile *,struct PyTiledTile *,int)" (?_wrap_PyTiledTile__tp_richcompare@@YAPEAU_object@@PEAUPyTiledTile@@0H@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyExc_StopIteration referenced in function "struct _object * __cdecl _wrap_PyQVector__lt__QRgb__gt__Iter__tp_iternext(struct PyQVector__lt__QRgb__gt__Iter *)" (?_wrap_PyQVector__lt__QRgb__gt__Iter__tp_iternext@@YAPEAU_object@@PEAUPyQVector__lt__QRgb__gt__Iter@@@Z)
pythonbind.obj : error LNK2019: unresolved external symbol __imp_PyExc_TypeError referenced in function "int __cdecl _wrap_PyTiledObject__tp_init(void)" (?_wrap_PyTiledObject__tp_init@@YAHXZ)
..\..\..\plugins\tiled\python.dll : fatal error LNK1120: 50 unresolved externals
jom: C:\CHRISTIAN\Sources\build-tiled-Desktop_Qt_5_4_0_MSVC2013_64bit-Release\src\plugins\python\Makefile [release] Error 2
jom: C:\CHRISTIAN\Sources\build-tiled-Desktop_Qt_5_4_0_MSVC2013_64bit-Release\src\plugins\Makefile [sub-python-make_first] Error 2
jom: C:\CHRISTIAN\Sources\build-tiled-Desktop_Qt_5_4_0_MSVC2013_64bit-Release\src\Makefile [sub-plugins-make_first-ordered] Error 2
jom: C:\CHRISTIAN\Sources\build-tiled-Desktop_Qt_5_4_0_MSVC2013_64bit-Release\Makefile [sub-src-make_first-ordered] Error 2
20:37:44: The process "C:\Qt\Tools\QtCreator\bin\jom.exe" exited with code 2.
Error while building/deploying project tiled (kit: Desktop Qt 5.4.0 MSVC2013 64bit)
When executing step "Make"

**Comment by Chaoseiro** [comment]
I managed to build Tiled in Debug mode using QT Creator by manually building python 2.7.9 from source (in debug mode of course).

Building Python is easy, just download the [source](https://www.python.org/downloads/source/), open the PCbuild/pcbuild.sln and build pythoncore. This will build the python27_d lib and dll, that you can copy to C:/Python27/libs

Then, download and install [Windows SDK](https://msdn.microsoft.com/en-US/windows/desktop/bg162891), that contains the MS Debugger. After installing, you can open tiled.pro and it will find the python lib and QT Creator will find the MS debugger.

**Comment by ariganl** [comment]
CONFIG(debug, debug|release) {
                QMAKE_LIBS += -LC:/Python27/libs -lpython27_d
            } else {
                QMAKE_LIBS += -LC:/Python27/libs -lpython27
I don't have a python27_d.lib in my route Python27/libs, but has python27.dll, so I can only build Tiled in Release mode. what is the different between two dll

**Comment by toddcarnes** [comment]
@ariganl  If you really want the static library you could download the source (https://www.python.org/downloads/release/python-279/), as Guilherme suggested, and compile it yourself.

**Comment by bjorn** [comment]
If there is no `python27_d.lib` file in the default installation of Python 2.7 then probably I should just take out that condition and always link to `python27.lib`. The only difference should be that the debug version of the library could provide more information in case something goes wrong in the Python plugin.

**Comment by JackLinMaker** [comment]
I'm getting the same error when a try to build using Qt in Windows in Debug Mode.
LINK : fatal error LNK1104: cannot open file 'python27_d.lib'.
But it's works fine in Release Mode

**Comment by bjorn** [comment]
Well I've taken out the linking to python27_d in commit 129ef0f83d08ddbec372f5a249510335925eefcd, which should fix this issue.

**Comment by westsuper2** [comment]
I have this problem too.
I have cloned tiled-0.12.3. 
when I compile in Debug mode, report that can not open Python_d.lib 
when I compile in Release mode, report many link errors
tiled-0.12.3 Qt5.3.2 MSVC2013_OpenGL_64bit python2.7.6

**Comment by bjorn** [comment]
@westsuper2 If you use MSVC you may need to compile the Python library yourself or find some other version, because the default Python 2.7 package for Windows ships with a library compiled with MinGW, which I think is not compatible with MSVC (hence many link errors).

**Comment by westsuper2** [comment]
year,I've got it.many thanks.
