### ISSUE TITLE
Export to .ini

### ISSUE THREAD

**Issue by triverske** [bjorn/tiled#881]
Currently the flare export does something very similar to this, but it'd be nice if it supported objects and did not separate tile data into new lines. Example of part of it might look like:

```
[header]
width=4
height=4
tilewidth=24
tileheight=24
orientation=orthogonal

[tilesets]
tileset=tiles.png,24,24,0,0

[layer]
type=Tile Layer 1
data= 0,0,0,0,1,1,1,1,0,0,0,0,1,1,1,1
```

Why? Certain engines (Gamemaker specifically) have trouble using traditional parsing methods of XML and JSON.

**Comment by bjorn** [comment]
I don't want to maintain yet another output format. The only thing I could imagine is to adjust the Flare export to be a more generic .ini format, though of course it still has to work with Flare as well. However, making sure all map information is included and also read back in correctly would be quite some effort.

Did you try this converter instead? http://j2h.ru/tiled2gm-eng/

**Comment by triverske** [comment]
Perhaps a export editor like you have described in the past may be the solution then.

The problem with the converter is that it doesn't support all of tiled's features and requires you to run the map through a processing program before it's compatible with Gamemaker. I was hoping to create a method in which a file could go straight from Tiled to Gamemaker (which is possible using the flare export, but it doesn't support objects).

**Comment by josefnpat** [comment]
You can try using @bartbes' inifile to convert exported Lua to ini: http://docs.bartbes.com/inifile

In the end, I feel like this would be best done with a glue library; something to convert xml/json/lua to the ini format you're looking for.

**Comment by triverske** [comment]
I'll look into that josef.

I do however think that at some point an editor that allows you to select what to and not to export and how to export them could be greatly beneficial. (and possibly make maintaining the current exports a lot easier)

**Comment by bjorndm** [comment]
Well, this would probably best be implemented as a separate "export/conversion" tool.

**Comment by bjorn** [comment]
@triverske What shall we do with the unclaimed bounty on this one? The next version of Tiled will actually have an exporter to GameMaker format (see #1386). If that helps you maybe @JonesBlunt could claim this bounty as well. Otherwise, you can also contact BountySource about releasing it to your account, so you can use it as a bounty for some other issue.

**Comment by triverske** [comment]
JonesBlunt solved my problem so I suppose we should arrange for him to get the bounty.

**Comment by bjorn** [comment]
Alright, I've sent him an e-mail.
