### ISSUE TITLE
Is it possible to erase selected areas?

### ISSUE THREAD

**Issue by cryo75** [bjorn/tiled#884]
Just like click the right mouse button and drag the mouse in a tile layer to select the selected tiles, is it possible to do the same to erase selected tiles using the Eraser?

**Comment by bjorn** [comment]
No, to erase selected areas, use the selection tool to select the area you want to erase and then press the Del button (or cut it with Ctrl+X).

I would like to add right-click drag area for faster erasing, though.

**Comment by bjorn** [comment]
Improving the eraser tool is already covered by issue #391.

Please consider [supporting me financially](https://www.patreon.com/bjorn) so that I may have time to work on such improvements.

**Comment by cryo75** [comment]
The selection tool is disabled when on a tile layer.

**Comment by bjorn** [comment]
@cryo75 There are two selection tools, one for object layers and one for tile layers.
