### ISSUE TITLE
Export Tileset bug

### ISSUE THREAD

**Issue by T1mL3arn** [bjorn/tiled#885]
So, I tried 'Export Tileset As' feature just for test how will be look a text representation of .tsx file. Then I removed .tsx file and I have lost all map graphic! F! And now is need to add all graphic to tileset again, and again place it on the map, set props and etc. Will be nice to use export feature as export, copy, clone, but without hard linked with the map. 

I make export for tileset based on collection of image.

**Comment by bjorn** [comment]
Hmm, this does not sound like a bug but rather a feature request. Though it could be that the Export Tileset is a little confusing...

**Comment by T1mL3arn** [comment]
Feature? Ok, something like a new button 'Save Tileset' that will save tileset without links to current map. Thanks!

**Comment by bjorn** [comment]
> Feature? Ok, something like a new button 'Save Tileset' that will save tileset without links to current map. Thanks!

I guess this now exists, also for embedded tilesets (since Tiled 1.1). You'd just click the button to edit the tileset and then go to _File > Export As..._ to save that tileset in any supported format without affecting the map.
