### ISSUE TITLE
Copy and pasting objects not working

### ISSUE THREAD

**Issue by jforkan** [bjorn/tiled#886]
Recently upgraded to 0.11.0 on OSX 10.10.2. When I click an object in an object layer and try to copy it, cmd+c does not work and Edit > Copy is greyed out. I haven't come across this issue before using older versions of Tiled.

**Comment by jforkan** [comment]
This seems to be fixed in the latest build.

**Comment by bjorn** [comment]
@jforkan Hmm, no fix related to this was checked in, so I guess I should still check up on this... Please tell me if you hit the issue again.

**Comment by thelucre** [comment]
I'm seeing the issue as well in the nightlies, on OSX 10.10.2

**Comment by bjorn** [comment]
@thelucre I could not reproduce it when I shortly checked for this issue. Is there maybe any specific context or steps you could mention to help me reproduce this issue?

**Comment by thelucre** [comment]
Apologies. It appears to be fixed here. Thanks!

**Comment by bjorn** [comment]
Alright, closing again then. :-)
