### ISSUE TITLE
I need the document of Tiled source code

### ISSUE THREAD

**Issue by ariganl** [bjorn/tiled#887]
I cannot find the document of the Tiled source code, can anyone give me one? Thinks very much

**Comment by ariganl** [comment]
my email is atquanquan@gmail.com, thinks

**Comment by bjorn** [comment]
What kind of document are you looking for?

If you mean the source code documentation, you can generate this yourself using [Doxygen](http://www.stack.nl/~dimitri/doxygen/). Just run it in the `docs` directory of your Tiled repository clone.

**Comment by ariganl** [comment]
thinks, since i can't understand the source code clearly, i wish to have a document which explains the source code, i will try to get a document using Doxygen.

**Comment by bjorn** [comment]
Ah, sorry but there is no documentation apart from the comments in the source code.
