### ISSUE TITLE
Unresponsive Object Reordering

### ISSUE THREAD

**Issue by Yukitty** [bjorn/tiled#889]
Raise Object `PageUp` and Lower Object `PageDown` aren't doing anything at all for objects (when used as a keyboard shortcut _or_ when clicked from the context menu), even though Raise Object to Top `Home` and Lower Object to Bottom `End` are working just fine.

Tested in both v0.11.0 and the latest daily build (2015-02-08).

Edit: **WAIT WHAT.** Does it only work when two objects are touching eachother?! X_x;; That's no good, objects in game engines _move_! If I have an enemy that can walk in front of some pots, currently I have to manually drag them over the pots and press the `PageUp` button to raise it above them, unless I want that particular enemy to be at the top of _everything_ currently in the map...

**Comment by bjorn** [comment]
It works the same way these actions work in other shape editing tools (like Inkscape), where "raise object" means to put it on top of the currently "lowest" object still higher than the object you're operating on. If no object is on top of the selected object, no action is required.

What do you expect 'raise object' to do in this case? Raise it by one index? What is to say that is the correct amount to raise the object by and how are you going to know without seeing the overlap?

I personally think changing the behavior of these actions may be confusing, especially considering the behavior in similar applications. So I think instead what you are looking for is to arbitrarily change the order of the objects, which is covered by #888.
