### ISSUE TITLE
Changing position of selected objects.

### ISSUE THREAD

**Issue by T1mL3arn** [bjorn/tiled#892]
When I select some objects and try to change their Y-coord (or X) then ALL objects gets the identical position. So if I need to place the group of some objects strictly vertical (or horizontal) I should to set each object coords separately. Same story with objects size.

It will be nice to edit one part of position property (and size) in a way that other part of property does not changing.

**Comment by bjorn** [comment]
Hmm, I agree. Probably the easiest approach would be to just separate the x, y, width and height properties rather than having 'position' and 'size' property groups.
