### ISSUE TITLE
Not able to edit layer object properties?

### ISSUE THREAD

**Issue by CodySquadroni** [bjorn/tiled#894]
As title says, trying to follow the tutorial from melonjs and when I create an object layer and I goto properties it doesn't show any of the right properties just the original layer properties panel.
I'm using the current version on a mac, am i doing it wrong or is this a bug?

**Comment by bjorn** [comment]
Can you show a screenshot? I'm not sure exactly what you mean.

**Comment by CodySquadroni** [comment]
Here are images, you can see that i create a new Layer Object.

When I right click the newly created object the only properties that appear are for layer properties, so I click that and then you see the layer properties panel. When I was looking through the melonjs tutorial using Tile there should be a way to edit the Object Properties but that option is not visible or at least giving me the setting for that object. Not sure if this is a bug or if I'm just not seeing the right thing. I've attached an image of the tutorial image of object properties. Im assuming this tutorial is outdated but I'm assuming you should still be able to edit the objects properties. Sorry if I'm making this confusing.

Create an Object Layer
![screen shot 2015-02-25 at 8 36 03 am]

Try to edit Object Layer Properties but only shows Layer Properties
(https://cloud.githubusercontent.com/assets/9661019/6373687/7d40f3aa-bcc9-11e4-80a2-7861a2a6807f.png)

![screen shot 2015-02-25 at 8 36 09 am](https://cloud.githubusercontent.com/assets/9661019/6373688/7d424de0-bcc9-11e4-957d-4bced804824d.png)

![screen shot 2015-02-25 at 8 36 18 am](https://cloud.githubusercontent.com/assets/9661019/6373689/7d4485ec-bcc9-11e4-926d-5b0bf008e0b9.png)

Tutorial Image (Object Properties)
![step3_addentity](https://cloud.githubusercontent.com/assets/9661019/6373750/f42ceeec-bcc9-11e4-82b6-8404a088ee10.png)

**Comment by bjorn** [comment]
Your last image shows the properties dialog for an object, not for an object layer. To edit the properties of an object, you need to create an object first, using any of the "create object" tools in the tool bar.

Judging by your last screenshot the tutorial you're following is very outdated. It may be from the time that Tiled did not even have multiple object creation tools yet, so maybe it failed to mention that you need to select one before you can draw objects (in which case you want the "insert rectangle" tool).
