### ISSUE TITLE
Flipped flag for tile objects.

### ISSUE THREAD

**Issue by T1mL3arn** [bjorn/tiled#895]
I place tile on object layer, flip it and `gid` become a large value! Then I saw that is using bitwise mask. It is really need to hide flipping of the object inside its gid property? Might be worth it to save a separate attribute for object?

**Comment by T1mL3arn** [comment]
Oh, I understand the reason. It is reduce data for tiles on tile layers.

**Comment by bjorn** [comment]
Yeah the reason it's using the bit flag also on the object tag is just for consistency with the tile layers, though I fully agree that it's not very ideal. Neither situation feels ideal. :-(

**Comment by bjorn** [comment]
Ah, also, having it as an attribute on the object may be confusing, since it really just applies to the tile graphic, not to the object in general. It can't be used to describe a flipped polygon object, for example.
