### ISSUE TITLE
When using Terrain brushes, Something wrong with the connection between center tiles

### ISSUE THREAD

**Issue by ypfsoul** [bjorn/tiled#898]
When using terrain brushes with 3X3, everything is ok. but when using terrain brushes with 4X4, problem happened. Terrain brushes  show the wrong tile(the middle two 2X2) , as shown below.

![qq 20150302143103](https://cloud.githubusercontent.com/assets/8327087/6436358/0098f694-c0e9-11e4-950e-6804c7f6c959.png)
![qq 20150302143110](https://cloud.githubusercontent.com/assets/8327087/6436359/04c3a9da-c0e9-11e4-813c-136b7e8bbb31.png)

**Comment by kheftel** [comment]
Are all 4 of your center tiles for each terrain freely tileable with each other?

**Comment by bjorn** [comment]
The terrain tool knows nothing about the requirement to place certain tiles always together. All you can tell it is that the 4 tiles in the middle all have the same terrain on all their corners, which will cause the terrain tool to pick one randomly for such situations.

So as @kheftel implied, you need to make sure that each of those tiles in the middle is tileable with each of the other tiles, which currently is not the case.

I don't know currently how this scenario could be supported. Apart from telling Tiled that certain blocks of tiles belong together, how would you expect Tiled to behave in case you have an uneven amount of tiles in the middle? You'd somehow need another tile graphic just for making sure things connect correctly in that case.

**Comment by ypfsoul** [comment]
I got it.Thanks!
