### ISSUE TITLE
Tiles placed with a multiple tile selection are incorrect in isometric/hex maps

### ISSUE THREAD

**Issue by parkm** [bjorn/tiled#900]
In my isometric map I have a tileset of a large structure that takes up multiple tile spaces. Normally in an orthogonal map you can just select the entire structure in the tileset dock and then place it into the map, but when doing this in an isometric and hexagonal map I found a strange problem.

![Imgur](http://i.imgur.com/vBrXjKs.jpg)

So at the top right is how the structure should look when placed. To the left is what I got when I placed the tiles in the map. I'm still able to place it correctly but I would have to manually select each tile and place it. 

I've only tested it on versions 0.11.0 and 0.10.0 on Windows 7.

**Comment by hexateron** [comment]
Disclaimer: I'm just working on a project which uses a slightly modified version of Tiled which is probably out dated.

Isometric tiles are still full rectangles, not diamonds. So you'll need to chop stuff up and space them out differently than for orthogonal maps. In normal isometric (as in not staggered) the rows start from the top left to the right.
![isotiles](https://cloud.githubusercontent.com/assets/2667395/6478442/be4cb01c-c1f8-11e4-9d9d-1f1d8618e4c7.png)

Also note that your tiles don't need to be the same size as the map tiles.
![tilehouse](https://cloud.githubusercontent.com/assets/2667395/6478531/c8b83e5c-c1fa-11e4-9cf3-3d1c30d8eea5.png)
By the way, for the particular case of the house above we use automapping rules instead to properly arrange the tiles of the house.

**Comment by parkm** [comment]
@hexateron Thanks for the help! New to isometric maps. 
Not a problem in Tiled, closing.
