### ISSUE TITLE
CLI --export-map needs better usage docs

### ISSUE THREAD

**Issue by josefnpat** [bjorn/tiled#903]
Thanks to @Ablu on IRC, I was able to write this issue with confidence that it is indeed an issue.

I'm running Arch Linux 64-bit, so I have a rather new release.

    $ tiled --version
    Tiled 0.11.0

Three issues:

1. `man tiled` does not show any information on the `--export-map` flag.
2. For `tiled --export-map` there is no way to determine what plugins are available for the [format] argument.
3. There is a plugin conflict for exporting to Lua from the CLI.

The first issue:

You'll notice that the `--export-map` flag is there, but not on the man page.

    $ tiled --help
    Usage:
      tiled [options] [files...]

    Options:
      -h --help           : Display this help
      -v --version        : Display the version
         --quit           : Only check validity of arguments
         --disable-opengl : Disable hardware accelerated rendering
         --export-map     : Export the specified tmx file to target

The second issue:

Perhaps this is my own ignorance, but I really have no way of figuring out what `[format]` should be.

    $ tiled --export-map
    Export syntax is --export-map [format] <tmx file> <target file>
    $ tiled --export-map map.tmx map.lua
    Non-unique file extension. Can't determine correct export format.
    $ tiled --export-map lua map.tmx map.lua
    No exporter found for target file.
    $ tiled --export-map Lua map.tmx map.lua
    No exporter found for target file.

The third issue:

@ablu mentioned that I could disable the `libtengine` plugin, so I removed:

`/usr/lib/tiled/plugins/libtengine.so`

I did so, and autodetecting the `.lua` extension works. But this feels like a workaround, and there should either be documentation on the wiki (which I would be happy to supply) or perhaps a `--list-map-exporters` flag.

Please feel free to close and triage this ticket as you see fit. Thanks for all the awesome work on Tiled!

**Comment by RobYed** [comment]
Hey,

I'd love to integrate the cli export feature into my build process. And I also wonder, what [format] should be, when I want to output as JSON. Did you figure it out? Or can someone give me a hint?

Thanks!

**Comment by RobYed** [comment]
Okay, I just found out that you can leave out `[format]` completely. Instead, the command seems to check the file ending. I successfully exported my tmx to json like this:

`tiled --export-map level1.tmx level1.json`

For this I used tiled-daily version 2015-04-29. I don't know whether this is possible in earlier versions.

**Comment by bjorn** [comment]
That the format is optional is what the `[...]` brackets are trying to indicate, whereas the `<...>` brackets signify something mandatory.

It seems that at the moment, the "format" would need to be the entire file type string also used in the file open dialog, and the translated version of it if you're using Tiled in a different language. So if you use Tiled in English and want to export to JSON, you'd need to do:

    tiled --export-map "Json files (*.json)" level1.tmx level1.json

I'll consider alternatives before releasing Tiled 0.12 because I don't really like this. Maybe the plugin name would be better.

**Comment by bjorn** [comment]
I realized the plugin name was not going to work due to the possibility of one plugin implementing multiple formats. So for now I just kept the `--export-map` option as is, and added an `--export-formats` option to retrieve the list of supported formats.

**Comment by RobYed** [comment]
Again, great feature! Thanks for your explanation :)

**Comment by josefnpat** [comment]
:+1:
