### ISSUE TITLE
Let Tiled remember the last active layer on exit

### ISSUE THREAD

**Issue by xerosugar** [bjorn/tiled#905]
This is kind of tied to another issue; Tiled doesn't always update the tilesheet image I'm working with.
This is my workflow atm: I paint some tiles, look at the result, make adjustments to tilesheet in drawing program, back to Tiled, close map, open map (to see changes), change layer to the one I'm working with, repeat...

So yeah, two issues in one here :p

**Comment by bjorn** [comment]
Remembering the active layer is a very reasonable request, thanks for opening an issue about it.

Regarding the auto-reload of the tilesheet image, are you affected by issue #44? Note that you can press Ctrl+T to manually trigger a reload, which should be faster than reopening the map.

**Comment by xerosugar** [comment]
Yes, #44 feels familiar. Btw, there's a Ctrl+R command which is also reload, (Ctrl+T isn't even an option in my version), is this for when the user is editing the map outside of Tiled?
Maybe these events should be triggered as soon as Tiled becomes the new active window again? Sublime Text comes to mind when talking about auto-updating open files, maybe Tiled could do the same?

**Comment by bjorn** [comment]
`Ctrl+T` is a hidden shortcut (doesn't appear in any menu) for reloading the tileset images.

`Ctrl+R` reloads the map file itself, and may not reload the tileset images. A Sublime-Text like automatic reload is already done for maps since Tiled 0.10, though it does not wait until the window becomes active again. Are you missing something there?

**Comment by xerosugar** [comment]
Ok, got it. Good luck with your work!

**Comment by bjorn** [comment]
I was just thinking that Tiled already did this, but then I realized it's only doing that for the open maps when you close and reopen Tiled, not when you close and reopen a map while keeping Tiled open. So I'll keep this issue as a reminder to implement the last part as well.
