### ISSUE TITLE
Tiled installed in OS's language (Dutch) rather than language picked while installing.

### ISSUE THREAD

**Issue by Silenia** [bjorn/tiled#919]
In spite of choosing English for the setup, the version of Tiled on my computer is in Dutch. This makes some amount of sense considering I use a Dutch version of Windows 7 and am indeed located in the Netherlands. 

However, I chose English for a reason. I speak both English and Dutch fluently, and when it comes to online support, tutorials and other such matters, English tends to be a lot more useful for graphics programs. Less effort figuring out which setting/option/function people mean if you don't first have to translate it back to English.

I could not find any place to change the language settings on my already installed Tiled. If I'm overlooking it, I'd appreciate if someone could point me in the right direction.

If not, is there any other way I can get an English-language version of Tiled on my pc?

**Comment by bjorn** [comment]
The language you choose for the installer has nothing to do with the language choice in Tiled. You can change the language of Tiled itself in *Edit -> Preferences...*

**Comment by Silenia** [comment]
Thank you. Apparently I kept overlooking that option.
