### ISSUE TITLE
How can i get the "Rotation" information of one object

### ISSUE THREAD

**Issue by castle321** [bjorn/tiled#921]
I set the value of the object's rotation, but i can't get the value of "Rotation" in code, so i want to know how can i get the "Rotation" information of the object.

**Comment by bjorn** [comment]
This is a question for whatever library you're using to load the map. Which one is it?

**Comment by castle321** [comment]
I use cocos2dx-3.3 for developing mobile game.

**Comment by bjorn** [comment]
Object rotation was added in Tiled 0.10 and evidently cocos2d-x was not updated to include support for it yet. Its map file parser is not reading this attribute at all. I've opened a pull request to add this, referenced above.

When it is merged you'll of course need to upgrade to either their latest master branch or await their next release and upgrade then. For the first option, you could of course use my fork until the change gets merged, if it's really urgent.
