### ISSUE TITLE
Load runtime library Error R6034

### ISSUE THREAD

**Issue by Ventura2** [bjorn/tiled#922]
I am getting an library error when I run:

![Alt text](http://snag.gy/cNntd.jpg)

It doesn't allow me to use the collision editor in the new versions. I tried  installing and uninstalling c++ redistributable packages 2010 but it didn't work.

**Comment by bjorn** [comment]
You mean, Tiled runs normally but once you try to open the collision editor, this message pops up?

**Comment by Ventura2** [comment]
It happens when I start the software. Just after click tiled.exe

**Comment by bjorn** [comment]
> After click accept the software open but the collision editor doesn't let me to add rectangles using the rectangle tool.

For this particular problem, could it be that you're trying to edit the collision of a tile in an external tileset? This is not supported at the moment, so for doing this you will have to temporary import the tileset using the "Import" button in the Tilesets view.

As for the error message, it's most likely unrelated to the collision editor. It's the first time I've heard about it and I have no idea what may be causing that.

**Comment by Ventura2** [comment]
Hello bjorn, good news, the collision editor was not working because what you told, I was using an external tileset, I tested creating a new one and now it work. 

The error in the begginning keep happening but it doesn't cause any problem or bug in the software for now.

**Comment by Ventura2** [comment]
Deleting python.dll in "plugins/tiled" makes disappear the error. Any idea why can it be?

**Comment by bjorn** [comment]
Do you have Python installed? If so, which version and from where?

You could try to use [Dependency Walker](http://www.dependencywalker.com/) to find out which Python DLLs are being used. I think it should not be using any though, since as far as I am aware Python is statically included in the `python.dll` plugin. Still, the tool may be able to show what causes the problems with loading the C runtime library.

**Comment by Ventura2** [comment]
I had a python27.dll dependency in Meld merge tool. I uninstalled the software and know I don't get error.

**Comment by bjorn** [comment]
Ah! I guess you had added this tool to your PATH, causing Tiled to pick up this apparently incompatible DLL? I wonder if I should ship the expected `python27.dll` in the TIled installer...

**Comment by bjorn** [comment]
Closing this old issue since we're no longer using Python 2.7.  Unfortunately, there are even worse problems for some people now that we're on Python 3.7 (#2091).
