### ISSUE TITLE
Can't open Tile Properties

### ISSUE THREAD

**Issue by maxinatorik** [bjorn/tiled#923]
What's the problem? Tile Properties seem not working. I'm right-clicking on tile, then clicking Tile Properties and nothing happens

**Comment by bjorn** [comment]
Then I guess the Properties view is already open?

**Comment by maxinatorik** [comment]
Well, it should open a new window where i can create new properties, but it didn't open

**Comment by Ablu** [comment]
Note that on recent tiled versions the editing of properties no longer happens in a popup but in a normal dock. So after you select the properties option you should have that dock open somewhere in your tiled window.

**Comment by kheftel** [comment]
Also make sure that you have the properties panel set to show from the view menu.  Here's a screenshot on mac, notice the properties panel in the bottom right.

![image](https://cloud.githubusercontent.com/assets/669328/7281332/3d45ae64-e8e6-11e4-9380-b83a61771398.png)

**Comment by bjorn** [comment]
@kheftel Well, the thing is that when the Properties view is not already open, then the "Tile Properties..." menu item will open it for you. Hence, if there is no response it usually means the view is already open somewhere.

**Comment by kheftel** [comment]
Actually, I just tried that - on 0.11.0 on OSX 10.10 Yosemite, I disabled the properties pane from the view window, and right-clicked on a tile in the tileset, and "tile properties" is still greyed out.

**Comment by bjorn** [comment]
> and right-clicked on a tile in the tileset, and "tile properties" is still greyed out.

If it is grayed out, then you're testing it with an external tileset. It is currently not possible to edit tile properties of an external tileset without first temporarily importing it.

**Comment by kheftel** [comment]
Of course, you are right LOL.  Forgive my bumbling efforts to help.

**Comment by bjorn** [comment]
@kheftel It's no problem. I really should find a way to fix this shortcoming so that I can stop explaining people these silly steps, but it's unfortunately not trivial.

**Comment by maxinatorik** [comment]
Thank u, guys. It worked for me. Properties were opened in the bottom right panel

**Comment by bjorn** [comment]
To avoid confusion maybe the panel should flash a little in this case, but this is not so easy to implement in the current interface and I think it is a rare problem, so I'll just close this issue for now.
