### ISSUE TITLE
Document JSON format

### ISSUE THREAD

**Issue by rcorre** [bjorn/tiled#925]
It would be nice to have some documentation in the wiki for what you can expect to find in an exported JSON tilemap.
What fields are always there, and which are optional? As the names are not always totally descriptive, what do they mean?

You can guess based on the [TMX](https://github.com/bjorn/tiled/wiki/TMX-Map-Format) documentation to some degree, but the fields are not completely the same and even for TMX the docs can be a bit lacking.

Two things I've wished for documented confirmation on are:
1. Can we assume that Tilesets are sorted by GID? As tilesets only provide the firstgid, sorting is useful for mapping a GID to a tileset, and its nice to know whether your parser can assume they are sorted or whether it has to do the sorting itself.
2. How do margin and spacing work? Is the offset of the first tile just (margin) or (margin + spacing)?

If you think this would be useful, I could try to put together a wiki page, but I'd need some confirmation on fields where I'm not sure of the meaning.

**Comment by bjorn** [comment]
I totally agree there should be a reference document for the JSON format as well. Even though I think the aim should be to keep it terse and refer to the TMX docs for the full descriptions of the information.

Of course, it's a good idea also to make sure the TMX format is also more completely documented. To answer your two questions:

> Can we assume that Tilesets are sorted by GID? As tilesets only provide the firstgid, sorting is useful for mapping a GID to a tileset, and its nice to know whether your parser can assume they are sorted or whether it has to do the sorting itself.

Tiled does not make this assumption in its map reader, but it does always write them out in sorted order. I see no reason for doing anything else and I can see how this would be useful, so I'm fine with requiring this in the TMX format.

> How do margin and spacing work? Is the offset of the first tile just (margin) or (margin + spacing)?

Margin defines the space on the borders of the tileset and spacing the space between the tiles. The offset of the first tile is only the margin.

One problem with 'margin' I'm aware of is that conceptually the margin is also present at the right and bottom sides of the tileset, but Tiled does not consider this. So if somehow a whole tile fits (partly or entirely) inside the margin, then these tiles will be included in the tileset. Fortunately this is a rather rare corner case, but I guess a note about this should be in the format docs. This may also be different from what Tiled Java did, but I did it this way so that margin could be used as purely a starting offset. Just that now the name is a little confusing...

**Comment by PMunch** [comment]
It's been over two years now and still no documentation of the JSON format? I'm trying to write a parser for the format but it's been a huge guesswork so far.

**Comment by rcorre** [comment]
Hi @PMunch, I wrote [a wiki page](https://github.com/bjorn/tiled/wiki/JSON-Map-Format) shortly after I posted this issue. I'm not sure how up-to-date it is.

I also wrote a [map parser in D](https://github.com/rcorre/dtiled) that works with the JSON format. It might be useful as a reference. There are also [parsers for many other languages](http://doc.mapeditor.org/en/latest/reference/support-for-tmx-maps/#support-by-language), though I'm not sure how many support JSON, as that page is about TMX.

**Comment by PMunch** [comment]
Aha, that sight is indeed helpful. Maybe it should be linked from the website (specifically the region on the TMX format)?

**Comment by bjorn** [comment]
It should be moved from the wiki to http://doc.mapeditor.org. I'll try to do this soon and also go through the document for necessary updates.

**Comment by PMunch** [comment]
Great! By the way, I noticed that it lacks information about text objects.

**Comment by bjorn** [comment]
The JSON Map Format page has now been moved to http://doc.mapeditor.org/en/latest/reference/json-map-format/. It still needs to be updated, though.

Nice project, @PMunch! When it's complete we can add it to http://doc.mapeditor.org/en/latest/reference/support-for-tmx-maps/#support-by-language :-)

@rcorre Btw, I don't really mean for that page to be TMX-specific and I think it would make sense to list your dtiled library also under the D section.

**Comment by DanTup** [comment]
I was looking at writing something for parsing the JSON format in Dart today and planned to code-gen classes to deserialise into. This turned out to not be as simple as I'd expected as the JSON spec wasn't written with machine-parsing in mind. For example, in the rst file the list of fields for a type can be split over multiple lines:

```
+------------------+----------+---------------------------------------------------------------+
| data             | array or | Array of ``unsigned int`` (GIDs) or base64-encoded            |
|                  | string   | data. ``tilelayer`` only.                                     |
+------------------+----------+---------------------------------------------------------------+
```

Similarly, the types are sometimes written in English sentences, like:

```
| properties       | array    | A list of properties (name, value, type).                     |
```

This generating the types has involved some hard-coded rules/assumptions which could break in future. It'd be really neat to have a machine-readable format to help create (and maintain) libraries that read this format :-)

**Comment by bjorn** [comment]
@DanTup I'd rather not maintain another file, given that it's already hard enough to get around to maintaining this single one. Hopefully it's possible to serve both needs from one file. Feel free to suggest changes if they help you parse the file more reliably while not compromising on human-readability.

**Comment by DanTup** [comment]
@bjorn one option could be to maintain it in a structured form, and then generate the human-readable doc from it. I do appreciate that's more effort though, so if I see other small tweaks that can be made to make it more parsable (without upsetting the human-readable version) I'll open further PRs. Thanks for the great software! 👍

**Comment by bjorn** [comment]
@DanTup Thanks! Btw, in the [scripting documentation](https://github.com/bjorn/tiled/blob/master/docs/reference/scripting.rst) I'm using a lot of CSV to format the tables, which I find much more comfortable than maintaining the ASCII artwork. Probably it would be good to transition the JSON docs to that table format as well.

**Comment by DanTup** [comment]
@bjorn I think the CSV format would be much nicer! :-)

**Comment by bjorn** [comment]
@DanTup It has been done, along with several other corrections and additions. :-)

**Comment by DanTup** [comment]
@bjorn thanks! This looks great, it adds types for many places I still had `object` and hadn't resolved. I'll try to update my scripts this weekend and let you know (or open PRs) if I find anything not easily parsed :-)

Btw, do you have know of any "complicated" public maps (ones that use as many features as possible) that would be good test cases to compare my rendering against the editor? The ones in the examples folder aren't very complicated so I started making my own, but I think I saw somewhere that you said you wanted to make examples that used all the features. Specifically I'm worried about things that might not be common in simple maps and easy to miss in testing (like render order, layer offsets, tile rotations).

**Comment by bjorn** [comment]
@DanTup The `orthogonal-outside.tmx` is the most "complicated" example map, where I tried to use as many features as possible, so it featured every kind of object for example.

Unfortunately, that map was created in 2016 and after that more features were added, so it does not feature any text objects, template instances or Wang tiles. In addition, we'll need multiple maps to actually use all features, like at least one for each orientation, at least one infinite map, one using a custom rendering order, etc. The set of example maps can definitely be improved and I'd welcome any help in this area.

**Comment by DanTup** [comment]
@bjorn Thinking about this more, I think smaller maps that cover less features each might be better for my purposes (eventually, I hope to have screenshot-based tests, so having smaller tests that are more obvious what they're testing would be best - for ex. one doing all the rotations/flipping, one doing offsets, one doing tile spacing, etc).

If I do end up producing something that might be useful, I'll let you know though. Whatever is helpful for me testing is no doubt helpful for anyone else making rendering libraries too.

By the way, I've mostly moved over to generating from the CSVs - the results are much better (less edge cases, and more things are typed). However I noticed that `transparentColor` on `imagelayer` doesn't seem to be included in the TMX spec. Is this just missing from the TMX one, or is it not used anymore?

**Comment by bjorn** [comment]
I agree many smaller example maps is a better approach when it comes to testing of features.

Regarding `transparentcolor`, in the TMX format this is stored as the `trans` attribute of the nested `<image>` element.

**Comment by DanTup** [comment]
Yeah, though as I made my first screenshot test just now, it occurs to me that the runtime of a single map would be much faster :D I'll see what I end up with anyway, and if anything looks useful we can see if it's worth adding to examples here (or another repo).

>  in the TMX format this is stored as the `trans` attribute of the nested `<image>` element.

Aha, got it! :)
