### ISSUE TITLE
Play Test Button

### ISSUE THREAD

**Issue by RPGHacker** [bjorn/tiled#940]
I don't know if this is the correct place for feature requests/suggestions, so I apologize if I'm wrong here.

Anyways, I wanted to request a feature which I've actually already implemented in a custom build of Tiled on my hard drive, but I thought that everyone could profit from it. Additionally, when I implemented this feature, I did it in a Windows-specific way, not knowing that Qt actually supports the functionality I needed in a platform-independent way. Anyways, the feature I want to request is a play test button in the editor:

![Image of my custom Tiled build](http://puu.sh/hJFbR/68231f64cd.png)

What this button does is the following:
-First it simply saves your map (optionally with a confirmation dialog, but in my case I just used the regular save function)
-Next it opens a file dialog and asks you for a path to an application
-After that it opens a path dialog and asks you for a path to a working directory
-It then finally creates a process using the specified application path and working directory path and passes the path to the currently opened map to this new process
-At the same time it creates a foreground dialog with the text "Map is being tested" and an abort button on it. The abort button, when clicked, instantly terminates the process and closes the dialog. The dialog also constantly checks the handle for the process and automatically closes itself once the process is terminated externally.

The whole point of this, as you can probably guess, is to have a comfortable and easy way to instantly test your map from within the editor, without having to manually switch applications or do fancy command-line stuff. Especially when you're working on a team project with people who have no Programming experience and only do level design, it can be really useful to have this kind of button so they can easily test their creations without having to mess with any source code or pass arguments to your game application manually. It also saves the programmer of a game a lot of time, since all he has to do is to parse some command-line arguments and then load a level based on the passed string instead of having to spend a lot of time programming a fancy debug level selection. To save even more time, Tiled could save the two path settings (applicaton path and working directory) somewhere so that you would only have to select the pathes once (and only switch them if you'd want to test you map in another application).

Code-wise, Qt's [QProcess](http://doc.qt.io/qt-5/qprocess.html) class should make it very easy to implement this kind of functionality. Even easier than my Windows-specific approach. It should be doable in about a weekend, probably even less for Qt-experienced people (I had no experienced with Qt at all, so it took me about two weekends, although most of the time was actually spent trying to get Tiled compiled in the first place).

I'd be glad if you considered implementing this feature into the main branch. And heads up for the great work on Tiled! ;)

**Comment by bjorn** [comment]
Hmm, most of the requested functionality is already implemented and also already available under the F5 shortcut. The action is on the toolbar:

![selection_007](https://cloud.githubusercontent.com/assets/531764/7575268/bd6a2474-f833-11e4-8478-68f4520d45ae.png)

It is documented on the wiki at [Using Commands](https://github.com/bjorn/tiled/wiki/Using-Commands). The only thing is does not do is keeping track of the process and allowing to quit it, unless I missed something in your request.

Maybe I should keep this issue open as a reminder to also put the action somewhere in the menus, to make it more easily discoverable.

**Comment by RPGHacker** [comment]
Really? I feel stupid now! x(
But that is great to know. I never knew what the command button was meant for and the name missled me to think that it was a menu for creating your own keyboard shortcuts or something like that. I definitely didn't expect this functionality under that button. Although, I guess, it's my own fault for not reading the documentation. I'm a learning by doing type and thought I'd figure everything out just by trial and error.
But yeah, I guess making this functionality a little less "hidden" could help.

Anyways, since this question is not covered by the linked wiki entry: Is it actually possible to set the working directory using the command button? That is actually a very important feature in my opinion since it's common practice in programming to have multiple build targets in different directories, but only a single resource directory. In my custom implementation of this feature, I'm setting the working directory to my project path, which is the same directory Visual Studio by default sets as its working directory, and then access my resources via relative pathes. That way I don't always have to copy my executable to the project root directory to test a map in the most recent build of my game. In case this isn't implemented already, it would definitely be a helpful feature.

And of course file picker dialogs would be nice, too, although of course absolutely not mandatory. In my case, entering pathes manually is actually quite fine. A file picker would just make it a little more comfortable.

Maybe the best solution would be a combination of both buttons. A play test button that lets you pick an executable and working directory (like I described), but also lets you pass custom command-line arguments (like the command button).

But yeah, now that I understand what the command button is intended for, this feature request can definitely be classified as "nice-to-have".

**Comment by bjorn** [comment]
For the working directory thing, I believe you could work around this missing feature by writing a small script that changes the working directory before executing your game binary, and then launch this script from Tiled.

**Comment by RPGHacker** [comment]
Sounds like a good idea. I will give that a try.

**Comment by bjorn** [comment]
Alright, I've opened issues for the all the important parts I think, then I can close this one given that the general feature is already there. Thanks for the additional suggestions! :-)
