### ISSUE TITLE
Add Execute Command action also to menu

### ISSUE THREAD

**Issue by bjorn** [bjorn/tiled#943]
Adding the Execute Command action also to the menu should help with its discoverability and would be the only way to see the shortcut currently, apart from browsing the wiki.

Idea came up at issue #940.

**Comment by RPGHacker** [comment]
I also suggest (in case this isn't how the keyboard shortcut works already) to add a designated button just for the execute command. If I got this right, then there is currently only one keyboard shortcut for all commands (F5). It might be a good idea to assign F5 to the execute command and then assign another key (F6 or whatever other key is available) to other commands. That way you'd always have a key for jumping right int your game without having to switch commands first, while still having another key for your regular command behavior.

**Comment by bjorn** [comment]
There is only one keyboard shortcut, but it runs the currently selected command directly. So I don't think there is a need for another shortcut unless you're frequently using multiple different commands.

**Comment by bjorn** [comment]
I've opened #1456 about user-configurable shortcuts for each custom command.
