### ISSUE TITLE
Terrain area informations are lost when saving in .json and then reopening

### ISSUE THREAD

**Issue by vichug** [bjorn/tiled#948]
Hey,
Apparently when i want to save a map in .json with a tileset that contains terrain information with defined area for terrains, those defined area are lost. I precies that i import an external tileset, which is containing said terrains, and i can - during the open session in which i imported the tileset - use the terrain feature, but if i close then reopen the .json map everything is lost.
It should be reproducible by :
* having a map that you save as .json
* opening the map as .json wiht Tiled
* import external tileset containing terrain
* you can use it at first
* save everything (still json), then re-open
* then, the terrains are apparently there but you can't use them anymore ; for the mapping informations are disappeared
* to see that they disappeared, you can click "Import the Tileset" (at the bottom of the Tileset window) after what you can open the terrains informations window and you can clearly see that the area affectations have disappeared

**Comment by bjorn** [comment]
I've pushed a fix for this to the `0.12` branch, so that it will be included in a Tiled 0.12.1 release. I've also merged it to master to trigger the daily builds, in case you need this fixed soon.

Many thanks for the report!

**Comment by vichug** [comment]
oh suepr cool thanks !
