### ISSUE TITLE
Command line arguments aren't working

### ISSUE THREAD

**Issue by ghost** [bjorn/tiled#953]
Hi,

build Tiled from Git, now when I try to run Tiled with an command line argument, nothing happens. I run Windows 8.1 64-bit, Qt 4.8.6 - MinGW.
Thats what I get:

```
user@Main-PC ~/Documents/Remote Repositories/tiled (master)
$ tiled.exe --version

user@Main-PC ~/Documents/Remote Repositories/tiled (master)
$ tiled.exe --show-formats
```

Nothing happens, only when I start Tiled using ``--disable-opengl``.

**Comment by bjorn** [comment]
It seems that for some reason the output is not written to the console. I'm not sure whether Windows applications can do that which are graphical applications.

**Comment by lefticus** [comment]
For a Qt project I used to work on, we ended up popping up a message box on Windows to display results from command line switches. It wasn't ideal, but it was the only solution we found. IIRC, Windows applications either do have a console (and it opens every time the application is launched, which is not ideal) or they do *not* have a console, and displaying output to the user is difficult.

There's some other application specific cruft in here, but you can see I just did a QMessageBox

https://github.com/NREL/OpenStudio/blob/v1.1.1/openstudiocore/src/runmanager/app/main.cpp#L32-L45

-Jason

**Comment by buckle2000** [comment]
FYI: http://msdn.microsoft.com/en-us/library/ms681952(VS.85).aspx

**Comment by bjorn** [comment]
@buckle2000 Thanks, that is worth looking into sometime. Did you actually use it yourself or do you have a more elaborate example of how this is supposed to be used?

**Comment by buckle2000** [comment]
```cpp
	bool has_console = AttachConsole(-1);
	HANDLE handle = GetStdHandle(-11); // stdout
	auto s = u"你好";
	WriteConsole(handle, s, sizeof(s), NULL, NULL);
```

**Comment by bjorn** [comment]
Thanks @buckle2000. I've just tried it out and I was able to output to the console using `WriteConsole` using the following snippet (the `u` thing didn't work with VS 2013, or may not be part of C++11):
```c++
    bool has_console = AttachConsole(ATTACH_PARENT_PROCESS);
    if (has_console) {
        HANDLE handle = GetStdHandle(STD_OUTPUT_HANDLE);
        QString s(QStringLiteral("foo bar baz\n"));
        WriteConsole(handle, s.constData(), s.length(), NULL, NULL);
    }
```
However, anything printed using `qDebug` or `qWarning` (or `printf` or `std::cout` for that matter) does not show up. Any idea how I might hook those up?

Actually I managed to get `std::cout` and `printf` working by adding:
```c++
        freopen("CONOUT$", "w", stdout);
```
But still `qWarning`, used to output text to console by Tiled, refuses to show anything. :/

**Comment by bjorn** [comment]
Alright, I had missed that those functions output to `stderr`! The following snippet does the trick:
```c++
    if (AttachConsole(ATTACH_PARENT_PROCESS)) {
        freopen("CONOUT$", "w", stdout);
        freopen("CONOUT$", "w", stderr);
    }
```

**Comment by buckle2000** [comment]
Two things:
The `u` thing means utf-8 encoding.
Visual studio says `freopen` is not safe.

**Comment by bjorn** [comment]
> The `u` thing means utf-8 encoding.

I know, but VS 2013 did not recognize it in C++11 mode.

> Visual studio says `freopen` is not safe.

In what way? And does it mention an alternative?

**Comment by buckle2000** [comment]
The "safe" alternative of `freopen` is [`freopen_s`](https://msdn.microsoft.com/en-us/library/88k7d7a7.aspx).

**Comment by bjorn** [comment]
The extra security seems to be in the form of enhanced error reporting, which doesn't apply in this case since I'm not even handling any errors. However, I'll replace them anyway to avoid using deprecated functions:
```c++
    if (AttachConsole(ATTACH_PARENT_PROCESS)) {
        FILE *dummy = nullptr;
        freopen_s(&dummy, "CONOUT$", "w", stdout);
        freopen_s(&dummy, "CONOUT$", "w", stderr);
    }
```

**Comment by buckle2000** [comment]
I think `freopen_s` is only avaliable on Windows. It is not part of c++ standards.

**Comment by bjorn** [comment]
That's right, but that's OK in this case because this code is Windows-only in the first place.

Thanks for your help in getting this fixed!

**Comment by buckle2000** [comment]
@bjorn I found something interesting but I don't have time to test it.
https://github.com/aseprite/aseprite/blob/f696d895b44234b4be3398cce4fd9eb0ec6bfb9e/src/base/system_console.cpp#L28-L82
Maybe you need to call ` std::ios::sync_with_stdio`?

**Comment by bjorn** [comment]
@buckle2000 Thanks for the reference, but I think I don't need this given that the change appears to be working fine as it is.

**Comment by bjorn** [comment]
Also, from the [documentation](http://www.cplusplus.com/reference/ios/ios_base/sync_with_stdio/) of `std::ios::sync_with_stdio`:

> By default, iostream objects and cstdio streams are synchronized (as if this function was called with true as argument).

So unless this was called with `false` as argument, there is no reason to call this.
