### ISSUE TITLE
Add automapping error output in debugging console

### ISSUE THREAD

**Issue by vichug** [bjorn/tiled#954]
Hey,
When using automap a lot of things could go wrong, given the specific filesystem/number of tilesets/layer names one needs to provide. So it would be great to be knowing what goes worng in the console debug ; then it would be faster to correct. Right now i'm not certain what this console is used for.
Thanks in advance !

**Comment by bjorn** [comment]
The console was added for and is currently only used by the Python plugin that makes it possible to write import/export scripts in Python. But, it's a great idea to use it for any useful error messages!

**Comment by Phlosioneer** [comment]
This appears to be solved, as pointed out in #2715

**Comment by bjorn** [comment]
@Phlosioneer Ah, that explains. Time to close this old issue indeed, this functionality was added in Tiled 1.3!
