### ISSUE TITLE
How to rotate objects and positionate correctly?

### ISSUE THREAD

**Issue by MrJookie** [bjorn/tiled#955]
In my game I am trying to rotate tiled objects, but unsuccessfully. They're placed at wrong X and Y position. Thanks for suggestions.

			    position.x = atof(objectElement->first_attribute("x")->value());
			    position.y = atof(objectElement->first_attribute("y")->value());

				float rotationAngle = objectElement->first_attribute("rotation") ? atof(objectElement->first_attribute("rotation")->value()) : 0.0;

				float centerX = tilewidth / 2;
				float centerY = tileheight / 2;

				float cosRotation = cos(-rotationAngle * M_PI / 180.0);
				float sinRotation = sin(-rotationAngle * M_PI / 180.0);

				float rotatedCenterX = centerX * cosRotation - centerY * sinRotation;
				float rotatedCenterY = centerX * sinRotation + centerY * cosRotation;

				position.x = position.x + rotatedCenterX;
				position.y = position.y + rotatedCenterY;

				sprite.setPosition(position.x, position.y);

				sprite.setOrigin(centerX, centerY);
				sprite.setRotation(rotationAngle);

**Comment by bjorn** [comment]
It seems like your code is based on this forum thread:

http://forum.mapeditor.org/t/deer-need-for-x-and-y-to-be-the-center-of-the-object-instead-of-top-left-corner/150

Since I can only guess, I'm thinking you should not be negating the `rotationAngle` while converting it to radians. I made the same mistake on the forum and later edited my post (twice). The negation is not necessary when the Y axis is inverted compared to Tiled.

**Comment by MrJookie** [comment]
Thanks for fast reply. Yes, thats exactly what I was following and tried both (negated and non-negated version) neither worked. Any other suggestions?
Just removed the negation, attaching screenshot. (objects with no rotation are placed correctly)
![tiled_wrong_positioning](https://cloud.githubusercontent.com/assets/8093682/7704267/8dafb540-fe3d-11e4-9c33-e483e36fa8c6.png)

**Comment by bjorn** [comment]
Well, it really depends on what this `sprite` object is doing with those position, origin and rotation properties. What framework are you using?

**Comment by MrJookie** [comment]
SFML http://www.sfml-dev.org/documentation/2.3/classsf_1_1Sprite.php

**Comment by bjorn** [comment]
@MrJookie Alright, from the documentation of `setOrigin`:

> The origin of an object defines the center point for all transformations (position, scale, rotation). The coordinates of this point must be relative to the top-left corner of the object, and ignore all transformations (position, scale, rotation). The default origin of a transformable object is (0, 0).

This really means you should not set the origin to the center of the sprite, since then the rotation will be applied around that point while Tiled rotates around (0, 0). It also means you should be able to drop all the business with the rotated center. That was only in the forum thread because the one asking for help there had his objects positioned and rotated by their center.

**Comment by bjorn** [comment]
@MrJookie Ah, one thing I forgot, the origin of tile objects, which you are using, is currently the bottom-left and not the top-left in Tiled. So you'll need to correct for this similarly to the way the code you have is correcting for a center origin.

**Comment by bjorn** [comment]
@MrJookie Ah, actually you should be able to shift the position of the object upwards by the height of the texture and use `setOrigin` to put the rotation origin in the bottom-left.

**Comment by MrJookie** [comment]
@bjorn Thanks! That was it! The origin should be 0,tileheight... and I was setting all the time centre of the object and then went into sine/cosine and totally got lost. Damn, knew the object is bottom-left and still automatically was trying 0,0 and later center! Thanks again :) In case others also get lost, hope they find this issue.

**Comment by bjorn** [comment]
@MrJookie I'm glad to hear you got it working now! I also hope others may find this issue, but really I should work on some actual documentation and include an explanation about this stuff. Closing this issue, anyway.

**Comment by gotenxds** [comment]
This is only a problem because of the why tiled works, why not just change this wird way and work with the center, the rotation and flips wont affect the position.

This happend twice and now to me to, and I'm sure more people.

**Comment by bjorn** [comment]
@gotenxds I see you already found issue #560 about that. The main issue is changing it while keeping compatibility. Also, I think the default should probably be top-left, with center being also one of the options (though in case of options, there is again the question of where to store this information).
