### ISSUE TITLE
Compile error on OSX with QT 4.8.6

### ISSUE THREAD

**Issue by franksauvag** [bjorn/tiled#956]
Hi, I got the following compile error while compiling Tiled on a Mac.

objectselectiontool.cpp:845:28: error: no member named 'removeAt' in 'QVector<Tiled::Internal::ObjectSelectionTool::MovingObject>'; did you mean 'remove'?
            mMovingObjects.removeAt(i);
                           ^~~~~~~~
                           remove

Looks the suggested solution fix the error so I was able to compile/run Tiled 0.12.1.

Not yet familiar with this repository, so I prefer letting you know for now.

Is there any preferred QT Version ? (I used my existing one) 

Thanks;
Frank;

**Comment by bjorn** [comment]
I had already fixed this in commit f3b896577750385a97769b9712ac82f4016843ea, but it wasn't merged to master yet. Thanks for the report, though. :-)
