### ISSUE TITLE
Cannot select & move objects in old (0.11) json maps

### ISSUE THREAD

**Issue by floriancargoet** [bjorn/tiled#959]
In JSON files created before `mapobjectresizev3` was merged, I cannot select tile objects by clicking on them. If I select them by drawing a rectangle, the selection looks broken (reduced to a single point) and I cannot move the objects.

If I insert a new tile object it works fine for this object.

This is due to tile objects now having a height != 0. Old tile objects have height = 0 and are hard to select and move.

Not sure what can be done but I thought you should know.

**Comment by bjorn** [comment]
Ouch, I forgot to check this format for compatibility issues... will look into fixing this immediately.

**Comment by bjorn** [comment]
I'll aim for releasing Tiled 0.12.2 tomorrow, since this is pretty bad. :-/

**Comment by floriancargoet** [comment]
I've tested this fix with my files and it works. :+1:
