### ISSUE TITLE
Object moving with keyboard issue

### ISSUE THREAD

**Issue by numagames** [bjorn/tiled#961]
On Tiled 0.12.1 when you try to move objects with keyboard they won't move but when deselected with mouse they update their position according to previous keyboard movement..

**Comment by bjorn** [comment]
Yeah, I noticed this as well late yesterday evening and will fix this today before releasing Tiled 0.12.2. Sorry about that.

Actually they do move correctly, but no repaints are triggered.

**Comment by numagames** [comment]
Thanks for quick fix, Bjorn...
