### ISSUE TITLE
Wrong tile index in layer in json export

### ISSUE THREAD

**Issue by lucaregini** [bjorn/tiled#963]
I have a tiled map that produces wrong indexed in the data field of a layer definition.

For example one extract of the data layer is the following:

1038, 2147485331, 2147485330, 2147485329, 2147485328, 2147485327

when the whole map has about 2000 tiles.
Could this be caused by the fact that the tilesets have dimensions that are not multiple of the tile dimension?

**Comment by bjorn** [comment]
Such large numbers appear when you flip tiles, since the flipping information is stored in the higher bits of the unsigned 32-bit global tile ID. See http://doc.mapeditor.org/reference/tmx-map-format/#tile-flipping for more information.

**Comment by lucaregini** [comment]
The fact is that I do not have used flipped tiles and if I did it I did not realize it.
I have noticed that I have issues when tileset width and height are not a multiple of the corresponding tile dimensions. Could it be the real reason?

**Comment by bjorn** [comment]
> The fact is that I do not have used flipped tiles and if I did it I did not realize it.

It's easy to trigger it by accidentally pressing X, Y or Z while having a stamp brush selected. And if your tile graphics are symmetric you would not notice it.

> I have noticed that I have issues when tileset width and height are not a multiple of the corresponding tile dimensions. Could it be the real reason?

What kind of issues? This is not expected to cause any issues.

**Comment by pentatrax** [comment]
I'm experiencing the same problem. CSV exports fine but JSON gives me numbers that are above 100 when my til set only has 41 tiles

**Comment by eishiya** [comment]
You're probably experiencing a similar issue to OP. Check the documentation on tile GIDs here: https://doc.mapeditor.org/en/stable/reference/global-tile-ids/
There are two sources of tile IDs being larger than expected: Flipping flags (if the numbers are very large, like OP's), and firstgid adjustments for multiple tilesets (which cause increases on the order of tilesets' tile counts). The page I linked discusses how both of these work and how to get the raw tile ID out of GIDs.
