### ISSUE TITLE
Rotation by Z key visualization bug

### ISSUE THREAD

**Issue by T1mL3arn** [bjorn/tiled#966]
If I use Z key for rotate object (whatever it is rectangle, polyline or any other object) its visualization updates only if I move that object by mouse (or keyboard).

Tiled 12.2, WinXP

**Comment by T1mL3arn** [comment]
Problem with visualization also with the "join nodes" action for poly-objects. After joining, the white node squares still visible and they disappear only after click on that object.

**Comment by bjorn** [comment]
Arg, more updating issues after already fixing some in Tiled 0.12.1 and 0.12.2. All caused by the same last-minute fix that seemed entirely alright (3d2513f5a5dd710094d702b9d3acb0c3f4130fc4). :-(

Thanks for the report, I'll be sure to fix these problems soon.
