### ISSUE TITLE
Triangle collider not working properly?

### ISSUE THREAD

**Issue by lputruele** [bjorn/tiled#971]
I'm making a platformer with 64x64 tiles, where there are boxes and triangles, triangles colliders on these work almost everytime but sometimes the character gets stucked.

**Comment by bjorn** [comment]
I think you got the wrong project for submitting your issue. This issue tracker is about issues with Tiled, the editor. It does generally cover engines or frameworks that support using Tiled maps, and do for example fancy stuff like physics.

You'll have to consider where the "triangle collider" comes from and figure out whether you're making a data error, an error in your code, or whether there's an issue with the framework you're using.
