### ISSUE TITLE
Feature request: "noncontiguous mode" for magic wand and fill tools

### ISSUE THREAD

**Issue by kheftel** [bjorn/tiled#973]
Title pretty much says it all, apologize if it's a duplicate, but it would be nice to be able to a.) select all instances of a particular tile on a particular map layer, and/or b.) replace it with another tile.

it could be a little checkbox that you turn on and off with the existing tools (which might require a tool options pane and open up a can of worms), or two new dedicated tools.

I may try to implement this myself if I can make some time.

**Comment by bjorn** [comment]
Makes sense. I'd say it should just be its own tool, like the "Select by Color" tool in GIMP.

**Comment by kheftel** [comment]
Either way is totally fine with me. If it were on the roadmap I'd vote for it :)

**Comment by bjorn** [comment]
I think having a tool for filling this way is a little much though. Once there is a "Select Same TIles" tool this already can be used to then fill that selection using the regular Fill tool in combination with the Shift modifier.

**Comment by kheftel** [comment]
wait, what does the shift modifier do on the fill tool?

**Comment by bjorn** [comment]
Makes it fill the current selection, regardless of the tiles.

**Comment by kheftel** [comment]
oh! Good to know... How have I used tiled for so long and not known this lol?

**Comment by bjorn** [comment]
Cause of the missing manual... :-)

**Comment by bjorn** [comment]
Was done for Tiled 0.13 by PR #1002.

**Comment by kheftel** [comment]
awesome!
