### ISSUE TITLE
Gap with TMX map and spacing tileset

### ISSUE THREAD

**Issue by Sparksx** [bjorn/tiled#976]
Hello

I use an TMX map with 1px spacing between tiles in Quintus framework.
Tiles on first line are correctly rendered. But other line have tiles gap.
line 2 : 1 tile gap
Line 3 : 2 tiles gap
etc

For exemple i put tile id 62 (green block) and in TMX file you register tile 63

I use this tileset (16 x 16 with 1px spacing)
![roguelikesheet_transparent](https://cloud.githubusercontent.com/assets/3260152/8110555/42f58246-105d-11e5-9581-265b28759e5e.png)
My tmx file : 
http://paf.im/WTrxX

They say it's tiled bug, so have I a bad config ?

Thanks

**Comment by bjorn** [comment]
> For exemple i put tile id 62 (green block) and in TMX file you register tile 63

You have to keep in mind that the TMX format uses 0 for storing empty cells, and that the first tile from the first tileset gets written with global ID 1.

Some information about how to deal with the global tile IDs and map them to tiles from possibly multiple tilesets can be found at http://doc.mapeditor.org/reference/tmx-map-format/#data.

**Comment by Sparksx** [comment]
Hi,

I have found the solution : my tilset is composed of 16px tiles with 1px spacing.
the last line tiles haven't the 1px spacing on right.

I've just add 1px spacing to correct this.

**Comment by bjorn** [comment]
Hmm, the last line is not supposed to require the spacing on the right, so that would indicate a bug.

**Comment by bjorn** [comment]
@Sparksx I've just tested your tileset in Tiled and it works fine, so you probably found a bug in the Quintus framework and should consider reporting it there.
