### ISSUE TITLE
Straight polyline disappear when you try to resize it

### ISSUE THREAD

**Issue by Darky-Lucera** [bjorn/tiled#981]
Version 0.12.3

If you have an horizontal straight polyline and you use any of the 'to down' arrows (down, left-down, right-down) the polyline disappear and the Y property is equal to -2147483647,00 (0x80000001?). 
There is no problem is you use any of the 'to up' arrows (up, left-up, right-up), then only X is modified.

If you have a vertical straight polyline and you use any of the 'to right' arrows (right, right-down, right-up) the polyline disappear and the X property is equal to -2147483647,00 (0x80000001?). 
There is no problem is you use any of the 'to left' arrows (left, left-down, left-up), then only Y is modified.

There is no problem if the polyline is not a straight line.

**Comment by bjorn** [comment]
Hmm, of course it is not actually possible to stretch a single horizontal line downwards. I'll probably have to deal with this case separately. Thanks for the report!

**Comment by IMMZ** [comment]
The problem really exists. The best possible fix I think is to prevent user from incorrect resizing and don't annoy him by showing incorrect variants. My pull request with fix => https://github.com/bjorn/tiled/pull/982
