### ISSUE TITLE
Problem compiling tiled on ubuntu 15.04

### ISSUE THREAD

**Issue by oawad79** [bjorn/tiled#994]
Hello,

Keep getting this when I try to compile tiled on Ubuntu 15.04

cd src/ && make -f Makefile 
make[1]: Entering directory '/home/user/Downloads/tiled-0.12.3/src'
cd libtiled/ && make -f Makefile 
make[2]: Entering directory '/home/user/Downloads/tiled-0.12.3/src/libtiled'
make[2]: Nothing to be done for 'first'.
make[2]: Leaving directory '/home/user/Downloads/tiled-0.12.3/src/libtiled'
cd tiled/ && make -f Makefile 
make[2]: Entering directory '/home/user/Downloads/tiled-0.12.3/src/tiled'
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.6/include/QtCore -I/usr/local/Trolltech/Qt-4.8.6/include/QtGui -I/usr/local/Trolltech/Qt-4.8.6/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.8.6/include -I../libtiled -I../qtpropertybrowser/src -I/usr/X11R6/include -I. -I. -o main.o main.cpp
In file included from main.cpp:24:0:
mainwindow.h:89:21: error: ‘QSessionManager’ has not been declared
void commitData(QSessionManager &manager);
^
Makefile:20324: recipe for target 'main.o' failed
make[2]: *** [main.o] Error 1
make[2]: Leaving directory '/home/user/Downloads/tiled-0.12.3/src/tiled'
Makefile:80: recipe for target 'sub-tiled-make_default-ordered' failed
make[1]: *** [sub-tiled-make_default-ordered] Error 2
make[1]: Leaving directory '/home/user/Downloads/tiled-0.12.3/src'
Makefile:40: recipe for target 'sub-src-make_default-ordered' failed
make: *** [sub-src-make_default-ordered] Error 2

any idea what is going on ?

**Comment by bjorn** [comment]
Please don't double-post to forum and issue tracker. Either of them would have done fine for your issue.

I'll close this one since I don't believe it's an issue with Tiled.

http://forum.mapeditor.org/t/problem-compiling-tiled-0-12-on-ubuntu-15-04/599
