### ISSUE TITLE
Building Python plugin on Windows using Qbs fails to link

### ISSUE THREAD

**Issue by jakepetroules** [bjorn/tiled#999]
I'm using the Python 2.7 installation from python.org, Qt 5.4.1 (MinGW 4.9.1), Qbs 1.4.0 and latest master of Tiled. I receive the following error when attempting to build the Python plugin.

    ERROR: C:\Qt\Tools\mingw491_32\bin\g++.exe -shared -Wl,--major-subsystem-version,5 -Wl,--minor-subsystem-version,01 -Wl,--major-os-version,5 -Wl,--minor-os-version,01 C:/qbs/bin/qt-5-4-1-mingw491_32-debug/python.qt-5-4-1-mingw491-32.1456ee5b/.obj/39301be37a6f50b4/moc_pythonplugin.cpp.o C:/qbs/bin/qt-5-4-1-mingw491_32-debug/python.qt-5-4-1-mingw491-32.1456ee5b/.obj/3a52ce780950d4d9/pythonbind.cpp.o C:/qbs/bin/qt-5-4-1-mingw491_32-debug/python.qt-5-4-1-mingw491-32.1456ee5b/.obj/3a52ce780950d4d9/pythonplugin.cpp.o -m32 -g -Wall -Wextra -LC:/Python27/libs -LC:/Qt/5.4/mingw491_32/lib C:/Qt/5.4/mingw491_32/lib/libqtmaind.a C:/qbs/bin/qt-5-4-1-mingw491_32-debug/libtiled.qt-5-4-1-mingw491-32.f8bd76a4/.socopy/tiled.dll -lpython27 C:/Qt/5.4/mingw491_32/lib/libQt5Guid.a C:/Qt/5.4/mingw491_32/lib/libQt5Cored.a C:/Qt/5.4/mingw491_32/lib/libQt5Widgetsd.a -Wl,--unresolved-symbols=ignore-in-shared-libs -o C:/qbs/bin/qt-5-4-1-mingw491_32-debug/python.qt-5-4-1-mingw491-32.1456ee5b/python.dll
    C:/Python27/libs/libpython27.a(dmmes01026.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
    C:/Python27/libs/libpython27.a(dmmes01027.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
    C:/Python27/libs/libpython27.a(dmmes00245.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
    C:/Python27/libs/libpython27.a(dmmes00239.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
    C:/Python27/libs/libpython27.a(dmmes00707.o):(.idata$7+0x0): undefined reference to `_head_C__build27_cpython_PCBuild_libpython27_a'
    C:/Python27/libs/libpython27.a(dmmes00708.o):(.idata$7+0x0): more undefined references to `_head_C__build27_cpython_PCBuild_libpython27_a' follow
    collect2.exe: error: ld returned 1 exit status

**Comment by bjorn** [comment]
Does the happen for you only in debug mode or also in release mode? On AppVeyor I'm building only in release mode and there are no problems with the Python plugin there.

It could be that it needs to link with some `libpython27d.a` instead, but I'm not sure if that file is actually available by default. Last time I was looking into this I could not find it.

**Comment by jakepetroules** [comment]
Apparently my Python install was built with MSVC, which can't be linked with MinGW.
